### ISSUE TITLE
to specify initial requirements, in draft version

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1]
_migrated from Trac, where originally posted by **yegor256** on 1-Aug-2010 1:36pm_

We have to specify initial requirements, in SRS.

<hr id='w'>

 - `1-b5151558`/#638 (by )

**Comment by karato** [comment]
@yegor256 there is a puzzle in this code `1-b5151558`/#638, we'll resolve it later

**Comment by karato** [comment]
@yegor256 last puzzled solved `1-b5151558`/#638

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#unknown]() is solved here.
