### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by sebing** [yegor256/netbout#1001]
On the earnings click; I got this error

```
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

Hope it is a one time issue.

**Comment by dmzaytsev** [comment]
@sebing is it reproducible issue?

**Comment by sebing** [comment]
@dmzaytsev I got them few times. I remember got the same error yesterday too. As I have no access to the log I cannot produce them.

**Comment by sebing** [comment]
@dmzaytsev I got the same error today too.

**Comment by sebing** [comment]
@dmzaytsev Now the error is so frequent, and it is almost impossible for me to post a message :(

**Comment by dmzaytsev** [comment]
@sebing yes, thanks

@yegor256 could you provide logs related to the time of the issue?
I need more information about the error

**Comment by dmzaytsev** [comment]
@sebing I think it fixed already
please close

**Comment by sebing** [comment]
@dmzaytsev Thanks. Closing the issue as the problem seems fixed.

**Comment by sebing** [comment]
@dmzaytsev I am still getting the problem. I am not sure it is the same.
