### ISSUE TITLE
Can't kick anyone from a room

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#1010]
I can't kick out anyone from a room.
Browser: Firefox 46

I move the mouse pointer to the user photo, it shows the name and an `x` (to kick), but when I lower my mouse over the username, it disappears (along with the `x`).

Screenshot when I have mouse over the user photo:
![kick](https://cloud.githubusercontent.com/assets/105730/13026938/739f2730-d23b-11e5-8527-9746022598a2.png)

And here when I try to move it lower to kick the user:
![kick-missing](https://cloud.githubusercontent.com/assets/105730/13026941/813f4834-d23b-11e5-9052-a933c1011ca0.png)

Unfortunately I can't create screenshots with mousepointer.

**Comment by dmzaytsev** [comment]
@krzyk  kick-out is the deprecated feature. it will be removed
see https://github.com/yegor256/netbout/issues/634#issuecomment-105601103 https://github.com/yegor256/netbout/issues/634#issuecomment-111782630

**Comment by krzyk** [comment]
@dmzaytsev OK
