### ISSUE TITLE
Autocomplete doesn't work with names ain't equivalent to  [A-Za-z0-9_].

### ISSUE THREAD

**Issue by 2686747** [yegor256/netbout#1011]
Autocomplete doesn't work with names contain non-alphanumeric symbols [A-Za-z0-9_]. Names will display in whole list but if you input non-alphanumeric symbol from needed name - it will not be processed.

Here you can see 2 names with such symbols
![bug-2016 02 12-13 39 08 592892103-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13027759/f9811026-d26c-11e5-8525-6b89140dfd44.jpg)

![bug-2016 02 12-13 39 23 581094899-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13027761/fe3ae074-d26c-11e5-9d8f-2aa9360dd4f2.jpg)
![2016 02 12-13 39 32 383480103-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13027763/fff35914-d26c-11e5-9e80-dd498cd8bc6c.jpg)

**Comment by dmzaytsev** [comment]
@2686747 only lower case English letters and numbers are accepted as an alias
https://github.com/yegor256/netbout/blob/12961da5bbb9f1079ef9b06a698379d179e4c820/netbout-web/src/main/java/com/netbout/dynamo/DyAliases.java#L132

I wonder how you have created a non alpha-numeric alias.
I's a bug if you did it using Netbout web interface
if so please update the ticket's title and its description

**Comment by 2686747** [comment]
@dmzaytsev Thank you, it will be closed.
