### ISSUE TITLE
pom.xml:747-752: These excludes were added during...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#1012]
Puzzle `961-58fc8a23` in `netbout-web/pom.xml:747-752` has to be resolved: These excludes were added during upgrade to qulice 0.15.2. New version of qulice adds new violations that need to be fixed. There are also excludes added to netbout-client/pom.xml (lines 192 - 207) related to this puzzle. They also need to be fixed in order to solve this puzzle.... The puzzle was created by Dan Baleanu on 12-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by karato** [comment]
@dmzaytsev attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@danff do this task

**Comment by danff** [comment]
@karato Thanks, I will do it.

**Comment by karato** [comment]
> @karato Thanks, I will do it.

@danff you are welcome

**Comment by danff** [comment]
@karato PR #1022 has been created addressing this issue. Thank you.

**Comment by karato** [comment]
> @karato PR #1022 has been created addressing this issue. Thank you.

@danff ok

**Comment by karato** [comment]
@danff 15 days already, in 48 hours I will re-assign

do not forget that you should remove the `@todo` puzzle from the source code

-30 added to your rating, current score is: [+30](http://www.netbout.com/b/36198?open=rating)

**Comment by danff** [comment]
@karato need more time to close the PR

**Comment by danff** [comment]
@karato the PR #1022 was merged and closed. Can the ticket be closed, please?

**Comment by karato** [comment]
> @karato need more time to close the PR

@danff agreed, take your time

**Comment by danff** [comment]
@dmzaytsev Who should close these tickets (from puzzles)?

**Comment by dmzaytsev** [comment]
@danff @karato will close it

**Comment by danff** [comment]
@dmzaytsev thanx

**Comment by karato** [comment]
@dmzaytsev 3 puzzles were created here: `1012-2dfa2c65`, `1012-7ae4ec06`/#1061, `1012-68768ab8`

**Comment by karato** [comment]
@dmzaytsev Thanks all, I am closing

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you ;)

**Comment by karato** [comment]
@danff just added 10 mins to @ypshenychka (for QA), payment ID is `79193542`

Much appreciated! **30 mins** was added to your account, payment ID `AP-7UJ268700W4853621`, time spent is 378 hours and 16 mins

added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/36198?open=rating)

**Comment by karato** [comment]
@dmzaytsev last 3 puzzles originated from here are solved: `1012-2dfa2c65`/#1063, `1012-7ae4ec06`/#1061, `1012-68768ab8`/#1062
