### ISSUE TITLE
Somehow my email is changed in Netbout and it wont change to another one 

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#1015]
I have noticed that I am not getting email from my Bouts, I saw that my email was changed and when I tried to change back it does not change back.
![screenshot from 2016-02-15 19-53-07](https://cloud.githubusercontent.com/assets/14311743/13057672/03f253f0-d41e-11e5-86b7-0e94968cc386.png)

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Could you take a look at this because it is a big issue for me.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I thin I used ``` mvn clean install -Dnetbout.token=${cookie_value} -Dnetbout.url=${netbout_server}``` some days ago to try and test  #989, this might have changed my email, but it does not explain why I cant change it back.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha did you check your inbox for the confirmation email from Netbout ?
Netbout shows your previous email until you click on a link in the confirmation email.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev that is the problem I am not recieving any email confirmation.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@kujtimiihoxha did you get any message like `Email changed to .... The verification link sent to this address` ?

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@karato please see PR #1016

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by kujtimiihoxha** [comment]
@dmzaytsev The only message I got is the one in the image.

**Comment by karato** [comment]
@kujtimiihoxha I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev the task is yours, please proceed

**Comment by karato** [comment]
> @karato please see PR #1016 

@dmzaytsev will check it soon, thanks

**Comment by karato** [comment]
@kujtimiihoxha thanks for the ticket, your account was topped for 15 mins, payment AP-3A625820J7439251G

**Comment by dmzaytsev** [comment]
@kujtimiihoxha fixed in  #1016 please close

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.27`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev   it looks like we need to solve #992  first.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha Rultor doesn't release a new version
but the production instance updated.
Please check the email changing

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Now it says no verification is needed after I click the link

**Comment by dmzaytsev** [comment]
@kujtimiihoxha I just changed my email, got the confirmation link and confirm the new email.
please try again

**Comment by kujtimiihoxha** [comment]
@dmzaytsev It is very interesting I used the link and after I verified It says email verified, when I go to my index page it shows me my old email and in the exclamation mark it tells my that the email I just verified is not verified. This could have to do with #989, but still my email should be changed in the save box , should I add this as a new issue ?
![screenshot from 2016-02-17 18-57-51](https://cloud.githubusercontent.com/assets/14311743/13119596/40efee38-d5aa-11e5-91ce-7dba49f1fc00.png)

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I should add that I cleared my cookies because I thought that it had something to do with the cookies but again the same.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha I guess it is a cache related issue we already have a ticket about it

**Comment by kujtimiihoxha** [comment]
@dmzaytsev so could it be that #989 is also related to the cache issue ? because I do not know how to test this issue locally ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha I'm afraid it is not related to the cache issue. It seems hi didn't change his email before so it can't be a cache issue
Also Netbout has been restarted recently

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @elenavolokhova, for QA review, payment code is `77970024`... thanks, I just added **45 mins** to your account, payment `77970033`, 33 hours and 54 mins spent... there is a bonus for fast delivery (m=2034)... +45 added to your rating, current score is: [+3346](http://www.netbout.com/b/35166?open=rating)
