### ISSUE TITLE
Users should not be allowed to add an email that already is bind to another user.

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#1019]
I just tested this, netbout allows me to have multiple users with the same email, I thinks this should not be allowed.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@kujtimiihoxha attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@kujtimiihoxha many thanks for the bug report, I added 15 mins to your acc, transaction `AP-3MK64717031365316`
