### ISSUE TITLE
We should add support for shortcuts in bout comments

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#1020]
We should add support for shortcuts  like here on github exp. ```ctrl+b``` will show ```** **``` for bold text and ```ctrl+i``` will add ```_ _``` for italic.

**Comment by karato** [comment]
@dmzaytsev take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Should I close this issue ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha yes please, I don't think  we need a github copy

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Ok I thought that it would be easier for users that are used to use this shortcuts in github that's why.
