### ISSUE TITLE
CasperJS tests are skipped when unit tests are skipped

### ISSUE THREAD

**Issue by HDouss** [yegor256/netbout#1026]
CasperJS tests are considered as integration tests. Now, they are configured to run if IT are skipped and they are skipped if unit tests are skipped. They should be configured to be run even if unit tests are skipped, and they should be skipped when IT are skipped.

**Comment by karato** [comment]
@dmzaytsev please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@hdouss I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@hdouss thank you for reporting this, I added 15 mins to your acc, transaction `78555520`
