### ISSUE TITLE
Coveralls maven plugin can't parse a date

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#1032]
Coveralls maven plugin failed with a message:

there is not same but similar [issue](https://github.com/trautonen/coveralls-maven-plugin/issues/90)
it may help

>Caused by: java.text.ParseException: Unparseable date: "2016-02-19T14:20:10"
        at java.text.DateFormat.parse(DateFormat.java:357)
        at org.eluder.coveralls.maven.plugin.util.TimestampParser.parse(TimestampParser.java:60)
        ... 23 more

see full log http://www.rultor.com/t/7129-186229487

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by longtimeago** [comment]
@dmzaytsev adding this to coveralls plugin configuration should solve the issue
```
<failOnServiceError>false</failOnServiceError>
```

**Comment by dmzaytsev** [comment]
@longtimeago thanks

**Comment by dmzaytsev** [comment]
@rultor release, tag='2.31'

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.31`

**Comment by longtimeago** [comment]
@dmzaytsev ah, that's why we have netbout down time ... new release is coming :)

**Comment by dmzaytsev** [comment]
@longtimeago just a test release, no features :)

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by longtimeago** [comment]
@dmzaytsev shit ... looks like the fix didn't help

**Comment by dmzaytsev** [comment]
@longtimeago so do I

**Comment by longtimeago** [comment]
@dmzaytsev you have a problem because of this
https://github.com/yegor256/netbout/blob/master/pom.xml#L115

**Comment by longtimeago** [comment]
@dmzaytsev coveralls expects some timestamp parameter in it's plugin configuration. If not found it takes one from `${maven.build.timestamp}`
Remove the line https://github.com/yegor256/netbout/blob/master/pom.xml#L115
and it should be fine

**Comment by karato** [comment]
@dmzaytsev thanks a lot for reporting, **30 mins** added to your acc, pmt ID `78316475`

**Comment by longtimeago** [comment]
@dmzaytsev also, there is an issue registered https://github.com/trautonen/coveralls-maven-plugin/issues/90

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.32`

**Comment by dmzaytsev** [comment]
@longtimeago would you like to do this task? :)

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.2`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.3`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.4`

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev got it, "urgent" label here

**Comment by dmzaytsev** [comment]
@karato it is not urgent anymore

**Comment by karato** [comment]
> @karato it is not urgent anymore

@dmzaytsev sure, thanks, I removed "urgent" tag to it

**Comment by karato** [comment]
@2686747 please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by longtimeago** [comment]
@dmzaytsev sorry, was really busy with 2 other projects :(

**Comment by 2686747** [comment]
@dmzaytsev please, check it #1051

**Comment by dmzaytsev** [comment]
@2686747 also please revert commits https://github.com/dmzaytsev/netbout/commit/2f612c5deea7af3c5f76355be519795422c76144
and https://github.com/dmzaytsev/netbout/commit/e1cf2987a4e28497a802818279589c2c40569172

**Comment by 2686747** [comment]
@dmzaytsev dmzaytsev@2f612c5 seems correct , doesn't it?

**Comment by dmzaytsev** [comment]
@2686747 I have removed that property but it did not affect to the issue
do you think we have to keep it removed?  if so let's do it

**Comment by 2686747** [comment]
It was timestamp property for coverall-plugin, i think. Maybe 63ebb1c438f204044571f7ea2c7c31fa4035fc54 has to be reverted?

**Comment by dmzaytsev** [comment]
@2686747 yes, let's remove it

**Comment by 2686747** [comment]
@dmzaytsev done 12ac1d9

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.10`

**Comment by dmzaytsev** [comment]
@2686747 any ideas?

**Comment by 2686747** [comment]
@dmzaytsev it seems like other issue

**Comment by 2686747** [comment]
@karato waiting for #1055

**Comment by karato** [comment]
> @karato waiting for #1055

@2686747 agreed, we'll wait for #1055

**Comment by 2686747** [comment]
@dmzaytsev could you close this ticket (resolved in #1051)?

**Comment by dmzaytsev** [comment]
@2686747 thanks

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@2686747 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 79940360... **30 mins** added to your account (payment number `56e15177be202c0fbf000359`), many thanks for your contribution! 259 hours and 16 mins spent here.... +30 to your rating, your total score is [+46](http://www.netbout.com/b/36452?open=rating)

**Comment by 2686747** [comment]
@karato thanks a lot

**Comment by karato** [comment]
> @karato thanks a lot

@2686747 sure, you are welcome
