### ISSUE TITLE
Insufficient documentation for JAVA newcomers.

### ISSUE THREAD

**Issue by wild-lotus** [yegor256/netbout#1033]
Current documentation is not enough for new Java programmers arriving to the project. There needs to be added more info about its architecture and setup:
- List of technologies, 3rd party plugins and libraries used. Including what they do, how and why they are used. Provide all relevant links.
- Folder structure explanation.
- Naming conventions used.
- Setup instructions for local development environments, including at least one IDE.

**Comment by CarlosGines** [comment]
@dmzaytsev please check.

**Comment by dmzaytsev** [comment]
@CarlosGines Netbout has a standart maven project structure,
all plugins and libraries you can find in `pom` files.
just read your IDE's guide about maven projects.
I think all java IDEs in the world support maven

**Comment by CarlosGines** [comment]
Thank you @dmzaytsev that is a starting point. Still many things missing for me in documentation. I will ask some questions related to the architecture to see if I can better explain this issue:

- What are the folders "netbout-client", "netbout-spi" and "netbout-web"?
- What are the REST objects like "RtBout"?
- What are the cached objects like "CdBout" and "ReBout"? ("Re-" objects are also defined as cached objects in their comments, but they are in the "retry" folder)
- Why can I find cached objects like "CdBout" in "net bout-web" and "netbout-client"?
- What is a dynamo object like "DyBout"?
- The same with "EmObject", "FkObject", "TkObject", "XeObject" and some other.

And also, even though I can read the POM file to see all plugins, that would take me a lot of time. At least most relevant libraries should be explained.

I creating this issue according to [this entry](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html#demand-better-documentation-and-wait). I am not saying that everything must be explained in detail, but there are many explanations needed for me about how this project works.
