### ISSUE TITLE
Removing participant from the discussion is very tricky in case of long name

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#1037]
For example,
![screenshot from 2016-02-22 22 48 23](https://cloud.githubusercontent.com/assets/1388994/13232185/beed40b4-d9b6-11e5-963f-716e756b628f.png)

When I move mouse to the red cross a label with name and red cross constantly disappears.
Please, add some timeout on hiding this label :)

**Comment by dmzaytsev** [comment]
@longtimeago kick-out is the deprecated feature. it will be removed
see https://github.com/yegor256/netbout/issues/634#issuecomment-105601103 https://github.com/yegor256/netbout/issues/634#issuecomment-111782630

**Comment by longtimeago** [comment]
@yegor256 @dmzaytsev I have several bouts created by mistake. Is there any way to get rid of them?

**Comment by dmzaytsev** [comment]
@longtimeago there is no way to delete a bout.
it is a kind of Netbout policy as I know.
no messages can be deleted
and no bouts can be deleted
