### ISSUE TITLE
Memory quota exceeded in Heroku

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1045]
From Heroku logs:

```
2016-02-23T22:48:39.192385+00:00 heroku[web.1]: Process running mem=674M(131.5%)
2016-02-23T22:48:39.192496+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

**Comment by yegor256** [comment]
@dmzaytsev there is a memory leakage somewhere... we're going over 512Mb in just about 10 minutes of work

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.5`

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by yegor256** [comment]
@dmzaytsev any ideas?

**Comment by yegor256** [comment]
@dmzaytsev I increased the size of VM at Heroku to 1Gb RAM. the problem is still there. we're eating the entire memory in 20-30 minutes. there is definitely a memory leak somewhere... some static variables, I assume...

**Comment by dmzaytsev** [comment]
it can be both a memory leak and the normal memory consumation by jcabi-cacheble
unfortunatelly jcabi-cacheble doen't allow to set a eviction policy for its cache, only by time we can't set a max size of the cache

**Comment by dmzaytsev** [comment]
@yegor256 let's shift back to PegDown for test

**Comment by yegor256** [comment]
@dmzaytsev yeah, but we didn't have any issues for months... let's try the PegDown. now we're having serious issues. I have to restart Heroku dyno every 20 minutes.

**Comment by dmzaytsev** [comment]
@yegor256 I'm going to release a few latest changes now.
and then will shift back to the Pegdown in a new release

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.6`

**Comment by dmzaytsev** [comment]
@yegor256 do you see the memory leak after the  latest release?

**Comment by yegor256** [comment]
@dmzaytsev watching...

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@yegor256 I'm ready to shift to the PegDown
let me know if the problem is still there

**Comment by yegor256** [comment]
@dmzaytsev yes, the problem is still there

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.7`

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by dmzaytsev** [comment]
@yegor256 could you check again?

**Comment by yegor256** [comment]
@dmzaytsev well... I don't see a problem any more. let's monitor for a few more hours

**Comment by yegor256** [comment]
@dmzaytsev in the mean time, I would strongly recommend to create a few performance/stress tests, to prevent this from happening in the future. we MUST control how stable is the product BEFORE deploying it to production

**Comment by yegor256** [comment]
@dmzaytsev nope, it didn't help. I put the memory limit back to 512m in Heroku and we see "memory quota exceeded" again, after about 15-20 minutes of work

**Comment by yegor256** [comment]
@dmzaytsev just start a server locally, put big traffic on it (using Apache Bench for example) and see what's going on inside, using some profiler. you will find the reason of memory leak pretty soon.

**Comment by dmzaytsev** [comment]
@yegor256 It's not too simple task to emulate real workload locally...
Just putting a big traffic on the root page not enough, we need make requests like a real user, log in, open bouts, post messages , scroll  pages, etc..
I would propose set up generating of memory dumps on Heroku as described here https://devcenter.heroku.com/articles/java-memory-issues#generating-heap-dumps-in-the-background

You can generate a memory dump every 30 mins and upload the dumps on a S3 bucket.
Then we can analyze these dumps

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by yegor256** [comment]
@dmzaytsev you can download that dumps from http://jmap.netbout.com (login: `team`, pwd: `sugar16`) But keep in mind that I restart heroku process every 20 minutes now, by cron. So, the information may not be very helpful. I can stop that restarts process, but the system will go out of memory very soon...

**Comment by yegor256** [comment]
@dmzaytsev I set jmap dump interval to 10 minutes:

```
heroku config:set JMAP_INTERVAL=10
```

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.8`

**Comment by dmzaytsev** [comment]
@yegor256 it seems dumps appear more then every 20 mins
would it possible display the creation time of the file?

**Comment by yegor256** [comment]
@dmzaytsev they are created every 10 minutes... let's make them less frequently?

**Comment by yegor256** [comment]
@dmzaytsev for the file creation time, submit a ticket to https://github.com/yegor256/s3auth

**Comment by dmzaytsev** [comment]
@yegor256 let's left it as is

>@dmzaytsev they are created every 10 minutes... let's make them less frequently?

**Comment by dmzaytsev** [comment]
@yegor256 is it eat the memory right now?
dumps not too big

**Comment by yegor256** [comment]
@dmzaytsev well, I restart it every 20 minutes... I can stop that and the memory leak will show up... stopped. let's see

**Comment by dmzaytsev** [comment]
@yegor256 the biggest file is
![image](https://cloud.githubusercontent.com/assets/9972909/13329885/33576980-dc18-11e5-9be0-678dc6bab41c.png)

**Comment by dmzaytsev** [comment]
@yegor256 but you said memory limit is 512mb right?

**Comment by dmzaytsev** [comment]
@yegor256 well..  I'm not expert in the memory dump analyzing
however as I can see there are two problems:
*  not closed streams in Takes I guess as Netbout doesn't use sockets directly
*  jcabi method cache

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev sure, the task is yours now

**Comment by yegor256** [comment]
@dmzaytsev now it's 1Gb on Heroku, and we set 512mb for the JVM

**Comment by yegor256** [comment]
@dmzaytsev I changed the interval: `heroku config:set JMAP_INTERVAL=120`

**Comment by dmzaytsev** [comment]
@yegor256 you don't restart by cron now, right?

**Comment by yegor256** [comment]
@dmzaytsev I restart every 4 hours

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.9`

**Comment by dmzaytsev** [comment]
@yegor256 I think we can stop auto restart the instance now
I don't see `java.lang.ref.Finalizer` leakages related to AWS for last two hours

however let's keep memory settings

**Comment by yegor256** [comment]
@dmzaytsev OK, stopped. what was the problem? can you explain?

**Comment by dmzaytsev** [comment]
@yegor256 is it stable now? have you seen any errors in heroku logs?

**Comment by dmzaytsev** [comment]
@yegor256 
> what was the problem? can you explain?

There were a few problems, I tried to fix one of them.
I have seen in heap dumps a lot of `java.lang.ref.Finalizer` objects that linked to AWS sockets
It seems that a `finalize()` method was deadlocked/blocked causing thread to be stuck at this object, hence the remaining of the Finalizer queue is not processed and piles up.

I have upgraded Netbout to latest AWS dependencies. 

The second big problem is that we able to remove objects from jcabi cache only by time, so we can't control the size of the cache and the memory consumption can grow up. 
By the way you have added a couple of classes to the cache recently.
The solution is to add some LRU eviction policy based on the cache size to jcabi-cache. Or we can shift to Guava cache instead.

**Comment by dmzaytsev** [comment]
@yegor256 I think easiest workaround is usage of `SoftReference` inside jcabi-cache
I just created a new [ticket](https://github.com/jcabi/jcabi-aspects/issues/214) there

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-fb1d0dd5

**Comment by yegor256** [comment]
@dmzaytsev I'm not against switching to Guava cache... but let's see what we have after that fix in jcabi cache. also, I'm restarting Heroku every 20 minutes now again

**Comment by dmzaytsev** [comment]
@yegor256 when do you plan to release that fix ?

on another note that fix should only prevent OOM

I think we have wrong design in `DyFriend`, a new `AwsTable` instance created (and cached) for each `Friend`

```
DyFriend(final Region region, final String alias) {
        this.table = region.table(DyAliases.TBL);
        this.name = alias;
    }
```
as result we have 135000 copies of AwsTable (and open sockets to Dynamo server)
I guess some bout have too many friends. Deletion of that bout should help for now

Is jcabi dynamo able to use a kind of a connection pool ?

is creation of a `com.jcabi.dynamo.Table` is cheap operation? Can we create the table before request and close then ?


![image](https://cloud.githubusercontent.com/assets/9972909/13377790/40ec7068-de0c-11e5-982a-f32d806665fa.png)

**Comment by yegor256** [comment]
@dmzaytsev it's an interesting catch... looks like that is the problem. let me investigate a bit

**Comment by dmzaytsev** [comment]
@yegor256 yep, also that's why we have a huge Finalizers queue

**Comment by dmzaytsev** [comment]
@yegor256 on the side note
it would be good to have a monitoring tool
Heroku offers hosted Graphite https://elements.heroku.com/addons/hostedgraphite (with Grafana dashboard)
Netbout can collect some metrics and send the metrics to the Graphite instance

**Comment by yegor256** [comment]
@dmzaytsev sure, let's use it. what do you need me to do?

**Comment by dmzaytsev** [comment]
@yegor256 I don't know right now
API key at least

**Comment by yegor256** [comment]
@dmzaytsev see #1057

**Comment by yegor256** [comment]
@dmzaytsev what is API key? where exactly to get it?

**Comment by dmzaytsev** [comment]
@yegor256 see https://devcenter.heroku.com/articles/hostedgraphite#provisioning-the-add-on
```
heroku config:get HOSTEDGRAPHITE_APIKEY
deadbeef-dead-beef-fade-feedbeefdead
```
> @dmzaytsev what is API key? where exactly to get it?

we don't need to do it right now
I think it should be added to MANIFEST later

if you prefer a free plan
we need ten metrics to collect

**Comment by yegor256** [comment]
@dmzaytsev done:

```
$ heroku addons:create hostedgraphite
Creating hostedgraphite-vertical-52349... done, (free)
Adding hostedgraphite-vertical-52349 to netbout... done
Setting HOSTEDGRAPHITE_APIKEY and restarting netbout... done, v118
Use `heroku addons:docs hostedgraphite` to view documentation.
/code/netbout$ heroku config:get HOSTEDGRAPHITE_APIKEY
... skipped ...
```

I put the key into `settings.xml`, which is available for rultor. It's called `${graphite.key}`

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.11`

**Comment by dmzaytsev** [comment]
@yegor256 please do the same for snapshot-netbout

**Comment by yegor256** [comment]
@dmzaytsev done:

```
$ heroku addons:create hostedgraphite --app netbout-snapshot
Creating hostedgraphite-horizontal-69379... done, (free)
Adding hostedgraphite-horizontal-69379 to netbout-snapshot... done
Setting HOSTEDGRAPHITE_APIKEY and restarting netbout-snapshot... done, v141
Use `heroku addons:docs hostedgraphite` to view documentation.
/code/netbout$ heroku config:get HOSTEDGRAPHITE_APIKEY --app netbout-snapshot
a17ee511-13c7-4253-a570-4987dd54bd4a
```

**Comment by dmzaytsev** [comment]
@yegor256 let's check the new release

**Comment by yegor256** [comment]
@dmzaytsev I turned off the restarting daemon... let's see what will happen in the next few hours

**Comment by dmzaytsev** [comment]
@yegor256 is it stable now?
do you see error messages in heroku logs?

**Comment by yegor256** [comment]
@dmzaytsev no, it's not... I had to turn the restarter ON again. I will monitor it in a few days again and will report here

**Comment by dmzaytsev** [comment]
@karato I need more time

**Comment by karato** [comment]
> @karato I need more time

@dmzaytsev OK, take your time

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.16`

**Comment by dmzaytsev** [comment]
@yegor256 let's try turn off the restarting daemon
I switched to latest jcabi-aspect that should use SoftReferences to prevent OutOfMemoryError

**Comment by yegor256** [comment]
@dmzaytsev turned it off

**Comment by dmzaytsev** [comment]
@yegor256 did you see "Error R14 (Memory quota exceeded)" in heroku logs after the restarting daemon has been turned off?

**Comment by yegor256** [comment]
@dmzaytsev no, I don't see it any more, thanks!

**Comment by yegor256** [comment]
@dmzaytsev thanks for finding the cause of the problem and for the fix!

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #1098

**Comment by dmzaytsev** [comment]
@yegor256 would it possible to get extra payment ? Because I have spent much more time than 30 min on this issue

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 82812926. Thanks for your contribution, **30 mins** was added to your account, payment ID is `82812939`, 977 hours and 20 mins spent total. +30 to your rating, your total score is [+2807](http://www.netbout.com/b/35166?open=rating)
