### ISSUE TITLE
Cobertura-maven-plugin doesn't generate xml report.

### ISSUE THREAD

**Issue by 2686747** [yegor256/netbout#1055]
It seems like cobertura-maven-plugin doesn't generate xml report (see [log](http://www.rultor.com/t/7215-189617466)) and as result https://github.com/yegor256/netbout/issues/1032#issuecomment-189618572

**Comment by dmzaytsev** [comment]
@karato  valid bug

**Comment by karato** [comment]
> @karato  valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@2686747 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@2686747 thank you for the ticket reported, I topped your account for 15 mins, transaction `56d2d91a313c2b3e50000312`

**Comment by 2686747** [comment]
@karato i can take this issue and resolve with #1032

**Comment by karato** [comment]
> @karato i can take this issue and resolve with #1032

@2686747 you should ask project architect for this (@dmzaytsev)

**Comment by dmzaytsev** [comment]
@2686747 the ticket performer and ticket resolver should be different persons

**Comment by 2686747** [comment]
@dmzaytsev No problems. I seen just §29. By the way, i have some ideas for resolver.

**Comment by dmzaytsev** [comment]
@2686747 it would be great if you can share your ideas

**Comment by 2686747** [comment]
@dmzaytsev Try update cobertura-maven-plugin to last version

**Comment by dmzaytsev** [comment]
@2686747 thank you

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.12`

**Comment by 2686747** [comment]
@dmzaytsev  is it solved? i have some fixes

**Comment by dmzaytsev** [comment]
@2686747 it's not solved yet as you can see above

**Comment by 2686747** [comment]
@dmzaytsev please, see #1065.

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.13`

**Comment by dmzaytsev** [comment]
@2686747 weird `com.github.github:site-maven-plugin:0.10:site` has been used instead of `0.12` after your PR.
would you like fix it in another ticket? 
I can assign you

**Comment by 2686747** [comment]
@dmzaytsev sure, thanks.

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by 2686747** [comment]
@karato @dmzaytsev it's resolved ( #1065 , #1069), can i close it?

**Comment by dmzaytsev** [comment]
@2686747 just close it by yourself
