### ISSUE TITLE
Netbout monitoring

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#1067]
Let's use [Metrics](http://metrics.dropwizard.io/3.1.0/) to monitor Netbout.
We can start with [JVM Instrumentation](http://metrics.dropwizard.io/3.1.0/manual/jvm/) and a reporting to [HostedGraphite](https://devcenter.heroku.com/articles/hostedgraphite) using [GraphiteReporter](http://metrics.dropwizard.io/3.1.0/manual/graphite/)
API key for Heroku graphite can be found in settings.xml, which is available for rultor. It's called ${graphite.key}

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 30 mins, payment 79244819
