### ISSUE TITLE
upgrade github maven plugin

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#1069]
let's upgrade github maven plugin to `0.12`

See https://github.com/yegor256/netbout/issues/1055#issuecomment-191572079 for details

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato assign @2686747 please

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@dmzaytsev attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@dmzaytsev thanks a lot for reporting, **30 mins** added to your acc, pmt ID `79248278`

**Comment by karato** [comment]
> @karato assign @2686747 please

@dmzaytsev OK @2686747 please go ahead, this task is yours

**Comment by 2686747** [comment]
@dmzaytsev see  #1071, please

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.22.14`

**Comment by dmzaytsev** [comment]
@2686747 perfect, thanks

**Comment by 2686747** [comment]
@dmzaytsev can we close this, #1055, #1032?

**Comment by dmzaytsev** [comment]
@2686747 thanks

**Comment by dmzaytsev** [comment]
@2686747 you should ask for close in these tickets and mention PRs which fixed the issues

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@2686747 paied 10 mins to @ypshenychka for QA review (payment ID is `79946068`)

Thanks for your contribution, **30 mins** was added to your account, payment ID is `56e175d4ebbe7b71a6000017`, 90 hours and 11 mins spent total

+30 added to your rating, at the moment it is: [+76](http://www.netbout.com/b/36452?open=rating)

**Comment by 2686747** [comment]
@karato thank you

**Comment by karato** [comment]
> @karato thank you

@2686747 sure, no problem
