### ISSUE TITLE
XSS vulnerability in bouts

### ISSUE THREAD

**Issue by 2686747** [yegor256/netbout#1076]
Can execute javascript by <img onload>
![2016 03 07-22 28 01 677820469-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13580636/3e1a17e2-e4b4-11e5-83d6-3a254d9c8122.jpg)
![2016 03 07-22 28 17 714157787-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13580637/3e4e4f1c-e4b4-11e5-8797-b0e4b94bb8b9.jpg)

**Comment by dmzaytsev** [comment]
@2686747 did you test it on http://snapshot.netbout.com?
I think it fixed already

**Comment by 2686747** [comment]
@dmzaytsev yes, did it

**Comment by dmzaytsev** [comment]
@2686747 thanks

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@2686747 there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@2686747 thanks for tis bug, I topped your account for 15 mins, transaction `56dece47e2989526460000f8`
