### ISSUE TITLE
DyBout.updated() not implemented correctly.

### ISSUE THREAD

**Issue by wild-lotus** [yegor256/netbout#1077]
In `DyBout`, `updated()` method is delegating in `date()` method:

```
    @Override
    public Date date() throws IOException {
        return new Date(
            Long.parseLong(
                this.item.get(DyFriends.ATTR_UPDATED).getN()
            )
        );
    }

    @Override
    public Date updated() throws IOException {
        return this.date();
    }
```

This is incorrect, since `date()` should be getting the creation time and `updated()` the update time. Please implement `updated()` correctly.

**Comment by karato** [comment]
@dmzaytsev dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)
