### ISSUE TITLE
Can't kick (with mouse) aliases from bouts at main page except bottom bout

### ISSUE THREAD

**Issue by 2686747** [yegor256/netbout#1084]
If you have few bouts
![2016 03 11-01 55 27 895258190-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13687712/11dd4970-e72e-11e5-9a15-4c0161a8ae86.jpg)

you can't kick any alias because alias popup  hides when mouse pointer leaves alias icon. All (except #528) is fine with bottom bout.

**Comment by karato** [comment]
@dmzaytsev please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))
