### ISSUE TITLE
Alias stays in the bout after kick

### ISSUE THREAD

**Issue by 2686747** [yegor256/netbout#1085]
In conversation 
![2016 03 11-02 19 26 351460552-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13688051/49990348-e730-11e5-915b-62edd3a4887c.jpg)
you try to kick somebody
![2016 03 11-02 19 38 435657304-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13688067/6469b622-e730-11e5-8c2b-63e4c74151dd.jpg)
but this alias stays in the bout, can post message and do other things.
![2016 03 11-02 20 03 770062251-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13688104/a08160f6-e730-11e5-8c57-a8233287856a.jpg)
You see his messages as messages from "someone"
![2016 03 11-02 20 13 668168986-max-vaio-arch](https://cloud.githubusercontent.com/assets/8187855/13688120/b3a62e82-e730-11e5-8879-6f9f703261a5.jpg)

**Comment by 2686747** [comment]
P.S. Some time ago (around 5 min) kicked alias can't open this bout and sees #834

**Comment by karato** [comment]
@dmzaytsev please do something about this issue

**Comment by dmzaytsev** [comment]
@2686747 kickout is deprecated feature
