### ISSUE TITLE
Coupling between RtXXX and XeXXX classes on directive names

### ISSUE THREAD

**Issue by wild-lotus** [yegor256/netbout#1088]
For example, between `XeAttachment` and `RtAttachment`:
- In `XeAttachment.make()` we create a directive using literal `"unseen"`.
- In `RtAttachment.unseen()` we read that directive using xpath and `"unseen/text()"`.
  There is coupling of the literal `"unseen"`. You might change the name of the directive, inadvertently creating an error on `RtAttachment` (and potentially in more places). 

This should be avoided for all directives created by Xembly classes and read anywhere else.

I know that we do not enforce the use of public static variables, that's why I find it even more interesting to see how this can be fixed.

**Comment by karato** [comment]
@dmzaytsev please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))
