### ISSUE TITLE
DyAttachment.java:166-172: An attribute for the creation...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#1090]
Puzzle `839-90f22678` in `netbout-web/src/main/java/com/netbout/dynamo/DyAttachment.java:166-172` has to be resolved: An attribute for the creation time must be added to the attachment item in the remote db. Until then, this method crashes. Once it is done, this must be developed: - Remove @Ignore from DyAttachmentITCase.obtainsCreationDate(). - Add directive for date in XeAttachment.make(). - Properly implement RtAttachment.date() to retrieve date from request. - Remove @Ignore from RtAttachmentsITCase.obtainsCreationDate().... The puzzle was created by Carlos Ginés on 9-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@ail-man this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by ail-man** [comment]
@karato, I assume that before the fix I need to setup my environment (I newbee in the project) and run it properly. I try to do it by myself, but it fails.Who can help me with it?

**Comment by ail-man** [comment]
@karato sorry, already figured out

**Comment by ail-man** [comment]
@karato I do not understand the statement of the problem? What should be done: prevent crashes of DyAttachment.date() or develop XeAttachment.make() and RtAttachmentsITCase.obtainsCreationDate()?

**Comment by karato** [comment]
> @karato, I assume that before the fix I need to setup my environment (I newbee in the project) and run it properly. I try to do it by myself, but it fails.Who can help me with it?

@ail-man check this out: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by karato** [comment]
> @karato sorry, already figured out

@ail-man OK

**Comment by karato** [comment]
> @karato I do not understand the statement of the problem? What should be done: prevent crashes of DyAttachment.date() or develop XeAttachment.make() and RtAttachmentsITCase.obtainsCreationDate()?

@ail-man you better address your questions to the architect of the project (@dmzaytsev)

**Comment by ail-man** [comment]
@karato please assign this puzzle someone else

**Comment by karato** [comment]
> @karato please assign this puzzle someone else

@ail-man 30 points deducted from your rating

**Comment by karato** [comment]
> @karato please assign this puzzle someone else

@ail-man no problem, I will try to find somebody else

**Comment by karato** [comment]
@carlosgines this is your task

**Comment by CarlosGines** [comment]
@karato Please check PR #1097

**Comment by CarlosGines** [comment]
@karato Please update labels of this ticket too, removing ail-man label and adding mine.

**Comment by karato** [comment]
> @karato Please check PR #1097

@carlosgines thank you!

**Comment by CarlosGines** [comment]
@karato PR #1097 successfully merged and closed. Please close this ticket.

**Comment by karato** [comment]
@dmzaytsev 2 puzzles were created here: `1090-b1fba4c1`, `1090-d49470f5`/#1105

**Comment by karato** [comment]
@dmzaytsev The issue should be closed..

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@carlosgines paied 10 mins to @ypshenychka for QA review (payment ID is `82799661`)

Much obliged! I have added **30 mins** to your account in payment "AP-8LJ60695TA182764G", 209 hours and 19 mins spent

added +30 to your rating, now it is equal to [+255](http://www.netbout.com/b/36645?open=rating)

**Comment by karato** [comment]
@dmzaytsev last 2 puzzles `1090-b1fba4c1`/#1106, `1090-d49470f5`/#1105 that originated from here were solved

**Comment by 0pdd** [comment]
@karato all 2 puzzles are solved here: [#1153](https://github.com/yegor256/netbout/issues/1153), [#1154](https://github.com/yegor256/netbout/issues/1154).
