### ISSUE TITLE
DyMessages.java:197-202: HttpException seems not really appropriate...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#1096]
Puzzle `1094-571b0dd7` in `netbout-web/src/main/java/com/netbout/dynamo/DyMessages.java:197-202` has to be resolved: HttpException seems not really appropriate here in database layer. I think we have to throw something like BoutNotFoundException and process its somewhere in web layer. Pay attention that we should also change a test DyMessagesITCase.exceptionIfBoutNotFound() which tests a presence of HttpException.... The puzzle was created by 2686747 on 27-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@dmzaytsev since the ticket has no milestone I set it to 3.1

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all

**Comment by karato** [comment]
@dmzaytsev Closing, thanks all
