### ISSUE TITLE
DyAttachments.java:52-54: No public static literals are...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#1105]
Puzzle `1090-d49470f5` in `netbout-web/src/main/java/com/netbout/dynamo/DyAttachments.java:52-54` has to be resolved: No public static literals are recommended according to our methodology. This class should be refactored to not contain any of them. See: http://www.yegor256.com/2015/07/06/public-static-literals.html... The puzzle was created by Carlos Ginés on 4-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
@dmzaytsev attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@dmzaytsev I am closing it, thanks all
