### ISSUE TITLE
RtAttachment.java:53-55: There is code duplication in...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#1106]
Puzzle `1090-b1fba4c1` in `netbout-client/src/main/java/com/netbout/client/RtAttachment.java:53-55` has to be resolved: There is code duplication in public methods in this class: ctype(), etag(), unseen(), date(), author(), read() and write(). Please refactor to avoid it.... The puzzle was created by Carlos Ginés on 4-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I will find someone else, no problem

**Comment by karato** [comment]
@dmzaytsev Thanks, closing it now.
