### ISSUE TITLE
Failure to authenticate with google+

### ISSUE THREAD

**Issue by wtpayne** [yegor256/netbout#1108]
I am trying to sign in to the service using my google profile from within a corporate network. 

One possibility is that the google authentication mechanism is blocked by firewall / access control policy (because the google social network is blocked too). 

Another possibility is a man-in-the-middle "attack" from the security appliance sitting at the edge of the network. Given these impediments, I would not be surprised (or disappointed) that the authentication failure occurred ... but an appropriate error message may provide a better user experience. "authentication provider not reachable" or "security of connection to authentication provider not guaranteed" or some such. 

Here is the stack trace:

    java.lang.IllegalStateException: [GET http://www.netbout.com/?PsByFlag=PsGoogle&code=4%2FhdL34R4gt_H9ieb9wnZLaxNsFxv4t4tQFrmwfWXATcw&state=http%3A%2F%2Fwww.netbout.com%2F] failed in 106ms: HTTP response status is not equal to 200:
    400 Bad Request [https://accounts.google.com/o/oauth2/token]
    Transfer-Encoding: chunked
    Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
    Server: GSE
    X-Content-Type-Options: nosniff
    P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
    Date: Wed, 06 Apr 2016 18:11:13 GMT
    Alternate-Protocol: 443:quic
    Accept-Ranges: none
    X-Frame-Options: SAMEORIGIN
    Cache-Control: private, max-age=0
    Vary: Accept-Encoding
    Set-Cookie: NID=78=Wwe85yi0IiKDQWqcpNz0J74n5IuvvGOhORZcdpmZ0-T3lMZw35_syfAKZOVP-1MfW8-NWjkTBfQIlJiv5bTjybJDVFF1smF55FZbEMMHkYpDTk4IWK6V1r1kMYlm3cwR;Domain=.google.com;Path=/;Expires=Thu, 06-Oct-2016 18:11:13 GMT;HttpOnly
    Expires: Wed, 06 Apr 2016 18:11:13 GMT
    X-XSS-Protection: 1; mode=block
    Content-Type: application/json; charset=utf-8

    {
      "error" : "invalid_grant",
      "error_description" : "Invalid code."
    }
    Expected: HTTP response with status 200
         but: was <400 Bad Request [https://accounts.google.com/o/oauth2/token]
    Transfer-Encoding: chunked
    Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
    Server: GSE
    X-Content-Type-Options: nosniff
    P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
    Date: Wed, 06 Apr 2016 18:11:13 GMT
    Alternate-Protocol: 443:quic
    Accept-Ranges: none
    X-Frame-Options: SAMEORIGIN
    Cache-Control: private, max-age=0
    Vary: Accept-Encoding
    Set-Cookie: NID=78=Wwe85yi0IiKDQWqcpNz0J74n5IuvvGOhORZcdpmZ0-T3lMZw35_syfAKZOVP-1MfW8-NWjkTBfQIlJiv5bTjybJDVFF1smF55FZbEMMHkYpDTk4IWK6V1r1kMYlm3cwR;Domain=.google.com;Path=/;Expires=Thu, 06-Oct-2016 18:11:13 GMT;HttpOnly
    Expires: Wed, 06 Apr 2016 18:11:13 GMT
    X-XSS-Protection: 1; mode=block
    Content-Type: application/json; charset=utf-8

    {
      "error" : "invalid_grant",
      "error_description" : "Invalid code."
    }>
        at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
        at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
        at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
        at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
        at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.http.BkBasic.print(BkBasic.java:100)
        at org.takes.http.BkBasic.accept(BkBasic.java:78)
        at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
        at org.takes.http.BkWrap.accept(BkWrap.java:52)
        at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
        at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
    400 Bad Request [https://accounts.google.com/o/oauth2/token]
    Transfer-Encoding: chunked
    Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
    Server: GSE
    X-Content-Type-Options: nosniff
    P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
    Date: Wed, 06 Apr 2016 18:11:13 GMT
    Alternate-Protocol: 443:quic
    Accept-Ranges: none
    X-Frame-Options: SAMEORIGIN
    Cache-Control: private, max-age=0
    Vary: Accept-Encoding
    Set-Cookie: NID=78=Wwe85yi0IiKDQWqcpNz0J74n5IuvvGOhORZcdpmZ0-T3lMZw35_syfAKZOVP-1MfW8-NWjkTBfQIlJiv5bTjybJDVFF1smF55FZbEMMHkYpDTk4IWK6V1r1kMYlm3cwR;Domain=.google.com;Path=/;Expires=Thu, 06-Oct-2016 18:11:13 GMT;HttpOnly
    Expires: Wed, 06 Apr 2016 18:11:13 GMT
    X-XSS-Protection: 1; mode=block
    Content-Type: application/json; charset=utf-8

    {
      "error" : "invalid_grant",
      "error_description" : "Invalid code."
    }
    Expected: HTTP response with status 200
         but: was <400 Bad Request [https://accounts.google.com/o/oauth2/token]
    Transfer-Encoding: chunked
    Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
    Server: GSE
    X-Content-Type-Options: nosniff
    P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
    Date: Wed, 06 Apr 2016 18:11:13 GMT
    Alternate-Protocol: 443:quic
    Accept-Ranges: none
    X-Frame-Options: SAMEORIGIN
    Cache-Control: private, max-age=0
    Vary: Accept-Encoding
    Set-Cookie: NID=78=Wwe85yi0IiKDQWqcpNz0J74n5IuvvGOhORZcdpmZ0-T3lMZw35_syfAKZOVP-1MfW8-NWjkTBfQIlJiv5bTjybJDVFF1smF55FZbEMMHkYpDTk4IWK6V1r1kMYlm3cwR;Domain=.google.com;Path=/;Expires=Thu, 06-Oct-2016 18:11:13 GMT;HttpOnly
    Expires: Wed, 06 Apr 2016 18:11:13 GMT
    X-XSS-Protection: 1; mode=block
    Content-Type: application/json; charset=utf-8

    {
      "error" : "invalid_grant",
      "error_description" : "Invalid code."
    }>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
        at org.takes.facets.auth.social.PsGoogle.token(PsGoogle.java:173)
        at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
        at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107)
        at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
        at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
        at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
        at org.takes.tk.TkWrap.act(TkWrap.java:61)
        at org.takes.facets.forward.TkForward.act(TkForward.java:68)
        at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
        ... 21 more

**Comment by karato** [comment]
@dmzaytsev please do something about this issue

**Comment by ekondrashev** [comment]
@dmzaytsev I believe it is pretty similar to #1089. Is it possible to prioritise this, I'm personally failing to login with my google account for pretty long time.

**Comment by ekondrashev** [comment]
@yegor256 any chance to give this a go? Can't login to netbout for several months already:(

**Comment by dmzaytsev** [comment]
@ekondrashev actually that problem related to Google account settings
only @yegor256 can change these settings

**Comment by ekondrashev** [comment]
@dmzaytsev could you please elaborate, not sure I understand.. I was able to login with Google account and after some time it started to respond with `Bad request`. I can assume that is because of me changed the password. No other reasons I can think of, but you're saying something different..?

**Comment by dmzaytsev** [comment]
@ekondrashev Netbout uses PsGoogle from Takes, PsGoogle uses G+ api in turn to fetch avatar and other info. G+ api not enabled for the Netbout's acount so the last api call causes an exception Bad request.

**Comment by ekondrashev** [comment]
@dmzaytsev and what is the reason for the G+ api not being enabled?

**Comment by dmzaytsev** [comment]
@ekondrashev Invalid link to g+ api was used in previous releases of Takes, They have fixed this bug and the api call throws an exception now. We can't use old release of Takes for some reasons.
Yegor should just click on "enable" for G+APi in his Google console

**Comment by ekondrashev** [comment]
@dmzaytsev ok, so, let ping @yegor256 to resolve this issue

**Comment by ekondrashev** [comment]
@yegor256 ping, could you please comment what @dmzaytsev said is possible:
 > Yegor should just click on "enable" for G+APi in his Google console

**Comment by yegor256** [comment]
@ekondrashev @dmzaytsev I've enabled Google+ API in Google Console, a minute ago

**Comment by ekondrashev** [comment]
@yegor256 just tried to login and got
```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by ekondrashev** [comment]
@yegor256 second try went fine though, I'm finally in:)

**Comment by yegor256** [comment]
@ekondrashev can you please logout and try to login again?

**Comment by ekondrashev** [comment]
@yegor256 done, no problems this time.

**Comment by yegor256** [comment]
@wtpayne please, close the ticket if authentication works

**Comment by wtpayne** [comment]
Authentication works from my current location. I'll try it again from within the corporate network later today, and if that works too, I'll close the ticket.

Many thanks.

**Comment by wtpayne** [comment]
Works from the corporate network too!
