### ISSUE TITLE
introduce redundancy in the DynamoDB

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#1109]
I think our current design of the persistence layer is not good enough. We keep data in a non-redundant way in DynamoDB and intensively cache it on Java level. Instead, we should duplicate it as much as necessary in DynamoDB and make sure Java is making just a few requests to the DynamoDB. They still may be cached, but there should be just a few of them.

**Comment by karato** [comment]
@yegor256 I added `indie` tag to this ticket

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-1a933d28
