### ISSUE TITLE
Why reserve an array with 16 objects from the start

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1110]
Inside method [RtMessages.search(term)](https://github.com/yegor256/netbout/blob/dad50237fd55646fdb58eeda56d0f87982c959c0/netbout-client/src/main/java/com/netbout/client/RtMessages.java), why reserve an array with 16 objects from the start? I think a result of 16 messages would be rather rare. I would simply do ``final List<Message> result = new ArrayList<Message>()``;

**Comment by karato** [comment]
@dmzaytsev dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@amihaiemil actually it is a kind of checkstyle suppression.
Checkstyle doesn't allow `ArrayList` declaration without capacity

**Comment by amihaiemil** [comment]
@dmzaytsev ok : D
