### ISSUE TITLE
Details about impediments in netbout agenda

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1111]
In the "agenda" tab you see all the task listed and on the "details" column you can see how many (if any) impediments are there. 

I think it would be nice to be able to click on it and see some sort of summary (what impediments are there?). 

If it's your task from the start you should know it already, but if you inherited the task and it has already a long conversation with more related tickets, then it would be a useful feature to have.

![image](https://cloud.githubusercontent.com/assets/6305156/16070675/be429452-32df-11e6-8560-0713bc6d3910.png)

**Comment by dmzaytsev** [comment]
@amihaiemil actually this is out of the scope of the project . 
I would suggest you to ask @yegor256 right in Netbout

**Comment by amihaiemil** [comment]
@dmzaytsev im going to leave this open a bit, maybe he replies here.
