### ISSUE TITLE
referenced classes (.jar files) with loggable annotation doesn't work

### ISSUE THREAD

**Issue by malele86** [yegor256/netbout#1113]
Hey,

my maven project:
[prj 1] maven web app
[prj 2] maven java app 

--> prj 1 has a reference to prj 2 !

prj1 and prj 2 has a class which is annotated with @Loggable.

After build + deploy (glassfish) for prj 1 logging is working like a charm but not for prj 2.

Why?
Is this not supported or does i have a misunderstanding (i am new @ java world comes from .net world ;) )..?

If you need further information please talk to me, thank you in advance.

**Comment by dmzaytsev** [comment]
@malele86 do you mean [Jcabi Loggable](http://aspects.jcabi.com/annotation-loggable.html) ?
if so I would suggest you ask here https://github.com/jcabi/jcabi-aspects/issues

**Comment by malele86** [comment]
Yes you are right! Thanks...
