### ISSUE TITLE
transient is not needed anymore

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#1114]
`transient` requirement has been removed from qulice. Please remove it everywhere where it was not added explicitly.

Also remove `of` parameter from all `@EqualsAndHashCode`, it was there because we had transient fields and we constantly were forgeting to add new fields there, now it won't be needed. (check tests for `EqualsVerifier.ignoredFields` for cases where `of` is still needed).

Also in case of tests that check equals/hashCode contract using `EqualsVerifier`, remove `suppress(Warning.TRANSIENT_FIELDS)`.

**Comment by karato** [comment]
@dmzaytsev please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@krzyk since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@krzyk thanks for tis bug, I topped your account for 15 mins, transaction `95597232`
