### ISSUE TITLE
Switch to jacoco maven plugin

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#1118]
Currently this project uses cobertura plugin for code coverage.
Cobertura requires a separate test phase for calculation of the coverage, which increases the build time.
Jacoco on the other hand is integrated into the standard phases (uses agent to connect to surefire process), so the build process won't need to run the unit tests twice - should speed up the builds in travis and rultor.

Another advantage is that maybe we will get rid of unstable coverage numbers (if they are caused by cobertura).

Jacoco maven plugin documentation: http://eclemma.org/jacoco/trunk/doc/maven.html

**Comment by karato** [comment]
@dmzaytsev please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@krzyk milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@krzyk thanks a lot for reporting, **15 mins** added to your acc, pmt ID `97263590`

**Comment by amihaiemil** [comment]
@dmzaytsev Can I have this task?

**Comment by dmzaytsev** [comment]
@karato assign @amihaiemil please

**Comment by karato** [comment]
> @karato assign @amihaiemil please

@dmzaytsev done. @amihaiemil you are assigned to this task. please proceed...

**Comment by amihaiemil** [comment]
@karato PR #1129 is for this

**Comment by karato** [comment]
> @karato PR #1129 is for this

@amihaiemil thanks for that

**Comment by amihaiemil** [comment]
@krzyk the PR was merged; please close this issue if it's ok with you

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato  Looks good!

**Comment by karato** [comment]
> @karato  Looks good!

@elenavolokhova thanks a lot :)

**Comment by karato** [comment]
@amihaiemil 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 101922351... done, I added **30 mins** in payment `AP-7U21695605532842X`, 263 hours and 10 mins spent to complete this... +30 added to your rating, at the moment it is: [+519](http://www.netbout.com/b/36402?open=rating)
