### ISSUE TITLE
Project uses outdated jcabi-parent

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#1119]
jcabi-parent used by the project is 0.32.1 but the current one is 0.45, please update it and fix all possible problems that might be caused by this upgrade.

Also remove an incorrect puzzle in pom.xml that wasn't parsed correctly by pdd (`<!--@todo #909:30min jcabi-parent used by Netbout is pretty outdated, `).

**Comment by karato** [comment]
@dmzaytsev take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@krzyk since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@krzyk thanks a lot for reporting, **15 mins** added to your acc, pmt ID `97259640`

**Comment by amihaiemil** [comment]
@dmzaytsev can you assign me here pls?

**Comment by dmzaytsev** [comment]
@karato assign @amihaiemil please

**Comment by karato** [comment]
> @karato assign @amihaiemil please

@dmzaytsev done. @amihaiemil the task is yours, please go ahead

**Comment by amihaiemil** [comment]
@karato PR #1124 is for this issue

**Comment by karato** [comment]
> @karato PR #1124 is for this issue

@amihaiemil thanks for that

**Comment by amihaiemil** [comment]
@krzyk PR #1124 was merged and closed; can u close this ticket? Thanks

**Comment by amihaiemil** [comment]
@krzyk ping

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by amihaiemil** [comment]
@karato ping

**Comment by amihaiemil** [comment]
@dmzaytsev @krzyk Do you know maybe if something is not working fine? Neither karator nor davvd answer.

karato should assign 2 tasks to me in netbout, davvd 1 task in qulice and this issue should be paid.

**Comment by krzyk** [comment]
@amihaiemil you usually have to wait longer for PMs in the open source projects (few days)

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.
> 

@ypshenychka thanks for the review

**Comment by karato** [comment]
@amihaiemil 10 mins was added to the account of @ypshenychka (for QA review), in transaction 99403416; **30 mins** was added to your account, many thanks for your contribution (payment AP-73W28244WA8950218)! The task took 87 hours and 20 mins.; +30 added to your rating, at the moment it is: [+458](http://www.netbout.com/b/36402?open=rating)
