### ISSUE TITLE
Let's upgrade to qulice 0.17.1

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#1120]
Project uses 0.16.2 version of qulice, which is quite old right now.
Upgrade to 0.17.1 and fix all newly reported errors like ones from following issues:

* teamed/qulice#659 Prohibit 'public static' methods
* teamed/qulice#715 Enforce usage of diamond operator
* teamed/qulice#741 Unification if checks display messages
* teamed/qulice#701 Duplicated PMD and Checkstyle checks for multiple string literals

**Comment by karato** [comment]
@dmzaytsev please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@krzyk I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@krzyk thanks for reporting! I topped your account for 15 mins, transaction 97253132

**Comment by amihaiemil** [comment]
@dmzaytsev Can I have this as well? I did it locally and it works. Some of the found defects I fixed, some I escaped (e.g. some duplicated strings in tests were already escaped for qulice, I added escape for pmd). Also, I escaped 2 where there were todos already.

**Comment by dmzaytsev** [comment]
@amihaiemil sure

**Comment by dmzaytsev** [comment]
@karato assign @amihaiemil please

**Comment by karato** [comment]
> @karato assign @amihaiemil please

@dmzaytsev OK @amihaiemil please proceed, this task is yours

**Comment by amihaiemil** [comment]
@karato PR #1127 is for this

**Comment by karato** [comment]
> @karato PR #1127 is for this

@amihaiemil thank you

**Comment by amihaiemil** [comment]
@krzyk the pr has been merged. Can you close this issue? Thanks

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.
> 

@ypshenychka many thanks

**Comment by karato** [comment]
@amihaiemil I added 10 mins to @ypshenychka (for QA review) in transaction 99369650

I added **38 mins** to your account, many thanks for working with the project (AP-4CY72412JH523225F)! The completion time here was 48 hours and 24 mins.

there is a bonus for fast delivery (m=2904)

+38 to your rating, your total score is [+428](http://www.netbout.com/b/36402?open=rating)
