### ISSUE TITLE
Download report file-format

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1121]
The content of all the pages bellow can be downloaded as a report using the little clowd icon on the right:

![image](https://cloud.githubusercontent.com/assets/6305156/17847949/7ed682c4-6859-11e6-9d66-a6794f875353.png)

However, the file-format cannot be opened in Windows (I'm running Windows 7, but I assume it's the same in all of them).
![image](https://cloud.githubusercontent.com/assets/6305156/17848001/d47d3b14-6859-11e6-9f9f-ab41458081d0.png)
![image](https://cloud.githubusercontent.com/assets/6305156/17848011/e136a2d2-6859-11e6-8907-904c23df7fc2.png)

Maybe there are some programs that can associate and open the file format, which is currently "text/x-markdown", but certainly not the mainstream ones. I think other format like .csv, .xlsx, .xml etc would be much more suitable. 

It might be a good thing to have a drop-down which would allow a choice of file formats.

**Comment by karato** [comment]
@dmzaytsev please dispatch this issue

**Comment by amihaiemil** [comment]
@dmzaytsev ping

**Comment by dmzaytsev** [comment]
@amihaiemil actually the issue out of the scope of the project
ask @yegor256

**Comment by amihaiemil** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@dmzaytsev we can make it downloadable in HTML (we can easily convert to HTML from Markdown, right)
