### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1122]
There are some [outdated dependencies](https://www.versioneye.com/user/projects/561ac5eca193340f2f001222), including some jcabi libs.

**Comment by karato** [comment]
@dmzaytsev please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by amihaiemil** [comment]
@dmzaytsev what do you think here?

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@amihaiemil milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@amihaiemil thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-96711558B8879473D`
