### ISSUE TITLE
Low test coverage

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1123]
Test coverage is really low (48%). We should start writing more unit tests. It can start from this issue - pick a class, unit test it and add puzzles to other class(es) you see lacks unit tests.

**Comment by karato** [comment]
@dmzaytsev please dispatch this issue

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@amihaiemil milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@amihaiemil thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-8GX07735WU847711X`
