### ISSUE TITLE
Unit test failing every now and then

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1125]
There is a unit test, `TouchBoutTest.changesUpdateAttribute`, which fails sometimes because it has some Thread sleep and then assert in it.

It should be fixed so it doesn't fail randomly again. E.g. maybe raise the Thread.sleep value from 100 to something greater.

The test is [here](https://github.com/yegor256/netbout/blob/master/netbout-client/src/test/java/com/netbout/mock/TouchBoutTest.java)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@amihaiemil I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@amihaiemil thanks for the ticket, your account was topped for 15 mins, payment AP-3W81335326133973M
