### ISSUE TITLE
Autocomplete for invite user field

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/netbout#1126]
One might not always know the entire alias of another user, yet might want to invite them to a bout. Autocomplete for the invite field would be usefull. Maybe even search by email. So for instance my alias is "mihai", but my email is "amihaiemil@gmail.com". It would be cool to start typing for example "ami", and get my alias as suggestion.

![image](https://cloud.githubusercontent.com/assets/6305156/18118559/6061b668-6f5e-11e6-9e3b-c4b42a4221d2.png)

Also, maybe a label explaining whether it's necessary to prefix the alias with "@" or not would be nice.

**Comment by karato** [comment]
@dmzaytsev please do something about this issue

**Comment by amihaiemil** [comment]
@dmzaytsev what do you think here? :D

**Comment by dmzaytsev** [comment]
@amihaiemil I'm not sure as email is a private thing
@yegor256 what do you think?

**Comment by yegor256** [comment]
@dmzaytsev yes, it's a private thing, we shouldn't do that
