### ISSUE TITLE
DyInbox.java:134-140: DynamoDBLocal doesn't work with all...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1131]
The puzzle `1-b5151558` in [`netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java) (lines 134-140) has to be resolved: DynamoDBLocal doesn't work with all attributes in global index. If we remove this check for a local version, most tests fail. I'm not sure how to fix that. I suspect, it's a bug in DynamoDBLocal, but I don't even know how to report it to them :( Anyway, let's try to investigate and either fix property or introduce a better workaround. Pay attention that this code works correctly in production.

The puzzle was created by Yegor Bugayenko on 14-Jun-14. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
