### ISSUE TITLE
TkStartTest.java:54-57: Test case for negative scenario of...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1132]
The puzzle `610-76d661ee` in [`netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java) (lines 54-57) has to be resolved: Test case for negative scenario of TkStart should be added, e.g. when a friend is not found, the error should be reported correctly and bout creation should be discarded.

The puzzle was created by Ivan Inozemtsev on 25-May-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
