### ISSUE TITLE
RtBout.java:155-157: Implement getting subscription by...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1133]
The puzzle `682-2583dc75` in [`netbout-client/src/main/java/com/netbout/client/RtBout.java`](https://github.com/yegor256/netbout/blob/master/netbout-client/src/main/java/com/netbout/client/RtBout.java) (lines 155-157) has to be resolved: Implement getting subscription by alias. Should return subscription status for current boat, passing friend alias value using REST service call.

The puzzle was created by Eugene Kondrashev on 11-Jun-15. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
