### ISSUE TITLE
DyInbox.java:62-65: Refactor DyInbox class to avoid...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1134]
The puzzle `603-0cf011c2` in [`netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java) (lines 62-65) has to be resolved: Refactor DyInbox class to avoid suppressing of PMD.TooManyMethods and PMD.ExcessiveImports warnings. for example there are some private static methods there, those could be easily extracted.

The puzzle was created by Ivan Inozemtsev on 15-Jun-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
