### ISSUE TITLE
TkRegister.java:67-71: During the user registraton if the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1138]
The puzzle `751-6f10d03b` in [`netbout-web/src/main/java/com/netbout/rest/login/TkRegister.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/login/TkRegister.java) (lines 67-71) has to be resolved: "During the user registraton if the invite-key` param presented in the original ticket (destination url) it should decrypt that value and use it to search for alias. using that alias, you must update urn and alias to use the alias that was choosen by the user."

The puzzle was created by Mesut Özen on 25-Aug-15. 

Estimate: 30 minutes, role: D.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
