### ISSUE TITLE
MkAttachments.java:86-88: This method needs to be implemented...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1139]
The puzzle `806-1e507f57` in [`netbout-client/src/main/java/com/netbout/mock/MkAttachments.java`](https://github.com/yegor256/netbout/blob/master/netbout-client/src/main/java/com/netbout/mock/MkAttachments.java) (lines 86-88) has to be resolved: "This method needs to be implemented because it is used in tests that read bout properties. Currently, this implementation always returns 0."

The puzzle was created by bdragan on 26-Oct-15. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
