### ISSUE TITLE
TkStart.java:57-59: Solve the puzzle for build...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1140]
The puzzle `750-23d45618` in [`netbout-web/src/main/java/com/netbout/rest/TkStart.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/TkStart.java) (lines 57-59) has to be resolved: "Solve the puzzle for build mysteriously failing for this task citing a NullPointerException (See qulice issue #608 raised for the same) and then remove TkStart.java from qulice exceptions."

The puzzle was created by Prahlad Yeri on 18-Jan-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
