### ISSUE TITLE
TkStartTest.java:63-65: TkStart should not create new bout...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1141]
The puzzle `954-b453159b` in [`netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java) (lines 63-65) has to be resolved: "TkStart should not create new bout when same token is specified. When this is fixed, remove @Ignore from handlesTokens test"

The puzzle was created by clarence ho on 23-Jan-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
