### ISSUE TITLE
pom.xml:730-735: Fix findbugs errors in web Some...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1144]
The puzzle `911-1ad8e6c0` in [`netbout-web/pom.xml`](https://github.com/yegor256/netbout/blob/master/netbout-web/pom.xml) (lines 730-735) has to be resolved: "Fix findbugs errors in web Some issues may not require fixing an should be excluded. Filters in qulice 0.12 are broken, right excludes should be more granular. I think it should be resolved when #961 completed due to broken Findbugs filters in current version of Qulice"

The puzzle was created by exper0 on 15-Jan-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
