### ISSUE TITLE
NbRule.java:42-45: No public static methods are allowed....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1145]
The puzzle `1012-2dfa2c65` in [`netbout-client/src/test/java/com/netbout/client/NbRule.java`](https://github.com/yegor256/netbout/blob/master/netbout-client/src/test/java/com/netbout/client/NbRule.java) (lines 42-45) has to be resolved: "No public static methods are allowed. This class should be refactored to not contain any of them. The method get() should either be an instance method with refrence to this (to avoid checkstyle NonStaticMethodCheck) or a static but not public."

The puzzle was created by Dan Baleanu on 29-Feb-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
