### ISSUE TITLE
pom.xml:754-757: These excludes were added because of...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1146]
The puzzle `1012-7ae4ec06` in [`netbout-web/pom.xml`](https://github.com/yegor256/netbout/blob/master/netbout-web/pom.xml) (lines 754-757) has to be resolved: "These excludes were added because of the upgrade to qulice 0.16.2. The new version of qulice adds some javadocs rules and also regexp rules for imported some wrong classes which should be replaced with others."

The puzzle was created by Dan Baleanu on 18-Feb-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
