### ISSUE TITLE
Ports.java:42-44: This class should not be left as...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/netbout#1147]
The puzzle `1012-68768ab8` in [`netbout-web/src/main/java/com/netbout/misc/Ports.java`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/misc/Ports.java) (lines 42-44) has to be resolved: "This class should not be left as utility one. All methods became static because of checkstyle NonStaticMethodCheck introduced after qulice upgrade to 0.15.2 and the contructor became private."

The puzzle was created by Dan Baleanu on 25-Feb-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/netbout/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.
