### ISSUE TITLE
Dependency conflicts on com.jcabi:jcabi-log, leading to inconsistent program behaviors

### ISSUE THREAD

**Issue by HelloCoCooo** [yegor256/netbout#1159]
Hi, in **netbout/netbout-client**, there are mulptiple versions of library **com.jcabi:jcabi-log**. However, according to Maven's dependency management strategy: **_"first declaration wins"_**, only **com.jcabi:jcabi-log:0.15.1** can be loaded, and **com.jcabi:jcabi-log:0.17** will be shadowed.

As shown in the following figure, your project expects to invoke method **_<com.jcabi.log.VerboseProcess: toString()Ljava/lang/String;>_**  in library _**com.jcabi:jcabi-log:0.17**_ (along the _original dependency path_). As it has been shadowed, this method defined in **_com.jcabi:jcabi-log:0.15.1_** is actually forced to be referenced via the following invocation path (along the _actual dependency path_):

```
<com.netbout.client.RtAttachment: read()Ljava/io/InputStream;> /home/wwww/sensor/unzip/netbout-2.23/netbout-client/target/classes
<com.jcabi.http.response.XmlResponse: rel(Ljava/lang/String;)Lcom/jcabi/http/Request;> /home/wwww/.m2/repository/com/jcabi/jcabi-http/1.14.2/jcabi-http-1.14.2.jar
<com.jcabi.http.response.RestResponse: jump(Ljava/net/URI;)Lcom/jcabi/http/Request;> /home/wwww/.m2/repository/com/jcabi/jcabi-http/1.14.2/jcabi-http-1.14.2.jar
<com.jcabi.http.request.BaseRequest: header(Ljava/lang/String;Ljava/lang/Object;)Lcom/jcabi/http/Request;> /home/wwww/.m2/repository/com/jcabi/jcabi-http/1.14.2/jcabi-http-1.14.2.jar
<com.jcabi.log.VerboseProcess: toString()Ljava/lang/String;>
```

![netbout](https://user-images.githubusercontent.com/46306510/94461759-2257fa00-01ed-11eb-8a48-d1e8511cdb49.png)

Although both of these conflicting libraries contain the referenced methods (**_with the same signature_**), they have **_different implementations_**. This issue will not cause runtime crashes, but it can introduce inconsistent semantic program hehaviors----

Code snippet of **_<com.jcabi.log.VerboseProcess: toString()Ljava/lang/String;>_** in _**com.jcabi:jcabi-log:0.17**_  (shadowed but expected to invoke method):

<details><summary>detailed method body</summary>

```java
public String toString() {
        return "VerboseProcess(process=" + this.process + ", olevel=" + this.olevel + ", elevel=" + this.elevel + ", monitors=" + Arrays.deepToString(this.monitors) + ", closed=" + this.closed + ")";
    }
```

</details>

Code snippet of **_<com.jcabi.log.VerboseProcess: toString()Ljava/lang/String;>_** in _**com.jcabi:jcabi-log:0.15.1**_ (loaded version):

<details><summary>detailed method body</summary>

```java
public String toString() {
        return "VerboseProcess(process=" + this.process + ", olevel=" + this.olevel + ", elevel=" + this.elevel + ")";
    }
```

</details>

## **Dependency tree--**

[INFO] com.netbout:netbout-client:jar:2.23
[INFO] +- com.netbout:netbout-spi:jar:2.23:compile
[INFO] |  +- (com.jcabi:jcabi-urn:jar:0.9:compile - omitted for duplicate)
[INFO] |  +- (com.jcabi:jcabi-aspects:jar:0.22.4:compile - version managed from 0.22.2; omitted for duplicate)
[INFO] |  +- (com.google.guava:guava:jar:18.0:compile - omitted for duplicate)
[INFO] |  \- (org.hamcrest:hamcrest-core:jar:1.3:compile - omitted for duplicate)
[INFO] +- org.projectlombok:lombok:jar:1.14.8:provided
[INFO] +- com.h2database:h2:jar:1.4.190:compile
[INFO] +- com.jcabi:jcabi-xml:jar:0.17.1:compile
[INFO] |  +- (com.jcabi:jcabi-log:jar:0.15.1:compile - version managed from 0.17; omitted for duplicate)
[INFO] |  +- com.jcabi:jcabi-immutable:jar:1.3:compile (version managed from 1.4)
[INFO] |  |  \- (com.jcabi:jcabi-aspects:jar:0.22.4:compile - version managed from 0.17.1; omitted for duplicate)
[INFO] |  \- (commons-io:commons-io:jar:2.4:compile - omitted for duplicate)
[INFO] +- **com.jcabi:jcabi-log:jar:0.15.1:compile**
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] |  \- (com.jcabi:jcabi-aspects:jar:0.22.4:compile - version managed from 0.18; omitted for duplicate)
[INFO] +- com.jcabi:jcabi-jdbc:jar:0.14:compile
[INFO] |  +- (com.jcabi:jcabi-aspects:jar:0.22.4:compile - version managed from 0.18; omitted for duplicate)
[INFO] |  +- (javax.validation:validation-api:jar:1.1.0.Final:compile - omitted for duplicate)
[INFO] |  \- (org.aspectj:aspectjrt:jar:1.8.4:compile - version managed from 1.8.2; scope updated from runtime; omitted for duplicate)
[INFO] +- com.jcabi:jcabi-urn:jar:0.9:compile
[INFO] |  +- (com.jcabi:jcabi-aspects:jar:0.22.4:compile - version managed from 0.17.1; omitted for duplicate)
[INFO] |  \- (org.apache.commons:commons-lang3:jar:3.3.2:compile - omitted for duplicate)
[INFO] +- javax.ws.rs:jsr311-api:jar:1.1.1:provided
[INFO] +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- com.google.guava:guava:jar:18.0:compile
[INFO] +- javax.json:javax.json-api:jar:1.0:provided
[INFO] +- org.glassfish:javax.json:jar:1.0.4:runtime
[INFO] +- com.sun.jersey:jersey-client:jar:1.19:runtime
[INFO] |  \- com.sun.jersey:jersey-core:jar:1.19:runtime
[INFO] |     \- (javax.ws.rs:jsr311-api:jar:1.1.1:provided - scope managed from runtime; omitted for duplicate)
[INFO] +- com.jcabi:jcabi-http:jar:1.14.2:compile
[INFO] |  +- (com.jcabi:jcabi-immutable:jar:1.3:compile - version managed from 1.4; omitted for duplicate)
[INFO] |  +- (com.jcabi:jcabi-aspects:jar:0.22.4:compile - version managed from 0.22.2; omitted for duplicate)
[INFO] |  +- **(com.jcabi:jcabi-log:jar:0.15.1:compile - version managed from 0.17; omitted for duplicate)**
[INFO] |  \- com.jcabi:jcabi-manifests:jar:1.1:compile
[INFO] |     \- (com.jcabi:jcabi-log:jar:0.15.1:compile - version managed from 0.14; omitted for duplicate)
[INFO] +- com.jcabi:jcabi-matchers:jar:1.3:runtime
[INFO] |  +- (org.hamcrest:hamcrest-library:jar:1.3:runtime - omitted for duplicate)
[INFO] |  +- (org.hamcrest:hamcrest-core:jar:1.3:runtime - omitted for duplicate)
[INFO] |  \- (com.jcabi:jcabi-log:jar:0.15.1:runtime - version managed from 0.14.3; omitted for duplicate)
[INFO] +- com.jcabi:jcabi-aspects:jar:0.22.4:compile
[INFO] |  +- (com.jcabi:jcabi-log:jar:0.15.1:compile - version managed from 0.17; omitted for duplicate)
[INFO] |  +- (org.aspectj:aspectjrt:jar:1.8.4:compile - version managed from 1.8.7; omitted for duplicate)
[INFO] |  \- (javax.validation:validation-api:jar:1.1.0.Final:compile - omitted for duplicate)
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] +- org.hibernate:hibernate-validator:jar:5.2.0.Alpha1:test
[INFO] |  +- (javax.validation:validation-api:jar:1.1.0.Final:test - omitted for duplicate)
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:test
[INFO] |  \- com.fasterxml:classmate:jar:1.0.0:test
[INFO] +- javax.el:javax.el-api:jar:3.0.1-b04:runtime
[INFO] +- org.aspectj:aspectjrt:jar:1.8.4:provided (scope not updated to compile)
[INFO] +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] +- junit:junit:jar:4.12-beta-3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test (scope not updated to runtime)
[INFO] |  \- (org.hamcrest:hamcrest-core:jar:1.3:test - omitted for duplicate)
[INFO] +- org.mockito:mockito-core:jar:1.10.8:test
[INFO] |  \- org.objenesis:objenesis:jar:2.1:test
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.7:test
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.7:test - omitted for conflict with 1.7.5)
[INFO] |  \- (log4j:log4j:jar:1.2.17:test - omitted for duplicate)
[INFO] \- log4j:log4j:jar:1.2.17:test

## **Suggested solutions:**

**Solution1:** Update direct dependency com.jcabi:jcabi-log from 0.15.1 to 0.17.

**Solution2:** Remove the dependency com.jcabi:jcabi-log:0.15.1.

Thanks.
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Executing the following test case on **com.jcabi:jcabi-log:0.15.1** and **0.17** separately, the risky method **_<com.jcabi.log.VerboseProcess: toString()Ljava/lang/String;>_** will get different return values:

```java
@Test(timeout = 4000)
    public void test01()  throws Throwable  {
        ProcessBuilder processBuilder0 = new ProcessBuilder("mvn");
        Process process0 = processBuilder0.start();
        VerboseProcess verboseProcess = new VerboseProcess(process0);
        String string0 = verboseProcess.toString();
        assertEquals("VerboseProcess(process=java.lang.UNIXProcess@7fb030fa, olevel=INFO, elevel=WARNING, monitors=[null, null], closed=false)", string0);
    }
```

Output results:

```java
string0 == "VerboseProcess(process=java.lang.UNIXProcess@7fb030fa, olevel=INFO, elevel=WARNING, monitors=[null, null], closed=false)"   //On **com.jcabi:jcabi-log:0.17**

string0 == "VerboseProcess(process=java.lang.UNIXProcess@2cce893c, olevel=INFO, elevel=WARNING)"    //On **com.jcabi:jcabi-log:0.15.1**
```

**Comment by HelloCoCooo** [comment]
@yegor256 Could please help me check this issue?
May I pull a request to fix it?
Thanks again.

**Comment by yegor256** [comment]
@HelloCoCooo definitely, you are welcome to submit a pull request!
