### ISSUE TITLE
Error while uploading file

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#526]
When I tried to upload pdf file I've got an error message on page
```invalid attachment name 'CV'```
here is response (observed in network analyser)
```
data=[{"msg":"ReferenceError: qbaka is not defined","script":"http://www.netbout.com/js/supplementary.js?2ff7f9b","line":2,"url":"http://www.netbout.com/b/35024","tags":[],"params":{},"tzone":-180,"rS":1,"v":6,"vhash":"6f0475af","t":1403191611994}]
```
Looks like response is not related to the problem, don't know.

As far as I understand, the problem occurred if user specify attachment name without file extension.

**Comment by dmzaytsev** [comment]
@longtimeago I uploaded a file without extension successfully. Seems this issue fixed already. If so close the task please

**Comment by longtimeago** [comment]
@dmzaytsev looks like that, thanks!

**Comment by karato** [comment]
@longtimeago I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@yegor256 there weren't any messages from you, no need to pay, as I understand (feel free to correct me)
