### ISSUE TITLE
Can't/very difficult to kick someone off the bout if their name is too long

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#528]
Not that I wanted to kick myself off, but I just happened to notice the following:

Note how the cursor shows my name and the "x" icon to the right of it.
![35023_carlos_miranda_-_google_chrome_2014-07-31_11-24-28](https://cloud.githubusercontent.com/assets/1917892/3759626/c9f77a2c-1862-11e4-8433-9aafb6ea22ad.png)

So I move my cursor to the right to reach for the "x". But when it goes under @davvd's gravatar, it then shows his name instead.
![35023_carlos_miranda_-_google_chrome_2014-07-31_11-22-35](https://cloud.githubusercontent.com/assets/1917892/3759617/ab60ef76-1862-11e4-971e-4f4086dbd0e6.png)

Actually, I found that if I was _extremely_ pixel precise and carefully moved my cursor only along the very bottom of the box displaying my name, I can reach for the "x".

![35023_carlos_miranda_-_google_chrome_2014-07-31_11-30-31](https://cloud.githubusercontent.com/assets/1917892/3759649/3d3711c8-1863-11e4-972a-97c25aaa483a.png)

Otherwise, it's quite difficult. Maybe the icons should be selectable instead, or what not?

If it helps, I'm running Chrome `36.0.1985.125 m` on Windows 7.

**Comment by karato** [comment]
@carlosmiranda milestone set to `3.1` (correct me if I am wrong)

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@yegor256 do this task, 30 mins is budget

**Comment by yegor256** [comment]
@karato assign someone else here

**Comment by karato** [comment]
> @karato assign someone else here

@yegor256 30 points was deducted from your rating

**Comment by karato** [comment]
> @karato assign someone else here

@yegor256 no problem, I will try to find somebody else
