### ISSUE TITLE
E-mail subscriptions per bout

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#529]
I think it would be great if a user had a way to configure an email subscription when new messages are posted in a bout that he belongs to.

**Comment by yegor256** [comment]
@rultor release, tag is `2.12`

**Comment by yegor256** [comment]
@rultor release, tag is `2.12`

**Comment by yegor256** [comment]
@rultor release, tag is `2.12`

**Comment by yegor256** [comment]
@rultor release, tag is `2.12`

**Comment by carlosmiranda** [comment]
@yegor256 , confirmed working. Thanks, closing now. :)

**Comment by karato** [comment]
@yegor256 **30 mins** sent to your balance (ID `000-9350bfa8`), many thanks!; added +30 to your rating, now it is equal to [+5173](http://www.netbout.com/b/35008?open=rating)
