### ISSUE TITLE
Menu bar coloring is broken

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#535]
In case of some activity menu bar displayed in red.
When I view the page it is back to default (black size).
But after some time I refresh the broser page and see those menue items as red again, despite the fact that no real changes occurred.

**Comment by karato** [comment]
@longtimeago attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@erimerturk do this task

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I added "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev got it, someone else will be assigned soon
