### ISSUE TITLE
Email notification: link gets hidden in gmail

### ISSUE THREAD

**Issue by maurezen** [yegor256/netbout#541]
Netbout sends a link to the bout in question in the notification email footer. On gmail, each notification for the same bout past the first is recognized as a dialogue reply and renders as an email chain. However, in these chained notifications, the footer is mistaken for the quote and gets hidden by default.

TLDR: footer separator gets it hidden on gmail, pls change.

**Comment by yegor256** [comment]
@maurezen I did it intentionally... you have the link in the first message, why would you need it again and again in every next message. Make sense? Or I missed the problem you explain

**Comment by maurezen** [comment]
@yegor256 by default only the last message is displayed. It has the link hidden, which makes me click/tap twice instead of once, which is inconvenient.

**Comment by karato** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@maurezen thank you for reporting this, I added 15 mins to your acc, transaction `50213619`

**Comment by karato** [comment]
@maurezen attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@antonini this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by antonini** [comment]
@karato PR #660 is available and waiting for review.

**Comment by antonini** [comment]
@karato Any progress on this issue?

**Comment by dmzaytsev** [comment]
@antonini ask the ticket reporter to close this

**Comment by antonini** [comment]
@maurezen PR was merged and also deployed. Can you check it?

**Comment by maurezen** [comment]
@antonini the email about your message still had the link hidden as the quoted text. I believe the problem is in the separator, not in the url itself.

**Comment by antonini** [comment]
@maurezen Remember that we changed Netbout. The e-mail that you received about this issue came from GitHub and we can't change that.

**Comment by maurezen** [comment]
@antonini sorry, that was me being distracted.

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@antonini 
>karato commented on Jan 13
I'm aware of the task, give me some time to find a developer...

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 IAs far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by antonini** [comment]
@karato Please, fix the message quoted by @elenavolokhova.

**Comment by karato** [comment]
@elenavolokhova @antonini I fixed my comment, thanks

**Comment by antonini** [comment]
@elenavolokhova We will try to do it better next time.

**Comment by elenavolokhova** [comment]
@antonini Thank you!

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by karato** [comment]
@antonini just added 10 mins to @elenavolokhova (for QA), payment ID is `59102685`; Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-9X809873YY642514Y`, 215 hours and 17 mins spent total; +30 added to your rating, at the moment it is: [+106](http://www.netbout.com/b/35346?open=rating)
