### ISSUE TITLE
"View Bout" action in Gmail

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#546]
Let's add support for subject-line links in Gmail to the email subscription messages. To be clear, I'm referring to those links you see at the far right of the subject line. For example, these Github email notifications:

![image](https://cloud.githubusercontent.com/assets/1917892/5771909/93c210ca-9d82-11e4-82e0-721faba39e58.png)

Let's make it similar to how Github does it - it should say "View Bout" and should take the receiver of the email directly to the bout being referred to.

As far as I know we have many Gmail users and this is a minor but beneficial feature for them.

See:
https://github.com/blog/1891-view-issue-pull-request-buttons-for-gmail
https://developers.google.com/gmail/markup/reference/go-to-action#view_action

**Comment by karato** [comment]
I'll ask someone to take care of this task soon

**Comment by karato** [comment]
@carlosmiranda thanks for tis bug, I topped your account for 15 mins, transaction `50342900`

**Comment by ndbroadbent** [comment]
@yegor256 - I would love to take care of this one too.

**Comment by yegor256** [comment]
@ndbroadbent sure, but right after I finish this one: #569

**Comment by karato** [comment]
@carlosmiranda milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@mbarbieri it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by mbarbieri** [comment]
@karato PR #659 is ready for review

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.15`

**Comment by dmzaytsev** [comment]
@yegor256 did you fill out the [registration form](https://developers.google.com/gmail/markup/registering-with-google) ?

**Comment by karato** [comment]
@rultor @carlosmiranda please take a look, rultor closed it automatically

**Comment by carlosmiranda** [comment]
@karato looks correct, closing it now.

**Comment by yegor256** [comment]
@carlosmiranda yes, just did

**Comment by yegor256** [comment]
@dmzaytsev yes, I just filled the registration form

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato 
>I'll ask someone to take care of this task soon

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please fix your message by adding the addressee at the beginning.

**Comment by ypshenychka** [comment]
@karato Please fix the above remark.

**Comment by carlosmiranda** [comment]
@ypshenychka Unfortunately @karato can't fix it, I believe that message is automated. However new tickets already address someone with this message. Let's move on so @mbarbieri can get paid.

**Comment by ypshenychka** [comment]
@carlosmiranda Yeah, you're right. This ticket is rather old.

**Comment by ypshenychka** [comment]
@yegor256 can @karato fix this message or we can move forward?

**Comment by karato** [comment]
@ypshenychka fixed, sorry for the delay

**Comment by ypshenychka** [comment]
@karato Thank you!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@mbarbieri just added 10 mins to @ypshenychka (for QA), payment ID is `59451516`

done, I added **30 mins** in payment `AP-0VD65516UB181173T`, 162 hours and 32 mins spent to complete this

+30 added to your rating, at the moment it is: [+143](http://www.netbout.com/b/35357?open=rating)

**Comment by dmzaytsev** [comment]
@yegor256 after you filled out the form, did you had any response on it?  Is your request been accepted or declined?

> yegor256 commented 15 days ago
> @dmzaytsev yes, I just filled the registration form

**Comment by yegor256** [comment]
@dmzaytsev they declined it. but I will try again, looks like I did something wrong

**Comment by dmzaytsev** [comment]
@yegor256 did you have any success?

> yegor256 commented 16 days ago
> @dmzaytsev they declined it. but I will try again, looks like I did something wrong

**Comment by yegor256** [comment]
@dmzaytsev I've sent it again to them... as soon as I get a response I'll update you here.
