### ISSUE TITLE
redundant email on message post

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#548]
When I post a message to a bout, I get an email about it. It's redundant.

**Comment by longtimeago** [comment]
@yegor256 Can we proceed here? This bug is quite annoying

**Comment by yegor256** [comment]
@longtimeago yep, I'll try to fix it soon

**Comment by karato** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-17e6fa74

**Comment by ndbroadbent** [comment]
@yegor256, I just noticed this bug too, and would like to fix it.

**Comment by yegor256** [comment]
@karato assign @ndbroadbent to this problem pls

**Comment by karato** [comment]
> @karato assign @ndbroadbent to this problem pls

@yegor256 OK @ndbroadbent please start, the task is yours

**Comment by ndbroadbent** [comment]
@karato - This will take longer than 30 minutes, and requires some refactoring. Please see #582

**Comment by dmzaytsev** [comment]
@karato set milestone 3.0

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `3.1`

**Comment by dmzaytsev** [comment]
@karato we are wating #582 here

**Comment by dmzaytsev** [comment]
@karato please assign @ndbroadbent to this task

**Comment by yegor256** [comment]
@karato milestone here is 3.0

**Comment by karato** [comment]
> @karato milestone here is 3.0

@yegor256 thanks, I set it to "3.0"

**Comment by karato** [comment]
@mbarbieri the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by mbarbieri** [comment]
Looks like this depends on #582 
Am I wrong?

**Comment by dmzaytsev** [comment]
@karato @yegor256 
please assign @ndbroadbent to this task

**Comment by dmzaytsev** [comment]
@mbarbieri btw keep in mind [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

**Comment by yegor256** [comment]
@dmzaytsev unfortunately @ndbroadbent is not with us any more

**Comment by mbarbieri** [comment]
@yegor256 Sorry I'm a little confused... it seems to me that #582 will fix this as well.
Should I wait for it to be merged or should I take the changes he did and continue?

**Comment by dmzaytsev** [comment]
@mbarbieri the previous performer closed his PR, you have to resolve this issue from scratch. I would to use [GreenMail](http://www.icegreen.com/greenmail/) for the unit tests.
Please start

**Comment by mbarbieri** [comment]
@dmzaytsev ok.
I don't think we need GreenMail for this.
From what I see GreenMail can be useful to test that the sending/retrieving code is working, but to unit test this I would rather mock the mail sender (not looked at the code yet) and verify that we are not putting the current user mail as a recipient.

**Comment by mbarbieri** [comment]
@dmzaytsev PR630 is ready for review

**Comment by mbarbieri** [comment]
@dmzaytsev can the issue be closed?

**Comment by dmzaytsev** [comment]
@mbarbieri ask the ticket reporter

**Comment by mbarbieri** [comment]
@yegor256 can the issue be closed?

**Comment by yegor256** [comment]
@mbarbieri in which pull request this problem was solved?

**Comment by mbarbieri** [comment]
@yegor256 here #630

**Comment by mbarbieri** [comment]
@yegor256 is there any problem causing the issue to be still open? Let me know if there is something wrong.

**Comment by yegor256** [comment]
@mbarbieri thanks, closing!

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato 
>I am aware of the task, give me some time to find a developer...

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please always indicate a person you're referring too in the beginning of the comment/message.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by ypshenychka** [comment]
@mbarbieri 
>Looks like this depends on #582 
Am I wrong?

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please always indicate a person you're referring too in the beginning of the comment/message.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by mbarbieri** [comment]
@ypshenychka yes thank you

**Comment by ypshenychka** [comment]
@karato Please confirm that you have no questions regarding above remark.

**Comment by karato** [comment]
@ypshenychka I fixed my comments, thanks for noticing

**Comment by ypshenychka** [comment]
@karato Thanks a lot!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@mbarbieri 10 mins was added to the account of @ypshenychka (for QA review), in transaction 58503835

paid, thanks, added **38 mins** to your account, payment `AP-8R272510DF090542W`, 152 hours and 14 mins was spent

the bonus for fast delivery (age=2972)

added +38 to your rating, now it is equal to [+68](http://www.netbout.com/b/35357?open=rating)
