### ISSUE TITLE
Build number doesn't displayed at 'Internal Application Error' page

### ISSUE THREAD

**Issue by alevohin** [yegor256/netbout#550]
If any uncatched exception occurs, error page doesn't contains build number.

> Internal Application Error
> **Build number: ${buildNumber}**
> Netbout team has already received a notification about this problem. We will investigate and fix as  soon as possible. In the mean time, click "Back" button in your browser and try again. It may work :)
If you want to help our project, please post the following exception stacktrace to our Github account.

**Comment by karato** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@alevohin thanks for the report, I topped your acc for 15 mins, payment ID `50517937`

**Comment by yegor256** [comment]
@alevohin it's fixed already

**Comment by karato** [comment]
@alevohin there is no milestone yet, so I set it to `3.1`
