### ISSUE TITLE
Sortable columns in "agenda" page

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#553]
Right now, the items on the "Agenda" page appear to be sorted by the "task" column in ascending alphabetical order. I suggest that we also implement sorting by other columns, which should work in a manner similar to the following:
1. If a user clicks a column that's not selected, that column will be sorted in ascending order.
2. If a user clicks a column that's already selected, that column will sort in the reverse of the current order.

It would be great, for example, for team members to be able to sort by "assigned" so that they can see which tasks are older and prioritize their work accordingly.

**Comment by karato** [comment]
I'll find a developer for the task soon...

**Comment by karato** [comment]
@carlosmiranda thanks for the report, I topped your acc for 15 mins, payment ID `50570275`

**Comment by longtimeago** [comment]
@carlosmiranda @yegor256 Very useful feature. Now it quite annoying to look over the list to find the oldest tasks

**Comment by karato** [comment]
@carlosmiranda I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I added "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev got it, someone else will be assigned soon

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev got it, "postponed" tag here

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev got it, someone else will be assigned soon

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev all right, we'll find someone else for this task
