### ISSUE TITLE
Scrollable message entry field

### ISSUE THREAD

**Issue by maurezen** [yegor256/netbout#554]
If I enter a really long message for which the text box doesn't have enough space, it is only visible partially (which is perfectly okay), but there is no scroll bar (which is mighty inconvenient).
Please make message entry text box scrollable.

**Comment by karato** [comment]
I'll find a developer for the task soon...

**Comment by karato** [comment]
@maurezen thanks for tis bug, I topped your account for 15 mins, transaction `50596075`

**Comment by dmzaytsev** [comment]
@karato set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato this issue will be resolved in #614 
please set duplicate tag

**Comment by karato** [comment]
@maurezen since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev milestone is set to 3.0

**Comment by karato** [comment]
@erimerturk this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@karato this task should not be assigned
this issue will be resolved in #614 
please set duplicate tag and close the task

**Comment by erimerturk** [comment]
@karato please decide it is duplicate or not. i will go on after your decision.

**Comment by yegor256** [comment]
@karato this task is duplicate

**Comment by karato** [comment]
> @karato this task is duplicate

@yegor256 right, I added "invalid", "duplicate" tags

**Comment by karato** [comment]
@maurezen It is "invalid", I am closing it
