### ISSUE TITLE
Outdated copyright year in LICENSE.txt

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/netbout#555]
The `LICENSE.txt` still has year 2014:

```
Copyright (c) 2009-2014, netbout.com
```

See https://github.com/yegor256/netbout/blob/master/LICENSE.txt

Please change it to 2015.

**Comment by karato** [comment]
I'll ask someone to take care of this task soon

**Comment by karato** [comment]
@dpisarenko thank you for reporting this, I added 15 mins to your acc, transaction `50663370`

**Comment by yegor256** [comment]
@dpisarenko fixed

**Comment by karato** [comment]
@dpisarenko since the ticket has no milestone I set it to 3.1
