### ISSUE TITLE
Speed page is outdated / out of sync

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#560]
The problem reported in #534 is occurring again.

See below my "Ratings" page. Last updated timestamp is shown as "2015-01-27T22:48:56Z by 0.68.3.815"
![image](https://cloud.githubusercontent.com/assets/1917892/5932826/2e43f5d4-a6f0-11e4-8c9f-0cd005a7e3a4.png)

Now here is my "Speed" page. Last updated time is shown as "2015-01-27T22:49:00Z by 0.68.3.815".

![image](https://cloud.githubusercontent.com/assets/1917892/5932841/6d68e77e-a6f0-11e4-8105-98a09723c781.png)

Despite the fact that the Speed page claims to have been updated recently, it's actually more than a month behind. Compare the number of recent tasks shown in my "Ratings" page.

**Comment by karato** [comment]
I'll find a developer for the task soon...

**Comment by karato** [comment]
@carlosmiranda many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `50954496`

**Comment by dmzaytsev** [comment]
@yegor256 this is out of the scope of the project. Isn't it ?

**Comment by yegor256** [comment]
@dmzaytsev yes it's out of scope

**Comment by dmzaytsev** [comment]
@karato this is invalid task

**Comment by karato** [comment]
@carlosmiranda there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
> @karato this is invalid task

@dmzaytsev got it, "invalid" tag here

**Comment by karato** [comment]
@carlosmiranda closed since "invalid"
