### ISSUE TITLE
Leaderboard enumeration

### ISSUE THREAD

**Issue by maurezen** [yegor256/netbout#561]
Leaderboard page says that it shows top 10 and last 5 developers.
Indeed, top 10 are shown, but only top 9 are enumerated. Shouldn't the №10 also have the position number?

Also, last 6 positions are actually shown, not 5.

**Comment by karato** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@maurezen many thanks for the bug report, I added 15 mins to your acc, transaction `50910674`

**Comment by dmzaytsev** [comment]
@yegor256 I think it's not in scope of this project, but I see the bug tag here.
Should we mark the ticket as invalid?

**Comment by yegor256** [comment]
@dmzaytsev yes, I agree, it's out of scope

**Comment by dmzaytsev** [comment]
@karato this is invalid task

**Comment by karato** [comment]
@maurezen attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
> @karato this is invalid task

@dmzaytsev got it, "invalid" tag here

**Comment by karato** [comment]
@maurezen I am closing it
