### ISSUE TITLE
Agenda page enhancement: task status

### ISSUE THREAD

**Issue by maurezen** [yegor256/netbout#562]
It would be great for useability if there was task status somewhere on agenda page, so the developer could discern the following points in the task lifecycle:
 - Task assigned
 - Pull request submitted
 - Pull request assigned to review (this status should change back to pull request submitted once the reviewer commented in the thread with something else than a command to merge)
 - Pull request merged
 - Task closed
 - Task paid

Currently only the first and the last points are discernable from the agenda page (at the last point the task disappears), so task management quickly gets out of hand (I, for example, find it hard to manage the tasks once their quantity approaches 10). 

It could be a separate column, or written in the details column (where task impediments are shown now). 

It would also be great to time since last status change.

**Comment by yegor256** [comment]
@maurezen I see what you're getting at, but this is against our core idea of definition of done. We believe that a task is either 0% done or 100% done, nothing in between. And there is only one person responsible for the task - the developer. In other words, a project manager doesn't know and doesn't want to know what is the status of the task. It's a problem of developer. If we start caring about it, we'll get into micro management and developers will start blaming management for losing status or reporting it inaccurately. We don't want that. The status of a task is a problem of the developer.

Moreover, a merge of a pull request is not a guarantee of task completion. Sometimes you need 2-3 pull requests to complete a task.

**Comment by maurezen** [comment]
@yegor256 please slow down! I wasn't saying that anybody should do that by hand. It should be automated, much as rultor monitors github threads automatically. Of course, no reporting by hand.

The task is still either open or closed for the rest of the world. Having a status along the lines I outlined saves the trouble of clicking each of the task links to see what else needs to be done there (a couple of tasks could be monitored via following the email updates, but a dozen of them? no way). That makes an individual developer more focused on actually doing something useful, by lessening his management overhead.

Does that make sense?

**Comment by yegor256** [comment]
@maurezen for example, what status we can fetch from a Github ticket automatically?

**Comment by maurezen** [comment]
@yegor256 
 - Task assigned - could be fetched by account name label.
 - Pull request submitted - could be fetched by a keyword in a comment from developer (with a link to the pull request in question) - either in an original issue or in a known pull request.
 - Pull request assigned - a label in pull request issue. Any reply from the reviewer (found by label) or architect (a role in the project) in the pull request thread other than `@rultor` command switches the status back to task assigned.
 - Pull request merged - rultor is able to close the pull request automatically, so this is not a problem.
 - Task closed - same mechanism as the pull request merged. 
 - Task paid - there always is a cliched message about the payment from PM. It could be easily tracked. Or it could be a point of integration with manager's task management mechanism.

Makes sense?

**Comment by yegor256** [comment]
task assigned is already in the table; task closed is the same as task paid, no reason to make a difference between them. a task may have multiple pull requests, and there is no guarantee that pull request will be automatically linked by github. so, again, I understand your ideas, but they are against the main principle - the task is a full responsibility of its developer.

**Comment by maurezen** [comment]
@yegor256 
>task closed is the same as task paid
Sorry, is that so? Last I checked, the speed is calculated as time elapsed from task assigned to task paid, and the task closed is usually at least a day earlier. 

>there is no guarantee that pull request will be automatically linked by github
Yeah, that's why I mentioned the keywords in developer's post.

>but they are against the main principle- the task is a full responsibility of its developer
Sorry, could you explain exactly where they are against that principle? There already is a tool which helps manage the tasks and is not against the principle. I propose an enhancement for tool useability and it suddenly becomes against the same principle? I don't get it.

**Comment by yegor256** [comment]
@maurezen I appreciate your suggestions, but they are not suitable right now for the project. Thanks.

**Comment by maurezen** [comment]
@ yegor256 ok, thanks.
