### ISSUE TITLE
Agenda page enhancement: hide closed tasks

### ISSUE THREAD

**Issue by maurezen** [yegor256/netbout#563]
It was mentioned in #562 discussion that
>task closed is the same as task paid, no reason to make a difference between them.

Yet on the agenda page the task disappears only when it is paid for, not once it is closed.
Won't it be reasonable to make tasks disappear once closed?

**Comment by yegor256** [comment]
Task closing is not a guarantee of its completion. You may close a task thinking that it's done, but then the reporter of the task will open it again. This process is not under our control. Once the task is paid, we officially take it out of your agenda. Everything that is happening between task assignment and task closing (which means paid by the PM) is out of our management control.

**Comment by maurezen** [comment]
@yegor256 okay, that's more or less clear now, thanks.
