### ISSUE TITLE
Netbout should respect newline in post messages

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#564]
Here is the test message:
```
First line 
Second line

Third line
```

Here is how it appears on the topic (and in the email)
```
First line Second line
Third line
```

This formatting issue is quite annoying

**Comment by karato** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@longtimeago thank you for reporting this, I added 15 mins to your acc, transaction `52105295`

**Comment by dmzaytsev** [comment]
@karato set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato this issue will be resolved in #614 
please set duplicate tag

**Comment by karato** [comment]
@longtimeago since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev the milestone here is 3.0

**Comment by karato** [comment]
@lautarobock this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@karato this task should not be assigned
this issue will be resolved in #614 
please set duplicate tag and close the task

**Comment by yegor256** [comment]
@karato it's a duplicate of #614

**Comment by karato** [comment]
> @karato it's a duplicate of #614

@yegor256 right, I added "invalid", "duplicate" tags

**Comment by karato** [comment]
@longtimeago the ticket is "invalid", closing it

**Comment by dmzaytsev** [comment]
@karato please reopen this issue

**Comment by karato** [comment]
> @karato please reopen this issue, remove the invalid label and dispatch this

@dmzaytsev right, I added "invalid" tag

**Comment by dmzaytsev** [comment]
@yegor256 could you please help here ?
I would like remove `invalid` and `duplicate` tags and reopen this ticket

**Comment by lautarobock** [comment]
@dmzaytsev I'm curious, why do you want to re-open it?

**Comment by dmzaytsev** [comment]
@lautarobock  I changed my mind, the issue won't be resolved in #614  .
that's why  I want to reopen the ticket

**Comment by lautarobock** [comment]
@dmzaytsev great

**Comment by yegor256** [comment]
@dmzaytsev I re-opened the ticket and removed the tags

**Comment by dmzaytsev** [comment]
@yegor256 thank you

**Comment by dmzaytsev** [comment]
@karato this is urgent task
please dispatch

**Comment by yegor256** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@yegor256 thanks, I added the "urgent" tag

**Comment by dmzaytsev** [comment]
@antonini could you pickup this task?

**Comment by antonini** [comment]
@dmzaytsev Sure! @karato assign it to me.

**Comment by dmzaytsev** [comment]
@karato assign this ticket to @antonini please

**Comment by karato** [comment]
> @karato assign this ticket to @antonini please

@dmzaytsev done. @antonini you are assigned to this task. please proceed...

**Comment by antonini** [comment]
@karato Issue is without the tag in my name. It also is not on my `agenda` on netbout.

**Comment by karato** [comment]
> @karato Issue is without the tag in my name. It also is not on my `agenda` on netbout.

@antonini I'll update your agenda soon and will add a tag... it takes usually some time

**Comment by antonini** [comment]
@karato Ok.

**Comment by antonini** [comment]
@karato PR #743 ready for review.

**Comment by karato** [comment]
> @karato Ok.

@antonini thanks

**Comment by karato** [comment]
> @karato PR #743 ready for review.

@antonini thanks will find someone soon

**Comment by antonini** [comment]
@longtimeago PR was merged and deployed on http://snapshot.netbout.com/. Please check it and if it looks good close the issue.

**Comment by longtimeago** [comment]
@antonini Shouldn't it preserve paragraph indentation?

**Comment by antonini** [comment]
@longtimeago, Did you tested on snapshot?

Bellow is the output of submitting this content:

    First line 
    Second line
    
    Third line

![capturar](https://cloud.githubusercontent.com/assets/209396/8828917/d53ef128-306a-11e5-9d78-d7432fbb1fcc.PNG)

And here is the generated source code:

    <p>First line
    <br>
    Second line</p>
    <p>Third line</p>

What was the problem that you got?

**Comment by longtimeago** [comment]
@antonini yep, I'm checking on http://snapshot.netbout.com/ version.
For example, initial message:
```
 Lorem ipsum
Lorem ipsum
 Lorem ipsum
Lorem ipsum
```
But after post it become:
```
Lorem ipsum 
Lorem ipsum 
Lorem ipsum 
Lorem ipsum
```

**Comment by antonini** [comment]
@longtimeago If you check the output source code, you will see that it generates a lot of spaces. All browsers ignores multiple spaces.
Even here on github if you do that you will receive all lines aligned.

Check it out:

 Lorem ipsum
Lorem ipsum
 Lorem ipsum
Lorem ipsum

**Comment by longtimeago** [comment]
@antonini ahhr ... you are right! Sorry :)

**Comment by antonini** [comment]
@longtimeago Thanks! :)

**Comment by antonini** [comment]
@karato Issue is closed!

**Comment by antonini** [comment]
@karato Ping.

**Comment by antonini** [comment]
@karato Ping.

**Comment by dmzaytsev** [comment]
@yegor256 FYI

**Comment by antonini** [comment]
@karato Ping.. waiting payment.

**Comment by dmzaytsev** [comment]
@antonini I suggest to ask @yegor256

**Comment by antonini** [comment]
@dmzaytsev I've just sent a message inside netbout about it. Thanks! :)

**Comment by yegor256** [comment]
@karato pls add extra 30 mins to @antonini

**Comment by antonini** [comment]
@karato ping.

**Comment by antonini** [comment]
@karato ping.

**Comment by antonini** [comment]
@karato Ping.

**Comment by antonini** [comment]
@yegor256 Need your help over here. I'm pinging @karato and there is no progress.

**Comment by yegor256** [comment]
@antonini you'll be paid in #703 for this, sorry for delay

**Comment by antonini** [comment]
@yegor256 I don't understand. There is no connection between those issues.

**Comment by yegor256** [comment]
@antonini yes, there is no connection, but this ticket is too old and is not under our control any more. that's why it's more convenient to pay "extra" in #703. don't worry, the total will be correct.

**Comment by antonini** [comment]
@yegor256 And what about ranking points?
