### ISSUE TITLE
prevent duplicate messages in bouts

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#567]
When I click "post message" twice, I get two identical messages. It's a bug

**Comment by karato** [comment]
@yegor256 right, I added the `bug` tag

**Comment by karato** [comment]
we will find someone to do this task, soon

**Comment by karato** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-dd662d09`

**Comment by dmzaytsev** [comment]
@yegor256 Is this issue resolved ? if so close the task please

**Comment by yegor256** [comment]
@dmzaytsev no, it's not resolved. if you click "Post Message" twice, you will get two identical messages

**Comment by dmzaytsev** [comment]
@karato set millestone to 3.0

**Comment by karato** [comment]
@yegor256 I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@mbarbieri can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by mbarbieri** [comment]
@yegor256 I'm thinking of doing that on client side, disabling the submit after the first click.
What do you think?

**Comment by yegor256** [comment]
@mbarbieri yes, I think it's the only way to do it

**Comment by mbarbieri** [comment]
@karato PR #678 ready to be reviewed

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.15.1`

**Comment by karato** [comment]
@rultor @yegor256 please take a look, rultor closed it automatically

**Comment by dmzaytsev** [comment]
@mbarbieri as the ticket performer you should ask the reporter(@yegor256) to close this ticket

**Comment by mbarbieri** [comment]
@yegor256 can this be closed?

**Comment by dmzaytsev** [comment]
@yegor256 as the ticket reporter you should close the ticket

**Comment by yegor256** [comment]
@mbarbieri thanks!

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@mbarbieri just added 10 mins to @elenavolokhova (for QA), payment ID is `59533902`; thank you, added **30 mins** to your acc, payment num is `AP-4LS60593JS895570R`, 262 hours and 40 mins spent in total to complete; added +30 to your rating, now it is equal to [+143](http://www.netbout.com/b/35357?open=rating)
