### ISSUE TITLE
migrate to Takes

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#569]
Let's migrate to Takes 0.8.5

**Comment by karato** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-56423597

**Comment by yegor256** [comment]
@rultor release, tag is `2.14`

**Comment by yegor256** [comment]
@rultor release, tag is `2.14`

**Comment by yegor256** [comment]
@rultor release, tag is `2.14`

**Comment by yegor256** [comment]
done
