### ISSUE TITLE
MkInbox should invite on start()

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#570]
`MkInbox` should automatically invite current user in `start()`

**Comment by karato** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-0728456b

**Comment by dmzaytsev** [comment]
@karato set milestone to 3.0

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by karato** [comment]
@lautarobock This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by lautarobock** [comment]
@yegor256 Where can I get documentation or some extra information to contextualize it?

**Comment by yegor256** [comment]
@lautarobock check this: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by lautarobock** [comment]
@yegor256 the project has almost empty readme and none general documentation. Is not school, is about software documentation. It is not self explained

**Comment by lautarobock** [comment]
@yegor256 I will make a more specific question

**Comment by lautarobock** [comment]
@karato PR#625 is ready for review

**Comment by lautarobock** [comment]
@yegor256 something else to close the issue?

**Comment by yegor256** [comment]
@lautarobock thanks!

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka many thanks

**Comment by karato** [comment]
@lautarobock just added 10 mins to @ypshenychka (for QA), payment ID is `58210802`

done, I added **30 mins** in payment `AP-28T54580VA541623D`, 168 hours and 30 mins spent to complete this

+30 added to your rating, at the moment it is: [+60](http://www.netbout.com/b/35344?open=rating)

**Comment by lautarobock** [comment]
@karato thanks!
