### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#576]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@komaz do this task

**Comment by komaz** [comment]
@karato fixed in #651, please close the issue

**Comment by komaz** [comment]
@dmzaytsev who can close this issue?

**Comment by dmzaytsev** [comment]
@komaz @karato should close this ticket

**Comment by yegor256** [comment]
@rultor deploy

**Comment by karato** [comment]
@yegor256 Thanks, closed

**Comment by karato** [comment]
@komaz Much obliged! I have added **30 mins** to your account in payment "AP-90619241HD722451H", 175 hours and 9 mins spent. +30 to your rating, your total score is [+360](http://www.netbout.com/b/35322?open=rating)
