### ISSUE TITLE
Travis CI should cache maven dependencies to speed up builds

### ISSUE THREAD

**Issue by ndbroadbent** [yegor256/netbout#579]
Please see [this comment](https://github.com/travis-ci/travis-ci/issues/1441#issuecomment-67607074) on the ["Cache downloaded Maven artifacts" Travis CI issue](https://github.com/travis-ci/travis-ci/issues/1441#issuecomment-67607074) for more information.

Example `.travis.yml`: https://github.com/alv-ch/alv-ch-sysinfos.api/blob/master/.travis.yml#L7-L18

**Comment by yegor256** [comment]
we have this already: https://github.com/yegor256/netbout/blob/master/.travis.yml#L2-L4

**Comment by ndbroadbent** [comment]
Ah, I missed that. However, the cache is not working at the moment. I think we need to add `sudo: false` to use the container-based infrastructure, where caching is allowed for public repos. See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by ndbroadbent** [comment]
Fixed in #585
