### ISSUE TITLE
urls in a message are a plain text instead html links

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#581]
Urls in a message should be clickable html links.
e.q.

>A few days ago we've introduced a new rule to our management model. From now on we're paying bonuses for quickly closed tasks. More details you get here: `http://www.teamed.io/policy.html#22` (par no.22)

looks better like this
>A few days ago we've introduced a new rule to our management model. From now on we're paying bonuses for quickly closed tasks. More details you get here: http://www.teamed.io/policy.html#22 (par no.22)

or like this
>A few days ago we've introduced a new rule to our management model. From now on we're paying bonuses for quickly closed tasks. More details you get here: [par no.22](http://www.teamed.io/policy.html#22)

**Comment by yegor256** [comment]
@dmzaytsev you're right, it's a valid bug

**Comment by karato** [comment]
@dmzaytsev I will find a developer for the task soon...

**Comment by karato** [comment]
@dmzaytsev many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `55165398`

**Comment by yegor256** [comment]
@ndbroadbent can you fix this? shall I assign it to you?

**Comment by dmzaytsev** [comment]
@karato set milestone to 3.0

**Comment by karato** [comment]
@dmzaytsev attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
> @karato set milestone to 3.0

@dmzaytsev milestone is set to 3.0

**Comment by karato** [comment]
@komaz this is your task

**Comment by komaz** [comment]
@dmzaytsev markdown syntax supports explicit links, hence once we detect a link we can replace it with `[link](link)` and markdown to html converter will do the rest of the work (just need to make sure we won't affect existing well-formed links. What do you think about implementing such link detection inside `com.netbout.rest.Markdown` class before passing a text into downstream converter?

**Comment by dmzaytsev** [comment]
@komaz I agree, let's implement this

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.14.17`

**Comment by dmzaytsev** [comment]
@komaz please mention PR right here in the ticket

**Comment by komaz** [comment]
@dmzaytsev fixed in pull request #653

**Comment by dmzaytsev** [comment]
@komaz thanks!

**Comment by yegor256** [comment]
@dmzaytsev @komaz now we have this #664

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@komaz I added 10 mins to @elenavolokhova (for QA review) in transaction 58670109... thanks, paid, **30 mins** to your account, payment ID is `AP-7N211370L5337983P`, task took 213 hours and 40 mins to complete... +30 added to your rating, current score is: [+420](http://www.netbout.com/b/35322?open=rating)
