### ISSUE TITLE
the posted message lost newline

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#583]
when I typed such message in the netbout
```
line 1
line 2

line 3
```
after post it displayed as
```
line 1 line 2 
line3
```
it would be nice to preserve EOLs in a message

**Comment by yegor256** [comment]
@dmzaytsev isn't it a duplicate of #564?

**Comment by dmzaytsev** [comment]
@yegor256 yes it is
this is my mistake
I have not seen a duplicate
sorry
