### ISSUE TITLE
Can't log out when I run the server locally

### ISSUE THREAD

**Issue by ndbroadbent** [yegor256/netbout#584]
When I run the server locally, I can't log out to create a new account. I need to do this so that I can post messages to a bout with multiple accounts.

**Comment by yegor256** [comment]
@rultor release, tag is `2.14.3`

**Comment by yegor256** [comment]
@ndbroadbent should be working now. start the app like this:

```
mvn clean integration-test -pl :netbout-web -Dport=8080 -Phit-refresh
```

Then, open `http://localhost:8080`

Then, open this URL: `localhost:8080/?PsByFlag=fake-user&urn=urn:test:12345`, register a user and enjoy. Any moment you can open the same URL with a different number after `urn:test:`

**Comment by karato** [comment]
@ndbroadbent I will ask someone to take care of this task soon

**Comment by karato** [comment]
@ndbroadbent thanks for the report, I topped your acc for 15 mins, payment ID `AP-18C51600567278336`

**Comment by dmzaytsev** [comment]
@ndbroadbent the issue resolved, right? if so close the task please

**Comment by karato** [comment]
@ndbroadbent since there is no milestone yet I set it to "3.1"
