### ISSUE TITLE
Application Error when login using Github account

### ISSUE THREAD

**Issue by super132** [yegor256/netbout#589]
I attempted to login to NetBout.com with version 3.0-SNAPSHOT using my GitHub account and I encounter the following error screen:
![screen shot 2015-05-10 at 11 39 35 am](https://cloud.githubusercontent.com/assets/6581896/7553000/56c1001a-f709-11e4-8ad1-b568e6664f92.png)

**Comment by yegor256** [comment]
@super132 yeah, we're temporary down... will be fixed in a few minutes

**Comment by yegor256** [comment]
@super132 works fine now
