### ISSUE TITLE
Netbout escapes HTML tags

### ISSUE THREAD

**Issue by cyberone** [yegor256/netbout#598]
After transformation netbouts outputs calculated pages with HTML tags escaped instead of direct output, e.g I see:

```
<h1>Your 90-Days Rating</h1> <p>Your rating is: <strong> <span style="color:green">+173</span> </strong></p> <p> <div> <div style="width:100%;height:100px;border:1px solid gray;"> <svg xmlns="http://www.w3.org/2000/svg" height="100%" 
```

instead of

```
<h1>Your 90-Days Rating</h1> <p>Your rating is: <strong> <span style="color:green">+XXX</span> </strong></p> <p> <div> <div style="width:100%;height:100px;border:1px solid gray;">
```

in a HTML source I see:
    
```
    &lt;p&gt;Your rating is: 
    &lt;strong&gt;
    &lt;span style="color:green"&gt;+XXX&lt;/span&gt;
    &lt;/strong&gt;&lt;/p&gt;
    &lt;p&gt;
    &lt;div&gt;
```

**Comment by longtimeago** [comment]
@cyberone @yegor256 Issue is reproduced in FF.
For Chrome all is OK

**Comment by yegor256** [comment]
@cyberone @longtimeago stupid FF... I'll take a look, thanks

**Comment by yegor256** [comment]
@cyberone seems to be a bug in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=98168

**Comment by cyberone** [comment]
@yegor256 sorry, closing then.

**Comment by yegor256** [comment]
@cyberone no no, we have to fix, don't close :)

**Comment by cyberone** [comment]
@yegor256 that'd be great.

**Comment by yegor256** [comment]
@rultor release, tag is `2.14.9`

**Comment by yegor256** [comment]
@cyberone check now

**Comment by cyberone** [comment]
@yegor256 thanks, closing now.
