### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#608]
@yegor256 
> fully functioned RESTful API, via Java client

Do you mean to create a new implementation `com.netbout.client` ? 
what it will be different from existing one?

**Comment by yegor256** [comment]
@dmzaytsev no no, I mean that existing one is not fully implemented. Some methods still throw `UnsupportedOperationException`

**Comment by dmzaytsev** [comment]
@yegor256 Ok 
thanks

**Comment by dmzaytsev** [comment]
@yegor256 
As far as I understand we need implement java client Restful API  for all classes in `com.netbout.spi` except `Base` and `Pageable`. Right?
If so we have to implement 

`com.netbout.client.RtAlias.email() `
`com.netbout.client.RtAlias.email(final String email)`
`com.netbout.client.RtUser.friends(String text)`
`com.netbout.client.RtFriends.friends()`

**Comment by yegor256** [comment]
@dmzaytsev yes, looks like that
