### ISSUE TITLE
return after login

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#609]
Say, I'm not logged in. I open `http://www.netbout.com/b/12345`. Now I'm getting "page not found" page.

Instead, would be better to throw me to the login page and ask to login. After I login (or login+register) I get back to the original page I was looking for (http://www.netbout.com/b/12345)

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@yegor256 I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev the milestone here is 3.0

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-122e7fef

**Comment by karato** [comment]
@komaz the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by komaz** [comment]
@yegor256 does this sound like a correct approach?
- Create `RsReturn` similar to `RsFlash`, which will set a cookie with path to return to.
- Once user is authenticated, `TkReturn`, similar to `TkFlash`, would send a redirect to stored path and clear the cookie

**Comment by yegor256** [comment]
@komaz looks like a perfect idea to me

**Comment by komaz** [comment]
@yegor256 fixed in pull request #642

**Comment by yegor256** [comment]
@komaz thanks!

**Comment by yegor256** [comment]
@dmzaytsev let's release it?

**Comment by dmzaytsev** [comment]
@yegor256 sure,
I waited until ticket will be closed

**Comment by yegor256** [comment]
@dmzaytsev @komaz looks like it doesn't work yet: #646 (let's continue in that ticket)

**Comment by yegor256** [comment]
@dmzaytsev FYI it's better to do "rultor release" inside the ticket where the fix/feature was introduced

**Comment by dmzaytsev** [comment]
@yegor256 got it

**Comment by karato** [comment]
@yegor256 once `609-bc8eaf9f`/#648 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@komaz I added 10 mins to @ypshenychka (for QA review) in transaction 58208209; **30 mins** added to your account (payment number `AP-0BD27849CE588701C`), many thanks for your contribution! 167 hours and 40 mins spent here.; +30 to your rating, your total score is [+240](http://www.netbout.com/b/35322?open=rating)

**Comment by karato** [comment]
@yegor256 last puzzled solved `609-bc8eaf9f`/#648
