### ISSUE TITLE
/start with arguments

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#610]
It should be possible to make this request:

```
/start?post=How+are+you&invite=yegor256&invite=dmzaytsev
```

Such a request should start a bout, invite a few users and post a message. All in one go.

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@yegor256 since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev milestone is set to 3.0

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-7fe61838

**Comment by karato** [comment]
@komaz this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by karato** [comment]
@yegor256 there is a puzzle in this code `610-76d661ee`/#641, we'll resolve it later

**Comment by komaz** [comment]
@yegor256 fixed in pull request #619

**Comment by yegor256** [comment]
@komaz thanks!

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@komaz I added 10 mins to @ypshenychka (for QA review) in transaction 58184010. thank you, added **30 mins** to your acc, payment num is `AP-4H06191740850015N`, 140 hours and 38 mins spent in total to complete. +30 added to your rating, current score is: [+210](http://www.netbout.com/b/35322?open=rating)

**Comment by karato** [comment]
@yegor256 last puzzled solved `610-76d661ee`/#641

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#unknown]() is solved here.
