### ISSUE TITLE
RtAlias.email not implemented yet

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#611]
`com.netbout.client.RtAlias.email()` and `com.netbout.client.RtAlias.email(final String email)` not implemented yet but has to be. Let's implement them and don't forget about the unit test.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev I set the milestone here to 3.0

**Comment by karato** [comment]
@dmzaytsev many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `57694731`

**Comment by karato** [comment]
@mbarbieri it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by mbarbieri** [comment]
By unit tests you mean similar to `com.netbout.client.RtMessagesITCase`?
I'm not able to run any of those tests because *netbout.token* is empty..
How can I run them?
Thanks

**Comment by mbarbieri** [comment]
@dmzaytsev sorry, forgot to mention you in the previous comment

**Comment by mbarbieri** [comment]
@dmzaytsev I'm not able to run Rt tests, raised an issue #626

**Comment by mbarbieri** [comment]
@dmzaytsev PR #639 is ready to be reviewed

**Comment by dmzaytsev** [comment]
@mbarbieri you should inform the project manager about it not me

**Comment by mbarbieri** [comment]
@karato PR #639 is ready to be reviewed

**Comment by dmzaytsev** [comment]
@yegor256 why Rultor closed this ticket?

**Comment by karato** [comment]
@rultor don't close it, ask @dmzaytsev to do do it, since he created it, thanks!

**Comment by dmzaytsev** [comment]
@mbarbieri thanks!

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@mbarbieri 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please always indicate a person you're referring too in the beginning of the comment/message.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by mbarbieri** [comment]
@ypshenychka yes, it was my first task... Thanks

**Comment by vbodak** [comment]
@mbarbieri thanks! Let's try to make high-quality tickets :)

**Comment by vbodak** [comment]
@karato Quality is acceptable.

**Comment by ypshenychka** [comment]
@mbarbieri thanks! Let's try to make high-quality tickets :)

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@mbarbieri 10 mins was added to the account of @ypshenychka (for QA review), in transaction 58206178; **30 mins** added to your account (payment number `AP-7T512155EN2896133`), many thanks for your contribution! 162 hours and 44 mins spent here.; added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/35357?open=rating)
