### ISSUE TITLE
RtFriends.friends() not implemented

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#613]
`com.netbout.client.RtFriends.friends()` not implemented yet but has to be.
Let's implement it and don't forget about the unit test

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev I attached this issue to milestone `3.0`

**Comment by karato** [comment]
@dmzaytsev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `57691869`

**Comment by karato** [comment]
@zshamrock this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by zshamrock** [comment]
@karato more time

**Comment by karato** [comment]
> @karato more time

@zshamrock sure, take your time

**Comment by zshamrock** [comment]
@karato started working on this one

**Comment by zshamrock** [comment]
@karato according to http://www.yegor256.com/2014/04/15/github-guidelines.html I create a bug https://github.com/yegor256/netbout/issues/686

**Comment by dmzaytsev** [comment]
@karato @yegor256 all methods of `com.netbout.spi.Friends` has the Restful API implementation already. My bad, sorry :(
I'm closing the ticket

**Comment by dmzaytsev** [comment]
@zshamrock sorry, it's invalid ticket

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is bad here. Ticket is invalid

**Comment by yegor256** [comment]
@karato quality is bad, I confirm

**Comment by zshamrock** [comment]
@yegor256 just curious, why do say quality is bad, if it is an invalid ticket?

**Comment by karato** [comment]
> @karato quality is bad, I confirm

@yegor256 thanks a lot, noticing bad quality is what makes us better

**Comment by karato** [comment]
@zshamrock just added 10 mins to @elenavolokhova (for QA), payment ID is `59135017`

**Comment by yegor256** [comment]
@dmzaytsev looks like you may consider creating a new ticket of similar content.. since this one is gone wrong
