### ISSUE TITLE
Preview the entered message

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#614]
It would be great if we will allow to preview a message before post it.
we should implement two tabs above the message area: Write and Preview like in the Github comments.  Let's use `com.netbout.rest.Markdown` for convert the entered message to html.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by yegor256** [comment]
@dmzaytsev markdown is already supported in messages, try it. The only thing that is not supported is that "preview" button

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev I attached this issue to milestone `3.0`

**Comment by karato** [comment]
@dmzaytsev many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `57685379`

**Comment by karato** [comment]
@mbarbieri it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by mbarbieri** [comment]
@karato Since I'm still learning the codebase, I'm sure I'll not be able to complete it in a short time.
I think it's better if you assign this task to someone else.

**Comment by mbarbieri** [comment]
@karato will you assign this to someone else?

**Comment by karato** [comment]
> @karato will you assign this to someone else?

@mbarbieri 30 points deducted from your rating

**Comment by karato** [comment]
> @karato will you assign this to someone else?

@mbarbieri no problem, I will try to find somebody else

**Comment by karato** [comment]
@lautarobock could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@lautarobock you need to implement two tabs above the message area: Write and Preview like in the  Github comments. For Preview you might to use `com.netbout.rest.Markdown`

**Comment by dmzaytsev** [comment]
@lautarobock is there any progress here?

**Comment by lautarobock** [comment]
@dmzaytsev yes, but with a little problem

**Comment by dmzaytsev** [comment]
@lautarobock  what's the status here?

**Comment by lautarobock** [comment]
@dmzaytsev I have a problem with visual components for tabs

**Comment by karato** [comment]
@lautarobock 15 days already, in 48 hours I will re-assign... -30 to your rating, your total score is [+120](http://www.netbout.com/b/35344?open=rating)

**Comment by karato** [comment]
@lautarobock task is too long, stop working with it. added -60 to your rating, now it is equal to [+30](http://www.netbout.com/b/35344?open=rating)

**Comment by lautarobock** [comment]
@karato ok, sorry

**Comment by dmzaytsev** [comment]
@antonini could you pick up this task?

**Comment by antonini** [comment]
@dmzaytsev Yes I can! Please assign this to me.

**Comment by dmzaytsev** [comment]
@karato please assign to @antonini

**Comment by antonini** [comment]
@karato Can you assign this to me?

**Comment by dmzaytsev** [comment]
@yegor256 @karato please assign this ticket to @antonini

**Comment by yegor256** [comment]
@karato assign this task to @antonini pls

**Comment by yegor256** [comment]
@karato assign this task to @antonini pls

**Comment by yegor256** [comment]
@karato assign this task to @antonini pls

**Comment by antonini** [comment]
@karato This issue depends on #728. There is an error on JS that stops all other events.

**Comment by dmzaytsev** [comment]
@karato assign this task to @antonini please

**Comment by antonini** [comment]
@karato, @dmzaytsev and @yegor256  I'm waiting for issue to be to me so I can do a PR. Am I going to have some trouble with the following [policy](http://www.teamed.io/policy.html#7)

**Comment by antonini** [comment]
@karato, @dmzaytsev and @yegor256 Ping.

**Comment by yegor256** [comment]
@karato assign it to @antonini

**Comment by karato** [comment]
@antonini do this task, 30 mins is budget

**Comment by antonini** [comment]
@karato As I said before, this issue depends on #728. Can you assign that to me too? 

That issue need to be merged before the fix of this one.

**Comment by antonini** [comment]
@karato and @dmzaytsev PR #734 waiting for review. Please assing issue #728 to me so I can create PR to be merged before this one!

**Comment by dmzaytsev** [comment]
@antonini I guess  the messagebox tabs won't  switch until  #728 will be resolved.
am I right?

**Comment by antonini** [comment]
@dmzaytsev Yeap. On that PR i fixed an error that is happening on console.

**Comment by dmzaytsev** [comment]
@antonini thanks!

**Comment by antonini** [comment]
@karato Issue is closed.

**Comment by karato** [comment]
> @karato Issue is closed.

@antonini thanks, I'll dispatch the payment soon

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you ;)

**Comment by karato** [comment]
@antonini I added 10 mins to @ypshenychka (for QA review) in transaction 60853834. done, I added **38 mins** in payment `AP-3SP03399W2380861F`, 62 hours and 3 mins spent to complete this. there is a bonus for fast delivery (m=3723). +38 added to your rating, current score is: [+309](http://www.netbout.com/b/35346?open=rating)
