### ISSUE TITLE
Network port reservation

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#615]
Let's create class `Ports` for network port reservation and put it into `com.netbout.misc` package.
We can copy-paste `Ports` class from Takes framework.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

please set milestone to 3.0

this is urgent task

**Comment by dmzaytsev** [comment]
@karato please assign @ndbroadbent to this task

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev I attached this issue to milestone `3.0`

**Comment by karato** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `58056210`

**Comment by karato** [comment]
@antonini this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by antonini** [comment]
@yegor256 Which module I put this? I think it should be on `netbout-client`. Is it right?

**Comment by dmzaytsev** [comment]
@antonini please put this into `netbout-web`. This class will be used in the future unit tests.

**Comment by dmzaytsev** [comment]
@antonini thanks!

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@antonini 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please mention link to the PR in any message.

**Comment by antonini** [comment]
@ypshenychka I didn't understood your point, because the PR mention the original issue.

**Comment by ypshenychka** [comment]
@antonini You should've written in this ticket at least one message that will point us to the PR in which the bug is fixed. 
For example, "Waiting for PR #654" or "Issue is fixed in PR #654".

**Comment by antonini** [comment]
@ypshenychka Now I understood. I´ll do that on other issues. Thanks.

**Comment by ypshenychka** [comment]
@antonini Thank you!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks, got it. everybody, please try to make it good next time

**Comment by karato** [comment]
@antonini just added 10 mins to @ypshenychka (for QA), payment ID is `58505496`; paid, thanks, added **38 mins** to your account, payment `AP-5BY68816K7131492E`, 69 hours and 46 mins was spent; there is a bonus for fast delivery (m=4186); +38 added to your rating, at the moment it is: [+106](http://www.netbout.com/b/35346?open=rating)
