### ISSUE TITLE
TkPost.act catches wrong exception

### ISSUE THREAD

**Issue by komaz** [yegor256/netbout#616]
`TkPost.act` posts messages like this:
```java
        try {
            bout.messages().post(...)
        } catch (final Attachments.InvalidNameException ex) {
            throw new RsFailure(ex);
        }
```
However according to `DyMessages.post`, the exception thrown should be `Messages.BrokenPostException`. Looks like the catch snippet is taken from `TkAttach`.

**Comment by dmzaytsev** [comment]
@komaz you're right, thanks!

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@komaz attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@komaz thanks for tis bug, I topped your account for 15 mins, transaction `AP-41274360G2475400S`

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev the milestone here is 3.0

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev OK, I labeled it as "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@lautarobock it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by lautarobock** [comment]
@karato PR #655 are ready for review

**Comment by dmzaytsev** [comment]
@karato this task is not postponed any more

**Comment by karato** [comment]
> @karato this task is not postponed any more

@dmzaytsev thanks, I removed the "postponed" tag

**Comment by lautarobock** [comment]
@karato anything else for close it?

**Comment by yegor256** [comment]
@lautarobock only @komaz can close it, talk to him

**Comment by komaz** [comment]
@lautarobock thanks for the fix

**Comment by lautarobock** [comment]
@karato what about my paid? thanks

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thanks a lot :)

**Comment by karato** [comment]
@lautarobock 10 mins was added to the account of @ypshenychka (for QA review), in transaction 58621465; Thank you, I have added **30 mins** to your account in payment/transaction "`AP-7PU11138212249406`", time consumed: 92 hours and 44 mins; +30 to your rating, your total score is [+90](http://www.netbout.com/b/35344?open=rating)
