### ISSUE TITLE
where com.netbout.mock is used?

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#617]
@yegor256  What is the purpose of these classes `com.netbout.mock.*` ? 
I could not find where it is used

**Comment by komaz** [comment]
@dmzaytsev I found MkBase usage in `com.netbout.rest` tests, e.g `con.netbout.rest.bout.TkCreateTest`

**Comment by dmzaytsev** [comment]
@komaz yes, thanks!

**Comment by yegor256** [comment]
@dmzaytsev we still need this ticket?

**Comment by dmzaytsev** [comment]
@yegor256 I'm closing this ticket ,
thanks
