### ISSUE TITLE
MkInbox is not equivalent to DyInbox

### ISSUE THREAD

**Issue by komaz** [yegor256/netbout#618]
Consider an inbox without bouts. The same snippet will work fine on dynamo db, but fails with `NoSuchElementException` on mock db:
```java
inbox.start();
inbox.iterable().iterator.next()
``` 
Looks like `MkInbox.start` should also add a self alias into `friend` table, as `MkFriends.invite` does.

**Comment by dmzaytsev** [comment]
@komaz isn't it a duplicate of #570 ?

**Comment by komaz** [comment]
@dmzaytsev you are right, it is, I'm closing an issue
