### ISSUE TITLE
Kick link is broken

### ISSUE THREAD

**Issue by komaz** [yegor256/netbout#620]
When I'm trying to kick someone from a conversation on an index page, the kick link looks like this: `http://www.netbout.com/b/5555555/%2Fkick?name=ivaninozemtsev`. When I click on it, I get an error message `page not found`. Looks like an extra slash is escaped as `%2F` here.

I think the problem is in `TkInbox.source(Bout, Friend)` method:
```java
            new XeLink(
                "kick",
                new Href("/b")
                    .path(bout.number())
                    .path("/kick")
                    .with("name", friend.alias())
            )
```

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@komaz thanks!

**Comment by dmzaytsev** [comment]
@karato please set milestone tp 3.0

**Comment by karato** [comment]
> @karato it's a valid bug
> 

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@komaz I set milestone here to `3.1`, let me know if it is wrong

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev milestone is set to 3.0

**Comment by karato** [comment]
@komaz thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-9PH37963PA2788132`

**Comment by karato** [comment]
@antonini this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by antonini** [comment]
PR #663 ready for review.

**Comment by antonini** [comment]
@komaz Code was deployed and available 4 days ago. Did you tested it?

**Comment by komaz** [comment]
@antonini thanks for a fix

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@antonini
>PR #663 ready for review.

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please  indicate a person you're referring to in the beginning of the message.

**Comment by antonini** [comment]
@ypshenychka Fixed my comment.

**Comment by ypshenychka** [comment]
@antonini Great! Thank you.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thank you, let's try to make it "good" next time

**Comment by karato** [comment]
@antonini just added 10 mins to @ypshenychka (for QA), payment ID is `59122447`

Many thanks! **30 mins** were added to your account in Transaction ID `AP-4R877570Y69337225` (task took 357 hours and 26 mins)

+30 added to your rating, at the moment it is: [+196](http://www.netbout.com/b/35346?open=rating)
