### ISSUE TITLE
User.friends documentation is not fully complete

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/netbout#622]
Current `User.friends` documentation states:

```
/**
     * Find potential friends to talk to.
     * @param text Text to search with
     * @return Friends
     * @throws java.io.IOException If fails
     */
    Iterable<Friend> friends(
        @NotNull(message = "text can't be NULL") String text)
        throws IOException
```

But it does not elaborate on who potential friends are.

It is also not specified on what is the semantic of `text` parameter. What is the format, is it a pattern to apply to the name, or a comma separated list of patterns. Example of a text parameter would help a lot.

**Comment by dmzaytsev** [comment]
@yegor256 I think we need a brief paper with a project description. Could you help us?

**Comment by dmzaytsev** [comment]
@ekondrashev the parameter `text` is the name of the user alias.
`User.friend()` looks for `Friends` by they alias name
https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/TkFriend.java#L81
you may proceed the task #612 on the basis of this.

@yegor256 Have you any plan to use this interface another way?
should we change the javadoc as above?

**Comment by ekondrashev** [comment]
@dmzaytsev 
I'm missing the meaning of word `potential` here. Who are potential friends? What is the algorithm of deciding whether it is a friend or not? 
```
parameter text is the name of the user alias
```
It is current user alias? If yes why it is not encapsulated into the User class itself?

**Comment by dmzaytsev** [comment]
@ekondrashev I don't know, I just looked into code and saw how this parameter used.
> I'm missing the meaning of word potential here. Who are potential friends? What is the algorithm of deciding whether it is a friend or not?

> It is current user alias? If yes why it is not encapsulated into the User class itself?
it's a friend alias. 
let's ask Yegor

@yegor256 please help us

**Comment by dmzaytsev** [comment]
@karato please assign this task to @yegor256

**Comment by karato** [comment]
@yegor256 dispatch this issue please

**Comment by karato** [comment]
> @karato please assign this task to @yegor256 

@dmzaytsev OK, will assign soon

**Comment by karato** [comment]
> @karato please assign this task to @yegor256 

@dmzaytsev OK, will assign soon

**Comment by karato** [comment]
> @karato please assign this task to @yegor256 

@dmzaytsev OK, will assign soon

**Comment by karato** [comment]
> @karato please assign this task to @yegor256 

@dmzaytsev OK, will assign soon

**Comment by karato** [comment]
> @karato please assign this task to @yegor256 

@dmzaytsev OK, will assign soon

**Comment by yegor256** [comment]
@dmzaytsev anyone else in the project can complete this task, pls try to avoid assigning tasks to me

**Comment by dmzaytsev** [comment]
@yegor256 sorry, I asked 40 days ago about it...

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
@ekondrashev since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato please assign this task to @yegor256 

@dmzaytsev yep, done. @yegor256 it is your task now

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev "postponed" label already in this issue

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will ask somebody else to pick this up

**Comment by karato** [comment]
@ekondrashev thanks for the ticket, your account was topped for 15 mins, payment 63342280
