### ISSUE TITLE
netbout needs js autocompletion lib implementing github like mention functionality

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/netbout#623]
As for now netbout code base missing js library that can be used in order to implement github like `@mention` functionality.

It has to be, making it possible to fix #606 defect.
The library should include js file(s) and style sheet file(s) to regulate styles of autosuggestion dropdown. 
It is also good idea to cover it with unit tests.

Brief googling gave following results that can be used 
* https://github.com/shovon/inlinedAutocomplete
* https://github.com/tactivos/jquery-sew
* https://github.com/ivirabyan/jquery-mentions

**Comment by dmzaytsev** [comment]
@ekondrashev If we will assign someone on this task what will be the result of this ticket? what a performer should be deliver?
There is no need to create a separate ticket in this case, I think.
You have a task,  you have to suggest a solution and implement it.
Let's continue in #606.

**Comment by ekondrashev** [comment]
@dmzaytsev the result is particular lib to use. 
The performer should search on the web the library, analyse if it fits to requirement like: license, support availability etc. If #606 will contains text like "use this particular lib" then this ticket is not needed.

**Comment by yegor256** [comment]
@ekondrashev looks like @dmzaytsev is right, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken and http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by ekondrashev** [comment]
@yegor256 I'm not sure where I'm not following those rules.
#606 requires investigation. Please let me know I'm missing.

**Comment by dmzaytsev** [comment]
@ekondrashev a ticket result is a merged PR. If no a ticket will get bad
quality mark and won't be paid.

**Comment by ekondrashev** [comment]
@dmzaytsev @yegor256 would it work if I change the initial issue title/details requesting js library to be imported to the source base that can be used to implement mention functionality?

**Comment by yegor256** [comment]
@ekondrashev something should be **broken** in order to become a good cause for a ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken

**Comment by yegor256** [comment]
@ekondrashev you're not supposed to _request_ anything in a ticket. Instead, you should say what is wrong in current version of the code base.

**Comment by yegor256** [comment]
@ekondrashev keep in mind that documentation can also be broken

**Comment by ekondrashev** [comment]
@yegor256 I was owner of several tickets requesting for implementing something to simplify coding/testing, like [takes259](https://github.com/yegor256/takes/issues/259) and takes [260](https://github.com/yegor256/takes/issues/260) that are tagged as enhancements.

**Comment by ekondrashev** [comment]
@dmzaytsev please review reworked ticket and let me know if it makes sense now.

**Comment by dmzaytsev** [comment]
@yegor256 @ekondrashev 
I think the library choice should be done inside #606. It's a particular task related only the  ticket #606. There is no need to update readme.
I propose to do so @ekondrashev  implement the input data preparation - add all bout's friends (full name and alias) into the page as js-array 
e.q. users: [{name: 'Lindsay Made',	username: 'lindsaym'}, 
{name: 'Rob Dyrdek',username: 'robdyrdek'}]
Then create a puzzle and another developer will complete the ticket.

**Comment by ekondrashev** [comment]
@dmzaytsev I totally agree with you on the input data preparation, but don't you think that the one who will be working with the lib should make a choice on which lib to use? I mean most of the time decision is made after tight work with the lib.

**Comment by dmzaytsev** [comment]
@ekondrashev I do not see a way to choose the library in a separate task  without violating the rules at the same time. "Choosing" as a process do nothing for the project. We can't merge "choosing". Do you see my point ?
I think a performer should choose a library and make a stub which just  show the empty friends list. But we already have the ticket #606 for this. I understand full implementation  may exceed the time limit for the task. In this case we can create a puzzle.
It seemed to me that you do not want to do UI part of the work, so I proposed to you to make the second part of the work. Correct me if I wrong.

@yegor256 what do you think about it?

**Comment by ekondrashev** [comment]
@dmzaytsev well, it is not like a "choosing" now, initial ticket description is changed pointing that the codebase misses proper library, asking the performer to import it to codebase.
@yegor256 wha is your word?

**Comment by yegor256** [comment]
@ekondrashev I'm with @dmzaytsev on this. First, "choosing" anything or thinking about anything is not what a project is willing to pay for. The project is paying for source code. How you create it - it's your business. If you need to choose, or to think, or to experiment, or to learn something first, do it, but the result is always a piece of code that we can add to the code base. This article explains it in more details: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

Second, I see that you changed the description of the ticket and now it sounds more like a bug - the code base "is missing a library". But it doesn't say what is broken for a user (!). "Our" code base is perfectly fine now. You're asking "us" to fix it by adding some extra library to it. Why would we do this? What value does this library give to an end user? Zero. It gives value to you, an implementer of #606, but why do we care? You already have a ticket #606, where the project will pay you for implementing a feature which will give value to product users. More about it in this article: http://www.yegor256.com/2015/02/12/top-down-design.html

So, the bottom line here is that you should create something in #606 and mark everything else with `@todo` puzzles. In other words, you should break (!) the product and let us come back to you later, with a new puzzle-generated ticket and ask you to fix it. More about this fix-and-break approach is here: http://www.yegor256.com/2014/04/12/puzzle-driven-development-by-roles.html#fix-and-break

Make sense?

**Comment by ekondrashev** [comment]
@yegor256 It does make sense. But I'd really love to understand difference between this ticket being refused as not giving any value to the user and [this](https://github.com/yegor256/takes/issues/260) which falls under same conditions(no end user value, nothing is broken), being accepted as valid.

From my POV the only difference between those tickets is that current one enriches project with a lib that is ready to be used by dev in order to implement #606 and last one enriches project with a class simplifying dev life and making code cleaner.

**Comment by yegor256** [comment]
@ekondrashev not really. In Netbout project a user is a web user with a browser. In Takes project a user is a software developer, who is using that Java framework to create some web app. That's why that ticket is perfectly legal, since it basically says "I'm a user and I can't use your library the way I want it, because it doesn't have this feature, fix it"

Here, we can't say so. A user of Netbout wouldn't be able to say that. Simply because he doesn't care about any JS libraries :)

**Comment by ekondrashev** [comment]
@dmzaytsev @yegor256 thank you guys for your answers, I believe pdd is my friend. Not sure if I should just close this guy or rename it once puzzle will be introduced.

**Comment by yegor256** [comment]
@ekondrashev yes, try to use PDD as much as possible, you will like it eventually :)
