### ISSUE TITLE
Missing documentation on how to run com.netbout.client.Rt*  tests

### ISSUE THREAD

**Issue by mbarbieri** [yegor256/netbout#626]
com.netbout.client.Rt* tests (for example `RtUserITCase`) are skipped because `netbout.token` is null.
Add documentation in README.md on how to run them. (see comments below)

**Comment by mbarbieri** [comment]
Ok, blaming the project now :smile: 
Tests like `RtUserITCase` are skipped because `netbout.token` is null and there is no documentation on how to run them.

**Comment by dmzaytsev** [comment]
@yegor256 could you please answer the question above?
how to run integration tests locally? is it possilble without the token?

**Comment by yegor256** [comment]
@mbarbieri just run them from command line, like this:

```
mvn clean install
```

You're probably trying to run them from your IDE. This way they won't work (but they won't fail, will just be skipped by JUnit)

**Comment by dmzaytsev** [comment]
@yegor256 are you sure? @mbarbieri talking about `com.netbout.client.Rt*`
I just run `mvn clean install`
```
Running com.netbout.client.RtInboxITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.netbout.client.RtInboxITCase
Running com.netbout.client.RtUserITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.012 sec - in com.netbout.client.RtUserITCase
Running com.netbout.client.RtMessagesITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.017 sec - in com.netbout.client.RtMessagesITCase
Running com.netbout.client.RtFriendsITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.netbout.client.RtFriendsITCase
Running com.netbout.client.RtAttachmentsITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.012 sec - in com.netbout.client.RtAttachmentsITCase
Running com.netbout.client.RtBoutITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.netbout.client.RtBoutITCase
```

all tests skiped because `netbout.token`  variable is not set

Anyway we need to test `com.netbout.client` classes. From my point to test the rest-client we just need a simple Take that will receive the request and respond to it. There is the problem we don't known which a Take should use. It's not clean.
E.g. we need to test `RtAlias` I guess the data for the corresponded rest-service make by `com.netbout.rest.XeAlias`... Could you explain how make valid Request to test `RtAlias` properly?

**Comment by yegor256** [comment]
@mbarbieri @dmzaytsev right, my fault. This `netbout.token` should be provided on command line, like this:

```
mvn clean install -Dnetbout.token=...
```

You can get its value from www.netbout.com. Just login there and then see the cookie returned at `Set-Cookie: PsCookie=...` (this is the token).

`ITCase` tests are intended to test the client against a real production server. We shouldn't mock anything there. We need to keep them the way they are.

**Comment by mbarbieri** [comment]
@dmzaytsev changed the issue to report it as a bug

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@mbarbieri since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@mbarbieri thanks for the report, I topped your acc for 15 mins, payment ID `AP-1RG2971751088271U`

**Comment by dmzaytsev** [comment]
@karato please assign this task

**Comment by karato** [comment]
> @karato please assign this task

@dmzaytsev we don't have enough people in the project now... we're working on it now

**Comment by dmzaytsev** [comment]
@karato  thanks for letting me know

**Comment by antonini** [comment]
@karato I can do this.

**Comment by karato** [comment]
> @karato  thanks for letting me know

@dmzaytsev no probs

**Comment by dmzaytsev** [comment]
@karato assign this to @antonini please

**Comment by karato** [comment]
> @karato assign this to @antonini please

@dmzaytsev done. @antonini the task is yours, please go ahead

**Comment by antonini** [comment]
@dmzaytsev I know that I asked for it, but I think we have a situation running local tests. When I did those steps maven threw an expcetion:

```
Results :

Failed tests: 
  RtAliasITCase.updateAndRetrieveEmail:62 
Expected: is "alias1030344790@example.com"
     but: was "xxxxxxxx@xxxxxxx.xxx.xx"

Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
```

What we should do?

**Comment by dmzaytsev** [comment]
@antonini perhaps it's the bug #737

**Comment by dmzaytsev** [comment]
@antonini try to ignore this test
You should update  readme in this ticket, right?

**Comment by antonini** [comment]
@dmzaytsev Ok.

**Comment by antonini** [comment]
@karato PR #745 ready for review.

**Comment by karato** [comment]
> @karato PR #745 ready for review.

@antonini thanks!

**Comment by antonini** [comment]
@mbarbieri PR was merged, please check if looks good for you.

**Comment by antonini** [comment]
@mbarbieri Did you checked it?

**Comment by antonini** [comment]
@mbarbieri @karato Ping.

**Comment by karato** [comment]
@antonini 15 days already, in 48 hours I will re-assign; -30 added to your rating, at the moment it is: [+399](http://www.netbout.com/b/35346?open=rating)

**Comment by antonini** [comment]
@karato PR was merged. I'm pinging issue author and he is not answering.

**Comment by antonini** [comment]
@dmzaytsev Can you help me over here?

**Comment by dmzaytsev** [comment]
@antonini sorry, I can't.
but if you had asked the PM for more time you had not be fined..

I suggest to ask @yegor256 about the closing and the payment.

**Comment by mbarbieri** [comment]
@antonini @dmzaytsev Sorry I was on vacation...

**Comment by antonini** [comment]
@mbarbieri Thank you.

**Comment by antonini** [comment]
@karato Issue is closed.

**Comment by karato** [comment]
> @karato Issue is closed. 

@antonini OK thanks

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks a lot

**Comment by karato** [comment]
@antonini just added 10 mins to @elenavolokhova (for QA), payment ID is `62249803`... thank you, added **30 mins** to your acc, payment num is `AP-7W464123EX439740N`, 380 hours and 57 mins spent in total to complete... added +30 to your rating, now it is equal to [+429](http://www.netbout.com/b/35346?open=rating)
