### ISSUE TITLE
MkFriends.invite never fails

### ISSUE THREAD

**Issue by komaz** [yegor256/netbout#628]
The following statement executes successfully, but `Friends.UnknownAliasException` expected:
```java
new MkBase().randomBout().friends().invite("NoSuchFriend");
```

**Comment by dmzaytsev** [comment]
@komaz  there is no need to create a new ticket, if you think that's the task exceed the budget.
Just create a puzzle in your PR and another developer will continue your work.
Check this article please www.yegor256.com/2009/03/04/pdd.html

**Comment by komaz** [comment]
@dmzaytsev I think the fact that the behavior of `MkFriends` and `DyFriends` differs is a separate issue, which is not directly related to completing #610. I'll create puzzle for negative tests, thanks for the information.

**Comment by dmzaytsev** [comment]
@komaz you should say what is wrong in current version of the code base, 
see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken
please reformat your ticket

**Comment by komaz** [comment]
@dmzaytsev does it look better now?

**Comment by dmzaytsev** [comment]
@komaz Is `DyFriends` raise exception if unknown friends invited?

**Comment by komaz** [comment]
@dmzaytsev yes, it is being thrown from [line 127](https://github.com/yegor256/netbout/blob/2.14.12/netbout-web/src/main/java/com/netbout/dynamo/DyFriends.java#L127), looks like this in a log:
```
[ERROR] pool-5-thread-12 com.netbout.dynamo.DyFriends: #invite('whoever'): 
thrown com.netbout.spi.Friends$UnknownAliasException(alias 'whoever' doesn't exist) 
out of com.netbout.dynamo.DyFriends#invite_aroundBody0[126]
```

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by dmzaytsev** [comment]
@karato this task is postponed

**Comment by dmzaytsev** [comment]
@komaz thanks!

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@komaz since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato this task is postponed

@dmzaytsev right, I will find someone else, no problem

**Comment by karato** [comment]
@komaz thanks for reporting! I topped your account for 15 mins, transaction AP-2T172356NM835162G

**Comment by dmzaytsev** [comment]
@karato this task is not postponed any more

**Comment by karato** [comment]
> @karato this task is not postponed any more
> 

@dmzaytsev sure, thanks, I removed "postponed" tag to it

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev got it, "urgent" tag here

**Comment by karato** [comment]
@erimerturk this is your task

**Comment by dmzaytsev** [comment]
@karato this task not urgent anymore

**Comment by karato** [comment]
> @karato this task not urgent anymore

@dmzaytsev right, I removed "urgent" tag

**Comment by erimerturk** [comment]
@komaz @dmzaytsev please see PR : #720

**Comment by erimerturk** [comment]
@komaz could you please check and close issue, thank you!

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks for the review and a good remark

**Comment by karato** [comment]
@erimerturk I added 10 mins to @ypshenychka (for QA review) in transaction 60405915... Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-81T36288L8809133N`, total time was 93 hours and 43 mins... +30 added to your rating, current score is: [+150](http://www.netbout.com/b/35280?open=rating)
