### ISSUE TITLE
Missing email validation

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/netbout#629]
In `TkSaveEmail` we save emails without any validation. You can save any string as an email.

**Comment by dmzaytsev** [comment]
@ikhvostenkov you're right, we should validate the email before save. I think we have to find suitable  RFC and use a regular expression according it

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@ikhvostenkov since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@ikhvostenkov thanks for reporting! I topped your account for 15 mins, transaction 58062748

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev sure, thanks, I added "postponed" tag to it

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev I will ask somebody else to pick this up
