### ISSUE TITLE
Logout functionality is not working on local env.

### ISSUE THREAD

**Issue by erimerturk** [yegor256/netbout#631]
Logout functionality is not working on local env. when i run it with this command. Because of this reason i am not able to create different users.
<code>$ mvn clean install -Phit-refresh -Dport=8080</code>

**Comment by dmzaytsev** [comment]
@erimerturk check this comment https://github.com/yegor256/netbout/issues/584#issuecomment-100732005 I guess it will help

**Comment by erimerturk** [comment]
@dmzaytsev thank you, it helped
