### ISSUE TITLE
infinite scrolling doesn't work in Firefox

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#632]
Infinite scrolling of messages in bout doesn't work in Firefox. I'm not sure about bouts in inbox, but I suspect that it also doesn't work.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@yegor256 since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev thanks, I set it to "3.0"

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-d4d28758

**Comment by karato** [comment]
@erimerturk do this task

**Comment by erimerturk** [comment]
@yegor256 is there anyway to disable compress, minify js files ? I couldn't find it how can do it ? I should be able to debug js files.

**Comment by erimerturk** [comment]
@yegor256 you can see PR #676

**Comment by erimerturk** [comment]
@yegor256 please review and close if it is acceptable, thank you!

**Comment by karato** [comment]
@erimerturk 15 days already, in 48 hours I will re-assign. -30 to your rating, your total score is [+180](http://www.netbout.com/b/35280?open=rating)

**Comment by erimerturk** [comment]
@karato it is fixed and waiting for @yegor256 approve

**Comment by dmzaytsev** [comment]
@erimerturk keep in mind http://www.teamed.io/policy.html#30
you should just ask more time if you hold the task more then  7 days
it's your responsibility as the ticket performer

**Comment by erimerturk** [comment]
@dmzaytsev i see, i am beginner at teamed so it will take time to learn all rules. it is my mistake.

**Comment by erimerturk** [comment]
@karato could you please wait until @yegor256 review ? I hope @yegor256  will accept my solution. Fix is already merged to master branch.

**Comment by erimerturk** [comment]
@yegor256 please review and close if it is acceptable, thank you!

**Comment by erimerturk** [comment]
@yegor256 please review and close if it is acceptable, issue is waiting for your approve , thank you

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@erimerturk we'll deploy now to snapshot.netbout.com and I'll check it there...

**Comment by yegor256** [comment]
@erimerturk I see exactly the same problem in http://snapshot.netbout.com Try to create a bout and post many messages into it. You won't be able to scroll. See #677, it talks about the same problem (or similar).

**Comment by yegor256** [comment]
@erimerturk this is what I see:

![screen shot 2015-06-16 at 12 57 57 pm](https://cloud.githubusercontent.com/assets/526301/8193059/5ba70864-1427-11e5-8e21-1d62ed40012e.png)

**Comment by erimerturk** [comment]
@yegor256 how can it be ? i am trying on snapshot also and it working for me :S . <b>38.0.5</b> is my firefox version, what is yours ? and could you please add me to that bout ? eerturk is my alias

**Comment by erimerturk** [comment]
@yegor256 could you please open a private window and try it again ? thank you

**Comment by yegor256** [comment]
@erimerturk added you there: http://snapshot.netbout.com/b/17

**Comment by erimerturk** [comment]
@yegor256 it is working for me, you can see two different paging request. could you please try it on private window and give me feedback ? thank you

![screen shot 2015-06-17 at 14 06 20](https://cloud.githubusercontent.com/assets/416283/8205533/2ecd2534-14fa-11e5-9df1-ae5c8d3af1bf.png)

**Comment by karato** [comment]
@erimerturk task is too long, stop working with it... -60 added to your rating, at the moment it is: [+120](http://www.netbout.com/b/35280?open=rating)

**Comment by yegor256** [comment]
@erimerturk this problem happens sometimes. Sometimes everything works just fine, but sometimes it just fails and I see what I mentioned above

**Comment by erimerturk** [comment]
@yegor256 before i made fix js was waiting ajax response as xml, but i netbout was returning html for ff. So i changed xml parsing to html parsing and scroll is working now. It maybe has another problem i dont know. I fixed parsing problem and lost 90 point, it is not fair

**Comment by yegor256** [comment]
@erimerturk you do remember this, right: http://www.teamed.io/policy.html#7 You should worry about task completion in time, that's your responsibility, not mine (as ticket reporter). When you see that you need more time than usual, you should inform project manager about it, see http://www.teamed.io/policy.html#10

**Comment by yegor256** [comment]
@karato assign @erimerturk back to this ticket pls

**Comment by karato** [comment]
> @karato assign @erimerturk back to this ticket pls

@yegor256 done. @erimerturk the task is yours, please go ahead

**Comment by erimerturk** [comment]
@yegor256 i think you should accept this solution and then we can open another issue for the other problem. Because i believe that they are two different problems and we haven't define reason of your problem.This solution is fixed <b>html parse handle problem</b> what do you think ? i am blocked.

**Comment by yegor256** [comment]
@erimerturk right, thanks

**Comment by erimerturk** [comment]
@yegor256 thank you!

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova many thanks

**Comment by karato** [comment]
@erimerturk 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 59912249... **30 mins** was added to your account, many thanks for your contribution (payment AP-22S982568Y486662F)! The task took 74 hours and 19 mins.... added +30 to your rating, now it is equal to [+90](http://www.netbout.com/b/35280?open=rating)
