### ISSUE TITLE
broken test com.netbout.rest.TkAppITCase

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#636]
@yegor256 after last commit eac2909e8b020529c23552988a3f48ca326b9a21 we have the  broken test `com.netbout.rest.TkAppITCase` in the master branch

>Running com.netbout.rest.TkAppITCase
Error 
  java.net.MalformedURLException: unknown protocol: about
[ERROR] BkParallel-1 com.netbout.rest.TkAppFallback: java.io.IOException: net.sf.saxon.trans.XPathException: java.net.MalformedURLException: unknown protocol: about
        at org.takes.rs.RsPrettyXML.transform(RsPrettyXML.java:119)

Could you please fix it?

**Comment by dmzaytsev** [comment]
@yegor256 sorry to have to say this, but let's follow the rules
http://www.yegor256.com/2014/07/21/read-only-master-branch.html

**Comment by yegor256** [comment]
@dmzaytsev totally my fault, sorry, reverted/fixed in c8ef239 Created this issue: #637 Again, sorry about it, won't do it again

**Comment by dmzaytsev** [comment]
@yegor256 thanks!
