### ISSUE TITLE
RsPrettyXML from takes 0.17 is not used yet

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#637]
Let's use `RsPrettyXML` in `RsPage`, to make our XML output pretty formatted (see also #636)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev I set the milestone here to 3.0

**Comment by karato** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-1fe0687f`

**Comment by karato** [comment]
@erimerturk this is your task

**Comment by erimerturk** [comment]
@yegor256 i am planning to remove <code>doctype-system="about:legacy-compat"</code> from <b>xsl</b> files. Is it the proper solution ? what do you think ? thank you

**Comment by yegor256** [comment]
@erimerturk I put it there because of http://stackoverflow.com/a/3404922/187141 (see other answers too)

**Comment by erimerturk** [comment]
@yegor256 I couldn't find any solution, do you have any suggestion ? should we consider upgrade saxon. you can see  saxon upgrade suggestion from [here] (http://stackoverflow.com/a/19379446/652945)

**Comment by yegor256** [comment]
@erimerturk sure, if you need to upgrade saxon, go for it, why not? @dmzaytsev any objections?

**Comment by dmzaytsev** [comment]
@erimerturk @yegor256 no objections
let's try

**Comment by erimerturk** [comment]
@yegor256 @dmzaytsev we need to upgrade takes saxon version because exception thrown on takes side. <code>RsPrettyXML</code> line :117 . So i think first we should fix this problem on takes project and then use updated <code>RsPrettyXML</code> and refactor xsl files. What do you think ? I am planning to open an issue on takes project about saxon upgrade, should i ? thanks you.

**Comment by yegor256** [comment]
@erimerturk keep in mind that Takes is DOM-agnostic, which means that it doesn't know how exactly DOM is implemented, either with Saxon or Apache or anything else.

**Comment by erimerturk** [comment]
@yegor256 <code>RsPrettyXml</code> ignore  this line ``` <xsl:text disable-output-escaping='yes'>&lt;!DOCTYPE html&gt;</xsl:text> ``` .  how can i check is ```disable-output-escaping``` enabled. Because there is a guy says it is optional [feature] (http://stackoverflow.com/a/3404922/652945). Do you have any idea, why it is happing ? And another thing i failed to ugrade saxon version.

**Comment by yegor256** [comment]
@erimerturk maybe it's a bug in `RsPrettyXML`?

**Comment by erimerturk** [comment]
@yegor256 i will test it again, be sure and then if it is a bug in <code>RsPrettyXML</code>, open a bug on takes.

**Comment by erimerturk** [comment]
@yegor256 i am sure, it is <code>RsPrettyXML</code> bug

**Comment by erimerturk** [comment]
@yegor256 i opened a bug on [takes] (https://github.com/yegor256/takes/issues/339) . Could you please postpone this issue until RsPrettyXML fix ? thank you.

**Comment by yegor256** [comment]
@dmzaytsev looks like we should ask the PM for more time here

**Comment by dmzaytsev** [comment]
@karato give us more time please

**Comment by dmzaytsev** [comment]
@erimerturk you might inform the PM like this `@karato  we are waiting for yegor256/takes#339`
so he can make that this task depended from the bug-task

**Comment by karato** [comment]
> @karato give us more time please

@dmzaytsev OK, no problem, take your time

**Comment by dmzaytsev** [comment]
@karato we are waiting for yegor256/takes#339 here

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all

**Comment by dmzaytsev** [comment]
@karato this task is not postponed anymore

**Comment by karato** [comment]
> @karato this task is not postponed anymore

@dmzaytsev OK, I un-labeled it as "postponed" tag

**Comment by dmzaytsev** [comment]
@karato we are waiting https://github.com/yegor256/takes/issues/400

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by dmzaytsev** [comment]
@karato please set milestone 3.1

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will try to find someone else

**Comment by karato** [comment]
> @karato please set milestone 3.1

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by dmzaytsev** [comment]
@karato this is not postponed anymore

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by karato** [comment]
> @karato this is not postponed anymore
> 

@dmzaytsev got it, "postponed" tag removed from here

**Comment by karato** [comment]
> @karato assign me to this please

@dmzaytsev the task is yours, please proceed

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #886 please close if alright

**Comment by dmzaytsev** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by ypshenychka** [comment]
@yegor256 @karato Please consider ticket #588. It was removed from backlog but performer was not yet paid.

**Comment by yegor256** [comment]
@karato pls add extra 30 min to @bdragan (for his contribution in #588)

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks for the review

**Comment by karato** [comment]
> @karato pls add extra 30 min to @bdragan (for his contribution in #588)

@yegor256 I've paid 30 mins to @bdragan in transaction `73946664`

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `73947502`

**38 mins** was added to your account, many thanks for your contribution (payment 73947507)! The task took 70 hours and 38 mins.

there is a bonus for fast delivery (m=4238)

added +38 to your rating, now it is equal to [+1302](http://www.netbout.com/b/35166?open=rating)
