### ISSUE TITLE
DyInbox.java:134-140: DynamoDBLocal doesn't work with all...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#638]
Puzzle `1-b5151558` in `netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java:134-140` has to be resolved: DynamoDBLocal doesn't work with all attributes in global index. If we remove this check for a local version, most tests fail. I'm not sure how to fix that. I suspect, it's a bug in DynamoDBLocal, but I don't even know how to report it to them :( Anyway, let's try to investigate and either fix property or introduce a better workaround. Pay attention that this code works correctly in production.... The puzzle was created by Yegor Bugayenko on 14-Jun-2014.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by dmzaytsev** [comment]
@yegor256 I would like mark this issue as postponed if you don't mind
Please let me know if you  want to  escalate this ticket

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I added "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev OK, I will try to assign someone else

**Comment by yegor256** [comment]
@karato it's postponed

**Comment by karato** [comment]
> @karato it's postponed

@yegor256 got it, "postponed" tag here

**Comment by karato** [comment]
> @karato it's postponed

@yegor256 someone else will help in this task, no problem at all

**Comment by karato** [comment]
@ekondrashev do this task

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I will find someone else, no problem

**Comment by karato** [comment]
@dmzaytsev Closed, done, thanks all
