### ISSUE TITLE
TkStartTest.java:54-57: Test case for negative scenario...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#641]
Puzzle `610-76d661ee` in `netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java:54-57` has to be resolved: Test case for negative scenario of TkStart should be added, e.g. when a friend is not found, the error should be reported correctly and bout creation should be discarded.... The puzzle was created by Ivan Inozemtsev on 25-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@yegor256 I set milestone here to `3.0`, let me know if it is wrong

**Comment by karato** [comment]
@komaz do this task

**Comment by komaz** [comment]
@karato waiting for #628

**Comment by dmzaytsev** [comment]
@karato we are waiting #628 here

**Comment by karato** [comment]
> @karato waiting for #628 

@komaz ok, let's wait for #628

**Comment by karato** [comment]
@dmzaytsev #628 is closed, we were waiting for it.. maybe we can continue?

**Comment by dmzaytsev** [comment]
@karato yes, please

**Comment by dmzaytsev** [comment]
@komaz  #628 is closed, please continue

**Comment by karato** [comment]
@komaz 15 days already, in 48 hours I will re-assign... do not forget to remove the TODO puzzle from the source code... -30 added to your rating, current score is: [+368](http://www.netbout.com/b/35322?open=rating)

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, someone else will be assigned soon

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by karato** [comment]
@dmzaytsev Finished, thanks, closing..
