### ISSUE TITLE
link to a message

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#643]
It would be great if the text `time ago` above a message will be a link to the message. When we open the link, the message should be appear ~~on the top of the list~~ on top of the browser window
~~Also let's add a hint for the `time ago` as the string representation of the message date .~~

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@dmzaytsev thanks for the report, I topped your acc for 15 mins, payment ID `58145878`

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev milestone is set to 3.1

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I added "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev all right, we'll find someone else for this task

**Comment by yegor256** [comment]
@dmzaytsev we already have a "hint": https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/xsl/bout.xsl#L136-L138

**Comment by dmzaytsev** [comment]
@yegor256 you're right 
I did not see it, thanks!

**Comment by yegor256** [comment]
@dmzaytsev I don't think it's a good idea to show the message "on top of the list". I would rather show it at its normal place, but highlight it somehow and point the browser to it. just like Github is doing. what do you think?

**Comment by dmzaytsev** [comment]
@yegor256 I mean like Github
if you open this link https://github.com/yegor256/netbout/issues/643#issuecomment-105899975 in a new browser window this comment will appear on the top of the window(on the top of the message list)

**Comment by yegor256** [comment]
@dmzaytsev aha, so it's not "on top of the list" but "on top of the browser window" :)

**Comment by dmzaytsev** [comment]
@yegor256 exactly :)

**Comment by dmzaytsev** [comment]
@karato this task is not postponed any more
please dispatch it

**Comment by antonini** [comment]
@dmzaytsev and @karato I can do this.

**Comment by dmzaytsev** [comment]
@karato assign this task to @antonini please

**Comment by karato** [comment]
> @karato assign this task to @antonini please

@dmzaytsev yep, done. @antonini it is your task now

**Comment by antonini** [comment]
@yegor256 This issue is going to change xsl. I didn't found any test that use the xsl. Does the project have it?

**Comment by yegor256** [comment]
@dmzaytsev looks like it's a question to you, can you help?

**Comment by antonini** [comment]
@dmzaytsev PR #710 waiting for review.

**Comment by dmzaytsev** [comment]
@antonini  If didn't found any test that use the xsl just create it :)

**Comment by karato** [comment]
@dmzaytsev the code made here contains a puzzle `643-0c6bbfa8`/#729, which will be resolved soon

**Comment by antonini** [comment]
@dmzaytsev Can you test it and close the issue if it is ok?

**Comment by dmzaytsev** [comment]
@antonini thanks!

**Comment by antonini** [comment]
@karato Issue is closed, waiting for QA.

**Comment by antonini** [comment]
@karato Any update over here?

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks!

**Comment by antonini** [comment]
@karato Any update over here?

**Comment by karato** [comment]
@antonini 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 60420220

Much obliged! I have added **30 mins** to your account in payment "AP-810886140X354821V", 291 hours and 54 mins spent

+30 added to your rating, at the moment it is: [+256](http://www.netbout.com/b/35346?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `643-0c6bbfa8`/#729 solved

**Comment by 0pdd** [comment]
@dmzaytsev the only puzzle [#unknown]() is solved here.
