### ISSUE TITLE
return-after-login feature doesn't work

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#646]
Return after login feature was introduced in #609. I believe it doesn't work. Here is what I'm doing:

 1. I'm logged off
 2. I open `http://www.netbout.com/b/123` (where 123 is a real number of bout I participate in)
 3. I see login page
 4. I login using Github
 5. I see inbox page, while I expect to see `http://www.netbout.com/b/123`

Let's investigate and fix.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please assign @komaz to this ticket

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by komaz** [comment]
@yegor256 investigation results:

1. `Set-Cookie` header is being sent and cookie is stored (e.g. in my case cookie value is `http%3A%2F%2Fwww.netbout.com%2Fb%2F35322`), but `Path` attribute is not set explicitly, hence it defaults to `/b/` and cookie is not resent when returning to `/` after login. Updating the source and the test accordingly.
1. Changing `Path` to `/` manually and refreshing reveals other problem – `TkReturn` does not url-decode cookie value, so I'm being redirected to `http://www.netbout.com/http%3A%2F%2Fwww.netbout.com%2Fb%2F35322`, which obviously gives `Page not found`. Updating the source and the test accordingly.

**Comment by yegor256** [comment]
@komaz looks good, thanks. I'm thinking, maybe this `TkReturn` should be moved to the Takes framework. Other applications may use the same functionality.. It looks rather generic to me. @dmzaytsev @komaz what do you think?

**Comment by dmzaytsev** [comment]
@yegor256 @komaz I agree, this is generic case
somebody should create a ticket on the Takes for this and @komaz should be assigned to the ticket

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-4b198ebc

**Comment by karato** [comment]
> @karato please assign @komaz to this ticket

@dmzaytsev yep, done. @komaz it is your task now

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev thanks, I set it to "3.0"

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.14.16`

**Comment by dmzaytsev** [comment]
@komaz it works :)
thanks!

**Comment by yegor256** [comment]
@komaz works fine, thanks!

**Comment by yegor256** [comment]
@komaz this is for you: https://github.com/yegor256/takes/issues/317

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@komaz 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please indicate in any of your messages link to the created PR.

**Comment by komaz** [comment]
@ypshenychka my bad, the issue isfized in pull request #647

**Comment by ypshenychka** [comment]
@komaz Thank you.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@komaz I added 10 mins to @ypshenychka (for QA review) in transaction 58230300; thank you, added **1 hour** to your acc, payment num is `AP-3XP12873NT5169641`, 2 hours and 20 mins spent in total to complete; the bonus for fast delivery (m=140); +60 added to your rating, at the moment it is: [+300](http://www.netbout.com/b/35322?open=rating)
