### ISSUE TITLE
TkAppTest.java:99-102: We need to be able...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#648]
Puzzle `609-bc8eaf9f` in `netbout-web/src/test/java/com/netbout/rest/TkAppTest.java:99-102` has to be resolved: We need to be able to send anonymous requests from tests to verify correct TkApp behavior for anonymous users. But now all requests from tests are authorized because of PsFake(TkAppAuth.TESTING) in TkAppAuth.... The puzzle was created by Ivan Inozemtsev on 27-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@antonini it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.0

**Comment by antonini** [comment]
PR #650 is available and waiting for a review.

**Comment by karato** [comment]
@yegor256 Thanks all, closed

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@antonini just added 10 mins to @ypshenychka (for QA), payment ID is `58683022`. I just added **30 mins** to your account, many thanks for your contribution (AP-5U878803RY6445325).. 193 hours and 23 mins spent here. added +30 to your rating, now it is equal to [+106](http://www.netbout.com/b/35346?open=rating)
