### ISSUE TITLE
users can't delete comments

### ISSUE THREAD

**Issue by k0r** [yegor256/netbout#649]
users should be able to delete comments for various reasons.

**Comment by dmzaytsev** [comment]
@yegor256 I think users should be able to delete comments, but the deleted comment should be printed with `[deleted]` instead the text

**Comment by yegor256** [comment]
@k0r @dmzaytsev I'm not sure about this feature... if we allow comment deletion, we'll lose the entire idea of "traceability" of information. maybe we should make it possible to **edit** comments (including the ability to remove the entire content). when I edit my comment, the content of the comment is changed, but also a new comment is posted, that says that I edited the content of the comment. when I click it, it expands and shows me the "diff"

**Comment by k0r** [comment]
@yegor256 most commenting systems have deletion implemented.

**Comment by yegor256** [comment]
@k0r I'm not against editing/deleting, but against loosing the information entirely. we must have a way to see absolutely everything that happened in the bout since it was created. otherwise, this whole Netbout system is not any different from Skype or any Slack or any other chatting system.

**Comment by k0r** [comment]
@yegor256 the comments a user would delete wouldn't disrupt the integrity.

**Comment by yegor256** [comment]
@k0r well, if I create a bout to discuss something with you, we both post 10 comments each and then you delete all of your comments. I have a bout with only 10 my own comments. I simply don't have a history of our conversation any more. That will be frustrating for me :) And this is not what Netbout guarantees. Netbout guarantees persistency of information, with no time limits

**Comment by k0r** [comment]
@yegor256 not entirely accurate, netbout emails copies of comments.

**Comment by yegor256** [comment]
@k0r not every user has an email notification in his/her account. And emails are not persistent at all. Netbout is a replacer of emails, for important long-term communications. That's its business idea.

**Comment by k0r** [comment]
@yegor256 `netbout` has a specific userbase that probably wouldn't misuse the deletion feature.

**Comment by yegor256** [comment]
@k0r no no, it's a public project, for an absolutely un-filtered audience. anyone can use Netbout for any needs. it's a communication platform.

**Comment by k0r** [comment]
@yegor256 [this](https://github.com/yegor256/netbout/issues/649#issuecomment-106699552) makes sense.

**Comment by yegor256** [comment]
@k0r yes, we have to show that the comment was deleted, but we should give an ability to see the original content. maybe through an extra click, but there has to be a way to get there and see what was posted originally

**Comment by dmzaytsev** [comment]
@yegor256 @k0r I think the user should be able delete/edit own comments 
in the bout If there are no comments sent later by other users.
We won't lost the content in this case, and will give ability to fix some mistakes

**Comment by yegor256** [comment]
@dmzaytsev yes, that's a good idea!

**Comment by dmzaytsev** [comment]
@karato this is valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
> @karato this is valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@k0r since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev I set the milestone here to 3.1

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I added "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev I will assign somebody else to this issue

**Comment by dmzaytsev** [comment]
@karato this task is not postponed any more
please dispatch it
