### ISSUE TITLE
takes 0.19

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#652]
Let's use `RqWithAuth` from Takes 0.19 instead of our custom `RqWithTester`. Also, let's use `RsFailure` from Takes 0.19 instead of our custom version.

See https://github.com/yegor256/takes/releases/tag/0.19

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-c93680a1`

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by karato** [comment]
@zshamrock this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmzaytsev** [comment]
@zshamrock any progress here ?

**Comment by zshamrock** [comment]
hi, @dmzaytsev, sorry for the delay, for the others tasks as well, I was off, will take a look into this one this week

**Comment by dmzaytsev** [comment]
@zshamrock FYI Netbout just upgraded to Takes 0.20.2
also keep in mind 
http://www.teamed.io/policy.html#16
http://www.teamed.io/policy.html#10

**Comment by zshamrock** [comment]
@dmzaytsev more time?

**Comment by zshamrock** [comment]
@dmzaytsev thank you, will start to make my head around the working principles, and the working workflow in general. Thank you.

**Comment by dmzaytsev** [comment]
@zshamrock I just wanted to remind, don't forget inform the project manager about the delay

**Comment by zshamrock** [comment]
@dmzaytsev and who is the project manager? @yegor256 ? What it is the easiest way to find out who is the PM for the specific project?

**Comment by dmzaytsev** [comment]
@zshamrock `@karato` is the PM

> karato commented 11 days ago
> @zshamrock this task is for you, keep these principles in mind, and don't hesitate to ask any technical questions. 30 mins is the budget of the task. This is exactly how much will be paid when the problem is solved (no matter how much time you will actually spend). See this for more information

**Comment by zshamrock** [comment]
@karato more time?

**Comment by karato** [comment]
> @karato more time?

@zshamrock OK, take your time

**Comment by zshamrock** [comment]
@yegor256 could you, please, share the order of the imports we use. Is there a checkstyle.xml I can consult in case of the any qulice failures?

**Comment by zshamrock** [comment]
@karato created a pull request https://github.com/yegor256/netbout/pull/680

**Comment by yegor256** [comment]
@zshamrock imports must be ordered alphabetically, no static imports, no star imports

**Comment by zshamrock** [comment]
@karato should I do anything specific related to the pull request? Is there some process of doing the pull request?

**Comment by yegor256** [comment]
@zshamrock this article may help you: http://www.yegor256.com/2014/04/15/github-guidelines.html

**Comment by zshamrock** [comment]
@yegor256 thank you

**Comment by zshamrock** [comment]
@karato the PR was merged, anything else should do as part of the process to proceed with this task?

**Comment by yegor256** [comment]
@zshamrock thanks (it's my ticket, you should ask ticket reporter to close it)

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks for the review

**Comment by karato** [comment]
@zshamrock just added 10 mins to @ypshenychka (for QA), payment ID is `59118846`; Much obliged! I have added **30 mins** to your account in payment "AP-7WG56382EB491654R", 353 hours and 53 mins spent; +30 added to your rating, current score is: [-150](http://www.netbout.com/b/35316?open=rating)
