### ISSUE TITLE
since version (on javadoc) is larger than it should be.

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#656]
On the following classes the since are larger than the current version.

https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/FkRegistered.java#L43

https://github.com/yegor256/netbout/blob/master/netbout-web/src/test/java/com/netbout/email/EmAliasITCase.java#L41

https://github.com/yegor256/netbout/blob/master/netbout-web/src/test/java/com/netbout/rest/bout/TkDeleteITCase.java#L43

https://github.com/yegor256/netbout/blob/master/netbout-web/src/test/java/com/netbout/rest/bout/TkIndexTest.java#L45

https://github.com/yegor256/netbout/blob/master/netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java#L58

**Comment by dmzaytsev** [comment]
@antonini now version of the project is higher than the version in the mentioned files
close the ticket please

**Comment by antonini** [comment]
@dmzaytsev But the since version should be the version that it was released. It helps developers to know the minimum version of component.

**Comment by karato** [comment]
@yegor256 dispatch this issue please

**Comment by dmzaytsev** [comment]
@antonini a developers won't look for a version of any test classes.
It's a cosmetic issue
