### ISSUE TITLE
User should be findable by email or alias

### ISSUE THREAD

**Issue by erimerturk** [yegor256/netbout#658]
Current version of User is just searchable by <code>URN</code>. #547 and also #566 issues are need <b>User</b> and <b>User's inbox</b> information. And we have <code>alias</code> or <code>email</code> information to find find. So i should be able to find user by <code>alias</code> or <code>email</code>  information. @yegor256 @dmzaytsev @karato what do you think ?

**Comment by yegor256** [comment]
@erimerturk I see what you need, but this is against the idea of netbout. You're not supposed to know my email or my URN when you talk to me. All you know is my alias. If you will be able to find me by my email - it will be a serious violation of my privacy.

**Comment by erimerturk** [comment]
@yegor256 i don't agree to violation of privacy. Because system will be able to find user by alias, it is not opened the world, so i think it is not a violation.

**Comment by yegor256** [comment]
@erimerturk but our SPI is accessible via RESTful interface. Everything that is accessible inside the system is visible outside of it.

**Comment by dmzaytsev** [comment]
@erimerturk close the ticket please 
if you have no more questions on the subject
