### ISSUE TITLE
TkReturn from Takes 0.20

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#662]
Let's use `TkReturn` and `RsReturn` from Takes 0.20 recently released: https://github.com/yegor256/takes/releases/tag/0.20

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev I attached this issue to milestone `3.0`

**Comment by karato** [comment]
@mbarbieri can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-92a3a706

**Comment by mbarbieri** [comment]
@yegor256 sorry. Use them where? To do what?

**Comment by mbarbieri** [comment]
@yegor256 replace those in netbout with those from takes, right?

**Comment by yegor256** [comment]
@mbarbieri we have our own `TkReturn` and `RsReturn` classes in Netbout project now. Let's remove them and use similar classes from the latest Takes

**Comment by mbarbieri** [comment]
@yegor256 @dmzaytsev not able to proceed on this task until #669 is fixed

**Comment by dmzaytsev** [comment]
@mbarbieri if the changes relate only tests, then yes, you can ignore part of them.
Try to make a PR.

> @dmzaytsev actually I've already done the changes for #662 and fixed some tests that were failing because of that. What if I push the code @Ignore the failing tests (there are quite a lot) and let someone else fix them?

**Comment by mbarbieri** [comment]
@karato @dmzaytsev PR #674 is ready for review.

**Comment by karato** [comment]
> @karato @dmzaytsev PR #674 is ready for review.

@mbarbieri I will take a look, thanks

**Comment by karato** [comment]
@rultor @yegor256 please take a look, rultor closed it automatically

**Comment by yegor256** [comment]
@mbarbieri thanks!

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thank you, good quality is always good :)

**Comment by karato** [comment]
@mbarbieri 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 59053316

thanks, I just added **30 mins** to your account, payment `AP-3NK99795VN266820Y`, 125 hours and 14 mins spent

+30 to your rating, your total score is [+98](http://www.netbout.com/b/35357?open=rating)
