### ISSUE TITLE
native markdown links are parsed twice

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#664]
After the changes made in #581 we have a problem with links rendering. A raw link like `http://www.google.com` is converted into `<a href="http://www.google.com">http://www.google.com</a>`, which is perfect. But a like like this `[google](http://www.google.com)` is converted into `<a href="[http://www.google.com](http://www.google.com)">google.com</a>`, which is not good.

**Comment by komaz** [comment]
@yegor256 links like `[google](http://google.com)` work fine, there's a special test to make sure that links  starting with `](` are not highlighted. Problem appears when part in square brackets contains url, e.g. `[http://google.com](http://google.com)`. We need to make sure that links having preceding `[` are not highlighted too.

**Comment by dmzaytsev** [comment]
@karato this is valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato please assign this ticket to @komaz

**Comment by karato** [comment]
> @karato this is valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-88f4b9bf

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev the milestone here is 3.0

**Comment by karato** [comment]
@lautarobock this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@karato please assign this ticket to @komaz

**Comment by dmzaytsev** [comment]
@yegor256 please confirm the assignment @komaz to the task

**Comment by yegor256** [comment]
@karato assign @komaz here pls

**Comment by karato** [comment]
> @karato assign @komaz here pls

@yegor256 OK. @komaz the ticket is yours, please proceed

**Comment by longtimeago** [comment]
@komaz @dmzaytsev the bug is really annoying. Hope you will fix it soon :)

**Comment by dmzaytsev** [comment]
@longtimeago  sorry for the inconvenience
I hope the PR #665 will pass CR soon

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.14.18`

**Comment by komaz** [comment]
@dmzaytsev looks like my agenda is fixed

**Comment by longtimeago** [comment]
@komaz @dmzaytsev for me too, perfect! Thank you!

**Comment by dmzaytsev** [comment]
@komaz Indeed :)
thanks!

**Comment by komaz** [comment]
@yegor256 fixed in pull request #665

**Comment by yegor256** [comment]
@komaz thanks!

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@komaz 10 mins was added to the account of @ypshenychka (for QA review), in transaction 59024364. thanks, I just added **30 mins** to your account, payment `AP-6D71791623036224W`, 87 hours and 47 mins spent. added +30 to your rating, now it is equal to [+488](http://www.netbout.com/b/35322?open=rating)
