### ISSUE TITLE
Netbout agenda tab links broken

### ISSUE THREAD

**Issue by erimerturk** [yegor256/netbout#667]
href part broken version : 

```[ https://github.com/yegor256/netbout/issues/547 ](https://github.com/yegor256/netbout/issues/547)```

it should be :

``` https://github.com/yegor256/netbout/issues/547 ```

**Comment by dmzaytsev** [comment]
@erimerturk  it's a duplicate of #664

**Comment by erimerturk** [comment]
@dmzaytsev thank you
