### ISSUE TITLE
Links are not redirected properly

### ISSUE THREAD

**Issue by lautarobock** [yegor256/netbout#668]
If you go to netbout **agenda** page and make click on any github bug, you cannot get the page, instead of it, you get an URL like this: http://www.netbout.com/b/[https://github.com/yegor256/takes/issues/263](https://github.com/yegor256/takes/issues/263)

**Comment by dmzaytsev** [comment]
@lautarobock it's a duplicate of #664

**Comment by lautarobock** [comment]
@dmzaytsev yes, I've see it later,

**Comment by dmzaytsev** [comment]
@lautarobock please close this ticket
