### ISSUE TITLE
space after link is swallowed in Markdown

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#671]
When I post this message:

```
Hi [google](http://www.google.com) how are you?
```

I see this HTML:

```
Hi <a href="http://www.google.com">google</a>how are you?
```

The space after the link is lost. Looks like a bug to me.

**Comment by dmzaytsev** [comment]
@yegor256 we'll add a test for it 
https://github.com/yegor256/netbout/pull/665#issuecomment-109344045

**Comment by yegor256** [comment]
@dmzaytsev ok, closing as duplicate of #665

**Comment by dmzaytsev** [comment]
@yegor256 please reopen the ticket

**Comment by yegor256** [comment]
@dmzaytsev indeed, the bug is still there

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato  please set milestone to 3.0

**Comment by karato** [comment]
@yegor256 I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
> @karato  please set milestone to 3.0

@dmzaytsev milestone set to `3.0`, thanks

**Comment by dmzaytsev** [comment]
@karato please remove the duplicate label

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by yegor256** [comment]
@dmzaytsev I removed the duplicate label

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev right, I added "urgent" tag

**Comment by antonini** [comment]
@karato I can do this, can you assign this to me?

**Comment by dmzaytsev** [comment]
@karato assign this task to @antonini please

**Comment by karato** [comment]
> @karato assign this task to @antonini please

@dmzaytsev OK @antonini please start, the task is yours

**Comment by antonini** [comment]
@karato @yegor256 PR #699 is available for this issue. Please review it.

**Comment by antonini** [comment]
@karato This issue is not on my agenda.

**Comment by antonini** [comment]
@yegor256 It is available on http://snapshot.netbout.com/ so you can test it.

**Comment by yegor256** [comment]
@antonini works fine, thanks!

**Comment by antonini** [comment]
@karato Any progress over here?

**Comment by antonini** [comment]
@karato This issue is not going to be paid?

**Comment by antonini** [comment]
@karato Any update over here?

**Comment by yegor256** [comment]
@antonini give us a few hours pls

**Comment by antonini** [comment]
@yegor256 2 days... And no update.. :(

**Comment by antonini** [comment]
@karato Is there any update over here?

**Comment by antonini** [comment]
@karato ping.

**Comment by antonini** [comment]
@karato ping.

**Comment by antonini** [comment]
@karato ping.

**Comment by dmzaytsev** [comment]
@antonini I think it would be better ask @yegor256 in Netbout about it

**Comment by antonini** [comment]
@karato ping.

**Comment by antonini** [comment]
@karato @yegor256 Ping.

**Comment by yegor256** [comment]
@karato pls add extra 30 mins to @antonini

**Comment by karato** [comment]
> @karato pls add extra 30 mins to @antonini 

@yegor256 I've paid 30 mins to @antonini in transaction `AP-3ML83078BE330230T`
