### ISSUE TITLE
Broken links on Agenda page

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#675]
The links on the agenda page (ones on the left, leading to the tickets) are broken.

![image](https://cloud.githubusercontent.com/assets/1917892/8023074/8fdca53c-0d2c-11e5-97b2-36fabb62a74b.png)

For example, the very last link leads to the following URL:

![image](https://cloud.githubusercontent.com/assets/1917892/8023086/26e5c238-0d2d-11e5-8fff-8678a6c5f7c1.png)

Which leads to the following error page:

![image](https://cloud.githubusercontent.com/assets/1917892/8023094/52783eda-0d2d-11e5-9d7c-e1d9a4a9cedc.png)

It was working before but now it isn't, we should fix it.

**Comment by dmzaytsev** [comment]
@carlosmiranda thanks for reporting
but  it's a duplicate of #664
The issue will be resolved soon

**Comment by carlosmiranda** [comment]
@dmzaytsev Right, thanks
