### ISSUE TITLE
Empty message after adding some message

### ISSUE THREAD

**Issue by mbarbieri** [yegor256/netbout#677]
After inserting some message in a new bout I start seeing an empty one:

![selection_035](https://cloud.githubusercontent.com/assets/110143/8045512/2382bd1e-0e34-11e5-96f3-5583bee99262.png)

Obviously it should not be there...
To reproduce:
- create a new bout
- type a first message
- then a second one
  after 2 or 3 (I guess is based on the screen resolution, but not sure) an empty one appears at the bottom.
  It seems to appear only when no one else is invited. but again not sure.

**Comment by dmzaytsev** [comment]
@mbarbieri please elaborate a bit 
what's wrong? what you expected to see?
how a performer should reproduce this bug?
It's occurs with any bout or not ?

**Comment by mbarbieri** [comment]
@dmzaytsev updated

**Comment by dmzaytsev** [comment]
@karato valid bag

**Comment by dmzaytsev** [comment]
please set milestone to 3.1

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by karato** [comment]
@yegor256 please pay attention to this issue

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by yegor256** [comment]
@karato  it's a bug

**Comment by karato** [comment]
> @karato  it's a bug

@yegor256 I just added bug tag here

**Comment by karato** [comment]
@mbarbieri I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
> @karato please set milestone to 3.1
> 

@dmzaytsev thanks, I set it to "3.1"

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev got it, "postponed" tag here

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev no problem, I will try to find somebody else

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev OK, I labeled it as "postponed" tag

**Comment by yegor256** [comment]
@mbarbieri just curious, what browsers this problems is reproducible in?

**Comment by mbarbieri** [comment]
@yegor256 with chrome (desktop and mobile). Didn't tried with others

**Comment by karato** [comment]
> @karato please set milestone to 3.1
> 

@dmzaytsev I set the milestone here to 3.1

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev sure, thanks, I added "postponed" tag to it

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev I will assign somebody else to this issue

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev sure, thanks, I added "postponed" tag to it

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev someone else will help in this task, no problem at all

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev sure, thanks, I added "postponed" tag to it

**Comment by karato** [comment]
@mbarbieri thanks for the ticket, your account was topped for 15 mins, payment AP-4UK733034S953262X

**Comment by karato** [comment]
> @karato please set milestone to 3.1
> 

@dmzaytsev milestone set to `3.1`, thanks

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already here

**Comment by yegor256** [comment]
@mbarbieri I also see it in Chrome, but only occasionally

**Comment by mbarbieri** [comment]
@yegor256 not sure, but I think it depends on the screen resolution... on my mobile it appears after two comments, on my laptop after 3, if I zoom out it appears after 5/6. Basically when the last message is "near the end of the screen"...

**Comment by karato** [comment]
> @karato please set milestone to 3.1
> 

@dmzaytsev milestone set to `3.1`, thanks

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already at this ticket

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev all right, we'll find someone else for this task

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already in this issue

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev I will assign somebody else to this issue

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already in this issue

**Comment by karato** [comment]
> @karato please set milestone to 3.1
> 

@dmzaytsev sure, milestone set to 3.1

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already here

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev OK, I will try to assign someone else

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already here

**Comment by karato** [comment]
> @karato please set milestone to 3.1
> 

@dmzaytsev thanks, I set it to "3.1"

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already at this ticket

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev right, I will find someone else, no problem

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev "postponed" label already at this ticket
