### ISSUE TITLE
snapshot.netbout.com

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#681]
Let's create a staging platform and deploy there on every "deploy" cycle.

**Comment by yegor256** [comment]
@dmzaytsev I'll do it

**Comment by dmzaytsev** [comment]
@yegor256 thanks

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@dmzaytsev I think it's ready, check this out: http://snapshot.netbout.com

**Comment by yegor256** [comment]
@dmzaytsev there is no HTTP Basic auth protection at the moment, so anyone can get access to it, which is not good, I think. And only Github works as an OAuth provider.

**Comment by dmzaytsev** [comment]
@yegor256 it works,
thank you!

**Comment by dmzaytsev** [comment]
is there single http-basic password? How we will share it ?

**Comment by yegor256** [comment]
@dmzaytsev there is no password at all now. but we have to create something, to protect this resource from public eyes. I think you don't need my help in this, right? I can close this ticket?

**Comment by dmzaytsev** [comment]
@yegor256 sure, you can, thank you!

**Comment by dmzaytsev** [comment]
@yegor256 can we use a command-line param for the HttpBasic auth?

**Comment by dmzaytsev** [comment]
@yegor256 I meant to set username/passwd via a command-line param

**Comment by dmzaytsev** [comment]
@yegor256 can we share user/password on the team page for the members of the netbout team.
what do you think?

**Comment by yegor256** [comment]
@dmzaytsev yeah, I think we can. there is no secret there, we just need to be sure that a stranger won't take this site for a real netbout site, that's all.

**Comment by dmzaytsev** [comment]
@yegor256 thanks!
