### ISSUE TITLE
EmMessages.java:96-97: Send email if friend subscribed...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#682]
Puzzle `547-299902f6` in `netbout-web/src/main/java/com/netbout/email/EmMessages.java:96-97` has to be resolved: Send email if friend subscribed to bout. Friend should be filtered before send email by subscription... The puzzle was created by erim erturk on 9-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by karato** [comment]
@ekondrashev this is your task

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.0`

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by ekondrashev** [comment]
@karato Could you please close this ticket, solution is provided at #689

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@ekondrashev please register on http://snapshot.netbout.com/
create a bout and invite me (`@dmzaytsev`)
I would check the subscribtion functionality

**Comment by ekondrashev** [comment]
@dmzaytsev done, here is the bout http://snapshot.netbout.com/b/3

**Comment by dmzaytsev** [comment]
send me a message via this bout

**Comment by karato** [comment]
@rultor I will close this task myself when it goes out of our backlog

**Comment by karato** [comment]
@dmzaytsev there is a puzzle in this code `682-753e25af`, we'll resolve it later

**Comment by karato** [comment]
@dmzaytsev Closing, thanks all

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@ekondrashev 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by ypshenychka** [comment]
@dmzaytsev 
>send me a message via this bout

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please  indicate a person you're referring to in the beginning of your message.

**Comment by ekondrashev** [comment]
@karato this one is fixed with #689

**Comment by dmzaytsev** [comment]
@ypshenychka I fixed the comment

**Comment by ypshenychka** [comment]
@ekondrashev Great! Thank you.

**Comment by ypshenychka** [comment]
@dmzaytsev much better :) Thanks!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by karato** [comment]
@ekondrashev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 59119236... I added **38 mins** to your account, many thanks for working with the project! The completion time here was 59119241.... the bonus for fast delivery (m=2953)... +38 added to your rating, current score is: [+294](http://www.netbout.com/b/35260?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `682-2583dc75`/#1003 originated from here solved

**Comment by 0pdd** [comment]
@karato all 2 puzzles are solved here: [#unknown](), [#unknown]().
