### ISSUE TITLE
login with google is broken

### ISSUE THREAD

**Issue by erimerturk** [yegor256/netbout#684]
On netbout [main page] (www.netbout.com) just click google+ and <code> 404 </code> page. You can see details.

```
java.lang.AssertionError: HTTP response status is not equal to 200:
404 Not Found [https://accounts.google.com/o%2Foauth2%2Ftoken]
Transfer-Encoding: chunked
Date: Wed, 10 Jun 2015 18:02:16 GMT
X-XSS-Protection: 1; mode=block
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Alternate-Protocol: 443:quic,p=1
Content-Type: text/html; charset=utf-8
Server: GSE
X-Content-Type-Options: nosniff
Pragma: no-cache
Cache-Control: no-cache, no-store, max-age=0, must-revalidate

404. That\u2019s an error.

The requested URL was not found on this server. That\u2019s all we know.


Expected: HTTP response with status 200
     but: was <404 Not Found [https://accounts.google.com/o%2Foauth2%2Ftoken]
Transfer-Encoding: chunked
Date: Wed, 10 Jun 2015 18:02:16 GMT
X-XSS-Protection: 1; mode=block
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Alternate-Protocol: 443:quic,p=1
Content-Type: text/html; charset=utf-8
Server: GSE
X-Content-Type-Options: nosniff
Pragma: no-cache
Cache-Control: no-cache, no-store, max-age=0, must-revalidate

404. That\u2019s an error.

The requested URL was not found on this server. That\u2019s all we know.

>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:117)
	at org.takes.facets.auth.social.PsGoogle.token(PsGoogle.java:164)
	at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:108)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:84)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.forward.TkForward.act(TkForward.java:66)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmzaytsev** [comment]
@erimerturk thanks for reporting

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
please set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato it's a valid bug
> 

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@erimerturk since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@erimerturk many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-9AJ449212P7962343`

**Comment by yegor256** [comment]
@dmzaytsev it's a bug in Takes: https://github.com/yegor256/takes/issues/341

**Comment by dmzaytsev** [comment]
@yegor256 thanks!

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev the milestone here is 3.0

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev OK, I labeled it as "urgent" tag

**Comment by karato** [comment]
@lautarobock this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@karato we are wating yegor256/takes#341 here

**Comment by lautarobock** [comment]
@dmzaytsev @karato still waiting?

**Comment by dmzaytsev** [comment]
@lautarobock yep, that’s right
if you click on the link above you can see that's the issue not resolved yet

**Comment by dmzaytsev** [comment]
@karato this task not urgent any more

**Comment by karato** [comment]
> @karato this task not urgent any more

@dmzaytsev right, I removed "urgent" tag

**Comment by karato** [comment]
@lautarobock 15 days already, in 48 hours I will re-assign

-30 to your rating, your total score is [+0](http://www.netbout.com/b/35344?open=rating)

**Comment by dmzaytsev** [comment]
@karato  I asked you put this task on hold two weeks ago...

> dmzaytsev commented 15 days ago
> @karato we are wating yegor256/takes#341 here

please put it on hold

@yegor256 could you please restore the rating ?

**Comment by yegor256** [comment]
@karato we need more time here

**Comment by karato** [comment]
> @karato we need more time here

@yegor256 right, take your time and thanks for informing

**Comment by karato** [comment]
@sretenperic it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@sretenperic Takes `0.23.3` just released, google auth bug resolved
please upgrade Netbout to this version

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by karato** [comment]
> @karato assign me to this please

@dmzaytsev done, the task is yours, whoever worked before, stop now

**Comment by dmzaytsev** [comment]
@erimerturk fixed in #781 close the task please

**Comment by erimerturk** [comment]
@dmzaytsev thank you

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 64276511

Much obliged! I have added **1 hour** to your account in payment "64276522", 4 hours and 24 mins spent

there is a bonus for fast delivery (m=264)

+60 added to your rating, at the moment it is: [+1876](http://www.netbout.com/b/35166?open=rating)
