### ISSUE TITLE
 the snapshot instance protection

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#685]
Let's protect the snapshot instance by HttpBasicAuth.

1. We should create a new `Pass` implementation e.g. `PsTwice` which use two a `Pass` instances. Inside `PsTwice.enter()` we have to check the first Pass and if it passed succesfully then continue with second `Pass` and return `Identity` from it.

2. Let's add a new command-line params to the application.
   `basic-user`, `basic-pwd` with basic auth credentials. The values we will use in `PsBasic`.`Entry` on the next step.

3.  inside `TkAppAuth` we have to use `PsTwice(PsBasic, PsChain)`  instead  `PsChain`

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

we are waiting for yegor256/takes#221

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `59053384`

**Comment by karato** [comment]
@ekondrashev this is your task

**Comment by ekondrashev** [comment]
@dmzaytsev Could you please elaborate on the necessity to create `PsTwice`? As I understand it can be replaced with `PsChain` easily, no?

**Comment by ekondrashev** [comment]
@karato thx!

**Comment by dmzaytsev** [comment]
@ekondrashev The idea to use BasicAuth is to enable access for developers only. We have to save current authentification capabilites.
PsChain returns the identity from first successful authentification step.
We can't add BasicAuth into it.

Thus first step is check BasicAuth, we will use one shared credentials for this step.
second step is check access using PsChain

**Comment by ekondrashev** [comment]
@dmzaytsev Got it, then I'd suggest to introduce PsAll concept at takes level. It will return identity of a first such step if all others were successful.

We even can have Opt implementation that will behave like Iterator, making it possible iterate over all the identities and make use of it at PsAll.

**Comment by dmzaytsev** [comment]
@ekondrashev do you propose to use it like this ?
```
PsAll(
  PsChain(....), 
  PsBasic()
)
```

**Comment by ekondrashev** [comment]
@dmzaytsev yes

But I'm not sure this is what you wanted originally, it will check the chain first, do you think it is ok?

Alternatively we can have it like
```java
PsAll(
  PsBasic(),
  PsChain(....), 
)
```
end access the identity with such flow:
```java
Opt<Identity> opt= ..
if(opt.has())
    opt.next();
if(opt.has)
identity = opt.next()
```
In other `PsAll` implies we can pass the index of identity that should be return, just thinking. I'd even wrap it with Pass impl that will raise exception if PsAll fails.

**Comment by dmzaytsev** [comment]
you wrote 
> It will return identity of a first such step if all others were successful.

in this case if we check PsBasic first then we will get the BasicAuth identity, but we need to have one of the real urns from PsChain.

or I misunderstood you?

**Comment by ekondrashev** [comment]
@dmzaytsev you got it correctly, I was proposing alternatives and possible ways to access all of the identities, not just first/last

**Comment by dmzaytsev** [comment]
@ekondrashev do you mean [Opt](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/misc/Opt.java) from Takes?

It hasn't method `get()` ...

How we can get the identity from PsChain ?

```
Opt<Identity> opt= PsAll(
  PsBasic(),
  PsChain(....), 
)

**Comment by ekondrashev** [comment]
@dmzaytsev well, it does has `get` method
```java
public interface Opt<T> {
    /**
     * Returns the contained instance.
     * @return Instance
     */
    T get();

    /**
     * Returns true if contains instance.
     * @return True if present
     */
    boolean has();
...
}
```

**Comment by dmzaytsev** [comment]
@ekondrashev the Opt instance contains only one value...well we can return Iterator, 
but we need to do something to extract main identity.

For this task we definitely need only one identity that's returns by PsChain
so I think the PsTwice idea in this particular case is more preferable. 

anyway thanks for suggestion, feel free submit the PsAll idea  to Takes project

**Comment by ekondrashev** [comment]
@dmzaytsev Do you think PsTwice is relevant only for netbout? Ot it is also good to have it at takes?

**Comment by dmzaytsev** [comment]
@ekondrashev I think it too specific case for be included into Takes framework

**Comment by ekondrashev** [comment]
@dmzaytsev Could you please also comment on cmdline args to be added. Currently all the arguments are passed to takes application. Does this consider creating own Options class in scope of this task? Or I can use `Manifests.read` for this?

**Comment by ekondrashev** [comment]
@dmzaytsev could you also help me to understand which version of takes should I change the pom dependency to in order to be able to use new `PsBasic` class. Can I use the last one?

**Comment by dmzaytsev** [comment]
@ekondrashev yes, I agree, let's read the credentials from Manifest

> @dmzaytsev Could you please also comment on cmdline args to be added. Currently all the arguments are passed to takes application. Does this consider creating own Options class in scope of this task? Or I can use Manifests.read for this?

**Comment by ekondrashev** [comment]
@dmzaytsev the latest version if 0.20.2 and it misses the new `PsBasic` I believe we are blocked here as of now.

**Comment by dmzaytsev** [comment]
@ekondrashev I think it would better to use the latest version of the Takes

> @dmzaytsev could you also help me to understand which version of takes should I change the pom dependency to in order to be able to use new PsBasic class. Can I use the last one?

**Comment by dmzaytsev** [comment]
@ekondrashev 0.20.3 released a few hours ago
it should contains `PsBasic`

**Comment by ekondrashev** [comment]
@dmzaytsev Cool! let me check.

**Comment by ekondrashev** [comment]
@karato need more time here, initial discussion took some time, the PR is on review stage.

**Comment by karato** [comment]
> @karato need more time here, initial discussion took some time, the PR is on review stage.

@ekondrashev sure, thanks for telling me, take your time

**Comment by dmzaytsev** [comment]
@ekondrashev thanks!

**Comment by ekondrashev** [comment]
@karato the issue should be fixed with #711 PR.

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@dmzaytsev 
>you wrote
It will return identity of a first such step if all others were successful.
in this case if we check PsBasic first then we will get the BasicAuth identity, but we need to have one of the real urns from PsChain.
or I misunderstood you?

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your message by indicating a person you're referring to in the beginning.

**Comment by dmzaytsev** [comment]
@ypshenychka my bad :( fixed!

**Comment by ypshenychka** [comment]
@dmzaytsev Please fix this [message](https://github.com/yegor256/netbout/issues/685#issuecomment-112751640).

**Comment by dmzaytsev** [comment]
@ypshenychka sorry, done

**Comment by ypshenychka** [comment]
@dmzaytsev Thank you!

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
@dmzaytsev once `685-6534dff2`/#713 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@ekondrashev just added 10 mins to @ypshenychka (for QA), payment ID is `59801985`; **30 mins** was added to your account, many thanks for your contribution (payment 59801997)! The task took 195 hours and 31 mins.; +30 to your rating, your total score is [+354](http://www.netbout.com/b/35260?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `685-6534dff2`/#713 solved
