### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by zshamrock** [yegor256/netbout#687]
And then we also can get rid of `com.google.common.base.Function` and others.

**Comment by dmzaytsev** [comment]
@zshamrock please check this article http://www.yegor256.com/2014/04/13/bugs-are-welcome.html#what-is-a-bug?

**Comment by zshamrock** [comment]
@dmzaytsev so there is no a way to propose improvement, which is not a bug according the definition?

**Comment by yegor256** [comment]
@zshamrock an improvement must explain the problem first. For example, "this car is very slow, would be great to tune it so that it can fly". First you say that the car is slow, that is the problem statement. Then, you suggest an improvement.

**Comment by zshamrock** [comment]
@yegor256 Make sense. So, you can close this one, and then I will come with the compelling reason (if so), why it is good to upgrade to Java 8 :)

**Comment by yegor256** [comment]
@zshamrock close it yourself, please, it's your ticket
