### ISSUE TITLE
Improve MkBase of managing aliases

### ISSUE THREAD

**Issue by zshamrock** [yegor256/netbout#688]
There are multiple places in the test (maybe in the main code as well) doing the following:

        final User user = base.user(new URN(urn));
        user.aliases().add(alias);

or 
in one line 

    base.user(URN.create(urn)).aliases().add(alias);

It violates http://en.wikipedia.org/wiki/Law_of_Demeter, and also a smell of unused variable (`user`) and hidden setup for the test.
I suggest making MkBase responsible for managing the user it creates and the aliases added to the user. Maybe, MkBase could have a ctor with alias as parameter.

**Comment by dmzaytsev** [comment]
@zshamrock `MkBase` just the mock object for the testing purpose. I'm not sure need any changes here.
@yegor256 what do you think?

**Comment by karato** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@dmzaytsev I agree, the design we have now is good enough. @zshamrock thanks for suggestion anyway

**Comment by dmzaytsev** [comment]
@zshamrock please close the ticket
