### ISSUE TITLE
Incorrect "confirm" link

### ISSUE THREAD

**Issue by YamStranger** [yegor256/netbout#690]
I found such message "UserName, you've been invited to "jcabi" team in Github, don't forget to confirm." word "confirm" is url to https://github.com/orgs/teamed/invitation, but must be url to invitation.

**Comment by dmzaytsev** [comment]
@YamStranger It's out of the scope of the project
please report such issues inside Netbout
I think @yegor256  can help you

**Comment by YamStranger** [comment]
may be, may be )
I will close it, if you want
