### ISSUE TITLE
EmCatch.java:188-194: Create bout message using using...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#692]
Puzzle `600-f8c0ce2e` in `netbout-web/src/main/java/com/netbout/email/EmCatch.java:188-194` has to be resolved: Create bout message using using msg values. Msg recipient value will hold boutId info. Msg from value will hold bout message creator info. Msg content will hold bout message content info. This method should get bout info from email and save it as bout message. And then change method signature like void run(Bout bout, String email, String body);... The puzzle was created by erim erturk on 9-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.0 since there is nothing set yet

**Comment by karato** [comment]
@erimerturk do this task

**Comment by erimerturk** [comment]
@dmzaytsev before this issue maybe we should make this issue.
<b>for security reason and avoid spam we have to generate an unique string for the message id, when we sending email we have to write to a table message_id, bout_id, author_alias </b>
And you can see detail on here #600. what do you think ? After insert operation we should implement read and create bout part, i mean this issue . Another thing we should decide message_id pattern. Should i create an issue for this what is your opinion ?

**Comment by dmzaytsev** [comment]
@erimerturk this outdated requirements...
I simplified the task, see  https://github.com/yegor256/netbout/issues/600#issuecomment-106876950

* we have to setup a redirection all incoming messages for @reply.netbout.com into bouts@reply.netbout.com
* we have to add header` Reply-To: <boat_id>@reply.netbout.com>` into an outgoing email. e.g `Reply-To: 35351@reply.netbout.com>`
* ~~netbout should monitor mailbox `bouts@reply.netbout.com`~~
* nebout recieve email with the header `To:<boat_id>@reply.netbout.com` looking for the alias by email and boat_id
* post the message as the author

so you have to
* add header `Reply-To` into an outgoing email 
* create an implementation for `EmCatch.Action` which should look for the alias by email and boat_id and post the message into the bout as the author

**Comment by erimerturk** [comment]
@dmzaytsev thank you! We have a problem and i have already created an issue #658 for this . To create new message we need user alias info. We have user email so <code> User should be findable by email </code> what do you think ?

**Comment by dmzaytsev** [comment]
@erimerturk well.. we can't find the user by his email but we can to encrypt his urn and boat_id and use it in the ReplyTo header. we might  create a string like `<urn>|<email>` encrypt it by some encrypt function (like  jasypt or any another) and set the ReplyTo header to string like this `74y478447y84748ydegxyg7dy@reply.netbout.com`
When we will receive a message we just decrypt the string split it into the urn and the bout id and use them.

@yegor256 what do you think about the idea?

btw benefits of the idea the unique ReplyTo header for each user

**Comment by yegor256** [comment]
@dmzaytsev yes, I like it!

**Comment by dmzaytsev** [comment]
@erimerturk go ahead :)

**Comment by erimerturk** [comment]
@dmzaytsev @yegor256 one of our main problem not resolved yet. you know we are sending email on <code>EmMessages.email</code>, on that context we have <code>friend</code> object and it doesn't hold <code>URN</code> . So i need to create new method on friend <code>Friend.urn()</code>. What do you think ?

**Comment by dmzaytsev** [comment]
@erimerturk why we need to use `EmMessages.email()` directly?
Look at  `com.netbout.rest.bout.TkPost` it recreates `Bout` uses the bout number and user's urn and then posts the messages into the bout. Isn't it?

**Comment by erimerturk** [comment]
@dmzaytsev we need to add ReplyTo header right ? i thought that it should be added on <code>EmMessages.email()</code> . We are sending bout email on that function, am i right ?

**Comment by antonini** [comment]
@dmzaytsev, About the thing you said to encrypt `<urn>|<email>`, take care to don't use same encrypt method that is used on other parts of the system. This must be a method that will just be used to mail purpose.

**Comment by dmzaytsev** [comment]
@erimerturk sorry, I was sure that responded you yesterday...
yes, you're right. we need to know friend's URN when we compose email.
Let's add a new  method  urn() to Friend.

**Comment by erimerturk** [comment]
@karato Could you, please, assign someone else or postpone this task until 25th of June, I will be out until this for personal reasons?

**Comment by erimerturk** [comment]
@karato @yegor256 please assign someone else or postpone it, thank you

**Comment by yegor256** [comment]
@karato assign someone else here

**Comment by karato** [comment]
> @karato assign someone else here

@yegor256 deducted 30 from your rating :(

**Comment by karato** [comment]
> @karato assign someone else here

@yegor256 someone else will help in this task, no problem at all

**Comment by karato** [comment]
@bilalyasar this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@bilalyasar  is there any progress on this issue?

**Comment by dmzaytsev** [comment]
@bilalyasar ping

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev sure, thanks, I added "postponed" label to it

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I removed the "urgent" tags

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by dmzaytsev** [comment]
@karato this is not postponed any more

**Comment by karato** [comment]
> @karato this is not postponed any more

@dmzaytsev OK, I un-labeled it as "postponed" tag

**Comment by dmzaytsev** [comment]
@karato assign this to me please

**Comment by dmzaytsev** [comment]
@karato please see PR #768

**Comment by karato** [comment]
> @karato assign this to me please

@dmzaytsev yep, it is yours, go ahead

**Comment by karato** [comment]
> @karato please see PR #768

@dmzaytsev thanks, I'll take a look

**Comment by dmzaytsev** [comment]
@karato fixed in #768 please close the task

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
> @karato fixed in #768 please close the task

@dmzaytsev I will close it, but only when the puzzle is removed from the code and project stats are updated (may take up to a day) after successful deployment

**Comment by karato** [comment]
@dmzaytsev there is a puzzle in this code `692-1caba32d`/#770, we'll resolve it later

**Comment by dmzaytsev** [comment]
@yegor256 @karato the puzzle removed and the project deployed 3 days ago. Please check

> @dmzaytsev I will close it, but only when the puzzle is removed from the code and project stats are updated (may take up to a day) after successful deployment

**Comment by karato** [comment]
@dmzaytsev Finished, thanks, closing..

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks a lot

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 63827734... Thanks for your contribution, **38 mins** was added to your account, payment ID is `63827745`, 51 hours and 58 mins spent total... m=3118, that's why a bonus here for fast delivery... +38 added to your rating, at the moment it is: [+1641](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `692-1caba32d`/#770 originated from here solved
