### ISSUE TITLE
RtBout.java:155-157: Implement getting subscription by alias....

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#693]
Puzzle `682-753e25af` in `netbout-client/src/main/java/com/netbout/client/RtBout.java:155-157` has to be resolved: Implement getting subscription by alias. Should return subscription status for current boat, passing friend alias value using REST call.... The puzzle was created by Eugene Kondrashev on 11-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.0` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@zshamrock this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by zshamrock** [comment]
Thank you, @karato

**Comment by zshamrock** [comment]
@karato could you, please, explain what does it mean in the ticket description "682-753e25af in netbout-client/src/main/java/com/netbout/client/RtBout.java:155-157", I don't see any comments or todo in RtBout.java around these lines in master.

**Comment by dmzaytsev** [comment]
@zshamrock I think you forget  merge with master...
I see the puzzle here
https://github.com/yegor256/netbout/blob/master/netbout-client/src/main/java/com/netbout/client/RtBout.java#L155

**Comment by zshamrock** [comment]
@dmzaytsev Yes, indeed, I run `merge upstream/master`, but apparently it does not get the latest changes, `pull upstream master` does.

**Comment by zshamrock** [comment]
@karato have started working on this one.

**Comment by karato** [comment]
@bilalyasar it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by bilalyasar** [comment]
@karato i need more time for this task please.

**Comment by karato** [comment]
> @karato i need more time for this task please.

@bilalyasar no problem, thanks for letting me know

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by dmzaytsev** [comment]
@karato set milestone to 3.1 please

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
> @karato set milestone to 3.1 please

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by karato** [comment]
@dmzaytsev I am closing it, thanks all
