### ISSUE TITLE
Netbout down: page not found

### ISSUE THREAD

**Issue by pinaf** [yegor256/netbout#694]
When accessing netbout.com, browser address changes to 
>
http://www.netbout.com/,PsCookie=23CA3E.......

(huge sequence)
and page says
>
page not found

**Comment by dmzaytsev** [comment]
@pinaf I can't reproduce it...
Please try again, maybe it would better use a new browser tab

**Comment by pinaf** [comment]
@dmzaytsev hmm it worked on firefox. let me close chromium - it looks like an issue with the github session

**Comment by pinaf** [comment]
@dmzaytsev yep, sorry about that!

**Comment by dmzaytsev** [comment]
@pinaf np :)
