### ISSUE TITLE
the subscription status frozen

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#695]
I use two browsers and two github accounts for log into http://snapshot.netbout.com
1. account1 creates  a new bout and invites account_2
2. account_2 turns off the subscription (the bell icon)
3. account_1 sends a message to account2, account_2 doesn't receive any email notifications. and this is right
4. account_2 turns on the subscription (the bell icon)
5. account_1 sends a message to account2, account_2 still doesn't receive any email notifications.

It's looks as a bug for me.

**Comment by dmzaytsev** [comment]
@karato this is valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.0

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@mbarbieri this is your task

**Comment by karato** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `59118199`

**Comment by karato** [comment]
> @karato please set milestone to 3.0

@dmzaytsev thanks, I set it to "3.0"

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev OK, I labeled it as "urgent" tag

**Comment by mbarbieri** [comment]
@dmzaytsev are you sure subscription is implemented and deployed there? I wrote a test to verify it and everything seems to be working fine.
I tried in snapshot but I keep getting mails for every message, no matter if I subscribe or not...

**Comment by dmzaytsev** [comment]
@mbarbieri yes, the master branch currently deployed on http://snapshot.netbout.com
I made the test today. Try to disable the subscription at once after you joined to the bout and you will get same result.
But I got same result as you when I disabled the subscription  after any message received.

**Comment by mbarbieri** [comment]
@dmzaytsev can you please check [here](https://github.com/mbarbieri/netbout/blob/695/netbout-web/src/test/java/com/netbout/email/EmMessagesITCase.java#L85) if the steps are right to reproduce the error?

**Comment by dmzaytsev** [comment]
@mbarbieri the steps look correct but the matchers is wrong..
I think it would better to change the messages
"send it" -> "subscribe on" 
"don't send it" -> "subscribe off" 
and the matchers should check that messages contains "subscribe on"  and not contains "subscribe off"

**Comment by mbarbieri** [comment]
@dmzaytsev this is what I'm doing. Verify that only 2 mails are sent and all of them have the text  "send it"...  And the test is passing.

**Comment by dmzaytsev** [comment]
@mbarbieri did you reproduce the error in the browser?
maybe the subscription flag doesn't set correct?

**Comment by dmzaytsev** [comment]
@karato this task not urgent any more

**Comment by karato** [comment]
> @karato this task not urgent any more

@dmzaytsev OK, I un-labeled it as "urgent" tag

**Comment by mbarbieri** [comment]
@karato can I have more time to work on this? I'm still not able to reproduce it

**Comment by karato** [comment]
> @karato can I have more time to work on this? I'm still not able to reproduce it

@mbarbieri OK, no problem, take your time

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all

**Comment by dmzaytsev** [comment]
@karato this task is not postponed anymore

**Comment by karato** [comment]
> @karato this task is not postponed anymore

@dmzaytsev right, I removed "postponed" tag

**Comment by karato** [comment]
@pecko This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by pecko** [comment]
@karato @dmzaytsev 

> I use two browsers and two github accounts

I have only one github account. You mean that I should create some helper accounts or there are some such accounts?

**Comment by dmzaytsev** [comment]
@pecko yeah you should create one more github account
it's free :)

**Comment by pecko** [comment]
@dmzaytsev 

OK. Thanks.

**Comment by pecko** [comment]
@dmzaytsev @karato 

I can reproduce the issue with two browsers/two accounts. When an account receives a message without email notification, email notification is dead for that bout. Log off/log on, notify off/notify on don't help.
I will try to fix it, but I don't know netbout enough (hoping for now) and maybe need more time.

**Comment by dmzaytsev** [comment]
@pecko you have 10 days to complete a task.
According the policy http://www.teamed.io/policy.html#10 if you need more time just type 
`@karato I need more time` right here in the ticket

**Comment by pecko** [comment]
@karato 
That should be enough. Thanks.

**Comment by karato** [comment]
> @karato 
> That should be enough. Thanks.

@pecko no problem :)

**Comment by pecko** [comment]
@dmzaytsev  @karato 

When I have tested the previous time I have reproduced the issue exactly how it described in the issue description.

Now, account 2 receives email notification not matter if she/he is subscribed or not.
I would like to start local server as http://snapshot.netbout.com/
I can created the server with 
```
mvn clean install -Phit-refresh -Dport=8080
```
but this server has only one user: tester. I can't (or don't know) create a more users locally.
I have opened https://github.com/yegor256/netbout/issues/810

**Comment by pecko** [comment]
@dmzaytsev @karato 

See the PR: https://github.com/yegor256/netbout/pull/811

**Comment by dmzaytsev** [comment]
@pecko I just tested on snaphot.netbout.com. It works.
thank you

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good.

**Comment by karato** [comment]
> @karato Looks good.

@elenavolokhova thanks a lot :)

**Comment by karato** [comment]
@pecko 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 67403093. Thanks so much! Your account was topped up for **30 mins** (transaction ID is `67403132`, the task took 162 hours and 4 mins). added +30 to your rating, now it is equal to [+135](http://www.netbout.com/b/35660?open=rating)
