### ISSUE TITLE
Show related PRs in "agenda"

### ISSUE THREAD

**Issue by caarlos0** [yegor256/netbout#696]
It would be nice to show the respective Pull requests of an issue in the agenda page.

Github has cross-references, don't know if they are consumable via API, but, if they do, this would be a nice feature to have...

**Comment by dmzaytsev** [comment]
@caarlos0  thanks for reporting,
but the agenda and other pages is out of the scope of the Netbout project.
Ask @yegor256 inside Netbout about this.

**Comment by karato** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@caarlos0 yeah, thanks for the idea, but it's outside of scope of netbout
