### ISSUE TITLE
suspend feature

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#697]
let' implement the suspend feature
- anybody can suspend other a bout participant. ~~Just post a message like this `@netbout suspend @yegor256` see #698~~
- anybody can unsuspend other the suspended bout participant.
- suspended participant has "disabled" (grayed-out) photo with a hint `<name> suspended by <name> yyyy-dd-mm HH24:mi`
- suspended participant can't invite someone into the bout
- suspended participant can't post new messages into the bout
- suspended participant can't see the text in the messages when he/she been suspended

**Comment by dmzaytsev** [comment]
@yegor256 what do you think about proposed implementation the suspend feature?

**Comment by karato** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@dmzaytsev I like it, but let's use the UI for that, not messages. Next to each photo/name we have a red cross, which you can click to "suspend" the user. Then, when a user is suspended, let's change the cross to something like an "undo" symbol. Make sense?

**Comment by dmzaytsev** [comment]
@yegor256 I believe we need a log when and who suspend/unsuspend someone.
I think the messages a good option for this one, we can see the event in history and get the email notification. We will use UI for suspend/unsuspend but we need to have  `@netbout` friend who can send a message

**Comment by yegor256** [comment]
@dmzaytsev yes, I like the idea. Let's use the feature through UI buttons, but post messages from `@netbout` after each operation, just like you suggested. Good thinking!

**Comment by dmzaytsev** [comment]
@karato it's a vald bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by karato** [comment]
> @karato it's a vald bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by karato** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `59823069`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else
