### ISSUE TITLE
@netbout assistant

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#698]
let's implement the `@netbout assistant`
- the assistant  should monitor entered messages for mention `@netbout`. Maybe it can be a friend in each bout.
- The assistant configuration should accept a search template, a response templates and an action interface implementation.
- The assistant should post a message into the bout before and after the action call.

**Comment by karato** [comment]
@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@zshamrock could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by karato** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 15 mins, transaction `59118883`

**Comment by dmzaytsev** [comment]
@karato I didn't ask to mark it as a bug yet...

please set postponed tag here.

**Comment by zshamrock** [comment]
Thank you, @karato

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, someone else will be assigned soon
