### ISSUE TITLE
DyInbox.java:62-65: Refactor DyInbox class to avoid...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#700]
Puzzle `603-0cf011c2` in `netbout-web/src/main/java/com/netbout/dynamo/DyInbox.java:62-65` has to be resolved: Refactor DyInbox class to avoid suppressing of PMD.TooManyMethods and PMD.ExcessiveImports warnings. for example there are some private static methods there, those could be easily extracted.... The puzzle was created by Ivan Inozemtsev on 15-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.0` (correct me if I am wrong)

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev no problem, I will try to find somebody else

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by karato** [comment]
@dmzaytsev The issue should be closed..
