### ISSUE TITLE
jslint is absent

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#701]
If I understand it right, we don't check the static quality of `.js` files now. It's wrong. Let's add a `jslint` step to `pom.xml` somehow

**Comment by karato** [comment]
@yegor256 added "indie" tag to this issue

**Comment by dmzaytsev** [comment]
@yegor256 what the indie tag does mean?
Should I mark this ticket as a bug?

**Comment by yegor256** [comment]
@dmzaytsev yes, please. "indie" means that the bug was reported by an "independent" reviewer (which is my role in this project)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-58938970`

**Comment by dmzaytsev** [comment]
@karato please assign this task

**Comment by karato** [comment]
> @karato please assign this task

@dmzaytsev we don't have enough people in the project now... we're working on it now

**Comment by dmzaytsev** [comment]
@karato  thanks for letting me know

**Comment by antonini** [comment]
@dmzaytsev What about the profile that is going to be used?

**Comment by dmzaytsev** [comment]
@antonini there is more priority tasks in the project... would be great if you pickup some of them

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato  thanks for letting me know

@dmzaytsev np

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, someone else will be assigned soon
