### ISSUE TITLE
TkIndex.java:53-55: Bout page should also display...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#702]
Puzzle `603-275d519b` in `netbout-web/src/main/java/com/netbout/rest/bout/TkIndex.java:53-55` has to be resolved: Bout page should also display search box so that user can search for text in messages. See Messages#search method for details.... The puzzle was created by Ivan Inozemtsev on 11-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.0"

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev OK, I labeled it as "urgent" tag

**Comment by karato** [comment]
@erimerturk do this task

**Comment by dmzaytsev** [comment]
@erimerturk is there any progress on this task?

**Comment by erimerturk** [comment]
@dmzaytsev i am working on it but i think i need more time. @karato i need more time for this task please.

**Comment by erimerturk** [comment]
@karato i need more time for this task please, thank you

**Comment by erimerturk** [comment]
@dmzaytsev @karato please see PR #724

**Comment by karato** [comment]
> @karato i need more time for this task please, thank you

@erimerturk right, take your time and thanks for informing

**Comment by dmzaytsev** [comment]
@karato this task not urgent  anymore

**Comment by karato** [comment]
> @karato this task not urgent  anymore

@dmzaytsev thanks, I removed the "urgent" tag

**Comment by erimerturk** [comment]
@karato @dmzaytsev  please check and close if it is acceptable, thank you

**Comment by erimerturk** [comment]
@karato @dmzaytsev could you please check and close if it is acceptable, thank you

**Comment by dmzaytsev** [comment]
@erimerturk karato will close it

**Comment by erimerturk** [comment]
@dmzaytsev just a reminder :)

**Comment by karato** [comment]
@dmzaytsev Closing..

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@erimerturk I added 10 mins to @ypshenychka (for QA review) in transaction 60421213. Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-2KP15954SY233664K`, the task took 259 hours and 7 mins). added +30 to your rating, now it is equal to [+180](http://www.netbout.com/b/35280?open=rating)
