### ISSUE TITLE
TkInbox.java:50-52: Index page should also display...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#704]
Puzzle `603-303ccd32` in `netbout-web/src/main/java/com/netbout/rest/TkInbox.java:50-52` has to be resolved: Index page should also display search box so that user can search for bouts containing text. See Inbox#search method for details.... The puzzle was created by Ivan Inozemtsev on 11-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.0 since there is nothing set yet

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev OK, I labeled it as "urgent" tag

**Comment by karato** [comment]
@bilalyasar please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@karato this task not urgent any more

**Comment by karato** [comment]
> @karato this task not urgent any more

@dmzaytsev got it, "urgent" tag removed from here

**Comment by dmzaytsev** [comment]
@bilalyasar  is there any progress on this task?

**Comment by dmzaytsev** [comment]
@erimerturk could you pickup this ticket?

**Comment by erimerturk** [comment]
@dmzaytsev  just assign it to me

**Comment by dmzaytsev** [comment]
@karato assign this task to @erimerturk  please

**Comment by dmzaytsev** [comment]
@yegor256 @karato  assign this task to @erimerturk please

**Comment by dmzaytsev** [comment]
@yegor256 @karato assign this task to @erimerturk please

**Comment by yegor256** [comment]
@karato assign @erimerturk to this pls

**Comment by karato** [comment]
> @karato assign @erimerturk to this pls

@yegor256 sure! @erimerturk the task is yours, please go ahead

**Comment by dmzaytsev** [comment]
@erimerturk is there any progress on this issue?

**Comment by erimerturk** [comment]
@dmzaytsev actually i am in <b>away</b> mode, you can see it from netbout, i can fix this issue but need more time. @karato could you please give me more time if it is possible ?

**Comment by dmzaytsev** [comment]
@erimertuk I have no access to your status :)
The ticket has been assigned to you  thats why I ask.
Could you estimate how much time you need?

**Comment by erimerturk** [comment]
@dmzaytsev i can start to work this issue on monday so i think 10 days maybe.

**Comment by dmzaytsev** [comment]
@erimerturk I think you will spend less than 10 days. You did such task recently

**Comment by dmzaytsev** [comment]
@karato we need more time here

**Comment by karato** [comment]
> @karato we need more time here

@dmzaytsev no problem, thanks for letting me know

**Comment by erimerturk** [comment]
@dmzaytsev please see PR details on #744

**Comment by dmzaytsev** [comment]
@erimerturk thanks!

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@dmzaytsev the code made here contains a puzzle `704-c6ad2d19`/#748, which will be resolved soon

**Comment by erimerturk** [comment]
@dmzaytsev please close it, if acceptable for you, thank you

**Comment by dmzaytsev** [comment]
@erimerturk this is the puzzle ticket. @karato will close it as the ticket reporter

**Comment by karato** [comment]
@dmzaytsev Closed, done, thanks all

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thank you

**Comment by karato** [comment]
@erimerturk I added 10 mins to @ypshenychka (for QA review) in transaction 61633789; Thank you, I have added **30 mins** to your account in payment/transaction "`AP-862964467W6089221`", time consumed: 239 hours and 51 mins; +30 added to your rating, at the moment it is: [+120](http://www.netbout.com/b/35280?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `704-c6ad2d19`/#748 solved
