### ISSUE TITLE
DyMessages.java:68-71: Refactor DyMessages class to avoid...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#705]
Puzzle `603-5d374ee5` in `netbout-web/src/main/java/com/netbout/dynamo/DyMessages.java:68-71` has to be resolved: Refactor DyMessages class to avoid suppressing of PMD.TooManyMethods and PMD.ExcessiveImports warnings. for example there are some private static methods there, those could be easily extracted.... The puzzle was created by Ivan Inozemtsev on 15-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.0`, let me know if it is wrong

**Comment by dmzaytsev** [comment]
@karato this is postponed taks

**Comment by dmzaytsev** [comment]
please set milestone to 3.1

**Comment by karato** [comment]
> @karato this is postponed taks

@dmzaytsev OK, I labeled it as "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed taks

@dmzaytsev all right, we'll find someone else for this task

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev the milestone here is 3.1

**Comment by karato** [comment]
@dmzaytsev The task is done, thanks all, I am closing it
