### ISSUE TITLE
Use message id on mail footer and link

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#706]
Instead of adding a timestamp on mail footer to avoid gmail to hide bout link (as shown below):
![netbout](https://cloud.githubusercontent.com/assets/209396/8216838/8476d5ec-150f-11e5-8e08-ba8ccef68dbb.PNG)

It would be nice that the link refers the full link of the message.

This will avoid a bad content on the message body and it will also put the user on top of the desired message.

Sample:

`to reply click here http://www.netbout.com/b/35387#msg509112`

**Comment by dmzaytsev** [comment]
@karato valid bag

**Comment by dmzaytsev** [comment]
@karato this is postponed task

**Comment by dmzaytsev** [comment]
@karato we are waiting for #643 here

**Comment by dmzaytsev** [comment]
@karato  this task has the impediment #643 
Is it possible put it on hold until #643 will be resolved ?

**Comment by yegor256** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@yegor256 I just added bug tag here

**Comment by karato** [comment]
@antonini attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@antonini thanks for reporting! I topped your account for 15 mins, transaction AP-00061796Y64389601

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev got it, "postponed" tag here

**Comment by karato** [comment]
> @karato this is postponed task

@dmzaytsev I will try to find someone else

**Comment by karato** [comment]
> @karato we are waiting for #643 here

@dmzaytsev ok, let's wait for #643

**Comment by karato** [comment]
@antonini we waited for #643, it is closed already
