### ISSUE TITLE
In MkUserTest.java class it was created a variable that is used just once.

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#707]
In MkUserTest.java class it was created a variable that is used just once.

Actual source code:

    final Base base = new MkBase();
    final User user = base.user(new URN("urn:test:9989"));

As it should be:

    final User user = new MkBase().user(new URN("urn:test:9989"));

This can be seen over [here](https://github.com/yegor256/netbout/blob/814170f92de98e2afefccf22217f7c924323e64a/netbout-client/src/test/java/com/netbout/mock/MkUserTest.java#L52).

**Comment by dmzaytsev** [comment]
@antonini  fixed in #709 please close

**Comment by antonini** [comment]
@dmzaytsev Thanks.
