### ISSUE TITLE
It would be good to have a history of earnings

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#708]
Currently the "earnings" page only show last 2 weeks detailed.

It would be nice to have a way to see all issues that you've worked.

**Comment by dmzaytsev** [comment]
@antonini it's out of the scope of the project
ask @yegor256 inside Netbout about it

**Comment by dmzaytsev** [comment]
@antonini please close the ticket

**Comment by antonini** [comment]
@dmzaytsev Thanks
