### ISSUE TITLE
TkAppAuth.java:92-101: Need to implement PsBasic.Entry. PsFake...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#713]
Puzzle `685-6534dff2` in `netbout-web/src/main/java/com/netbout/rest/TkAppAuth.java:92-101` has to be resolved: Need to implement PsBasic.Entry. PsFake usage should be changed to PsBasic( Manifests.read("Netbout-Basic-Realm"), new PsBasic.Default( Manifests.read("Netbout-Basic-User"), Manifests.read("Netbout-Basic-Pwd"))) But PsBasic.Default like class is currently missing. See takes #349. It is also needed to be able to switch on/off BasicAuth e.g. by via change the manifest entry "Netbout-Basic":true/false.... The puzzle was created by Eugene Kondrashev on 19-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev got it, "urgent" tag here

**Comment by dmzaytsev** [comment]
@karato it's not urgent anymore

**Comment by karato** [comment]
> @karato it's not urgent anymore

@dmzaytsev thanks, I removed the "urgent" tag

**Comment by dmzaytsev** [comment]
@karato assign this to me please

**Comment by karato** [comment]
> @karato assign this to me please

@dmzaytsev the task is yours, please proceed

**Comment by dmzaytsev** [comment]
@karato please see PR #777

**Comment by karato** [comment]
> @karato please see PR #777 

@dmzaytsev thank you, I will check it

**Comment by dmzaytsev** [comment]
@karato fixed in #777 please close the ticket

**Comment by karato** [comment]
> @karato fixed in #777 please close the ticket

@dmzaytsev I will close it when the puzzle disappears from the source code, and keep in mind that it may take up to a day to update project stats after a successful deployment

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by karato** [comment]
@dmzaytsev We are done here, thanks all

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks!

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 64001598

**45 mins** was added to your account, many thanks for your contribution (payment 64001606)! The task took 38 hours and 15 mins.

the bonus for fast delivery (m=2295)

+45 to your rating, your total score is [+1794](http://www.netbout.com/b/35166?open=rating)
