### ISSUE TITLE
/start with rename query argument

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#714]
We made something similar in #610  

Let's make it possible to rename bout right after start in `/start` entry point. Something like this should be possible to do:

```
/start?post=How+are+you&invite=dmzaytsev&rename=let's+talk
```

Pay attention, rename should happen _before_ inviting and posting a message.

**Comment by karato** [comment]
@yegor256 I tagged this as "indie"

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-c6958835`

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please assign this to me

**Comment by karato** [comment]
> @karato please assign this to me

@dmzaytsev of course, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 fixed in PR #771  
I just checked it on snapshot.netbout.com. it works
Please close the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by dmzaytsev** [comment]
@karato @yegor256 I don't see a bug tag here

> dmzaytsev commented on 23 Jun
@karato it's a valid bug

I guess that's why the ticket not paid yet
what we shall to do?

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 63941640. Thanks a lot, I just topped your account for **38 mins**, transaction ID `63941646`, total time was 63 hours and 51 mins. m=3831, that's why a bonus here for fast delivery. added +38 to your rating, now it is equal to [+1729](http://www.netbout.com/b/35166?open=rating)
