### ISSUE TITLE
return after login looses query params

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#715]
We introduced this feature in #609 

I'm logged off and I'm opening this URL:

```
http://www.netbout.com/b/35086?open=agenda
```

I see a login page. I click "github" button and logs in correctly. I see this page:

```
http://www.netbout.com/b/35088
```

Query params are lost. I believe it's a bug.

**Comment by yegor256** [comment]
@dmzaytsev this is rather critical feature, in combination with #610. Let's say, I want to give my friend this URL:

```
http://www.netbout.com/start?invite=yegor256&post=I+am+ready+to+talk
```

I give him this URL and say: click it when you're ready to discuss. He clicks the URL, logins (or creates an account) and immediately lands into a new bout, where I'm invited and a simple message is posted. I will reply to him right there.

At the moment this scenario doesn't work, because of the bug explained above.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by dmzaytsev** [comment]
@yegor256 is it priority task? should I set urgent tag here?

**Comment by yegor256** [comment]
@dmzaytsev yes, would be nice to have it fixed ASAP (and released in 2.16)

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by dmzaytsev** [comment]
@karato this task is  urgent

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-79f5c1e0

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev I attached this issue to milestone `3.1`

**Comment by karato** [comment]
> @karato this task is  urgent

@dmzaytsev right, I added "urgent" tag

**Comment by karato** [comment]
@sretenperic this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by karato** [comment]
@sretenperic you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). -30 added to your rating, current score is: [-30](http://www.netbout.com/b/35464?open=rating)

**Comment by dmzaytsev** [comment]
@karato assign this to me please

**Comment by dmzaytsev** [comment]
@karato assign this to me please

**Comment by karato** [comment]
> @karato assign this to me please

@dmzaytsev done, the task is yours, go ahead

**Comment by karato** [comment]
> @karato assign this to me please

@dmzaytsev this task was already yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #778 
I just checked on snapshot.netbout.com, it works fine
please close the ticket

**Comment by dmzaytsev** [comment]
@karato this is not urgent anymore

**Comment by karato** [comment]
> @karato this is not urgent anymore

@dmzaytsev OK, I un-labeled it as "urgent" tag

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks!

**Comment by karato** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `63982424`... Much obliged! I have added **1 hour** to your account in payment "63982434", 3 hours and 40 mins spent... there is a bonus for fast delivery (m=220)... added +60 to your rating, now it is equal to [+1794](http://www.netbout.com/b/35166?open=rating)
