### ISSUE TITLE
Redirect to http://www.netbout.com/,PsCookie=

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#716]
sometimes Netbout redirected to http://www.netbout.com/,PsCookie= and put `,PsCookie=value` into query param...

![image](https://cloud.githubusercontent.com/assets/9972909/8314771/16e7de86-1a05-11e5-8100-98b15916eb58.png)

It need to be investigated and fixed

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by yegor256** [comment]
@dmzaytsev never seen this... just curious, how can it be reproduced?

**Comment by dmzaytsev** [comment]
@yegor256 seems the RsReturn cookie is related to this bug.
We had already such issue #694, but I saw it my own eyes yesterday and catched the http headers.
We have some issue with setting the RsReturn cookie value

**Comment by karato** [comment]
@dmzaytsev since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 15 mins, transaction `59899742`

**Comment by yegor256** [comment]
@dmzaytsev I think I know how to reproduce. Just try to attach a file with an empty form field "name"

**Comment by yegor256** [comment]
@dmzaytsev it's reproducable on production, but it's not reproducable on snapshot. Looks like it's fixed already...

**Comment by dmzaytsev** [comment]
@yegor256 I will mark it as postponed and check again after the release

**Comment by dmzaytsev** [comment]
@yegor256 I don't understand how it is possible.
I just checked tests for RsWithCookies in Takes, it rejects comma for the cookie values.

**Comment by yegor256** [comment]
@dmzaytsev maybe this happens during cookies aggregation. This line means that we have **two** cookies:

```
Set-Cookie: RsReturn=,PsCookie=...
```

**Comment by dmzaytsev** [comment]
@yegor256 btw I can't attach a file with an empty name
got the error `invalid attachment name ""`

**Comment by dmzaytsev** [comment]
@yegor256 I checked it already
Takes uses `;` as cookie separator

**Comment by yegor256** [comment]
@dmzaytsev yes, you can't attach a file without a name, but in production you end up in that wrong page (as you mentioned above), while in the snapshot you see a proper error message.

**Comment by dmzaytsev** [comment]
@yegor256 I just created the issue https://github.com/yegor256/takes/issues/353
I think it will prevent such errors

**Comment by dmzaytsev** [comment]
I tried to attach the file with empty name on the production and I saw a proper error message.
I checked the cookies after it. everything is okay

> yegor256 commented a minute ago
> @dmzaytsev yes, you can't attach a file without a name, but in production you end up in that wrong page (as you mentioned above), while in the snapshot you see a proper error message.

**Comment by yegor256** [comment]
@dmzaytsev are you sure?? I just checked production, the error is there

**Comment by dmzaytsev** [comment]
@yegor256 absolutely
is there a browser specific issue ?

**Comment by dmzaytsev** [comment]
@yegor256 issue that's fixed already on the snapshot...

**Comment by dmzaytsev** [comment]
@yegor256 I propose postpone this task and check again after the release

**Comment by dmzaytsev** [comment]
@yegor256  anyway after it https://github.com/yegor256/takes/issues/353 
we will got the error before the invalid cookie will be set .
It will allow localize the error location

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added the "postponed" tag

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by yegor256** [comment]
@dmzaytsev I believe the problem is caused by this bug in Takes: https://github.com/yegor256/takes/issues/375

**Comment by dmzaytsev** [comment]
@yegor256 many thanks

but I believe we should check the location yegor256/takes#353  in any case

**Comment by yegor256** [comment]
@dmzaytsev I upgraded takes to 0.23.2. let's try to release a new version and see how it works

**Comment by yegor256** [comment]
@dmzaytsev I'm not sure about that idea of checking the `Location`... we don't know what users have in mind... in some applications `,PsCookie=abc` may be a perfectly valid location. it's not against the architecture of HTTP

**Comment by yegor256** [comment]
@rultor release, tag is `2.16.2`

**Comment by yegor256** [comment]
@dmzaytsev the problem is gone

**Comment by dmzaytsev** [comment]
@yegor256 thanks!
