### ISSUE TITLE
RtAttachment#write() breaks the content

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#717]
`RtAttachment#write()` uses `IOUtils.toString()` in order to convert the stream to String, which is fine for text content but is not acceptable for binary content. It simply breaks the content. We should use `IOUtils.toByteArray()` instead.

**Comment by dmzaytsev** [comment]
@yegor256 seems it duplicate #703 isn't it ?
Anyway thanks for your investigate! It will help the ticket performer

**Comment by yegor256** [comment]
@dmzaytsev I think these are two separate issues. In #703 we're dealing with user interface, while here is the problem in the RESTful client

**Comment by dmzaytsev** [comment]
@yegor256 you're right, sorry

**Comment by dmzaytsev** [comment]
@karato it's valid bug

**Comment by karato** [comment]
> @karato it's valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@yegor256 there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-57148a6b`

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by karato** [comment]
> @karato assign me to this please

@dmzaytsev sure, the task is yours now

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #798 please close the ticket if alright

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@dmzaytsev just added 10 mins to @ypshenychka (for QA), payment ID is `65821708`. I added **1 hour** to your account, many thanks for working with the project! The completion time here was 65821724.. there is a bonus for fast delivery (m=599). +60 added to your rating, current score is: [+1261](http://www.netbout.com/b/35166?open=rating)
