### ISSUE TITLE
Change email broken

### ISSUE THREAD

**Issue by erimerturk** [yegor256/netbout#721]
Step 1 : Go  http://www.netbout.com/acc/index and change email to <b>"xxx@mail.com" </b>

After redirection to home page 

Step 2 : Go  http://www.netbout.com/acc/index and see flash message as <b>email changed to "xxx@mail.com" </b> but inside mail box you will see  <b>old email</b>, it must be <b>"xxx@mail.com" </b>

**Comment by dmzaytsev** [comment]
@erimerturk thanks for reporting!

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@erimerturk there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@erimerturk many thanks for the bug report, I added 15 mins to your acc, transaction `AP-5MT14451TW489401T`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will try to find someone else

**Comment by original-brownbear** [comment]
@dmzaytsev see my comment here:
https://github.com/yegor256/netbout/issues/989#issuecomment-190744882
... essentially this one, #853 ( clear duplicate of this one ) and #989 are all the same issue.
I think at least either this one or #853 should be marked as duplicate.

**Comment by karato** [comment]
@rultor rultor closed it by mistake, @erimerturk please take a look
