### ISSUE TITLE
Message posted flash message is broken

### ISSUE THREAD

**Issue by erimerturk** [yegor256/netbout#722]
1. Enter a bout (bout id:XXX) and post a message and then u will see <b>message posted to the bout XXX </b>
2. Go to main page and again u will see again <b>message posted to the bout XXX </b>

I am expecting that <b>Message posted</b> flash message should be lost.

**Comment by dmzaytsev** [comment]
@erimerturk thanks !
 it's a bug in Takes https://github.com/yegor256/takes/issues/354

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed task

until yegor256/takes#354 will be resolved

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@erimerturk I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@erimerturk thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-38U09202H29436733`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev all right, we'll find someone else for this task
