### ISSUE TITLE
bout.xsl:45-45: The line below should be...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#723]
Puzzle `606-457eb15d` in `netbout-web/src/main/xsl/bout.xsl:45-45` has to be resolved: The line below should be changed to avoid linking... The puzzle was created by Matteo Barbieri on 27-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev since the ticket has no milestone I set it to 3.0

**Comment by dmzaytsev** [comment]
@antonini could you pickup this ticket?

**Comment by antonini** [comment]
@dmzaytsev I can.

**Comment by dmzaytsev** [comment]
@antonini thanks

**Comment by dmzaytsev** [comment]
@karato assign @antonini please to this issue

**Comment by karato** [comment]
> @karato assign @antonini please to this issue

@dmzaytsev done. @antonini you are assigned to this task. please proceed...

**Comment by antonini** [comment]
@dmzaytsev Do you know how do I disable validations (all tests) to a given file? I added 'jquery.textcomplete.min.js' file to the project and added that to the "exclude" on pom file.
But qulice still check that js.

**Comment by antonini** [comment]
@dmzaytsev and @karato Just found that this issue is blocked by this one: [qulice/#424](https://github.com/teamed/qulice/issues/424).

**Comment by dmzaytsev** [comment]
@antonini  you should download this `.js` file during mvn package phase and place it into `target/classes/js`. You don't need to disable jslint.
You can use [bower for instance](https://github.com/yegor256/netbout/pull/712#issuecomment-114315530) see #712 for details

>@todo #606 The line below should be changed to avoid linking
             directly to the plugin author's website. Before doing that,
             we should add the functionality to download third party libraries
             from their website (like https://github.com/yuku-t/jquery-textcomplete/
             in this case) by Bower.
             Refer to #712 for suggestions on how to do it.

**Comment by antonini** [comment]
@karato PR #779 ready for review.

**Comment by antonini** [comment]
@karato PR #779 was merged and deployed.

**Comment by karato** [comment]
@dmzaytsev It is closed now

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by karato** [comment]
> @karato PR #779 ready for review.

@antonini OK, will take a look

**Comment by karato** [comment]
> @karato PR #779 was merged and deployed.

@antonini OK

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you ;)

**Comment by karato** [comment]
@antonini just added 10 mins to @elenavolokhova (for QA), payment ID is `64038096`... I added **45 mins** to your account, many thanks for working with the project! The completion time here was AP-35W57876DP712680C.... the bonus for fast delivery (m=1720)... +45 added to your rating, current score is: [+692](http://www.netbout.com/b/35346?open=rating)
