### ISSUE TITLE
Highlight message when accessed from a permalink

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#725]
Message that is accessed from permalink on email should be highlighted.
This is to help the user to know where the new content begins.

**Comment by antonini** [comment]
This issue depends on #643.

**Comment by dmzaytsev** [comment]
@antonini see a bug definition 
http://www.yegor256.com/2014/04/13/bugs-are-welcome.html#what-is-a-bug?
this functionality not implemented yet

please close this ticket and create a puzzle about "highlight a message" in your pull request #710

**Comment by antonini** [comment]
Ok. I'll add it over there.
