### ISSUE TITLE
Each loaded page generates a new div inside external content.

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#726]
Each loaded page (when scrolling down) generates a new div inside the external div that holds the content.

This can be seen on the print screen below.

![screen shot 2015-06-27 at 10 13 59 pm](https://cloud.githubusercontent.com/assets/209396/8394660/2eb93420-1d1a-11e5-8365-93228f5c37ba.png)

**Comment by dmzaytsev** [comment]
@antonini please elaborate a bit what's wrong here and how you suggest fix it.

**Comment by antonini** [comment]
@dmzaytsev When you access a BOUT that has more then 16 messages, it loads latest 16 messages (As you can see `div#messages >div.message``).
When you scroll down your browser it loads next page and so on, but instead of adding new messages on same level, it generates an inner div that holds all messages.

On the printscreen above you can see that the second page starts on `div#messages > div >div.message` and so on...

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@antonini since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@antonini thanks for the ticket, your account was topped for 15 mins, payment AP-9LA14211U7555905R

**Comment by yegor256** [comment]
@antonini @dmzaytsev I believe it's by design... I made it this way. I didn't find a way to do it differently. If we can fix it and make them "flat", would be great of course.

**Comment by antonini** [comment]
@yegor256 Yes. It is possible to do it "flat". Using `insertBefore` method. I think i can't implement it because I reported it. Am I wrong?

**Comment by yegor256** [comment]
@antonini not sure... I'm not a big expert in HTML/jQuery. We have to create a proper test first, before making changes

**Comment by antonini** [comment]
@yegor256 I've created the [following](http://jsfiddle.net/antonini/dbxqyws5/) code so you can see the main change that will be done on JS file.

**Comment by yegor256** [comment]
@antonini I like it, but again, in order to be able to change the JS we should test it first (just like with all other parts of the system)

**Comment by antonini** [comment]
@yegor256 Agree. And how you suggest it? We don't have much view tests (using CasperJS). I think it would be nice to create more tests before changing it. What do you think about it?

**Comment by yegor256** [comment]
@antonini exactly, first step is to create tests and reproduce the problem. Then, we'll think about fixing

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will ask somebody else to pick this up
