### ISSUE TITLE
Cross-Origin Resource Sharing (CORS) error 

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#727]
When accessing a bout and looking over Chrome console i saw the following error:

`Font from origin 'http://img.netbout.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.netbout.com' is therefore not allowed access.`

**Comment by dmzaytsev** [comment]
@antonini I can't reproduce it or I misunderstood the reproduction steps. Could you attach a screenshot?

**Comment by antonini** [comment]
Just open http://www.netbout.com on your google chrome and open browser console. Here is a screenshot.
![screen shot 2015-06-28 at 9 18 36 am](https://cloud.githubusercontent.com/assets/209396/8396415/73ec010c-1d7a-11e5-9144-3f6c66aa63ad.png)

**Comment by dmzaytsev** [comment]
@antonini I don't see any error...

![image](https://cloud.githubusercontent.com/assets/9972909/8396714/81b0c66e-1dcb-11e5-99c3-5d6552cc1394.png)

the future performer should know steps for reproduce the issue

**Comment by antonini** [comment]
@dmzaytsev Strange. I just opened the web site. And when I checked my console there were the error.
Even on the login page it happens (tried to access with an anonymous session).

My environment: 
OS: OSX Yosemite
Google Chrome: Version 43.0.2357.124 (64-bit)
DNS: 8.8.8.8, 4.4.4.4
Resolve: 
`www.netbout.com -> us-east-1-a.route.herokuapp.com -> 23.21.247.21`
`img.netbout.com -> dxe6yfv2r7pzd.cloudfront.net -> 54.230.225.12`

Steps to reproduce:
1. Open Google Chrome;
2. Open a new tab/window;
3. Open Development Tools;
4. Chose `console` tab;
5. Access `www.netbout.com`;
6. The error is displayed on the console;

**Comment by dmzaytsev** [comment]
@antonini I did all steps, but I can't get the error...
anyway, whats wrong in Netbout except the error in the developer's console?
the developer's console is not a common way using Netbout, isn't it?

**Comment by antonini** [comment]
@dmzaytsev I tried in a different computer and no error happened too. I´ll try to find why this is happening just on my devel machine. Do you want me to close it and when I find the reason reopen it?

**Comment by dmzaytsev** [comment]
@antonini yes, please
