### ISSUE TITLE
paste a link to a message causes wrong sequence of the  messages

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#728]
when I paste a link on last message, Netbout shows earlier messages after it.
See screenshot.
Looks as a bug for me.

![image](https://cloud.githubusercontent.com/assets/9972909/8413677/9fb05f2c-1eab-11e5-8b85-fdbd7eab0e1a.png)

**Comment by dmzaytsev** [comment]
@karato it's a vald bug

**Comment by dmzaytsev** [comment]
@karato please assign to @antonini

**Comment by karato** [comment]
> @karato it's a vald bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 15 mins, transaction `60017918`

**Comment by dmzaytsev** [comment]
@karato please assign to @antonini

**Comment by yegor256** [comment]
@karato assign it to @antonini

**Comment by antonini** [comment]
@karato can you assign this to me?

**Comment by antonini** [comment]
@dmzaytsev I can't reproduce the error. Can you add me on that bout? my user on snapshot is `endrigotest`.

**Comment by dmzaytsev** [comment]
@antonini I just added you to this bout http://snapshot.netbout.com/b/4

**Comment by antonini** [comment]
@dmzaytsev All messages came in correct sequence as can be seen on the screenshot below.

![screen shot 2015-06-30 at 12 55 09 am](https://cloud.githubusercontent.com/assets/209396/8423651/ebc02ae8-1ec2-11e5-9541-eecf002d7f2c.png)

I used same message Id that you used. Is there any other step that you did?

**Comment by dmzaytsev** [comment]
@antonini 
* I posted a new message to the bout
* closed the tab
* opened the link http://snapshot.netbout.com/b/4#msg13 in the new browser tab 
* and got the messages list in the wrong order , same as screenshot in the ticket description

**Comment by yegor256** [comment]
@karato assign it to @antonini pls

**Comment by antonini** [comment]
@karato I'm waiting the issue to be assign to create the pull request.

**Comment by dmzaytsev** [comment]
@karato assign it to @antonini please

**Comment by antonini** [comment]
@karato, @dmzaytsev and @yegor256  I'm waiting for issue to be to me so I can do a PR. Am I going to have some trouble with the following [policy](http://www.teamed.io/policy.html#7)?

**Comment by antonini** [comment]
@karato , @dmzaytsev and @yegor256 Ping.

**Comment by dmzaytsev** [comment]
@antonini I don't know what happens. Why @karato not respond...
I hope after weekend we'll get a new information.
Regarding your PR, you shouldn't create it before you will be assigned.
You won't be paid if you not assigned to the task before.
Let's wait for the answer from @yegor256 or @karato

**Comment by dmzaytsev** [comment]
@karato assign it to @antonini please

**Comment by karato** [comment]
> @karato assign it to @antonini please

@dmzaytsev done. @antonini you are assigned to this task. please proceed...

**Comment by antonini** [comment]
@dmzaytsev and @karato PR #735 is ready.

**Comment by dmzaytsev** [comment]
@antonini the bug is still here

* I posted a new message to the bout http://snapshot.netbout.com/b/4
* closed the tab
* opened the link http://snapshot.netbout.com/b/4#msg13 in the new browser tab
* and got the messages list in the wrong order 
* also an empty message appears below #msg13

![image](https://cloud.githubusercontent.com/assets/9972909/8612708/61fb7fea-26ee-11e5-8b4b-3d6157d3bddc.png)

**Comment by antonini** [comment]
@dmzaytsev Strange, I tested on chrome and safari and it worked. Can you clean your cache?

**Comment by dmzaytsev** [comment]
I just cleared the cache and tested on Chrome and Firefox,  the bug is still here.
Did you repeat all steps from the comment above ?

**Comment by dmzaytsev** [comment]
@antonini please repeat all steps, including first

**Comment by antonini** [comment]
@dmzaytsev I could reproduce it on a windows VM. On my dev machine i jumped first step. Going to try it again.

**Comment by antonini** [comment]
@dmzaytsev A new PR was created fixing the problem that you reported. Here it is #740.

**Comment by dmzaytsev** [comment]
@antonini the bug is still here... Could you reproduce it ?

**Comment by antonini** [comment]
@dmzaytsev No.. I tested on Safari, Chrome and Firefox on OSX and didn't got the error. 
I was getting the error only with Firefox on OSX... 
Did you follow same steps as you said above? What is your environment?
I'll try it on Windows too.

**Comment by dmzaytsev** [comment]
@antonini absolutely same steps as above..
and same error.
I tested on  Chrome and Firefox on windows 8.1

**Comment by dmzaytsev** [comment]
@antonini sorry, it works on Firefox

**Comment by antonini** [comment]
@dmzaytsev Ok. Thanks for update. I'll do a simulation on Windows + Chrome

**Comment by antonini** [comment]
@dmzaytsev Check issue #741. 

This is happening on production and I tested against an old version and the problem was there.
I used the following commit to test it 520cecdbf7d93b8c47a0b84c51009ca63a2f6bf4. If you checkout that commit and run same steps that are described on the issue you will receive the results that are listed there.

That problem affects this issue because when the message is old, it forces the browser to load next page and so one.

**Comment by dmzaytsev** [comment]
@antonini if so what did you fix in #735 #740 ?

**Comment by antonini** [comment]
@dmzaytsev Here it is:
#735 I fixed JS error that was being thrown on console, improved the logic of "load next page or scroll user to the message that he wants". I thought that part was wrong, so I created a test case for that.
#740 I fixed the part that was counting how many messages was received on a new page if server return it as html.

**Comment by dmzaytsev** [comment]
@antonini thanks!

**Comment by antonini** [comment]
@karato Issue is closed.

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks!

**Comment by karato** [comment]
@antonini just added 10 mins to @elenavolokhova (for QA), payment ID is `61244041`

paid, thanks, added **30 mins** to your account, payment `AP-7UM142597H299501S`, 169 hours and 24 mins was spent

+30 added to your rating, at the moment it is: [+354](http://www.netbout.com/b/35346?open=rating)
