### ISSUE TITLE
bout.js:141-144: System should highlights a message...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#729]
Puzzle `643-0c6bbfa8` in `netbout-web/src/main/js/bout.js:141-144` has to be resolved: System should highlights a message when accessing it through message's permalink. This must be implemented on a different method and must be called over here and on the `else` statement of the same `if else` block.... The puzzle was created by Endrigo Antonini on 28-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by dmzaytsev** [comment]
@karato this task not postponed anymore

**Comment by karato** [comment]
> @karato this task not postponed anymore 

@dmzaytsev thanks, I removed the "postponed" tag

**Comment by karato** [comment]
@dmzaytsev Finished, thanks, closing..
