### ISSUE TITLE
Redirected to home if submit empty message inside a bout.

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#730]
In a bout, when user try to post an empty message, system redirect user to home page with error instead of leaving the user on boat page with error.

Steps to reproduce:
1. Access netbout;
2. Access any bout;
3. Just hit submit;
4. And there you are redirected to home instead of leaving you inside the bout;

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed task

we are waiting for  https://github.com/yegor256/takes/issues/355

**Comment by dmzaytsev** [comment]
@karato this task not postponed anymore

the issue yegor256/takes#355 resolved
we can continue with Takes 0.21

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@antonini since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@antonini thanks for reporting! I topped your account for 15 mins, transaction AP-6LH92432E43579520

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev all right, we'll find someone else for this task
