### ISSUE TITLE
Add ARC reviews to the agenda

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#733]
ARC misses notification about pending ARC review very often.
I propose to add such pending reviews to the agenda as well as other assigned PRs

**Comment by dmzaytsev** [comment]
@longtimeago unfortunately the agenda's issues is out of the scope of the project.
Please submit such issues inside Netbout to @yegor256

**Comment by longtimeago** [comment]
@dmzaytsev ok, no problem! Thanks!
