### ISSUE TITLE
send email verification link

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#738]
If email has been changed let's verify it.

* add a new attribute to Alias, name: emverified, type: boolean
* after the email update, print the message `Email changed to "XXX@XXX.XXX". The verification link sent to this address.`
* set emverified to false
* add a new attribute Netbout-EmailCryptSecret to the manifest.
* after email update we should generate the verification link  `http://www.netbout.com/emverify/{code}`
where {code} is encrypted string `<alias>:<email>`
use the Netbout-EmailCryptSecret value as encryption key
* send a confirmation email to user with the verification link inside.
* if the email not verified we should display an exclamation icon with hint "the email not verified yet" near the alias name

**Comment by dmzaytsev** [comment]
@karato its a valid bug

**Comment by karato** [comment]
> @karato its a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev many thanks for the report, I topped your account for 15 mins, transaction 60856342

**Comment by yegor256** [comment]
@dmzaytsev I don't think we should add anything to interface `Alias`... we can implement all this internally, in `com.netbout.email` package. Nobody else should not know about this mechanism. Or I'm wrong?

**Comment by dmzaytsev** [comment]
@yegor256 we should implement deferred update the `email` attribute for `Alias`. I don't know how implement it without a separate storage for a confirmation data because the email confirmation  not in one stage. The user changed the attribute, we sent an email, email delivered, user opened it, clicked on link... it can take a long time.
If we don't want change Alias interface so we need to create a new table.
Maybe it would be better...
in this case we should do following:

* create new table e.g. `emconfirm`
* after the email update, insert a new record with random key (uuid?). Attribuites: user alias, new email, creation date
* generate the verification link `http://www.netbout.com/emverify/{emconfirm.hash}`
* send a confirmation email to user with the verification link inside.

...
in #739
* when user click on the link we should update email to the new value

**Comment by yegor256** [comment]
@dmzaytsev how about storing emails as `"yegor@teamed.io"` for confirmed ones and `"yegor@teamed.io!my-new-email@teamed.io"` for not yet confirmed ones? Once a confirmation arrives, we just remove the first part before `!` and start using the second part. Just to simplify the design..

**Comment by dmzaytsev** [comment]
@yegor256 ok than

a new action plan for the ticket:

* add a new attribute `Netbout-EmailCryptSecret` to the manifest.
* after the email update, print the message `Email changed to "XXX@XXX.XXX". The verification link sent to this address.`
* the email attribute value should be set to `<old email>!<new email>` as @yegor256 suggested above
* generate the verification link `http://www.netbout.com/emverify/{code}` where {code} is encrypted string `<alias>:<new email>`. We should use the `Netbout-EmailCryptSecret` value as the encryption key.
* send a confirmation email to user with the verification link inside.
* if the email attribute value contains `!` we should display an exclamation icon with hint `the email not verified yet` near the alias name.
* we should use first part of the email attribute (before `!`) for sending email or displaying the email attribute.

**Comment by yegor256** [comment]
@dmzaytsev looks good to me

**Comment by antonini** [comment]
@dmzaytsev and @yegor256 I disagree about how generating `{code}`. If you do that you can expose the value of `Netbout-EmailCryptSecret`.
In my opinion, the value of code should be generated randomly.

**Comment by dmzaytsev** [comment]
@antonini yes, you're right, it would better if we need strong security.
But it's the product owner choice. I agree with him.
Say we lost the encryption key. Someone generated the fake link and try to change your email. We will reject this request if you didn't change your email before or the email from the link doesn't match with the new email. See #739
Do you have any scenario to hack Netbout using  the Netbout-EmailCryptSecret value ?

**Comment by antonini** [comment]
@dmzaytsev No I don't have it right now.

**Comment by dmzaytsev** [comment]
@antonini fine :)

**Comment by karato** [comment]
@dimonn12 this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all

**Comment by dmzaytsev** [comment]
@karato this is not postponed anymore

**Comment by karato** [comment]
> @karato this is not postponed anymore

@dmzaytsev right, I removed "postponed" tag

**Comment by karato** [comment]
@dimonn12 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@bdragan would you like to pickup this?
I can assign you to this task?

**Comment by bdragan** [comment]
@dmzaytsev Yes, please. Thanks.

**Comment by dmzaytsev** [comment]
@karato assign @bdragan to this please

**Comment by karato** [comment]
> @karato assign @bdragan to this please

@dmzaytsev OK. @bdragan the ticket is yours, please proceed

**Comment by bdragan** [comment]
@dmzaytsev PR #836 has been merged. The issue can be closed.

**Comment by dmzaytsev** [comment]
@bdragan thanks!

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@dmzaytsev these 2 puzzles were created in this ticket: `738-4d284963`/#841, `738-d76bd177`

**Comment by karato** [comment]
@bdragan 10 mins was added to the account of @ypshenychka (for QA review), in transaction 70053244; Many thanks! **30 mins** were added to your account in Transaction ID `70053249` (task took 98 hours and 38 mins); +30 to your rating, your total score is [+361](http://www.netbout.com/b/35709?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `738-4d284963`/#841 solved
