### ISSUE TITLE
process the email verification link

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#739]
if user click on the verification link we should process this.

* create a new Take `TkEmVerify`, map it to `http://www.netbout.com/emverify/{code}`
in `TkEmVerify.act()`
* decrypt `{code}`, 
* find the alias
* reject request if the email attribute doesn't contain `!`
* compare the email attribute part after `!`  with value from the verification link
* if the values match, update the 'old part' from the email attribute and print a message `email verified`
* if the values  not match, reject request with a message `verification link not valid`

see #738 for an additional info

**Comment by karato** [comment]
@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@dmzaytsev thanks for reporting! I topped your account for 15 mins, transaction 60855633

**Comment by karato** [comment]
@pecko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by pecko** [comment]
@dmzaytsev @karato 

I think that this issue depends on #738 that is still open. Right?

**Comment by dmzaytsev** [comment]
@pecko you can process this ticket
no need to wait #738
furthermore the verification should be implemented before sending confirmation, isn't?

**Comment by pecko** [comment]
@dmzaytsev 

> if user click on the verification link we should process this.

What is the verification link? You mean the Save button or it must be added in some of these two tasks?

**Comment by dmzaytsev** [comment]
@pecko the verification link will be sent by email see #738 and then the user will click on it. I this ticket you should implement a handler for the link `TkEmVerify`

**Comment by pecko** [comment]
@dmzaytsev 

When I will do it? When user click save to change an email?

**Comment by pecko** [comment]
@dmzaytsev 

Sorry for a lot questions, but I still don't understand requirement completely.

**Comment by dmzaytsev** [comment]
@pecko you should  implement the verification as it described in the ticket description

> create a new Take TkEmVerify, map it to http://www.netbout.com/emverify/{code} 
> in TkEmVerify.act() 
> decrypt {code},
> find the alias
> reject request if the email attribute doesn't contain !
> compare the email attribute part after ! with value from the verification link
> if the values match, update the 'old part' from the email attribute and print a message email verified
> if the values not match, reject request with a message verification link not valid

you don't need the real link to test your code isn't it ?

 #738 will be resolved by another developer(or you will do it)  later

**Comment by pecko** [comment]
@dmzaytsev 

OK. Thanks.
I probably have to explore it more. I don't know still what exactly is Take or similar concepts.
Need some more times, but probably not more than 10 days from today.

**Comment by dmzaytsev** [comment]
@pecko yep, definitely you  need to know something about [Takes](https://github.com/yegor256/takes) because Netbout build on Takes.  
don't worry, I'm sure it won't be too hard for you

btw please ask @karato about more time 
He is the project manager on the project

**Comment by pecko** [comment]
@dmzaytsev 

Thank you. I will ask @karato if I need more time.
It would be good when we would have a more documentation about takes/netbout, but I will try to use existing docs and the code.

**Comment by pecko** [comment]
@karato 
Can I have more time to work on this issue, please?

**Comment by karato** [comment]
> @karato 
> Can I have more time to work on this issue, please?

@pecko right, take your time and thanks for informing

**Comment by karato** [comment]
@bdragan this is your task

**Comment by bdragan** [comment]
@dmzaytsev Could you please assist with the following questions:
1. How do I find `Alias` for the provided alias which is the first part of the code?
2. Can alias names change?

**Comment by dmzaytsev** [comment]
@bdragan yeah, you're right, we can't find `Alias` using alias.
let's use `urn` to find `Alias`
in #738 we will make {code} as `<URLEncoder.encode(urn)>:<new email>`

also let's use Jasypt to decrypt {code},  see EmCatch for instance

>  Can alias names change?

No, we can't

**Comment by bdragan** [comment]
@dmzaytsev Thanks. I would say that there is no need to encode the `urn`, since it will already be part of the encrypted `code`. What do you think?

**Comment by dmzaytsev** [comment]
@bdragan
Yep, indeed, no needs to encode the urn, but it contains colons. You should take it into account when you will parse it. We can use another separator in this case. Up to you.

Let's do as you suggested about the alias

**Comment by bdragan** [comment]
@dmzaytsev Thanks. I kept the colon as separator. The regex is fairly simple anyway: `(.+):([^:]+):([^:]+)`. PR submitted.

**Comment by bdragan** [comment]
@dmzaytsev PR #832 has been merged. The issue can be closed.

**Comment by dmzaytsev** [comment]
@bdragan thanks!

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@bdragan added 10 mins to @elenavolokhova, for QA review, payment code is `69623218`... Much appreciated! **38 mins** was added to your account, payment ID `69623230`, time spent is 70 hours and 29 mins... m=4229, that's why a bonus here for fast delivery... added +38 to your rating, now it is equal to [+301](http://www.netbout.com/b/35709?open=rating)
