### ISSUE TITLE
User should be allowed to rename his alias

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#742]
User should be allowed to rename his alias.
Right now, when you choose an alias you can't change it any more.

**Comment by karato** [comment]
@dmzaytsev please do something about this issue

**Comment by dmzaytsev** [comment]
@yegor256 you're the product owner, I need your opinion on this issue.
Do we really need to be able rename an alias? I think it will impact on an infrastructure related with an agents. Isn't it?

**Comment by yegor256** [comment]
@dmzaytsev I think we should not allow this. Github, for example, doesn't allow this. If a user needs a new alias, he/she will create a new one. But the old one can't be renamed.

**Comment by dmzaytsev** [comment]
@antonini thanks for your suggestion, but it's not applicable for the project
close the ticket please

**Comment by antonini** [comment]
@dmzaytsev @yegor256 Ok, thanks.
