### ISSUE TITLE
TkInboxTest.java:46-48: Test case for search bouts...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#748]
Puzzle `704-c6ad2d19` in `netbout-web/src/test/java/com/netbout/rest/TkInboxTest.java:46-48` has to be resolved: Test case for search bouts of TkInbox should be added, e.g. response should have filtered bouts by search term... The puzzle was created by erimerturk on 20-Jul-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.0` to this issue, let me know if there has to be something else

**Comment by dmzaytsev** [comment]
@karato please set milestone to 3.1

**Comment by karato** [comment]
> @karato please set milestone to 3.1

@dmzaytsev the milestone here is 3.1

**Comment by karato** [comment]
@sretenperic this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by karato** [comment]
@sretenperic the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

do not forget to remove the TODO puzzle from the source code

-30 added to your rating, at the moment it is: [-210](http://www.netbout.com/b/35464?open=rating)

**Comment by karato** [comment]
@hs3180 this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by karato** [comment]
@hs3180 the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch. -30 added to your rating, current score is: [-82](http://www.netbout.com/b/35610?open=rating)

**Comment by hs3180** [comment]
@karato 
`MkBout` can't work with TkInbox now because of #805.
I'm waiting for #805.

**Comment by hs3180** [comment]
@karato 
`MkAttachments` can't work because of #806.
I'm waiting for #806

**Comment by karato** [comment]
> @karato 
> `MkBout` can't work with TkInbox now because of #805.
> I'm waiting for #805.

@hs3180 yes, right, let's wait for #805

**Comment by karato** [comment]
> @karato 
> `MkAttachments` can't work because of #806.
> I'm waiting for #806 

@hs3180 yes, of course, we'll wait for #806

**Comment by karato** [comment]
@bdragan This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by bdragan** [comment]
@karato PR #821 has been merged to master.

**Comment by karato** [comment]
> @karato PR #821 has been merged to master.

@bdragan OK thanks

**Comment by bdragan** [comment]
@karato Please close this issue.

**Comment by dmzaytsev** [comment]
@bdragan puzzle tickets like this one will close automatically when the puzzle will be removed from the code base. You didn't remove the puzzle  in PR #821.  Both @pinaf and me have missed this mistake. Please create a new PR and remove the original puzzle.

**Comment by bdragan** [comment]
@karato PR #821 and PR #825 have been merged to master. The issue can be closed.

**Comment by karato** [comment]
@dmzaytsev We are done here, thanks all

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://www.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@bdragan 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >The ticket describes one specific problem and provides a single solution.
 
 Two PRs were created for this issue. Please try to follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by bdragan** [comment]
@elenavolokhova Thanks, I confirm.

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by elenavolokhova** [comment]
@bdragan Thanks!

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by karato** [comment]
@bdragan I added 10 mins to @elenavolokhova (for QA review) in transaction 68845867

Much obliged! I have added **30 mins** to your account in payment "68845872", 303 hours and 23 mins spent

+30 added to your rating, current score is: [+233](http://www.netbout.com/b/35709?open=rating)
