### ISSUE TITLE
Preview tab doesn't work at all

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#749]
I tried to write some text in the message window (http://snapshot.netbout.com/b/25)
and click `Preview` tab, but nothing happens.

Url was changed to `http://snapshot.netbout.com/b/25#preview`.

Not sure if it's a bug or not implemented yet. Didn't found any task or puzzle for that.

**Comment by dmzaytsev** [comment]
@longtimeago Preview functionality has been implemented. It works fine..
Maybe you catched a browser specific issue?
Let me know your environment please

**Comment by longtimeago** [comment]
@dmzaytsev sure
Chrome Version 43.0.2357.134 (64-bit) Ubuntu 14.04
same as
FF 39.0 Ubuntu 14.04

**Comment by dmzaytsev** [comment]
@longtimeago I just opened Preview on latest Chrome (Version 44.0.2403.107 (64-bit)) on Ubuntu 14.04
![image](https://cloud.githubusercontent.com/assets/9972909/8895226/dae81cc0-33ea-11e5-86f9-4170744d7142.png)

any idea how a developer can reproduce the issue?

**Comment by longtimeago** [comment]
@dmzaytsev humm ... it works from my home PC now ... gonna check ones again from work tomorrow

**Comment by dmzaytsev** [comment]
@longtimeago ping

**Comment by longtimeago** [comment]
@dmzaytsev I've found the cause.
Corporate firewall blocks call to this resource for some reason
``` http://yuku-t.com/jquery-textcomplete/media/javascripts/jquery.textcomplete.js ```
It causes errors in browser console

**Comment by longtimeago** [comment]
@dmzaytsev It would be really cool to load it from some other places ... or copy in project resources

**Comment by dmzaytsev** [comment]
@longtimeago you're right, we have the puzzle #723 for it
anyway thanks you for reporting

**Comment by longtimeago** [comment]
@dmzaytsev thank you
