### ISSUE TITLE
TkInvite.java:119-124: Invited user should receive an...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#751]
Puzzle `602-3825bd3b` in `netbout-web/src/main/java/com/netbout/rest/bout/TkInvite.java:119-124` has to be resolved: Invited user should receive an email message with a text like this 'You are invited into the Netbout click on the link to register' and the link should be `http://www.netbout.com/b/

?invite= ` where `invite-key` is the encrypted urn. We can use `CcAES` from Takes project.... The puzzle was created by Endrigo Antonini on 20-Jul-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.0"

**Comment by karato** [comment]
@mstzn36 could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by karato** [comment]
@mstzn36 the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch... -30 added to your rating, at the moment it is: [-45](http://www.netbout.com/b/35470?open=rating)

**Comment by mstzn36** [comment]
@karato PR #769  ready for review.

**Comment by karato** [comment]
> @karato PR #769  ready for review.

@mstzn36 OK, thanks, will take a look soon

**Comment by dmzaytsev** [comment]
@mstzn36  I would suggest ask more time  ASAP 
http://www.teamed.io/policy.html#10

**Comment by mstzn36** [comment]
@dmzaytsev I forgot about that and i lose -30 point for nothing :(

**Comment by karato** [comment]
@dmzaytsev there is a puzzle in this code `751-6f10d03b`/#775, we'll resolve it later

**Comment by karato** [comment]
@dmzaytsev Closing, thanks all

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thanks a lot ;)

**Comment by karato** [comment]
@mstzn36 10 mins was added to the account of @ypshenychka (for QA review), in transaction 63939818... Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-1WX43412YU091532F`, total time was 479 hours and 53 mins... +30 to your rating, your total score is [-15](http://www.netbout.com/b/35470?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `751-6f10d03b`/#775 originated from here solved

**Comment by 0pdd** [comment]
@karato the only puzzle [#unknown]() is solved here.
