### ISSUE TITLE
pom.xml:58-58: Current version of Takes doesn't...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#753]
Puzzle `703-ca5668ad` in `netbout-web/pom.xml:58-58` has to be resolved: Current version of Takes doesn't support... The puzzle was created by Endrigo Antonini on 4-Aug-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by dmzaytsev** [comment]
@antonini I guess we don't need this ticket anymore, right ?
https://github.com/yegor256/takes/issues/372#issuecomment-136180325

**Comment by antonini** [comment]
@dmzaytsev Yeap.

**Comment by dmzaytsev** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@karato I just removed the puzzle from the code. we don't need this anymore

**Comment by karato** [comment]
@dmzaytsev The task is done, thanks all, I am closing it
