### ISSUE TITLE
User should be able to delete an attachment

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#754]
Netbout should allow an user to delete an attachment from a bout using web interface.

**Comment by karato** [comment]
@dmzaytsev dispatch this issue please

**Comment by dmzaytsev** [comment]
@antonini  I think the user should be able delete an attachment If there are no comments sent later by other users. We won't lost the content in this case, and will give ability to fix some mistakes.
The deletion of the attachment should be logged by posting a message like `the attachment <name> deleted` into the bout.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@antonini I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@antonini thanks for the report, I topped your acc for 15 mins, payment ID `AP-05282870WN448321W`

**Comment by karato** [comment]
@bdragan do this task

**Comment by bdragan** [comment]
@antonini Attachment deletion is already supported ([`TkDelete`](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/bout/TkDelete.java)).

Could you please provide more details about what is required in this issue regarding attachments deletion? Thanks!

**Comment by antonini** [comment]
@bdragan I updated the description. Also, take a look on what @dmzaytsev [said](#issuecomment-129173355)!

**Comment by bdragan** [comment]
@antonini Thanks. How can I verify that there are no messages posted to the bout after the attachment is created? Should we introduce a new field in the `Attachment`, like upload date or similar?

**Comment by antonini** [comment]
@bdragan You should ask @dmzaytsev. He is the architect.

**Comment by dmzaytsev** [comment]
@bdragan I just created the ticket #839
would you like to do that ticket?
let me know if so

**Comment by dmzaytsev** [comment]
@karato we are waiting for #839

**Comment by bdragan** [comment]
@dmzaytsev Sure, please assign #839 to me.

**Comment by karato** [comment]
> @karato we are waiting for #839 

@dmzaytsev yes, waiting for #839

**Comment by karato** [comment]
@antonini #839 is closed, it was an impediment

**Comment by antonini** [comment]
@karato, Unfortunately I was removed from the project and I don't know why until now. :(

**Comment by karato** [comment]
> @karato, Unfortunately I was removed from the project and I don't know why until now. :(

@antonini I see

**Comment by karato** [comment]
@bdragan check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 to your rating, your total score is [-30](http://www.netbout.com/b/35709?open=rating)

**Comment by karato** [comment]
@bdragan it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... added -60 to your rating, now it is equal to [-120](http://www.netbout.com/b/35709?open=rating)

**Comment by karato** [comment]
@ail-man this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)
