### ISSUE TITLE
Add method of Aliases class should return an Alias instead of void.

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#755]
Add method on Aliases interface return void. Instead of that it should return an instance of the recent created Alias.

This will avoid to instantiate an RqAlias to retrieve the desired alias.

That situation can be seen on the following peace of code:

https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/bout/TkInvite.java#L135

**Comment by karato** [comment]
@dmzaytsev please pay attention to this issue

**Comment by dmzaytsev** [comment]
@yegor256 I'm not sure we can change any spi interface, am I right?

**Comment by yegor256** [comment]
@dmzaytsev why not? we can change the SPI, but have to do it carefully. in this case I don't see anything bad in this change. do you?

**Comment by dmzaytsev** [comment]
@yegor256 I agree with this change

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@antonini I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@antonini thank you for reporting this, I added 15 mins to your acc, transaction `AP-3SU73540EW158083J`

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by karato** [comment]
> @karato assign me to this please

@dmzaytsev the task is yours, please proceed

**Comment by dmzaytsev** [comment]
@antonini fixed in #818 please close if alright

**Comment by antonini** [comment]
@dmzaytsev Looks good.

**Comment by karato** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://www.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thanks for the review and a good remark

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `67932499`

**1 hour** was added to your account, many thanks for your contribution (payment 67932514)! The task took 8 hours and 37 mins.

the bonus for fast delivery (m=517)

+60 to your rating, your total score is [+1488](http://www.netbout.com/b/35166?open=rating)
