### ISSUE TITLE
notification/logging about the attachment uploading

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#756]
at the moment uploading an attachment into the bout non loggable, participants of the bout don't get the notification about it. Let's post a message into the bout after uploading the attachment.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@dmzaytsev thank you for reporting this, I added 15 mins to your acc, transaction `62638349`

**Comment by karato** [comment]
@bdragan do this task

**Comment by bdragan** [comment]
@dmzaytsev PR #837 has been merged. The issue can be closed.

**Comment by dmzaytsev** [comment]
@bdragan thanks!

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you

**Comment by karato** [comment]
@bdragan just added 10 mins to @elenavolokhova (for QA), payment ID is `70622540`

I added **30 mins** to your account, many thanks for working with the project! The completion time here was 70622547.

added +30 to your rating, now it is equal to [+421](http://www.netbout.com/b/35709?open=rating)
