### ISSUE TITLE
Not showing charts of "Rating" and "Speed".

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#759]
When accessing "rating" and "speed" charts are not been displayed.

Below there is an screen shot that i took.

![screen shot 2015-08-10 at 7 46 13 pm](https://cloud.githubusercontent.com/assets/209396/9186290/b295d7ca-3f99-11e5-87b4-eb22193c1f59.png)

**Comment by dmzaytsev** [comment]
@antonini it's not in scope of this project. Submit such issues inside the netbout

**Comment by antonini** [comment]
@dmzaytsev
