### ISSUE TITLE
Not possible to remove a user from a bout if he has a long name and is not the last one

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#760]
It is not possible to remove a user, that has a long name, from a bout if is not the last one.

When you try to put the mouse cursor on top of the "x" button it hides current username and show the next one.

Below there is an image that represents the situation that I'm describing.

![screen shot 2015-08-10 at 8 27 45 pm](https://cloud.githubusercontent.com/assets/209396/9186789/7b1d35c6-3f9f-11e5-8470-576ace4c41da.png)

**Comment by dmzaytsev** [comment]
@antonini kick-out feature deprecated. it will be removed soon
https://github.com/yegor256/netbout/issues/634#issuecomment-111782630

**Comment by antonini** [comment]
@dmzaytsev Ok.
