### ISSUE TITLE
User should be able to change his picture (avatar)

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#761]
User should be able to change his picture (avatar) or it should use external systems such as www.gravatar.com.

**Comment by dmzaytsev** [comment]
@antonini right now  Netbout stores url to user's picture. e.g. if you login via github you can change your picture in your Github profile. Is this not enough? 
though we can allow to use www.gravatar.com or another external system...

**Comment by antonini** [comment]
My account on github has picture but my user on netbout doesn't.

If I inspect generated HTML I see that netbout is using the following URL as my picture.
http://img.netbout.com/unknown.png

**Comment by dmzaytsev** [comment]
@antonini okay.
Gravatar uses the email as the key for the avatar image, right?
we can add a check-box to user's profile and if it checked we will put gravatar's url instead github
if the check-box unchecked we will request the picture from github again

**Comment by antonini** [comment]
@dmzaytsev Agree.

**Comment by dmzaytsev** [comment]
@karato it's a vald bug

**Comment by antonini** [comment]
@karato Any progress over here?

**Comment by karato** [comment]
> @karato it's a vald bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@antonini attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@antonini thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-8JD47947GK606493J`

**Comment by karato** [comment]
@mkordas this is your task

**Comment by mkordas** [comment]
@karato I need more time here

**Comment by karato** [comment]
> @karato I need more time here

@mkordas yes, take your time, thanks for letting me know

**Comment by mkordas** [comment]
@karato please assign someone else

**Comment by karato** [comment]
> @karato please assign someone else

@mkordas 30 points deducted from your rating

**Comment by karato** [comment]
> @karato please assign someone else

@mkordas no problem, I will try to find somebody else

**Comment by karato** [comment]
@danff could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by danff** [comment]
@karato Need more time here

**Comment by karato** [comment]
> @karato Need more time here

@danff yeah, I know, take your time
