### ISSUE TITLE
User's autocomplete is not filtering after typing a char

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#764]
After I type an @ and start to type an user name, the list not filter available names.

Image below show that autocomplete shows all options. I moved the cursor to the user that it should just be visible.
![image](https://cloud.githubusercontent.com/assets/209396/9236624/511e4cb4-411c-11e5-99fa-3cf3d0b92a25.png)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by antonini** [comment]
@karato Any progress over here?

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@antonini there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@antonini thanks for this report, I added 15 mins to your account, in transaction `AP-78160544EC304761S`

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task
