### ISSUE TITLE
Page not found when accessing www.netbout.com

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#765]
Try www.netbout.com and see
```
page not found
```
as a body.
Browser url automatically changed to
```
http://www.netbout.com/,PsCookie=278DDFDD-6367071B-1A434902 .....
```

Reproduces in Chrome last version on Ubuntu
Works fine in FF

**Comment by dmzaytsev** [comment]
@longtimeago we have already #716 for this 
I would suggest workaround: to clear cookies for www.netbout.com

**Comment by longtimeago** [comment]
@dmzaytsev sorry for duplicating

**Comment by dmzaytsev** [comment]
@longtimeago no problem
