### ISSUE TITLE
MarkdownTest broken on windows

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#767]
We have a broken test on Windows
```
Failed tests:
  MarkdownTest.breaksSingleLine:170
Expected: "<p>line1\n<br />\nline2</p>\n<p>line3</p>"
     but: was "<p>line1\r\n<br />\r\nline2</p>\r\n<p>line3</p>"
```
let's fix it

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@dmzaytsev thanks for reporting! I topped your account for 15 mins, transaction 63497618

**Comment by dmzaytsev** [comment]
@yegor256 will the [new paragraph](http://www.teamed.io/policy.html#34) be applied?

**Comment by dmzaytsev** [comment]
@karato assign @mkordas to this ticket please

**Comment by karato** [comment]
> @karato assign @mkordas to this ticket please

@dmzaytsev OK @mkordas please go ahead, this task is yours

**Comment by karato** [comment]
@mkordas I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by mkordas** [comment]
@karato I've completed this task in #870, sorry for no message above

**Comment by karato** [comment]
> @karato I've completed this task in #870, sorry for no message above

@mkordas thanks, please don't forget to report PR number in each ticket you complete

**Comment by yegor256** [comment]
@karato pls add extra 30 mins to @mkordas

**Comment by karato** [comment]
@rultor @dmzaytsev please take a look, rultor closed it automatically

**Comment by karato** [comment]
> @karato pls add extra 30 mins to @mkordas 

@yegor256 I've sent 30 mins extra to @mkordas in transaction ID "5672a55e000f564b5e0002c9"

**Comment by karato** [comment]
@mkordas do this task, 30 mins is budget

**Comment by mkordas** [comment]
>@mkordas do this task, 30 mins is budget

@karato I did this task in #870

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good.

**Comment by karato** [comment]
> @karato Looks good.

@elenavolokhova many thanks

**Comment by karato** [comment]
@mkordas paied 10 mins to @elenavolokhova for QA review (payment ID is `72469393`)

**1 hour** sent to your balance (ID `56745a65129ba5381a000065`), many thanks! It took 2 hours and 27 mins.

the bonus for fast delivery (m=147)

+60 added to your rating, current score is: [+510](http://www.netbout.com/b/36080?open=rating)
