### ISSUE TITLE
EmMessages.java:137-141: Header `Reply-To` should be added...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#770]
Puzzle `692-1caba32d` in `netbout-web/src/main/java/com/netbout/email/EmMessages.java:137-141` has to be resolved: Header `Reply-To` should be added to an outgoing email. Format is crypt-string@reply.netbout.com where crypt-string is user-urn|bout-number Use EmCatch.encrypt() to encrypt the string see #692 and EmActionTest for additional info... The puzzle was created by Dmitry Zaytsev on 20-Aug-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by exper0** [comment]
@dmzaytsev ready to take this

**Comment by dmzaytsev** [comment]
@karato assign @exper0 please

**Comment by karato** [comment]
> @karato assign @exper0 please
> 

@dmzaytsev OK @exper0 please go ahead, this task is yours

**Comment by exper0** [comment]
@dmzaytsev please look at #946 and check if I understand you correctly.
@karato please assign reviewer

**Comment by exper0** [comment]
@karato PR #946 is merged. Could you close the request?

**Comment by exper0** [comment]
@karato PR #946 is merged. Could you close the ticket?

**Comment by exper0** [comment]
@dmzaytsev @karato ping

**Comment by exper0** [comment]
@dmzaytsev who should close this puzzle issue - you or @karato ?

**Comment by dmzaytsev** [comment]
@exper0 @karato will close the puzzle
I'm not able to close puzzle tickets

**Comment by karato** [comment]
@dmzaytsev The issue should be closed..

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@exper0 I added 10 mins to @ypshenychka (for QA review) in transaction 75185381

Many thanks! **1 hour** were added to your account in Transaction ID `AP-4XG27124F0955872C` (task took 23 hours and 46 mins)

the bonus for fast delivery (m=1426)

+60 to your rating, your total score is [+391](http://www.netbout.com/b/36185?open=rating)
