### ISSUE TITLE
Integration test should be able run on snapshop netbout.com

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#772]
Integration test should be able run on http://snapshop.netbout.com.
like this
> $ mvn clean install -Dnetbout.token=${cookie_value} -Dnetbout.url=http://snapshot.netbout.com

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@dmzaytsev thanks a lot for reporting, **30 mins** added to your acc, pmt ID `63560585`

**Comment by dmzaytsev** [comment]
@karato this issue is invalid

**Comment by karato** [comment]
> @karato this issue is invalid

@dmzaytsev sure, thanks, I added "invalid" label to it
