### ISSUE TITLE
Integration test creates a lot of new bouts

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#773]
I tried to run integration tests. It was in running state ~ 10min then I terminated it.
Later I have opened netbout.com and saw a lot of new bouts

![image](https://cloud.githubusercontent.com/assets/9972909/9429461/2336ed34-49ea-11e5-9540-f9a3bbc68dac.png)

Let's fix it

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@dmzaytsev since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@dmzaytsev thanks for this report, I added 30 mins to your account, in transaction `63547205`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will try to find someone else
