### ISSUE TITLE
Netbout is down (Application Error)

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#774]
I'm trying to access netbout and server is taking a long time.
Sometimes it logs in, and sometimes it shows the screen bellow.

![image](https://cloud.githubusercontent.com/assets/209396/9470488/984fa906-4b22-11e5-9652-4c13d9ee62a1.png)

**Comment by dmzaytsev** [comment]
@antonini Thanks for reporting. Maybe some hosting problem...
@yegor256 Could you check the logs please?

**Comment by dmzaytsev** [comment]
@antonini I think you could close the ticket 
I believe it was a temporary hosting related issue

**Comment by antonini** [comment]
@dmzaytsev Yeap. working fine for me. Tks!
