### ISSUE TITLE
Netbout client integration tests should be able to run on snapshop

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#776]
Netbout-client integration tests should be able run on the snapshot instance.
Let's allow to set target server via Maven variable like this
```
$ mvn clean install -Dnetbout.token=XXXX -Dnetbout.url=http://snapshot.netbout.com
```

**Comment by dmzaytsev** [comment]
@karato this is valid bug

**Comment by karato** [comment]
> @karato this is valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@dmzaytsev many thanks, **30 mins** added to your acc for reporting this bug, pmt ID `63918371`

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev thanks, I added "urgent" label

**Comment by dmzaytsev** [comment]
@antonini could you pickup this task?

**Comment by karato** [comment]
@sretenperic it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by karato** [comment]
@hs3180 please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by hs3180** [comment]
@dmzaytsev unit test failed in netbout-client when I run

    mvn clean install -Dnetbout.token=xxx

It showed me that:

    -------------------------------------------------------------------------------
    Test set: com.netbout.client.RtAliasITCase
    -------------------------------------------------------------------------------
    Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.069 sec <<< FAILURE! - in com.netbout.client.RtAliasITCase
    updateAndRetrieveEmail(com.netbout.client.RtAliasITCase)  Time elapsed: 1.069 sec  <<< FAILURE!
    java.lang.AssertionError: 
    Expected: is "alias633356285@example.com"
         but: was "xxx@gmail.com"
    	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
    	at com.netbout.client.RtAliasITCase.updateAndRetrieveEmail(RtAliasITCase.java:62)

I have changed my token and email to `xxx`

**Comment by dmzaytsev** [comment]
@hs3180 I think #737 is the reason
Let's try ignore this test

**Comment by hs3180** [comment]
@dmzaytsev 
I added netbout.url property functionality, but I found that `RtFriendsITCase` test will get stuck when there is no alias called `alex` in a local snapshot.
By using the method mentioned in #584 , a fake `alex` user added and passed all the client integration tests.
Should I document it in `README.md` or fire a new ticket about it?

**Comment by dmzaytsev** [comment]
@hs3180 I think it's the bug #773
I can assign you to that ticket if you want
we will discuss there how we can fix this bug

**Comment by dmzaytsev** [comment]
@hs3180 if you're ready please create a new pull request with netbout.url property functionality

**Comment by hs3180** [comment]
@dmzaytsev PR #790 created, please review.

**Comment by hs3180** [comment]
@dmzaytsev PR #790 created. Please review it.

**Comment by hs3180** [comment]
@dmzaytsev 

You can run the integration tests as follow while a local netbout server is running on 8080:

    mvn clean install -Dnetbout.token=XXXX -Dnetbout.url=http://localhost:8080

But there is a more step you should do. 

*open this URL on your local server __http://localhost:8080/?PsByFlag=fake-user&urn=urn:test:12345__ and give the user a alias __alex__*

It is because `RtFriendsITCase` tries to find a friend named **alex** and operate on him(invite and kick), integration test will always get stuck here unless you add a **alex** or skip this test.

**Comment by dmzaytsev** [comment]
@hs3180 you're right, sorry
please submit a new ticket about this bug

**Comment by dmzaytsev** [comment]
@hs3180 just for information, you should ask the ticket reporter to close the ticket and mention the pull request that fixed the issue

**Comment by hs3180** [comment]
thank you for your remind.

PR #790 solved this ticket. @dmzaytsev please close this.

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks a lot

**Comment by karato** [comment]
@hs3180 I added 10 mins to @elenavolokhova (for QA review) in transaction 65455823; thanks, I just added **38 mins** to your account, payment `AP-61A43367SX3811819`, 52 hours and 50 mins spent; m=3170, that's why a bonus here for fast delivery; +38 to your rating, your total score is [+53](http://www.netbout.com/b/35610?open=rating)
