### ISSUE TITLE
Kick a user should be using a DELETE request and not using a GET

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#780]
Netbout uses a GET request to kick users from bout.

Actions that remove things from database or relationship should be using a DELETE method and not a GET.

**Comment by dmzaytsev** [comment]
@antonini you're right but kick-out feature is deprecated. it will be removed soon https://github.com/yegor256/netbout/issues/634#issuecomment-111782630

**Comment by antonini** [comment]
@dmzaytsev Ok.
