### ISSUE TITLE
/start: multiple post arguments

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#784]
see #610 

Let's make it possible to use multiple `post` arguments:

```
/start?post=How+are+you&post=I+am+fine
```

This request should create a new bout and post **two** messages into it. At the moment I only see the first message.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug
> 

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-ec9c1c23

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by karato** [comment]
> @karato assign me to this please

@dmzaytsev this task is yours now, please proceed

**Comment by dmzaytsev** [comment]
@karato please see PR #785

**Comment by dmzaytsev** [comment]
@yegor256 fixed in PR #785 close the ticket please if alright

**Comment by yegor256** [comment]
@dmzaytsev let's release 2.17.1 with this feature on board?

**Comment by yegor256** [comment]
@dmzaytsev thanks for the fix!

**Comment by karato** [comment]
> @karato please see PR #785

@dmzaytsev thank you, I will check it

**Comment by dmzaytsev** [comment]
@yegor256 done

> yegor256 commented 3 hours ago
> @dmzaytsev let's release 2.17.1 with this feature on board?

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@alex-palevsky Quality is good here.

**Comment by dmzaytsev** [comment]
@elenavolokhova,  @karato is PM here :)

**Comment by elenavolokhova** [comment]
@dmzaytsev ooops :) Thanks!

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 65366512. done, I added **1 hour** in payment `65366521`, 3 hours and 47 mins spent to complete this. the bonus for fast delivery (m=227). +60 added to your rating, current score is: [+1322](http://www.netbout.com/b/35166?open=rating)
