### ISSUE TITLE
unable to logon via Google

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#786]
when I tried to logon via Google I got exception
see the screenshot below 
![image](https://cloud.githubusercontent.com/assets/9972909/9884906/d0844874-5bfb-11e5-8ef7-af554474938c.png)

**Comment by dmzaytsev** [comment]
@karato this is valid bug

**Comment by karato** [comment]
> @karato this is valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by yegor256** [comment]
@dmzaytsev I see this in logs:

```
[ERROR] 269a496 com.netbout.rest.TkAppFallback: java.lang.AssertionError: HTTP response status is not equal to 200: 404 Not Found [https://accounts.google.com/o%2Foauth2%2Ftoken] Alt-Svc: quic=":443"; p="1"; ma=604800 Transfer-Encoding: chunked Date: Tue, 15 Sep 2015 07:06:23 GMT X-XSS-Protection: 1; mode=block Expires: Fri, 01 Jan 1990 00:00:00 GMT Alternate-Protocol: 443:quic,p=1 Content-Type: text/html; charset=utf-8 Server: GSE X-Content-Type-Options: nosniff Pragma: no-cache Cache-Control: no-cache, no-store, max-age=0, must-revalidate <!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 404 (Not Found)!!1</title><style>*{margin:0;p...
```

**Comment by karato** [comment]
@dmzaytsev many thanks, **30 mins** added to your acc for reporting this bug, pmt ID `65326527`

**Comment by dmzaytsev** [comment]
@yegor256 I wonder why it use invalid link `https://accounts.google.com/o%2Foauth2%2Ftoken`
it has been fixed already in `0.23.3`
https://github.com/yegor256/takes/commit/8eb99ecc0f72c3b30a170bc56f19a00588bab985

**Comment by yegor256** [comment]
@dmzaytsev it looks strange to me too

**Comment by yegor256** [comment]
@dmzaytsev it's a bit annoying to have this in production... can we make this urgent?

**Comment by dmzaytsev** [comment]
@yegor256 can we force this https://github.com/yegor256/takes/issues/383 ?

**Comment by yegor256** [comment]
@dmzaytsev I will try...

**Comment by dmzaytsev** [comment]
@yegor256  the issue resolved, Google login works now
I'm closing the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!
