### ISSUE TITLE
incorrect value for `unread messages` in favicon

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#787]
there is  incorrect value for `unread messages` in favicon.
the value not be changed when the message has been read.
I think this line in `CdInbox.unread()`
`@Cacheable(lifetime = Tv.FIVE, unit = TimeUnit.HOURS)` is the reason
we should clear the cache when a message been read.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@dmzaytsev attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@dmzaytsev thanks for reporting! I topped your account for 30 mins, transaction 65328765

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev OK, I put "urgent" label here

**Comment by karato** [comment]
@mkordas this is your task

**Comment by mkordas** [comment]
@dmzaytsev can you assist me with this issue? I have several questions:
* What class should be modified? 
* How cache can be cleaned or refreshed?
* How to identify whether message has been read or not?

**Comment by dmzaytsev** [comment]
@mkordas there is the subject of the ticket...

**Comment by mkordas** [comment]
@dmzaytsev subject doesn't say anything different than issue description, but I looked into code and managed to come up with solution
@karato please see PR #874

**Comment by mkordas** [comment]
@karato @dmzaytsev this was done 3 days ago, please proceed

**Comment by dmzaytsev** [comment]
@mkordas you should ask the ticket reporter to close task and mention the PR that fixed the issue
it's needed to track tickets and to do the payment automatically

**Comment by mkordas** [comment]
@dmzaytsev as a ticket reporter please close this issue - it was implemented in #874

**Comment by karato** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thanks for the review

**Comment by karato** [comment]
@mkordas 10 mins was added to the account of @ypshenychka (for QA review), in transaction 72553523... I added **30 mins** to your account, many thanks for working with the project! The completion time here was 567803cfeb3fb64e940002f2.... +30 to your rating, your total score is [+660](http://www.netbout.com/b/36080?open=rating)
