### ISSUE TITLE
new users don't have avatars

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#788]
All new users I see in Netbout don't have avatars. I think it's some bug in our system. All other avatars work just fine, but new users have "unknown" images.

**Comment by karato** [comment]
@yegor256 tagged this issue with "indie"

**Comment by karato** [comment]
@yegor256 I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-3498d692

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by yegor256** [comment]
@karato assign @dmzaytsev to this pls

**Comment by karato** [comment]
> @karato assign @dmzaytsev to this pls

@yegor256 OK @dmzaytsev please proceed, this task is yours

**Comment by dmzaytsev** [comment]
@yegor256 I need your help here. There is a problem to save an avatar for a new user into the database. I can't expect Dynamo but I guess the problem is here. It would be great If you can check attribute `photo` for any new user which have avatar on his github account. So if if will be empty or invalid we on the right way.
Also I can't find any usage of `DyAlias.photo(URI)`. It has to save the avatar link into Dynamo. Could you remember how exactly you have implemented storing avatar from the `#Identity.properties()` into Dynamo at the time?

**Comment by yegor256** [comment]
@dmzaytsev hm... I also can't find it, but it has to be in `RqAlias`. It has to work like this:

```java
public final class RqAlias extends RqWrap {
    public Alias alias() throws IOException {
        final Aliases aliases = this.user().aliases();
        if (!aliases.iterate().iterator().hasNext()) {
            throw new RsForward(
                HttpURLConnection.HTTP_MOVED_TEMP,
                "/login/start"
            );
        }
        final Alias alias = aliases.iterate().iterator().next();
        if (alias.photo().equals(Alias.BLANK)) {
            alias.photo(
                URI.create(
                    new RqAuth(this).identity().properties().get("avatar")
                )
            );
        }
        return alias;
    }
}
```

But it's not always "avatar". We should check `identity.urn()`. If it starts with "urn:github" - it's "avatar". If it's "urn:google" - it's "photo", if it's "urn:facebook" - it's something else. Check sources of Takes.

**Comment by yegor256** [comment]
@dmzaytsev I don't know what happened to this code... I suspect it just got lost after the migration to Takes. No idea...

**Comment by dmzaytsev** [comment]
@karato we need more time here

**Comment by karato** [comment]
> @karato we need more time here

@dmzaytsev of course, thanks for letting me know, take your time

**Comment by dmzaytsev** [comment]
@karato please see PR #831

**Comment by karato** [comment]
> @karato please see PR #831

@dmzaytsev thank you, I will check it

**Comment by dmzaytsev** [comment]
@yegor256 the issue fixed in PR#831
Please close if alright

**Comment by dmzaytsev** [comment]
@yegor256 I just checked on http://snapshot.netbout.com/
and I see that the avatar updated.
so we can release it

**Comment by yegor256** [comment]
@dmzaytsev thanks! let's release

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thank you

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `69562702`

Thanks for your contribution, **30 mins** was added to your account, payment ID is `69562707`, 270 hours and 59 mins spent total

+30 added to your rating, current score is: [+1281](http://www.netbout.com/b/35166?open=rating)
