### ISSUE TITLE
Not receiving all messages in a subscribed bout

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#792]
In the netbout conversation below, I'm subscribed to it from the moment `@alice` mentions me:

![netbout - copy](https://cloud.githubusercontent.com/assets/1917892/9960732/ec7231ea-5e4e-11e5-8ecb-7cf1d755db85.PNG)

However, I only ever received notifications for messages sent by `@alice`. The subsequent messages posted by `@shelan` did not trigger any email notifications. The message highlighted in red are the ones that had corresponding notifications (the first one in my email is an older message from `@alice` that's not visible in the Netbout screenshot:

![gmail - copy](https://cloud.githubusercontent.com/assets/1917892/9960734/ef207794-5e4e-11e5-818b-bf0e77e5488f.PNG)

I'm not certain that it was because I was explicitly mentioned by `@alice` but not by `@shelan`, but I expected to see all messages by virtue of being subscribed to the conversation.

**Comment by dmzaytsev** [comment]
@carlosmiranda I think it duplicates #695
Are you agree?

**Comment by carlosmiranda** [comment]
@dmzaytsev yup you're right thanks. Closing...

**Comment by dmzaytsev** [comment]
@carlosmiranda `2.18` just released
this feature should works
