### ISSUE TITLE
View/Change subscription status from home page

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/netbout#793]
When I enter a conversation, I see a bell icon next to the title which tells me whether I'm subscribed to it or not. I can also click it to toggle the subscription status:

![netbout-inbout](https://cloud.githubusercontent.com/assets/1917892/9961056/03f38222-5e51-11e5-9a14-e151d5041db3.PNG)

However, I can't see which conversations I'm subscribed to from the home page:

![netbout-home](https://cloud.githubusercontent.com/assets/1917892/9961052/01389e50-5e51-11e5-933f-bf79ea41e922.PNG)

It would be good to include this feature on the home page as well. This way, I can see quickly which conversations I'm subscribed to. Even better would be to allow toggling of the subscription from the home page as well.

**Comment by dmzaytsev** [comment]
@carlosmiranda thanks for reporting

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@carlosmiranda milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@carlosmiranda thanks a lot for reporting, **15 mins** added to your acc, pmt ID `65412302`

**Comment by karato** [comment]
@exper0 this is your task

**Comment by exper0** [comment]
@carlosmiranda @karato done, PR #920

**Comment by carlosmiranda** [comment]
@exper0 let's wait for PR to be merged

**Comment by exper0** [comment]
@carlosmiranda PR #920 is merged and closed

**Comment by carlosmiranda** [comment]
@exper0 Excellent, thanks!

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good :)

**Comment by karato** [comment]
@exper0 added 10 mins to @elenavolokhova, for QA review, payment code is `74579212`

paid, thanks, added **30 mins** to your account, payment `AP-7GY47672AE737203N`, 118 hours and 50 mins was spent

+30 added to your rating, at the moment it is: [+301](http://www.netbout.com/b/36185?open=rating)
