### ISSUE TITLE
document default encoding issue

### ISSUE THREAD

**Issue by hs3180** [yegor256/netbout#794]
running netbout-web unit tests in simplified chinese windows will cause following failure:

      <testcase name="redirectsToReturnCookie" classname="com.netbout.rest.TkAppTest" time="0.417">
        <error message="default encoding is GBK" type="java.lang.IllegalStateException"><![CDATA[java.lang.IllegalStateException: default encoding is GBK
    	at com.netbout.rest.TkApp.make(TkApp.java:120)
    	at com.netbout.rest.TkApp.<init>(TkApp.java:107)
    	at com.netbout.rest.TkApp.<init>(TkApp.java:97)
    ...

changing system language setting will only make **GBK** change to other non-UTF8 encoding, and unit tests will also be failed. 

Why not add tips about default encoding problem like what [takes](https://github.com/yegor256/takes#how-to-contribute) do in its `README`

> If your default encoding is not UTF-8, some of unit tests will break. This is an intentional behavior. To fix that, set this environment variable in console (in Windows, for example):
> 
> SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@hs3180 since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@hs3180 thanks for reporting! I topped your account for 15 mins, transaction AP-07606277AJ7491150

**Comment by karato** [comment]
@prahladyeri please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by prahladyeri** [comment]
@karato I've clubbed this in PR #921. See my latest commit [2c070e6 - fix for issue #794; Added note about utf-8 related problem pertaining to unit tests in README.md](https://github.com/yegor256/netbout/commit/2c070e69c0123ac269c5a59908f9bcdd1c46e83f) which provides resolution to this.

**Comment by dmzaytsev** [comment]
@prahladyeri one ticket - one PR
please create a new PR for your fix

**Comment by prahladyeri** [comment]
@dmzaytsev Does that mean I can't create new PR when existing is open? If I commit anything it will go to the latest PR. If I created PR for this issue (750) and I want to push anything for the other issue (750), how can I do that? All changes will be pushed to this new PR instead.

**Comment by dmzaytsev** [comment]
@prahladyeri I mean you have to create a separate PR for this ticket
and you can do it right now for sure
We prefer small PRs, each of them should fix only one issue

**Comment by dmzaytsev** [comment]
@prahladyeri yepp
a new branch for each issue

>EDIT: I guess one way is to create a separate branch for this issue, then use this new branch for the new PR instead of master branch. Is that what I should do?

**Comment by prahladyeri** [comment]
@dmzaytsev Sorry, I wasn't aware of that. I've reverted the `README.md` change from that PR, I'll create a separate PR for this issue.

**Comment by dmzaytsev** [comment]
@prahladyeri by the way you should change only Readme
not TkStart and pom.xml

**Comment by prahladyeri** [comment]
@dmzaytsev Apologies, I reverted changes in `TkStart.java` and `pom.xml`. I forked it from `master` branch which was already tainted with changes related to issue #750. Won't happen from next time as I'll create a separate branch for each issue instead of tainting the `master` branch.

**Comment by prahladyeri** [comment]
@hs3180 I've created PR #930 for this. Please close if the same resolves your issue.

**Comment by hs3180** [comment]
@prahladyeri thanks

**Comment by dmzaytsev** [comment]
@hs3180 @prahladyeri let's wait until PR be merged :)

**Comment by prahladyeri** [comment]
@hs3180 PR #930 is merged. Please have a look and close if this resolves the issue.

**Comment by hs3180** [comment]
@prahladyeri thank you

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@prahladyeri added 10 mins to @ypshenychka, for QA review, payment code is `75203799`; **30 mins** sent to your balance (ID `75203813`), many thanks! It took 289 hours and 45 mins.; +30 added to your rating, at the moment it is: [+135](http://www.netbout.com/b/36189?open=rating)
