### ISSUE TITLE
netbout-client integration test RtInboxITCase

### ISSUE THREAD

**Issue by hs3180** [yegor256/netbout#796]
RtInboxITCase fails when tests with an empty netbout account.

To reproduce the problem:
1. set up a local netbout-web
   
   `mvn clean install -Phit-refresh -Dport=8080`
2. find your token as in [README](https://github.com/yegor256/netbout#integration-tests)
3. run RtInboxITCase in netbout-client
   
   `cd netbout-client`
   `mvn -Dit.test=RtInboxITCase clean verify -Dnetbout.token=${your_token} -Dnetbout.url=http://localhost:8080`

**Comment by karato** [comment]
@dmzaytsev please do something about this issue

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@hs3180 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I will find someone else, no problem
