### ISSUE TITLE
Can't add an attachment with underscore

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#797]
Shouldn't it be possible to add and attachment with underscore, such as this one ```projects_evaluation.txt```?

Now I see a flash error ```invalid attachment name "projects_evaluation.txt" ```
It came from https://github.com/yegor256/netbout/blob/814170f92de98e2afefccf22217f7c924323e64a/netbout-web/src/main/java/com/netbout/dynamo/DyAttachments.java#L200

UPD: If it's by design, let's update error message to make it clear for the user what is the allowed symbols in the file name.

**Comment by yegor256** [comment]
@longtimeago it's by design. just `[a-z]+` names should be there, for simplicity

**Comment by longtimeago** [comment]
@yegor256 Then the error message should be more meaningful, so the user will figure out what's wrong with his file and correct it

**Comment by yegor256** [comment]
@longtimeago yes, agree

**Comment by dmzaytsev** [comment]
@yegor256 what's wrong if the underscore in the attachment name with will be allowed? People often use the underscore in file names..

**Comment by yegor256** [comment]
@dmzaytsev I think it's always possible to give a name without an underscore... especially in scope of one bout. or I'm wrong?

**Comment by dmzaytsev** [comment]
@yegor256 I guess you don't like an underscore, right? ))
of course it's possible...
someone uses underscores to break words in a filename, 
someone else uses  low/uppercase for same goal
Camel case vs snake case you know...

@longtimeago the message like below will be enough?
`invalid attachment name "projects_evaluation.txt". Attachment name should match  regex [a-zA-Z\.\-0-9]{3,100}`

**Comment by longtimeago** [comment]
@dmzaytsev I don't think someone is interested in our regexp :) It should be some user friendly message.

**Comment by yegor256** [comment]
@dmzaytsev yeah, I also think so... let's show something more user friendly..

**Comment by dmzaytsev** [comment]
@longtimeago `attachment name can contains letters in upper or lower case, numbers, dots, dashes` ?

**Comment by longtimeago** [comment]
@dmzaytsev kind of that

**Comment by dmzaytsev** [comment]
@longtimeago fixed in #799 please close the ticket

**Comment by longtimeago** [comment]
@dmzaytsev thanks
