### ISSUE TITLE
Missing page with DEV's statuses

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#800]
Sometimes developers are on vacation.
It's useful information for other developers/architects to plan their activities accordingly.
I propose to create a netbout page with statuses of each developer.
Kind of:
@longtimeago   away  (starting from ...)
@karato             available

**Comment by dmzaytsev** [comment]
@longtimeago this is out of the scope of the project, sorry

I would suggest to report this to http://www.netbout.com/b/35298
or direct to @yegor256

**Comment by longtimeago** [comment]
@dmzaytsev ok, no problem! Thanks
