### ISSUE TITLE
"Waiting" message showing unnecessarily

### ISSUE THREAD

**Issue by bguidolim** [yegor256/netbout#801]
When you access a bout with many messages that needs to be load with "endless scrolling" functionality and reach the bottom, the message "please, wait a second..." still showing even without more data to load.

Steps to reproduce:

  1 - Get a bout with many messages (mine has 23 messages)
  2 - Scroll to bottom
  3 - Wait loading
  4 - Reach the first bout's message
  5 - Look ate the bottom and you will see that the message still there

**Comment by dmzaytsev** [comment]
@karato this is valid bug

**Comment by karato** [comment]
> @karato this is valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@bguidolim since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@bguidolim thanks for the ticket, your account was topped for 15 mins, payment AP-1DB382714C4081947

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I will try to assign someone else
