### ISSUE TITLE
switch to an hourglass cursor when Netbout processes a request

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#803]
Sometimes when I click on Preview nothing happens for a while because request to netbout takes a long time.
Let's switch to an hourglass cursor when Netbout processes a request and then back to a normal cursor when the process has completed.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@dmzaytsev thank you for reporting this, I added 30 mins to your acc, transaction `66748676`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all
