### ISSUE TITLE
Gmail doesn't show  actions in emails from netbout

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#804]
Right now we can't see Gmail action in emails from Netbout because registration on Google not completed yet.

Need to fill out the registration form 
https://developers.google.com/gmail/markup/registering-with-google

Proper email body for sending to `schema.whitelisting+sample@gmail.com`
can be found here https://github.com/yegor256/netbout/pull/659#issuecomment-109174392
this email should be sent using production server SMTP credentials.

**Comment by dmzaytsev** [comment]
@karato it's valid bug

**Comment by dmzaytsev** [comment]
@karato please assign @yegor256 to this

**Comment by karato** [comment]
> @karato it's valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
> @karato please assign @yegor256 to this

@dmzaytsev yep, done. @yegor256 it is your task now

**Comment by karato** [comment]
@dmzaytsev thanks for the report, I topped your acc for 30 mins, payment ID `66784521`

**Comment by yegor256** [comment]
@dmzaytsev isn't it a duplicate of #546

**Comment by dmzaytsev** [comment]
@yegor256 #546 closed, we already add gmail action support to Netbout. But
it doesn't work properly, it's a bug. I guess something wrong with
registering on google . Only product owner can do this ticket, that's why I
asked to assign it to you.

**Comment by yegor256** [comment]
@dmzaytsev but we can't fix it at the moment, because Google doesn't accept our application. We have to send at least 100 emails per day to be qualified for this feature. I think I explained it already in #546

**Comment by dmzaytsev** [comment]
@karato this is invalid

**Comment by dmzaytsev** [comment]
@yegor256 Sorry, I hadn't knew about the restriction. You didn't tell me.
It looked like you forgot about filling the form. Sorry again
I'm  closing the ticket

**Comment by karato** [comment]
> @karato this is invalid

@dmzaytsev sure, thanks, I added "invalid" label to it
