### ISSUE TITLE
MkBout.java:103-105: MkBout's updated method hasn't be implemented yet

### ISSUE THREAD

**Issue by hs3180** [yegor256/netbout#805]
`updated` method in `MkBout` class always throws an `UnsupportedOperationException` now.

**Comment by dmzaytsev** [comment]
@hs3180 why do you need implementation of `MkBout.updated()`

**Comment by hs3180** [comment]
@dmzaytsev 
`TkInobx.source` retrieves bout information and builds sheets.
It needs `bout.updated()`.
When testing it, the `bout` is actually a `MkBout`, but `MkBout.updated()` only throws an `UnsupportedOperationException` right now.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@hs3180 there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@hs3180 thanks for tis bug, I topped your account for 15 mins, transaction `AP-9J9054174W551444M`

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev yep, it is yours, go ahead

**Comment by dmzaytsev** [comment]
@hs3180 the issue fixed in PR #964 please close the ticket

**Comment by hs3180** [comment]
@dmzaytsev thanks

**Comment by karato** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.
> 

@ypshenychka thank you

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @ypshenychka for QA review (payment ID is `75634386`)

**1 hour** was added to your account, many thanks for your contribution (payment 75634449)! The task took 2 hours and 12 mins.

there is a bonus for fast delivery (m=132)

+60 added to your rating, at the moment it is: [+2704](http://www.netbout.com/b/35166?open=rating)
