### ISSUE TITLE
MkAttachments.java:85-87: MkAttachments's unseen method hasn't be implemented yet

### ISSUE THREAD

**Issue by hs3180** [yegor256/netbout#806]
`unseen` method in `MkAttachments` class always throws an `UnsupportedOperationException` now.

<hr id='w'>

 - ~~`806-43ee63d7`/#827~~ (by )
 - `806-1e507f57`/#826 (by )

**Comment by dmzaytsev** [comment]
@hs3180 why do you need implementation of `MkAttachments.inseen()` ?

**Comment by hs3180** [comment]
@dmzaytsev 
`TkInobx.source` retrieves bout information and builds sheets.
It needs `bout.attachements().unseen()`.
When testing it, the bout is actually a `MkBout`.
`bout.attachements` will give me a `MkAttachments`.
`MkAttachments.unseen()` will only throws an `UnsupportedOperationException` right now.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@hs3180 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@hs3180 thanks for the report, I topped your acc for 15 mins, payment ID `AP-32C10218H0367811U`

**Comment by karato** [comment]
@hs3180 these 2 puzzles were created in this ticket: `806-1e507f57`/#826, `806-43ee63d7`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@hs3180 the last puzzle `806-1e507f57`/#826 solved

**Comment by 0pdd** [comment]
@hs3180 all 2 puzzles are solved here: [#unknown](), [#unknown]().
