### ISSUE TITLE
How to create a more accounts on local server

### ISSUE THREAD

**Issue by pecko** [yegor256/netbout#810]
@dmzaytsev 

I have created local server at http://localhost:8080 as described in README.
However, I couldn't (or don't know) create a more accounts.
There is only one account: tester
Is it possible create server similar to http://snapshot.netbout.com/ locally. It could sign up with google, github, facebook ...

**Comment by pecko** [comment]
@dmzaytsev 

This is related to my task: https://github.com/yegor256/netbout/issues/695
I'm not sure but it could be important: What database is used on http://snapshot.netbout.com/?

**Comment by dmzaytsev** [comment]
@pecko try to use similar link `http://localhost:8080/?PsByFlag=fake-user&urn=urn:test:54321` to register a new user. 

> I'm not sure but it could be important: What database is used on http://snapshot.netbout.com/?
Amazon DynamoDB

**Comment by pecko** [comment]
@dmzaytsev 

It works, but I can create only one user this way. There isn't any way to logout and get register page again.

Is there some documentation related to this project? I have seen general documentation about the takes project, but ask if there some about netbout except README.

**Comment by dmzaytsev** [comment]
@pecko we have only README

**Comment by pecko** [comment]
@dmzaytsev 

Thanks!
It's all for this issue.
