### ISSUE TITLE
jcabi-aspects  is outdated

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#812]
Right now we have the outdated dependence  in the project 
jcabi-aspects `0.22`  but latest is  `0.22.1`
https://www.versioneye.com/user/projects/561ac5eca193340f2f001222
![image](https://cloud.githubusercontent.com/assets/9972909/10425644/9d7af598-70f2-11e5-8ba1-3b72d171b4e9.png)

@yegor256 should we move to latest jcabi-aspects ?
to make the green badge in Readme

**Comment by yegor256** [comment]
@dmzaytsev yeah, I think it's a valid bug

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@dmzaytsev thanks for the report, I topped your acc for 30 mins, payment ID `67376875`

**Comment by mkordas** [comment]
@dmzaytsev please assign me here

**Comment by dmzaytsev** [comment]
@karato assign @mkordas please

**Comment by mkordas** [comment]
@karato please see #935

**Comment by karato** [comment]
> @karato assign @mkordas please

@dmzaytsev OK @mkordas please go ahead, this task is yours

**Comment by karato** [comment]
> @karato please see #935

@mkordas thanks, I'll take a look

**Comment by mkordas** [comment]
@dmzaytsev done in #935, can you close the issue?

**Comment by dmzaytsev** [comment]
@mkordas thanks!

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good :)

**Comment by karato** [comment]
@mkordas I added 10 mins to @elenavolokhova (for QA review) in transaction 75006305
