### ISSUE TITLE
New user Start button disabled until Find is used

### ISSUE THREAD

**Issue by Rossiar** [yegor256/netbout#813]
After signing up with GitHub, I read the introduction text and try to start a new bout by clicking "Start", but the button is not selectable.

![image](https://cloud.githubusercontent.com/assets/1635940/10499214/f84aa470-72c6-11e5-973a-8f6f6eccd4b9.png)

Once I search for any string the button changes and becomes selectable, allowing me to start new bouts:

![image](https://cloud.githubusercontent.com/assets/1635940/10499239/1661b08e-72c7-11e5-9957-1c92cea36d26.png)

Logging in and out of Netbout does not resolve this issue. Adding my email address did also not solve this issue.I am using Google Chrome Version 47.0.2526.8 dev-m (64-bit).

**Comment by dmzaytsev** [comment]
@Rossiar thanks

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@rossiar milestone set to `3.1` (correct me if I am wrong)

**Comment by dmzaytsev** [comment]
@yegor256  what was the idea of `Start(later)` ?
Start of  a new bout disabled when `"/page/bouts and count(/page/bouts/bout) = 0 and /page/query = ''`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I will try to assign someone else

**Comment by dmzaytsev** [comment]
@yegor256 ping

>dmzaytsev commented on 23 Jan
@yegor256 what was the idea of Start(later) ?
Start of a new bout disabled when "/page/bouts and count(/page/bouts/bout) = 0 and /page/query = ''
