### ISSUE TITLE
User email not verified

### ISSUE THREAD

**Issue by Rossiar** [yegor256/netbout#814]
After signing up to NetBout and entering my email, no confirmation email was sent to my email address. I would expect there to be a confirmation address to ensure that I am not a robot / mis-representing some other GitHub user. For further justification see http://stackoverflow.com/questions/7069228/why-do-we-send-confirmation-emails.

**Comment by dmzaytsev** [comment]
@Rossiar thanks for reporting but we already have the ticket #738 for same purpose

**Comment by Rossiar** [comment]
@dmzaytsev closing this issue as a duplicate
