### ISSUE TITLE
@help doesn't exist

### ISSUE THREAD

**Issue by Rossiar** [yegor256/netbout#816]
I create a new bout and attempt to Invite "@help" as recommended:

![image](https://cloud.githubusercontent.com/assets/1635940/10528308/6118b962-738d-11e5-9e3d-74a1864f7031.png)

The user "@help" does not exist:

![image](https://cloud.githubusercontent.com/assets/1635940/10528324/79d752d8-738d-11e5-84cb-b4bcad027389.png)

This also does not work when attempting to Invite user "help". I am using Google Chrome Version 47.0.2526.8 dev-m (64-bit).

**Comment by dmzaytsev** [comment]
@Rossiar thanks

**Comment by dmzaytsev** [comment]
@karato it's valid bug

**Comment by dmzaytsev** [comment]
@yegor256 what do you think about this feature?
to be honest I have no idea what the user `@help` should be able to do. Just provides something like a sandbox where a new user can play with Netbout ?
In this case we need check existing of `@help` alias and create it if need on startup.

**Comment by karato** [comment]
> @karato it's valid bug 

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@rossiar attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by yegor256** [comment]
@dmzaytsev I think this user should just be ready to answer some simple questions to the user, explaining how Netbout works. for example:

```
@help tell me more about it
@help how to invite someone?
@help how to leave this conversation?
```

Something similar to Apple Siri, but in a text mode. Make sense?

**Comment by dmzaytsev** [comment]
@yegor256 it will be hard to implement and the user will get a little benefit.
I mean hard to implement good text version of Siri :)
To be honest I prefer to use simple commands instead of  a simulation the human talk.

In my opinion will be enough to have a brief faq about Netbout. and put a link to the faq somewhere.
Also we should remove the recommendation to invite `@help` user

**Comment by yegor256** [comment]
@dmzaytsev make sense, let's do as you suggested, I agree

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all
