### ISSUE TITLE
MkAttachments.java:86-88: This method needs to be...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#826]
Puzzle `806-1e507f57` in `netbout-client/src/main/java/com/netbout/mock/MkAttachments.java:86-88` has to be resolved: This method needs to be implemented because it is used in tests that read bout properties. Currently, this implementation always returns 0.... The puzzle was created by bdragan on 26-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, someone else will be assigned soon

**Comment by karato** [comment]
@dmzaytsev I'm closing the issue...
