### ISSUE TITLE
X-Netbout-Alias

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#828]
Let's add HTTP header `X-Netbout-Alias` to each response, when a user is authenticated and has an alias. We don't have it now and it's difficult to understand by HTTP response what user is talking to the Netbout server.

**Comment by dmzaytsev** [comment]
@karato it's a vald bug

**Comment by karato** [comment]
> @karato it's a vald bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@yegor256 I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-f0fff31c`

**Comment by exper0** [comment]
@yegor256 do you mean something similar to [X-Netbout-Bout](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/bout/FkBout.java#L79)?

**Comment by yegor256** [comment]
@exper0 yes

**Comment by yegor256** [comment]
@dmzaytsev would be great to implement this in the next version. this is rather important for me now. thanks.

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev right, I added "urgent" label

**Comment by karato** [comment]
@kujtimiihoxha do this task

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  Is there any class that would affect all the requests from authenticated users, or do I have do do  this in many classes ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  where should I start with this task could you please assist.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha I think you can create a new `Take` decorator and use it in `TkApp` in `FkRegistered` constructor

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Is there any possibility to get the Alias of the user in TkApp ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I think I got it i will submit a pull request soon.

**Comment by kujtimiihoxha** [comment]
@yegor256  @dmzaytsev @karato  Please see PR #1070

**Comment by kujtimiihoxha** [comment]
@yegor256 please close this issue, the changes are merged.

**Comment by yegor256** [comment]
@kujtimiihoxha thanks!

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks a lot ;)

**Comment by karato** [comment]
@kujtimiihoxha paied 10 mins to @elenavolokhova for QA review (payment ID is `79791002`)

thank you, added **30 mins** to your acc, payment num is `AP-1A428767F7306625G`, 240 hours and 20 mins spent in total to complete

+30 added to your rating, current score is: [+788](http://www.netbout.com/b/36323?open=rating)
