### ISSUE TITLE
Using bold causes the space after it to disappear

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#838]
When I write text like this: `This is **bold** test`, the space after `bold` disappears, here's the result:
This is **bold**test.
`bold` and `test` merge into one word.
Bolding a word shouldn't make spaces after it disappear.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@krzyk there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@krzyk many thanks for the bug report, I added 15 mins to your acc, transaction `69670447`

**Comment by dmzaytsev** [comment]
@krzyk we fixed it already 
the ticket can be closed

![image](https://cloud.githubusercontent.com/assets/9972909/12489854/4e2fdf98-c094-11e5-9305-e832fd7f0d6a.png)

![image](https://cloud.githubusercontent.com/assets/9972909/12489872/606cb7b2-c094-11e5-9b44-d892d70bfddc.png)

**Comment by krzyk** [comment]
@dmzaytsev thanks
