### ISSUE TITLE
When a file is uploaded, system should add a message to notify it in timeline

### ISSUE THREAD

**Issue by antonini** [yegor256/netbout#840]
When a user uploads a file, the system should automatically generate a message in the timeline that describes that the file was uploaded.

Example: 
![image](https://cloud.githubusercontent.com/assets/209396/11189935/328e4a2a-8c7a-11e5-8954-5dd96c429c8d.png)

**Comment by dmzaytsev** [comment]
@antonini thanks, but we already have a ticket #756

**Comment by antonini** [comment]
@dmzaytsev You are right! It's duplicated! Tks!
