### ISSUE TITLE
EmAlias.java:130-134: We need to improve the...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#841]
Puzzle `738-4d284963` in `netbout-web/src/main/java/com/netbout/email/EmAlias.java:130-134` has to be resolved: We need to improve the format and content of the verification email. Currently, it only asks the user to verify the new email by using the provided verification link. We may add some header, footer, note like "Ignore this email if you did not change your email address", etc.... The puzzle was created by bdragan on 14-Nov-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@bdragan do this task

**Comment by bdragan** [comment]
@karato Please assign someone else.

**Comment by karato** [comment]
> @karato Please assign someone else.

@bdragan -30 points to your rating :(

**Comment by karato** [comment]
> @karato Please assign someone else.

@bdragan someone else will help in this task, no problem at all

**Comment by karato** [comment]
@ivanjunckes the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by karato** [comment]
@ivanjunckes you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... as a reminder, don't forget to remove the `@todo` puzzle from the source code... -30 added to your rating, current score is: [-30](http://www.netbout.com/b/36097?open=rating)

**Comment by ivanjunckes** [comment]
@karato Thanks for the tips, I was stuck trying to configure the SMTP, and couldn' t find a way to do it. I will probably not be able to deliver this in time.

**Comment by karato** [comment]
@ivanjunckes you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... added -60 to your rating, now it is equal to [-120](http://www.netbout.com/b/36097?open=rating)

**Comment by karato** [comment]
> @karato Thanks for the tips, I was stuck trying to configure the SMTP, and couldn' t find a way to do it. I will probably not be able to deliver this in time.

@ivanjunckes @karato someone else

**Comment by yegor256** [comment]
@karato assign someone else here pls

**Comment by karato** [comment]
> @karato assign someone else here pls

@yegor256 someone else will help in this task, no problem at all

**Comment by amihaiemil** [comment]
@dmzaytsev Can I have this task? :D I ask you for tasks because all my 7 tasks are blocked on jcabi, waiting for ARC to approve (some of them for 2-3 weeks...)

**Comment by dmzaytsev** [comment]
@karato assign @amihaiemil please

**Comment by karato** [comment]
> @karato assign @amihaiemil please

@dmzaytsev done. @amihaiemil the task is yours, please go ahead

**Comment by amihaiemil** [comment]
@karato PR #1128 is for this

**Comment by karato** [comment]
> @karato PR #1128 is for this

@amihaiemil thanks for that

**Comment by amihaiemil** [comment]
@karato the PR was merged. Please close this issue

**Comment by karato** [comment]
@dmzaytsev I am closing it, thanks all

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks for the review and a good remark

**Comment by karato** [comment]
@amihaiemil I added 10 mins to @ypshenychka (for QA review) in transaction 99209429; Thanks so much! Your account was topped up for **45 mins** (transaction ID is `AP-6YB14967XU653835C`, the task took 27 hours and 18 mins); m=1638, that's why a bonus here for fast delivery; added +45 to your rating, now it is equal to [+390](http://www.netbout.com/b/36402?open=rating)
