### ISSUE TITLE
TkSaveEmail.java:53-55: If the email attribute value...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#842]
Puzzle `738-d76bd177` in `netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java:53-55` has to be resolved: If the email attribute value contains !, we should display an exclamation icon with hint that the email is not verified yet near the alias name.... The puzzle was created by bdragan on 14-Nov-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@mkordas this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by mkordas** [comment]
@karato I think it is blocked by #853. Please let me know if you see possibility to implement this one without #853 being done first.

**Comment by dmzaytsev** [comment]
@mkordas I think this ticket and #853 are different issues and can be resolved separately

**Comment by mkordas** [comment]
@karato I need more time

**Comment by karato** [comment]
> @karato I need more time

@mkordas agreed, take your time

**Comment by mkordas** [comment]
@karato done in #842

**Comment by karato** [comment]
@rultor @karato please take a look, rultor closed it automatically

**Comment by mkordas** [comment]
@karato GitHub automatically closes all issues when pull request with description `fixes #XXX` is merged by anyone (including rultor)

**Comment by karato** [comment]
> @karato GitHub automatically closes all issues when pull request with description `fixes #XXX` is merged by anyone (including rultor)

@mkordas yeah, this is how GitHub works, we can't change that

**Comment by karato** [comment]
@dmzaytsev there is a puzzle in this code `842-9eb73ef4`/#879, we'll resolve it later

**Comment by mkordas** [comment]
@karato @dmzaytsev this was done 3 days ago, please proceed

**Comment by dmzaytsev** [comment]
@mkordas @karato will close this ticket

**Comment by mkordas** [comment]
@karato please close this one, it was done 5 days ago in #866

**Comment by mkordas** [comment]
@karato ping

**Comment by karato** [comment]
> @karato ping

@mkordas I'm here

**Comment by mkordas** [comment]
@karato can you accept and close this issue?

**Comment by karato** [comment]
> @karato can you accept and close this issue?

@mkordas will do

**Comment by mkordas** [comment]
@karato can you close this issue? It's hanging too long.

**Comment by karato** [comment]
@dmzaytsev The issue should be closed..

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you

**Comment by karato** [comment]
@mkordas added 10 mins to @elenavolokhova, for QA review, payment code is `73038738`; Thanks a lot, I just topped your account for **30 mins**, transaction ID `567eb72bc9e434779700006f`, total time was 376 hours and 7 mins; +30 to your rating, your total score is [+862](http://www.netbout.com/b/36080?open=rating)

**Comment by karato** [comment]
@dmzaytsev last puzzled solved `842-9eb73ef4`/#879
