### ISSUE TITLE
RtFriends#invite() doesn't throw UnknownAliasException

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#843]
`Friends#invite()` must throw `UnknownAliasException` when/if alias is unknown. We have to add this to the Javadoc of the method.

`RtFriends#invite()` never throws this type of exception. We should fix that.

`ReFriends#invite()` should not retry if `UnknownAliasException` is thrown. We should add `ignore` to `@RetryOnFailure`.

similar to #844

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@yegor256 milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-903031e6

**Comment by dmzaytsev** [comment]
@karato please assign me to this

**Comment by karato** [comment]
> @karato please assign me to this

@dmzaytsev of course, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 fixed in PR #845 
please close if alright

**Comment by dmzaytsev** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by yegor256** [comment]
@dmzaytsev can we release a new version with these changes?

**Comment by dmzaytsev** [comment]
@yegor256 sure

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato  Quality is good here.

**Comment by karato** [comment]
> @karato  Quality is good here.

@elenavolokhova many thanks

**Comment by karato** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `71773003`; **30 mins** was added to your account, many thanks for your contribution (payment 71773026)! The task took 100 hours and 43 mins.; +30 to your rating, your total score is [+854](http://www.netbout.com/b/35166?open=rating)
