### ISSUE TITLE
RtFriends#kick() doesn't throw UnknownAliasException

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#844]
`Friends#kick()` must throw `UnknownAliasException` when/if alias is unknown. We have to add this to the Javadoc of the method.

`RtFriends#kick()` never throws this type of exception. We should fix that.

`ReFriends#kick()` should not retry if `UnknownAliasException` is thrown. We should add `ignore` to `@RetryOnFailure`.

very similar to #843

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@yegor256 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-727c5197

**Comment by dmzaytsev** [comment]
@karato assign me to this please

**Comment by karato** [comment]
> @karato assign me to this please

@dmzaytsev of course, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 fixed in PR #846 
please close the ticket

**Comment by yegor256** [comment]
@dmzaytsev many thanks!

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato  Quality is good here.

**Comment by karato** [comment]
> @karato  Quality is good here.

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `71768357`... Many thanks! **38 mins** were added to your account in Transaction ID `71768390` (task took 53 hours and 20 mins)... m=3200, that's why a bonus here for fast delivery... +38 added to your rating, current score is: [+794](http://www.netbout.com/b/35166?open=rating)
