### ISSUE TITLE
org.pegdown.ParsingTimeoutException

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#847]
I see this in production logs, very often:

```
[WARN] 06da0da com.netbout.rest.Markdown: #html(): attempt #1 of 3 failed in 4s (4s waiting already) with org.parboiled.errors.ParserRuntimeException: Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Table/Sequence/Optional/Sequence/NodeSequence/Sequence/TableRow/Sequence/OneOrMore/Sequence/TableCell/Sequence/OneOrMore/Sequence/Inline/Inline_Action1' at input position (line 1, pos 1): [...]. ^  org.pegdown.ParsingTimeoutException
```

Would be great to fix this somehow.

**Comment by karato** [comment]
@yegor256 added "indie" tag to this issue

**Comment by karato** [comment]
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-19c8b22a`

**Comment by dmzaytsev** [comment]
@yegor256 there is a bug inside Pegdown.
btw you submitted it year and a half ago https://github.com/sirthias/pegdown/issues/136
but it seems the author of Pegdown don't want to fix it.

it's impossible to fix this bug if we will still use Pegdown

**Comment by yegor256** [comment]
@dmzaytsev maybe we can replace pegdown with something else?

**Comment by dmzaytsev** [comment]
@yegor256 okay, let's try
I didn't use another markdown processors before...
but what do you think about https://github.com/rjeschke/txtmark ?

**Comment by yegor256** [comment]
@dmzaytsev looks good... let's try

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato please assign me to this

**Comment by karato** [comment]
> @karato please assign me to this

@dmzaytsev of course, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@yegor256 please see PR #854
`MardownTxtmark` will be implemented in the next puzzle
I think this ticket can be closed

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
@yegor256 there is a puzzle in this code `847-f2a7caae`/#867, we'll resolve it later

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks!

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 71916111

Thanks for your contribution, **1 hour** was added to your account, payment ID is `71916116`, 15 hours and 37 mins spent total

the bonus for fast delivery (m=937)

+60 added to your rating, at the moment it is: [+1005](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@yegor256 the last puzzle `888-3f71fb04`/#937 solved
