### ISSUE TITLE
Multiple tests do not work on Windows due to encoding set to 'windows-1250' by default

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#850]
On Windows default encoding is set to `windows-1250`. This makes the following tests failing:
```
  TkAppTest.redirectsToReturnCookie:165 » IllegalState default encoding is windo...
  TkAppTest.redirectsToLoginAndSetsCookie:124 » IllegalState default encoding is...
  TkAppTest.rendersStaticResources:105 » IllegalState default encoding is window...
  TkAppTest.rendersFrontPage:64 » IllegalState default encoding is windows-1250
  TkAppTest.rendersSearchPage:78 » IllegalState default encoding is windows-1250
  TkInboxTest.kicksAnUser:66 » IllegalState default encoding is windows-1250
  TkPreviewTest.previewMessageBeforePost:63 » IllegalState default encoding is w...
```
Sample stack trace from `TkAppTest.redirectsToReturnCookie`:
```
java.lang.IllegalStateException: default encoding is windows-1250
	at com.netbout.rest.TkApp.make(TkApp.java:121)
	at com.netbout.rest.TkApp.<init>(TkApp.java:107)
	at com.netbout.rest.TkApp.<init>(TkApp.java:97)
	at com.netbout.rest.TkAppTest.redirectsToReturnCookie(TkAppTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmzaytsev** [comment]
@mkordas if you opened `com.netbout.rest.TkApp#make()` you would  see
```
if (!"UTF-8".equals(Charset.defaultCharset().name())) {
            throw new IllegalStateException(
                String.format(
                    "default encoding is %s", Charset.defaultCharset()
                )
            );
        }
```
so this is an intentional behavior

I guess you meant that we need to update Readme, right ? :)

**Comment by mkordas** [comment]
@dmzaytsev Yes, README doesn't say anything about preconditions about environment, but the less manual steps the better. If different default encoding is needed for tests, this can be set in Maven by `file.encoding` argument for the JVM running the tests.

**Comment by dmzaytsev** [comment]
@mkordas 
btw how it can be set in pom.xml?

>this can be set in Maven by file.encoding argument for the JVM running the tests.

I think it will be enough if we mention the environment preconditions in README

**Comment by ivanjunckes** [comment]
@mkordas I have the same issue when running maven through eclipse in windows 10. Please let me know if you found out how to fix it.
```
java.lang.IllegalStateException: default encoding is windows-1252
```

**Comment by mkordas** [comment]
@dmzaytsev 
> btw how it can be set in pom.xml?

Just like below. Would be good to incorporate it into POM. Can I raise pull request?

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>-Dfile.encoding=UTF-8</argLine>
                </configuration>
            </plugin>
@ivanjunckes you can use the above as temporary solution. But Windows users are blocked also by #767

**Comment by ivanjunckes** [comment]
@mkordas That works, thanks.

**Comment by dmzaytsev** [comment]
@mkordas 

> But Windows users are blocked also by #767

the broken test ignored

**Comment by dmzaytsev** [comment]
@mkordas  
>Can I raise pull request? 

no, you can't 
Problem reporter and problem solver should be two different persons

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@mkordas thanks for the ticket, your account was topped for 15 mins, payment 566d8936d4a82e7a1c000159

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I can do this one please assign me.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  If we incorporate
```
      <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
                <argLine>-Dfile.encoding=UTF-8</argLine>
            </configuration>
        </plugin>
```
 in the pom I don't think we need to mention it in the readme what do you think ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha I agree

**Comment by kujtimiihoxha** [comment]
@karato  @dmzaytsev  please see PR #1042

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev OK @kujtimiihoxha please proceed, this task is yours

**Comment by karato** [comment]
> @karato  @dmzaytsev  please see PR #1042

@kujtimiihoxha I will take a look, thanks

**Comment by kujtimiihoxha** [comment]
@mkordas  changes have been merged please close this issue.

**Comment by mkordas** [comment]
@kujtimiihoxha thx

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by karato** [comment]
@kujtimiihoxha just added 10 mins to @elenavolokhova (for QA), payment ID is `78632709`... **1 hour** sent to your balance (ID `AP-7CR966840D138283T`), many thanks! It took 23 hours and 3 mins.... the bonus for fast delivery (m=1383)... +60 added to your rating, at the moment it is: [+473](http://www.netbout.com/b/36323?open=rating)
