### ISSUE TITLE
Email that is not yet verified is not displayed on account page

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#853]
1. Go to http://www.netbout.com/acc/index
2. Fill in new email (valid one), press save
3. See that information `Email changed to "new@email.com". The verification link sent to this address.` is displayed at the top and email is sent
4. Refresh page at http://www.netbout.com/acc/index - **old email is still displayed instead of new one**

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@mkordas since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@mkordas many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `566aacd5ee243500a5000059`

**Comment by karato** [comment]
@original-brownbear do this task

**Comment by original-brownbear** [comment]
@mkordas same as in #989 this should be resolved by #1066 for the time being :)

**Comment by original-brownbear** [comment]
@mkordas ping :)

**Comment by mkordas** [comment]
@original-brownbear right, thanks

**Comment by original-brownbear** [comment]
@karato please pay attention to this ticket as well as my other closed tickets in your project. I closed all of them in a very short period of time each, still I'm blocked by having them pile up as open tasks and receive an unrealistic speed rating by them staying open long after the PRs are closed and payment on them is handled.
Thanks :)

**Comment by karato** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you :)

**Comment by karato** [comment]
@original-brownbear just added 10 mins to @ypshenychka (for QA), payment ID is `79311186`
