### ISSUE TITLE
No information whether search has returned any results

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#855]
When I search for something that has never occurred in my bouts I would expect error message like `No results found for "invalid search"`. Instead, just empty homepage without any information is shown:

![image](https://cloud.githubusercontent.com/assets/5467276/11756833/007d1b28-a05d-11e5-9fb3-e2cc6faa07c4.png)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@mkordas since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 566c5ffdc12c540c83000110

**Comment by karato** [comment]
@kujtimiihoxha do this task

**Comment by karato** [comment]
@kujtimiihoxha 15 days already, in 48 hours I will re-assign

-30 added to your rating, current score is: [+659](http://www.netbout.com/b/36323?open=rating)

**Comment by karato** [comment]
@kujtimiihoxha task is too long, stop working with it; -60 added to your rating, current score is: [+449](http://www.netbout.com/b/36323?open=rating)

**Comment by yegor256** [comment]
@karato assign someone else here

**Comment by karato** [comment]
> @karato assign someone else here

@yegor256 I will ask somebody else to pick this up

**Comment by karato** [comment]
@2686747 this is your task

**Comment by 2686747** [comment]
@yegor256 please, answer to my [question](www.netbout.com/b/37028).

**Comment by 2686747** [comment]
@karato thanks, please move this task, i stop working with team.

**Comment by karato** [comment]
> @karato thanks, please move this task, i stop working with team.

@2686747 -30 points to your rating :(

**Comment by karato** [comment]
> @karato thanks, please move this task, i stop working with team.

@2686747 right, I will find someone else, no problem

**Comment by karato** [comment]
@carlosgines do this task

**Comment by karato** [comment]
@carlosgines 15 days already, in 48 hours I will re-assign

added -30 to your rating, now it is equal to [+195](http://www.netbout.com/b/36645?open=rating)

**Comment by karato** [comment]
@carlosgines task is too long, stop working with it

added -60 to your rating, now it is equal to [+75](http://www.netbout.com/b/36645?open=rating)

**Comment by karato** [comment]
@amihaiemil this is your task

**Comment by amihaiemil** [comment]
@karato I created pr #1115 for this issue

**Comment by karato** [comment]
> @karato I created pr #1115 for this issue

@amihaiemil thank you!

**Comment by amihaiemil** [comment]
@mkordas the PR was closed, can u close this ticket? :D

**Comment by mkordas** [comment]
@amihaiemil thanks

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato  Looks good!

**Comment by karato** [comment]
> @karato  Looks good!

@elenavolokhova thank you

**Comment by karato** [comment]
@amihaiemil I added 10 mins to @elenavolokhova (for QA review) in transaction 96585672... thank you, added **30 mins** to your acc, payment num is `AP-01S65480SL136520N`, 159 hours and 14 mins spent in total to complete... +30 added to your rating, current score is: [+135](http://www.netbout.com/b/36402?open=rating)
