### ISSUE TITLE
Not possible to search by bout names

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#856]
I would expect bout names to be searchable.

For example when I have the following bout:
![image](https://cloud.githubusercontent.com/assets/5467276/11756969/ee212054-a05d-11e5-9295-7fa8d730cfb8.png)
I would expect it to be returned during the search, but it doesn't:

![image](https://cloud.githubusercontent.com/assets/5467276/11756985/098627ae-a05e-11e5-812d-9b0cab7f4f3b.png)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@mkordas I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 566c4c34c12c543358000161

**Comment by karato** [comment]
@kujtimiihoxha do this task

**Comment by karato** [comment]
@kujtimiihoxha 15 days already, in 48 hours I will re-assign

added -30 to your rating, now it is equal to [+689](http://www.netbout.com/b/36323?open=rating)

**Comment by karato** [comment]
@kujtimiihoxha task is too long, stop working with it... -60 added to your rating, at the moment it is: [+509](http://www.netbout.com/b/36323?open=rating)

**Comment by CarlosGines** [comment]
@karato I have realized this task is assigned to me since yesterday according to Netbout , but I have had no notice here. Can you please confirm something about this?

**Comment by karato** [comment]
@carlosgines this is your task

**Comment by CarlosGines** [comment]
@karato please check PR #1093

**Comment by karato** [comment]
> @karato please check PR #1093 

@carlosgines thanks for that

**Comment by CarlosGines** [comment]
@mkordas PR #1093 merged, please please close this ticket.

**Comment by mkordas** [comment]
@CarlosGines thanks!

**Comment by karato** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@carlosgines just added 10 mins to @ypshenychka (for QA), payment ID is `81432796`... Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-0CJ11269334707018`, the task took 130 hours and 44 mins)... +30 added to your rating, current score is: [+225](http://www.netbout.com/b/36645?open=rating)
