### ISSUE TITLE
Pressing 'Upload' without attachment chosen redirects to home page

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#857]
When no file is chosen and 'Upload' button is pressed:
![image](https://cloud.githubusercontent.com/assets/5467276/11757165/715dd114-a05f-11e5-9509-fd3a06be00f2.png)

user is redirected from bout to home page with the following error:
![image](https://cloud.githubusercontent.com/assets/5467276/11757141/4e34d53e-a05f-11e5-8c59-62cabfdbf7d9.png)

**Comment by dmzaytsev** [comment]
@mkordas what are you expect in this case?
the user made an invalid action and got the error message, what's wrong?

**Comment by mkordas** [comment]
@dmzaytsev 
I would expect one of the following:
* upload button is greyed out/not displayed when no file is chosen
* do not redirect to home page, just display information that file choice is needed
I don't expect the following behaviours:
* redirection to home page
* typo in message (`can contains`)
* being not precise in message (technically speaking empty string doesn't contain any disallowed characters, but it is still invalid)
* saying that attachment name is invalid, but in fact there was no attachment at all

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug
> 

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@mkordas thanks a lot for reporting, **15 mins** added to your acc, pmt ID `566d3b5ed4a82e15c600011c`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I could do this task please assign me.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by kujtimiihoxha** [comment]
@karato  @mkordas  see PR #1040

**Comment by kujtimiihoxha** [comment]
@mkordas  This is how it looks now if you have not selected any file : 
![screenshot from 2016-02-23 08-28-07](https://cloud.githubusercontent.com/assets/14311743/13244606/ce54146e-da07-11e5-91e4-de538eddbdc7.png)

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev OK @kujtimiihoxha please go ahead, this task is yours

**Comment by karato** [comment]
>  @karato  @mkordas  see PR #1040

@kujtimiihoxha will take a look at it, thanks

**Comment by kujtimiihoxha** [comment]
@mkordas please close.

**Comment by mkordas** [comment]
@kujtimiihoxha thanks

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you, good quality is always good :)

**Comment by karato** [comment]
@kujtimiihoxha added 10 mins to @ypshenychka, for QA review, payment code is `78634494`... **45 mins** sent to your balance (ID `AP-2WN03557XL626570S`), many thanks! It took 46 hours and 40 mins.... m=2800, that's why a bonus here for fast delivery... +45 added to your rating, at the moment it is: [+518](http://www.netbout.com/b/36323?open=rating)
