### ISSUE TITLE
XSS vulnerability in bouts

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#858]
If someone would type the following message in the bout:
![image](https://cloud.githubusercontent.com/assets/5467276/11757329/b2844870-a060-11e5-98f7-4177100e4b37.png)

Then every time the bout is open, alert window will be shown:
![image](https://cloud.githubusercontent.com/assets/5467276/11757590/dbf85f00-a062-11e5-9feb-d2cc74aa6aeb.png)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@mkordas milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `566c3cb3fededc5f510000f8`

**Comment by dmzaytsev** [comment]
@mkordas we fix it already, please close the ticket

![image](https://cloud.githubusercontent.com/assets/9972909/12424802/85c99392-bef3-11e5-89f8-f6cfdf31af6a.png)

![image](https://cloud.githubusercontent.com/assets/9972909/12424789/733dac86-bef3-11e5-9fcc-b37282e3bfcf.png)

**Comment by mkordas** [comment]
@dmzaytsev please use `script` not `scrypt`

**Comment by dmzaytsev** [comment]
@mkordas sorry, my mistake
so now we haven't allert window but we have empty message 
let's keep it open, this is a bug

**Comment by karato** [comment]
@kujtimiihoxha this is your task

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I think this should be done in RsHTML of task, not here on netbout. What do you think ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  becuase this would not only affect this case but all html responses will have this vulnerability.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha it should be done in MarkdownTxtMark.
perhaps TxtMark has an option for it
see https://github.com/rjeschke/txtmark

**Comment by dmzaytsev** [comment]
@kujtimiihoxha all messages in a bout processed by Markdown

**Comment by kujtimiihoxha** [comment]
@karato  @dmzaytsev  see PR #1054

**Comment by karato** [comment]
> @karato  @dmzaytsev  see PR #1054 

@kujtimiihoxha thanks, will take a look

**Comment by kujtimiihoxha** [comment]
@mkordas changes have been merged please close this issue.

**Comment by mkordas** [comment]
@kujtimiihoxha thanks

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!
