### ISSUE TITLE
Visual glitches when using markdown titles in bouts

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#859]
In any bout post a message with markdown-like titles, for example:
 ```md
#Title
###Subtitle
```

Here is how it looks just after pressing 'Post new message' button:
![image](https://cloud.githubusercontent.com/assets/5467276/11757691/d671f9c8-a063-11e5-9603-d82d3c043a01.png)

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@mkordas thanks for this report, I added 15 mins to your account, in transaction `566c21a3c12c547c34000051`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  could you assign this to me please.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by karato** [comment]
@kujtimiihoxha this is your task

**Comment by kujtimiihoxha** [comment]
@karato @dmzaytsev  see PR #1036

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev no problem, @kujtimiihoxha is already assigned to this task, please go on

**Comment by karato** [comment]
> @karato @dmzaytsev  see PR #1036  

@kujtimiihoxha thank you, I will check it

**Comment by kujtimiihoxha** [comment]
@mkordas  Please close this issue changes have been merged.

**Comment by mkordas** [comment]
@kujtimiihoxha thanks

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you ;)

**Comment by karato** [comment]
@kujtimiihoxha 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 78631142... **1 hour** sent to your balance (ID `AP-8G559753YG607102Y`), many thanks! It took 23 hours and 3 mins.... there is a bonus for fast delivery (m=1383)... +60 to your rating, your total score is [+413](http://www.netbout.com/b/36323?open=rating)
