### ISSUE TITLE
Email can be 'changed'  to the same email

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#860]
1. Go to http://www.netbout.com/acc/index
2. See your current email
3. Without changing it, press 'save'

Expected: no action, as there was no change to an email
Actual: entire procedure to confirm your current email begins, which doesn't really make sense

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `566c0d6f530033475e0000bc`

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev the task is yours, please proceed

**Comment by dmzaytsev** [comment]
@mkordas fixed in #928 the ticket can be closed

**Comment by mkordas** [comment]
@dmzaytsev thank you

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 74666081. **1 hour** sent to your balance (ID `74666091`), many thanks! It took 5 hours and 11 mins.. m=311, that's why a bonus here for fast delivery. +60 added to your rating, current score is: [+1871](http://www.netbout.com/b/35166?open=rating)
