### ISSUE TITLE
Reference-style markdown images do not work in bouts

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#863]
When posting as a bout the following text:
```
Inline-style: 
![alt text](https://camo.githubusercontent.com/f60dcff129bbc252ab48a4bace2aa92cc982774a/687474703a2f2f696d672e7465616d65642e696f2f62746e2e737667)

Reference-style: 
![alt text][logo]

[logo]: https://camo.githubusercontent.com/f60dcff129bbc252ab48a4bace2aa92cc982774a/687474703a2f2f696d672e7465616d65642e696f2f62746e2e737667
```
It renders as follows:
![image](https://cloud.githubusercontent.com/assets/5467276/11764066/82ace34c-a122-11e5-95ce-5a807b5e560b.png)

It is because square brackets are added around the link
![image](https://cloud.githubusercontent.com/assets/5467276/11764071/a81ef476-a122-11e5-9fe8-3db8857c44e0.png)

The same here in GitHub works fine as it is proper markdown:

Inline-style: 
![alt text](https://camo.githubusercontent.com/f60dcff129bbc252ab48a4bace2aa92cc982774a/687474703a2f2f696d672e7465616d65642e696f2f62746e2e737667)

Reference-style: 
![alt text][logo]

[logo]: https://camo.githubusercontent.com/f60dcff129bbc252ab48a4bace2aa92cc982774a/687474703a2f2f696d672e7465616d65642e696f2f62746e2e737667

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `566d5d84fededc47350003cd`

**Comment by karato** [comment]
@kujtimiihoxha do this task

**Comment by kujtimiihoxha** [comment]
@karato  waiting for  #993

**Comment by karato** [comment]
> @karato  waiting for  #993

@kujtimiihoxha yep, got it, let's wait for #993 being solved

**Comment by kujtimiihoxha** [comment]
@karato , @mkordas see PR #996

**Comment by karato** [comment]
> @karato , @mkordas see PR #996

@kujtimiihoxha thanks, I'll take a look

**Comment by karato** [comment]
@mkordas we waited for #993, it is closed already

**Comment by kujtimiihoxha** [comment]
@mkordas  Please close this issue changes have been merged.

**Comment by mkordas** [comment]
@kujtimiihoxha  thanks

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@kujtimiihoxha added 10 mins to @elenavolokhova, for QA review, payment code is `77171926`... Thanks a lot, I just topped your account for **1 hour**, transaction ID `AP-4FM11258K6921634E`, total time was 5 hours and 6 mins... there is a bonus for fast delivery (m=306)... added +60 to your rating, now it is equal to [+210](http://www.netbout.com/b/36323?open=rating)
