### ISSUE TITLE
Obsolete text field "attachment name..."

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#865]
Field "attachment name..." displayed when adding files to bouts doesn't seem to be used anywhere and it doesn't impact anything:
![image](https://cloud.githubusercontent.com/assets/5467276/11764248/ec007bc8-a128-11e5-87f0-e57b55879d08.png)

I think it should be removed. Or maybe I'm missing something?

**Comment by dmzaytsev** [comment]
@mkordas I guess, there  was an idea, "attachment name" should be a label for an attachment.
@yegor256 am I right?
if so field "attachment name" should be filled by a file name by default
unallowed  chars like spaces or dashes should be replaced/removed as well

**Comment by yegor256** [comment]
@dmzaytsev yes, attachment name should be taken from the form field, not file name

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@mkordas Field "attachment name..."  shouldn't be removed, however we have a bug here

**Comment by mkordas** [comment]
@dmzaytsev should I rename the issue and change the description? Or just comments are enough?

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 566fecb821649a322a0000a7

**Comment by dmzaytsev** [comment]
@mkordas I think comments are enough

**Comment by karato** [comment]
@jhyle this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by jhyle** [comment]
@karato please find someone to review the PR #979

**Comment by karato** [comment]
> @karato please find someone to review the PR #979

@jhyle thank you

**Comment by karato** [comment]
@jhyle 15 days already, in 48 hours I will re-assign. added -30 to your rating, now it is equal to [+105](http://www.netbout.com/b/36320?open=rating)

**Comment by jhyle** [comment]
@karato waiting for https://github.com/yegor256/takes/issues/577

**Comment by karato** [comment]
> @karato waiting for https://github.com/yegor256/takes/issues/577

@jhyle agreed, take your time
