### ISSUE TITLE
Markdown.java:38-40: MarkdownTxtmark not implemented but has...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#867]
Puzzle `847-f2a7caae` in `netbout-web/src/main/java/com/netbout/rest/Markdown.java:38-40` has to be resolved: MarkdownTxtmark not implemented but has to be. This class should be implementation of Markdown using TxtMark. See https://github.com/rjeschke/txtmark. Don't forget about unit tests.... The puzzle was created by Dmitry Zaytsev on 11-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by dmzaytsev** [comment]
@karato assign me to this ticket please

**Comment by karato** [comment]
> @karato assign me to this ticket please

@dmzaytsev of course, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@karato fixed in PR #869 the task can be closed

**Comment by karato** [comment]
> @karato fixed in PR #869 the task can be closed

@dmzaytsev thanks, will take a look

**Comment by karato** [comment]
@dmzaytsev there is a puzzle in this code `867-4e7e6e8f`/#873, we'll resolve it later

**Comment by karato** [comment]
@dmzaytsev Thanks all, I am closing

**Comment by karato** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka many thanks

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @ypshenychka for QA review (payment ID is `72373678`)... I just added **45 mins** to your account, many thanks for your contribution (72373704).. 24 hours and 37 mins spent here... the bonus for fast delivery (m=1477)... added +45 to your rating, now it is equal to [+942](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev last puzzled solved `888-3f71fb04`/#937
