### ISSUE TITLE
Appveyor setup

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#872]
we have many windows-specific issues in the project.
it will be good to setup Appveyor CI for netbout to validate pull requests against that  issues.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@yegor256  you are owner of the repository. Could you register netbout in Appveyor?
I will create the configuration file later

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by yegor256** [comment]
@dmzaytsev done: https://ci.appveyor.com/project/yegor256/netbout

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 30 mins, transaction `72234292`

**Comment by dmzaytsev** [comment]
@karato assign @exper0  to this ticket please

**Comment by karato** [comment]
> @karato assign @exper0  to this ticket please

@dmzaytsev done. @exper0 you are assigned to this task. please proceed...

**Comment by exper0** [comment]
@dmzaytsev @karato done

**Comment by exper0** [comment]
@dmzaytsev PR #916 is merged and closed - could you please close the ticket?

**Comment by dmzaytsev** [comment]
@exper0 thanks!

**Comment by karato** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@exper0 10 mins was added to the account of @ypshenychka (for QA review), in transaction 74448890; Thanks a lot, I just topped your account for **38 mins**, transaction ID `AP-69718615RT161511A`, total time was 69 hours and 19 mins; m=4159, that's why a bonus here for fast delivery; +38 to your rating, your total score is [+233](http://www.netbout.com/b/36185?open=rating)
