### ISSUE TITLE
MarkdownTxtmarkTest.java:42-46: MarkdownTxtmark not implemented but has...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#873]
Puzzle `867-4e7e6e8f` in `netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java:42-46` has to be resolved: MarkdownTxtmark not implemented but has to be. See #847 for details. This class should be implementation of Markdown using TxtMark. See https://github.com/rjeschke/txtmark. After that don't forget remove Ignore annotation from unit tests.... The puzzle was created by Dmitry Zaytsev on 13-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@karato please see PR #885

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev this task is yours now, please proceed

**Comment by karato** [comment]
> @karato please see PR #885 

@dmzaytsev thanks, will take a look

**Comment by dmzaytsev** [comment]
@karato fixed in PR #885 , the ticket can be closed

**Comment by karato** [comment]
> @karato fixed in PR #885 , the ticket can be closed

@dmzaytsev ok thanks

**Comment by karato** [comment]
@dmzaytsev 2 puzzles were created here: `873-bdf7b68b`, `873-3b1d8aa3`/#888

**Comment by karato** [comment]
@dmzaytsev I'm closing the issue...

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `72874455`. done, I added **30 mins** in payment `72874472`, 72 hours and 20 mins spent to complete this. +30 added to your rating, at the moment it is: [+1070](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `888-3f71fb04`/#937 solved
