### ISSUE TITLE
More than 3 asterisks, hyphens or underscores in line are not displayed in bout

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#876]
To reproduce e.g. post in bout 

```
***
```

Such message will not be displayed:
![screenshot from 2015-12-17 00 55 41](https://cloud.githubusercontent.com/assets/5467276/11857489/eced565e-a458-11e5-9bdb-1ea9e14e2f69.png)
while I would expect **horizontal rule** to be displayed as per [Markdown reference](http://daringfireball.net/projects/markdown/syntax#hr).

Same goes with hyphens (-) or underscores (_) whenever there are more than 3 of them in the line.

**Comment by dmzaytsev** [comment]
@mkordas please submit a bug properly
you wrote
>Such message will not be displayed:

but what are you expect to see? 3 asterisks  ? or a line ? or something else?

it would better if you the bug description contains something like 

>I would expect to see a horizontal rule because the markdown reference http//:... says 
"you can produce a horizontal rule by placing three or more hyphens"

**Comment by mkordas** [comment]
@dmzaytsev you are right, I've fixed the description

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@mkordas milestone set to `3.1` (correct me if I am wrong)

**Comment by karato** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `5672caeaa1032f624000002f`

**Comment by karato** [comment]
@danff this is your task

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev someone else will help in this task, no problem at all
