### ISSUE TITLE
XeAlias.java:95-97: Write test for the logic...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#879]
Puzzle `842-9eb73ef4` in `netbout-web/src/main/java/com/netbout/rest/XeAlias.java:95-97` has to be resolved: Write test for the logic of generating Xembly for {@link Alias} class. It should focus on checking whether tags "email" and "newEmail" are properly populated based on input.... The puzzle was created by mkordas on 12-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by dmzaytsev** [comment]
@yegor256 what does label `D` mean ?

**Comment by yegor256** [comment]
@dmzaytsev looks like a bug in Github... I removed it

**Comment by dmzaytsev** [comment]
@yegor256 there is same label here https://github.com/yegor256/netbout/issues/775

**Comment by exper0** [comment]
@karato @dmzaytsev what does `D` label means?

**Comment by dmzaytsev** [comment]
@exper0 :)

> @yegor256 what does label D mean ?
Owner
yegor256 commented 7 days ago
@dmzaytsev looks like a bug in Github... I removed it

**Comment by exper0** [comment]
@dmzaytsev sorry, I missed it :)

**Comment by dmzaytsev** [comment]
@karato assign @CarlosGines please

**Comment by karato** [comment]
> @karato assign @CarlosGines please

@dmzaytsev OK @carlosgines please proceed, this task is yours

**Comment by CarlosGines** [comment]
@dmzaytsev thank you :)

**Comment by CarlosGines** [comment]
@karato please check PR #1079

**Comment by karato** [comment]
> @karato please check PR #1079

@carlosgines thank you

**Comment by CarlosGines** [comment]
@karato PR #1079 merged. Please close this ticket.

**Comment by CarlosGines** [comment]
@karato please close this issue.

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks for the review

**Comment by karato** [comment]
@carlosgines paied 10 mins to @ypshenychka for QA review (payment ID is `80596220`). Much appreciated! **30 mins** was added to your account, payment ID `AP-19E26381XW290394P`, time spent is 182 hours and 56 mins. +30 to your rating, your total score is [+180](http://www.netbout.com/b/36645?open=rating)

**Comment by CarlosGines** [comment]
@karato Thank you! Please do not forget to close the ticket so that I can get a new task assigned!

**Comment by karato** [comment]
@dmzaytsev The issue is closed
