### ISSUE TITLE
Error message when uploading files with short names in not meaningful

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#880]
To reproduce create file named `a` and upload it to any bout. The following error will be displayed in red:
>invalid attachment name "a". Attachment name can contains letters in upper or lower case, numbers, dots, dashes.

This error message is misleading because name contains just lower case letters and should pass the validation. 

Only by looking into code of `DyAttachments`, it appears that to pass the validation name must have at least 3 characters. I see two possible solutions:
* do not demand at least 3 characters for filename
* change error message to be more specific

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@mkordas I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@mkordas thank you for the ticket reported, I topped your account for 15 mins, transaction `5676d8533bfa9c68dc000122`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I am ready for this one. @mkordas and @dmzaytsev. What solution should I use 
  
 1.do not demand at least 3 characters for filename
 2.change error message to be more specific

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev done. @kujtimiihoxha you are assigned to this task. please proceed...

**Comment by kujtimiihoxha** [comment]
@mkordas please see PR #959

**Comment by kujtimiihoxha** [comment]
@mkordas the changes have been merged please close this issue.

**Comment by mkordas** [comment]
@kujtimiihoxha thanks

**Comment by karato** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks!

**Comment by karato** [comment]
@kujtimiihoxha added 10 mins to @elenavolokhova, for QA review, payment code is `75932075`... paid, thanks, added **30 mins** to your account, payment `AP-9NT33999KY979062P`, 166 hours and 29 mins was spent... +30 added to your rating, at the moment it is: [+120](http://www.netbout.com/b/36323?open=rating)
