### ISSUE TITLE
Strange behaviour when uploading empty attachment

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#881]
To reproduce create empty file using e.g. command `touch temp.md`.

When trying to upload it into any bout, there will be redirect to homepage with error
> content of attachment "temp.md" can't be empty

Surprisingly, the attachment gets added to the bout:
![screenshot from 2015-12-17 21 02 16](https://cloud.githubusercontent.com/assets/5467276/11880523/804a89f0-a501-11e5-8b5e-359f72ad58db.png)
but even more strange is that after download this attachment is not empty anymore. Instead, it contains text `temporary unavailable` inside.

I would expect either of those:
* do not accept empty attachments at all
* accept empty attachments without error and do not add any text to them

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@mkordas since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 5676c41a7d98e517440000c6

**Comment by exper0** [comment]
@dmzaytsev ready to take this

**Comment by dmzaytsev** [comment]
@karato assign @exper0 please

**Comment by karato** [comment]
> @karato assign @exper0 please

@dmzaytsev OK @exper0 please go ahead, this task is yours

**Comment by exper0** [comment]
@mkordas it's fixed - empty attachments are rejected correctly now. It's in #951 which is merged already.

**Comment by mkordas** [comment]
@exper0 thanks

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Quality is good here!

**Comment by karato** [comment]
> @karato Quality is good here!

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@exper0 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 75207950... Much appreciated! **45 mins** was added to your account, payment ID `AP-9FH86824K34004604`, time spent is 43 hours and 28 mins... the bonus for fast delivery (m=2608)... +45 added to your rating, current score is: [+466](http://www.netbout.com/b/36185?open=rating)
