### ISSUE TITLE
Preview does not display properly markdown when line begins with space

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#882]
To reproduce put the following message as a text to post to bout:
```
 #### Test
```
Note that there is space at the beginning of line.

Here's how preview looks for it:
![screenshot from 2015-12-17 21 25 46](https://cloud.githubusercontent.com/assets/5467276/11881070/c42bc622-a504-11e5-97d2-888b848e280d.png)

After posting the message it looks correctly though:
![screenshot from 2015-12-17 21 26 38](https://cloud.githubusercontent.com/assets/5467276/11881093/e097d5da-a504-11e5-93d0-a5d194cec9a5.png)

I'd expect preview showing something like that:
![screenshot from 2015-12-17 21 27 44](https://cloud.githubusercontent.com/assets/5467276/11881118/0599d216-a505-11e5-8632-828d5b993fb0.png)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@mkordas thanks for the ticket, your account was topped for 15 mins, payment 5676ab367d98e5731800005b

**Comment by dmzaytsev** [comment]
@mkordas we fix it already please close the ticket

![image](https://cloud.githubusercontent.com/assets/9972909/12424564/96204dcc-bef2-11e5-9d6b-fc187b4bf5fb.png)

![image](https://cloud.githubusercontent.com/assets/9972909/12424573/a0f91094-bef2-11e5-9516-9e7884e9b948.png)

![image](https://cloud.githubusercontent.com/assets/9972909/12424586/aed2168e-bef2-11e5-95aa-dd62c1beb0d6.png)

**Comment by mkordas** [comment]
@dmzaytsev thx
