### ISSUE TITLE
Frame for code in preview is too wide and causes visual glitch

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#883]
To reproduce prepare the following text in post new message to bout field:
```
    this is code
```
Note that it begins with four spaces.

Press preview button and observe too wide frame:
![screenshot from 2015-12-17 21 40 21](https://cloud.githubusercontent.com/assets/5467276/11881381/cb5a8c6a-a506-11e5-97bc-6c23044b9785.png)

I'd expect it fitting exactly to the parent frame:
![screenshot from 2015-12-17 21 41 45](https://cloud.githubusercontent.com/assets/5467276/11881412/fc4b64fc-a506-11e5-83ad-1c577750759f.png)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@mkordas there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `56769ee36efb162b59000073`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I  was looking if I could solve this one, but when i try to add an email to the tester account (to be able to write a bout) locally it fails to send the verification link, is this supposed to happen or is it a bug.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I can start a bout without an email, nevertheless should I be able to add an email locally ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha  you can start a new bout from the profile page  see #941

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I am ready to take this one, could you please assign me this task.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by kujtimiihoxha** [comment]
@dmzaytsev see PR  #944

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev done. @kujtimiihoxha you are assigned to this task. please proceed...

**Comment by kujtimiihoxha** [comment]
@mkordas please close the issue.

**Comment by kujtimiihoxha** [comment]
@mkordas could you please review the solution and close the issue.

**Comment by mkordas** [comment]
@kujtimiihoxha can you provide screenshot before and after fix to prove that issue is fixed?

**Comment by kujtimiihoxha** [comment]
@mkordas here you can se the before and after pictures.

Before:
![before](https://cloud.githubusercontent.com/assets/14311743/12399394/1fc59eb2-be1a-11e5-962c-91c8b1ac9acd.png)

After:
![solved](https://cloud.githubusercontent.com/assets/14311743/12399399/26bf7b7a-be1a-11e5-9b84-927aa67429f3.png)

**Comment by kujtimiihoxha** [comment]
@mkordas is everything ok now ?

**Comment by mkordas** [comment]
@kujtimiihoxha thanks!

**Comment by karato** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@kujtimiihoxha added 10 mins to @ypshenychka, for QA review, payment code is `75140340`

Thanks so much! Your account was topped up for **1 hour** (transaction ID is `AP-12076489JA235323Y`, the task took 20 hours and 10 mins)

m=1210, that's why a bonus here for fast delivery

+60 added to your rating, current score is: [+105](http://www.netbout.com/b/36323?open=rating)

**Comment by yegor256** [comment]
@karato pls add extra 210 minutes to @kujtimiihoxha since all his previous transactions were reverted by PayPal

**Comment by karato** [comment]
> @karato pls add extra 210 minutes to @kujtimiihoxha since all his previous transactions were reverted by PayPal

@yegor256 I've sent 3 hours and 30 mins extra to @kujtimiihoxha in transaction ID "AP-14R57234Y0219745R"
