### ISSUE TITLE
Emphasis within the words does not work for bout message contents

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#884]
According to [the Markown spec](http://daringfireball.net/projects/markdown/syntax#em), e.g. the text `un*frigging*believable` should be rendered as un_frigging_believable, but it is not.

![screenshot from 2015-12-17 21 48 19](https://cloud.githubusercontent.com/assets/5467276/11881574/e8b54f24-a507-11e5-8934-58403c2f1a88.png)
produces:

![screenshot from 2015-12-17 21 47 36](https://cloud.githubusercontent.com/assets/5467276/11881550/d08c4ca4-a507-11e5-92de-05e23b0c6aa5.png)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@mkordas thank you for the ticket reported, I topped your account for 15 mins, transaction `56768eaa90b4583059000165`

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev sure, thanks, I added "postponed" label to it

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will assign somebody else to this issue
