### ISSUE TITLE
MarkdownTxtmarkTest.java:200-204: MarkdownTxtmark doesn't break a line...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#888]
Puzzle `873-3b1d8aa3` in `netbout-web/src/test/java/com/netbout/rest/MarkdownTxtmarkTest.java:200-204` has to be resolved: MarkdownTxtmark doesn't break a line on a new line symbol. It should put br code or make a new paragraph on each new line in the input data. I didn't find that option in TxtMark's settings, but perhaps I missed something. If the option won't be found we can replace single eol symbol to double eol as workaround.... The puzzle was created by Dmitry Zaytsev on 18-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev yep, it is yours, go ahead

**Comment by dmzaytsev** [comment]
@karato fixed in #925 please close the ticket

**Comment by karato** [comment]
> @karato fixed in #925 please close the ticket

@dmzaytsev the ticket will be closed when the puzzle is removed from the code, keep in mind that it takes some time after deployment to update our statistics, please give me at least a day

**Comment by karato** [comment]
@dmzaytsev once `888-3f71fb04`/#937 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by karato** [comment]
@dmzaytsev Thanks, closed

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 75011243; Thanks so much! Your account was topped up for **1 hour** (transaction ID is `75011260`, the task took 17 hours and 49 mins); m=1069, that's why a bonus here for fast delivery; +60 to your rating, your total score is [+2106](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `888-3f71fb04`/#937 originated from here solved
