### ISSUE TITLE
MarkdownTxtmark.java:62-64: We need more tests for...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#889]
Puzzle `873-bdf7b68b` in `netbout-web/src/main/java/com/netbout/rest/MarkdownTxtmark.java:62-64` has to be resolved: We need more tests for the case, when text contains several links. Both plain links and markdown preformatted links need to be checked.... The puzzle was created by Dmitry Zaytsev on 20-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by karato** [comment]
@dmzaytsev milestone set to `3.1` (correct me if I am wrong)

**Comment by prahladyeri** [comment]
@karato What's the puzzle in that? Isn't it something as straightforward as adding a unit-test case in `MarkdownTxtmarkTest` like this one (example):

    @Test
    public void handlesTextWithLotsOfLinks() throws Exception {
        MatcherAssert.assertThat(
            new MarkdownTxtmark().html(
                "Foo Bar Baz [google](http://www.google.com) Quick Brown"
                + "Fox Jumped across http://www.yahoo.com the lazy dog."
                + "Linux is a really cool http://www.ubuntu.com operating system."
            ),
            Matchers.equalTo(
                "<p>Foo Bar Baz <a href=\"http://www.google.com\">google</a> Quick Brown"
                + "Fox Jumped across <a href=\"http://www.yahoo.com\">http://www.yahoo.com</a> the lazy dog."
                + "Linux is a really cool <a href=\"http://www.ubuntu.com\">http://www.ubuntu.com</a> operating system.</p>"
            )
        );
    }

**Comment by karato** [comment]
> @karato What's the puzzle in that? Isn't it something as straightforward as adding just another unit-test in `MarkdownTxtmarkTest.java` like this one (example):
> 
>     @Test
>     public void handlesTextWithLotsOfLinks() throws Exception {
>         MatcherAssert.assertThat(
>             new MarkdownTxtmark().html(
>                 "Foo Bar Baz [google](http://www.google.com) Quick Brown"
>                 + "Fox Jumped across http://www.yahoo.com the lazy dog."
>                 + "Linux is a really cool http://www.ubuntu.com operating system."
>             ),
>             Matchers.equalTo(
>                 "<p>Foo Bar Baz <a href=\"http://www.google.com\">google</a> Quick Brown"
>                 + "Fox Jumped across <a href=\"http://www.yahoo.com\">http://www.yahoo.com</a> the lazy dog."
>                 + "Linux is a really cool <a href=\"http://www.ubuntu.com\">http://www.ubuntu.com</a> operating system.</p>"
>             )
>         );
>     }

@prahladyeri I have no idea, don't ask me technical questions. You see who is the author of the puzzle, you can talk to him

**Comment by dmzaytsev** [comment]
@karato assign me to the ticket please

**Comment by karato** [comment]
> @karato assign me to the ticket please

@dmzaytsev sure, the task is yours now

**Comment by dmzaytsev** [comment]
@karato fixed in #906 , #907 
please close the ticket

**Comment by karato** [comment]
> @karato fixed in #906 , #907 
> please close the ticket

@dmzaytsev I will close it when the puzzle disappears from the source code, and keep in mind that it may take up to a day to update project stats after a successful deployment

**Comment by dmzaytsev** [comment]
@yegor256 PR #906 , #907 merged 7 days ago
but this ticket is open

**Comment by yegor256** [comment]
@dmzaytsev are you sure that the puzzle is gone? please check `PUZZLES.md`

**Comment by dmzaytsev** [comment]
@yegor256 the puzzle present in PUZZLES.md
but the puzzle has been removed in source code 7 days ago in PR #907

**Comment by yegor256** [comment]
@dmzaytsev it means that the deployment is broken or you have the puzzle still in the code

**Comment by dmzaytsev** [comment]
@yegor256 the puzzle removed from the source code
how to restart the deployment?

**Comment by yegor256** [comment]
@dmzaytsev just `@rultor deploy`, as usual

**Comment by dmzaytsev** [comment]
@yegor256 I can't do that
rultor rejects my command

**Comment by yegor256** [comment]
@rultor deploy

**Comment by dmzaytsev** [comment]
@karato I need more time

**Comment by karato** [comment]
> @karato I need more time

@dmzaytsev of course, take your time

**Comment by karato** [comment]
@dmzaytsev Done, the task is closed

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@dmzaytsev 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >The ticket describes one specific problem and provides a single solution.
 
 Two PRs were created for this issue. Please try to follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 74132253; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `74132266`, the task took 181 hours and 34 mins); +30 added to your rating, at the moment it is: [+1656](http://www.netbout.com/b/35166?open=rating)
