### ISSUE TITLE
Tests should timeout when there are freeze issues

### ISSUE THREAD

**Issue by prahladyeri** [yegor256/netbout#892]
I came across this when working on #791. As a quick workaround, I have raised CR [891](https://github.com/yegor256/netbout/pull/891). I have added an arbitary value to `parallelTestsTimeoutInSeconds`. Not sure whether it is the ideal thing to do, but looks like we need some generic blanket check when a rogue task runs indefinitely and the entire build process stalls because of that one thing.

**EDIT**
Made a permanent fix to freeze issue by removing the `ReUser` wrapper class. However, I still think that parallel tests timeout is needed as an overall check in `pom.xml` (though I've removed it for the time being).

**Comment by dmzaytsev** [comment]
@prahladyeri I think we don't timeouts on tests right now

**Comment by prahladyeri** [comment]
@dmzaytsev Maybe not right now, but such a scenario may occur in future. This is just for an overall check in `pom.xml` (forget #791 for the moment) that whenever a test takes infinitely long time (like say >10 mins), there should be a constraint to kill that process. Otherwise, it will just freeze our `travis` or `appveyor` machine and the entire build queue will halt because of that one rogue test case.

If you think this is quite trivial and doesn't need any handling in `pom.xml`, let me know and I'll close this.

**Comment by dmzaytsev** [comment]
@prahladyeri yes please close this one
