### ISSUE TITLE
Perform RCA on RtFriendsITCase getting stuck

### ISSUE THREAD

**Issue by prahladyeri** [yegor256/netbout#893]
This is linked to issue #791. I did lots of trial-error with the `pom.xml` of `netbout-client` by adjusting the various configuration parameters of `maven-failsafe-plugin` but still couldn't find the root cause of it. I am told that the issue is related to this one test class `RtFriendsITCase`, but I couldn't pinpoint that by debugging (running various builds with different configurations). Even after commenting out the entire `RtFriendsITCase` class, I could still get the freeze issue.

As a workaround, I've introduced *parallel tests timeout* and submitted CR #891 which certainly solves the freeze problem, but the owner of that issue is looking for a RCA solution, not a workaround. So can someone help with finding out the root cause of this issue?

**Comment by dmzaytsev** [comment]
@prahladyeri https://github.com/yegor256/netbout/pull/891#issuecomment-166977950

**Comment by prahladyeri** [comment]
I've fixed #791 by removing the rogue wrapper class `ReUser` from `NbRule` which was causing the freeze. Hence, closing this.
