### ISSUE TITLE
upgrade to latest Takes

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#894]
Let's upgrade to latest Takes
I expect a few broken tests, related to missed `Accept` header
see https://github.com/yegor256/takes/issues/475
just use something like this `new RqWithHeader(req, "Accept", "text/xml")` in appropriate places

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is urgent

**Comment by dmzaytsev** [comment]
@exper0, @danff, @bdragan, @erimerturk, @komaz, @ivanjunckes, @mbarbieri, @prahladyeri, @lauresh
let me know if anyone of you would like to do it

**Comment by exper0** [comment]
@dmzaytsev I can take this. How urgent is it? Since this is my first task I may need some time to get into Takes and Netbout in general (learn some basic things)

**Comment by dmzaytsev** [comment]
@exper0 according the policy www.teamed.io/policy.html 
you have 10 days to complete the ticket
anyway you can reject the ticket anytime

**Comment by prahladyeri** [comment]
@dmzaytsev  I can take the ticket in case @exper0 rejects it.

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by exper0** [comment]
@dmzaytsev I'll take it

**Comment by dmzaytsev** [comment]
@karato assign @exper0 to this ticket please

**Comment by dmzaytsev** [comment]
@karato this not urgent anymore

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 30 mins, transaction `72950391`

**Comment by karato** [comment]
> @karato this is urgent

@dmzaytsev got it, "urgent" label here

**Comment by karato** [comment]
> @karato assign @exper0 to this ticket please

@dmzaytsev OK @exper0 please go ahead, this task is yours

**Comment by karato** [comment]
> @karato this not urgent anymore

@dmzaytsev sure, thanks, I removed "urgent" tag to it

**Comment by exper0** [comment]
@dmzaytsev netbound with current version of Takes(0.24.1) fails some tests:
  TkAppTest.rendersSearchPage:78 » IllegalState default encoding is windows-1251
  TkAppTest.redirectsToLoginAndSetsCookie:124 » IllegalState default encoding is...
  TkAppTest.rendersStaticResources:105 » IllegalState default encoding is window...
  TkAppTest.rendersFrontPage:64 » IllegalState default encoding is windows-1251
  TkAppTest.redirectsToReturnCookie:165 » IllegalState default encoding is windo...
  TkInboxTest.kicksAnUser:66 » IllegalState default encoding is windows-1251
  TkFriendTest.buildsPngImage:59 » IO failed after 4 attempts
  TkPreviewTest.previewMessageBeforePost:63 » IllegalState default encoding is w...
  TkAttachTest.sendsMessageToBout:94 » IO Unable to delete file: C:\Users\agelis...

Is it something known/expected?

**Comment by exper0** [comment]
@dmzaytsev by current version I mean the version I actually cloned. With newer version of Takes (0.28.2) there are more failed tests but this is expected and in scope of this task

**Comment by dmzaytsev** [comment]
@exper0 try to use `set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8`

**Comment by exper0** [comment]
@dmzaytsev thanks, it helped to solve encoding problem. I finished it: pull request https://github.com/yegor256/netbout/pull/895 . Please review and comment if anything is wrong

**Comment by dmzaytsev** [comment]
@exper0 the PM will assign someone to review

**Comment by exper0** [comment]
@karato @dmzaytsev how disputes are being solved? What should I do if I don't agree with reviewer? Are there any arbitrage?

**Comment by exper0** [comment]
@dmzaytsev finally this has been done ( PR #895 ). Please confirm and close ticket

**Comment by dmzaytsev** [comment]
@exper0 thanks!

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@exper0 added 10 mins to @elenavolokhova, for QA review, payment code is `73519041`... thanks, I just added **30 mins** to your account, payment `AP-84561307MF502311G`, 171 hours and 44 mins spent... +30 added to your rating, current score is: [+120](http://www.netbout.com/b/36185?open=rating)
