### ISSUE TITLE
jcabi-http versions

### ISSUE THREAD

**Issue by exper0** [yegor256/netbout#896]
netbout-web uses jcabi-http version 1.10.3
netbout-client uses jcabi-http version 1.10.4
netbout-web depends on netbout-client  -> potentially dangerous versions mismatch(actually only one version is used depending on which one is first appeared in classpath). I think we need to upgrade both to latest 1.14.1

**Comment by dmzaytsev** [comment]
@exper0 netbout-web doesn't depend on netbout-client
but let's upgrade to lates jcabi-http anyway

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by exper0** [comment]
@dmzaytsev you're right, I missed that it's a test scope dependency in netbout-web. Anyway it's better to have consistent and fresh versions

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@exper0 since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@exper0 thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-5S735906DC988552U`

**Comment by exper0** [comment]
@dmzaytsev @karato ready to take it

**Comment by dmzaytsev** [comment]
@exper0 the ticker reporter and the ticker performer should be different persons

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev this task is yours now, please proceed

**Comment by dmzaytsev** [comment]
@exper0 fixed in #922 please close the ticket

**Comment by exper0** [comment]
@dmzaytsev thanks

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you ;)

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @elenavolokhova for QA review (payment ID is `74582921`). done, I added **1 hour** in payment `74582944`, 16 hours and 30 mins spent to complete this. the bonus for fast delivery (m=990). +60 to your rating, your total score is [+1704](http://www.netbout.com/b/35166?open=rating)
