### ISSUE TITLE
maven.netbout.com is out of date 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#898]
the site deployment has been disabled some time ago
that's why http://maven.netbout.com is out of date 
see https://github.com/yegor256/netbout/issues/640 , https://github.com/yegor256/netbout/issues/577#issuecomment-105406368

it seems the issue Github maven plugin fixed already,
see https://github.com/github/maven-plugins/issues/88#issuecomment-108613808 

let's upgrade to latest Github maven plugin 
and  turn on the the site deployment

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev thanks a lot for reporting, **30 mins** added to your acc, pmt ID `73017088`

**Comment by karato** [comment]
@prahladyeri this is your task

**Comment by prahladyeri** [comment]
@karato I'm looking into this.

**Comment by prahladyeri** [comment]
@karato @dmzaytsev 
I've made the following changes in PR #972. Please let me know if this is sufficient or anything else needs to be done here.

- Upgraded `site-maven-plugin` to `v0.12` in pom.xml.
- site-deployment enabled in `.rultor.yml`.

**Comment by karato** [comment]
> @karato I'm looking into this.

@prahladyeri thanks

**Comment by karato** [comment]
> @karato @dmzaytsev 
> I've made the following changes in PR #972. Please let me know if this is sufficient or anything else needs to be done here.
> 
> - Upgraded `site-maven-plugin` to `v0.12` in pom.xml.
> - site-deployment enabled in `.rultor.yml`.

@prahladyeri the reviewer will take a look

**Comment by karato** [comment]
@prahladyeri 15 days already, in 48 hours I will re-assign

-30 added to your rating, at the moment it is: [+105](http://www.netbout.com/b/36189?open=rating)

**Comment by prahladyeri** [comment]
@karato May I request some more time?

**Comment by karato** [comment]
> @karato May I request some more time?

@prahladyeri sure, take your time
