### ISSUE TITLE
ReUser class is causing friends iteration to freeze

### ISSUE THREAD

**Issue by prahladyeri** [yegor256/netbout#899]
I came across this while working on #791. The netbout verification was freezing on `RtFriendsITCase` and it turns out that was because of this one rogue class:

```
com.netbout.client.retry.ReUser
```

 `rule.get()` was returning a `ReUser` object and that was fixed by using a `CdUser` object instead, but the deeper puzzle still remains as to _why ReUser is going in an infinite loop_? This is happening despite the fact that `@RetryOnFailure` is clearly specified to be `false` for the friends `Iterable`:

```
@Override
@RetryOnFailure(
    verbose = false, attempts = Tv.TWENTY,
    delay = Tv.FIVE, unit = TimeUnit.SECONDS
)
```

**Comment by karato** [comment]
@dmzaytsev take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@prahladyeri why you define it as an infinity loop?
the exception occurs on every call  so the method will retry 12 times, with a 5 sec **exponential** back-off delay between attempts.
http://aspects.jcabi.com/annotation-retryonfailure.html

**Comment by prahladyeri** [comment]
@dmzaytsev I did not define anything. All I did was remove the `ReUser` wrapper class from `NbRule.java`:

    return new ReUser(new CdUser(new RtUser(url, token)));

Since it is now using `CdUser` it had stopped freezing. Since this was my first ticket and I don't know anything in detail about `netbout`, I was unable to perform an `RCA` analysis as to WHY `ReUser` was problematic and causing the freeze, that's why I created this bug :smile:

**Comment by dmzaytsev** [comment]
@prahladyeri okay :)
if you verified that ReUser doesn't work as expected(I guess it's not an in-depth RCA analysis) 
I register this ticket  as a bug
>the exception occurs on every call so the method will retry 12 times, with a 5 sec exponential back-off delay between attempts

btw feel free to submit a bug to jcabi-aspect if `@RetryOnFailure` doesn't work as expected

**Comment by prahladyeri** [comment]
> if you verified that ReUser doesn't work as expected(I guess it's not an in-depth RCA analysis) 

@dmzaytsev I verified using the same way as the ticket owner of #791. I ran the integration test and it just freezes infinitely, now I don't know whether its owing to `@RetryOnFailure` or anything else. To verify, I did the same test again today and it froze for around 60 minutes (and still counting):

![netbout_freeze](https://cloud.githubusercontent.com/assets/5732256/12152417/8e9e89b4-b4da-11e5-9552-3943f64136dd.png)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@prahladyeri attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@prahladyeri thanks for the ticket, your account was topped for 15 mins, payment 74012521

**Comment by karato** [comment]
@danff this is your task

**Comment by danff** [comment]
@karato need more time here

**Comment by karato** [comment]
> @karato need more time here

@danff of course, thanks for letting me know, take your time
