### ISSUE TITLE
Upgrade dependencies in netbout-client

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#900]
Some dependencies in `netbout-client` module are outdated, let's upgrade them:
```
jcabi-http 	1.10.4 -> 1.14.1 	
h2 	1.4.186 -> 1.4.190 
jersey-client 	1.18.1 -> 1.19 
```

**Comment by karato** [comment]
@dmzaytsev please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@mkordas I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `568abc1202373e6c5f0004ad`

**Comment by exper0** [comment]
@dmzaytsev @karato ready to take this

**Comment by dmzaytsev** [comment]
@karato assign @exper0 to this ticket please

**Comment by karato** [comment]
> @karato assign @exper0 to this ticket please

@dmzaytsev OK @exper0 please proceed, this task is yours

**Comment by exper0** [comment]
@mkordas @karato done

**Comment by exper0** [comment]
@mkordas PR #916 is merged and closed - could you please close the ticket?

**Comment by mkordas** [comment]
@exper0 thanks!

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks a lot :)

**Comment by karato** [comment]
@exper0 paied 10 mins to @elenavolokhova for QA review (payment ID is `74525199`)

thank you, added **38 mins** to your acc, payment num is `AP-1BF48510GV285280H`, 69 hours and 19 mins spent in total to complete

there is a bonus for fast delivery (m=4159)

+38 added to your rating, current score is: [+271](http://www.netbout.com/b/36185?open=rating)
