### ISSUE TITLE
After removing yourself from the bout it becomes abandoned

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#901]
It is possible for author of the bout to kick of himself even if he's the only person in the conversation. After that action bout becomes zombie and it is not possible to rejoin it. 

It should be not possible to remove author from bout when he's the last person.

**Comment by karato** [comment]
@dmzaytsev please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by dmzaytsev** [comment]
@mkordas kick-out is the deprecated feature. it will be removed

**Comment by mkordas** [comment]
@dmzaytsev I don't see any issue opened for such removal, should I reword this one?

**Comment by dmzaytsev** [comment]
@mkordas see https://github.com/yegor256/netbout/issues/634#issuecomment-105601103 https://github.com/yegor256/netbout/issues/634#issuecomment-111782630

**Comment by mkordas** [comment]
@dmzaytsev thanks for explanation!
