### ISSUE TITLE
Page elements are overlapping on small resolutions

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#902]
When I'm using Netbout on my phone it displays like that:
![screenshot from 2015-12-28 22 51 45](https://cloud.githubusercontent.com/assets/5467276/12026087/c18e7a72-adb5-11e5-87c4-4a8b1fcc6803.png)
Home icon is overlapping with find textbox and "plus" icon is overlapping with logout.

I wouldn't expect any overlaps, especially when there's enough place to fit everything like above.

To reproduce just decrease width of any web browser.

**Comment by karato** [comment]
@dmzaytsev please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by dmzaytsev** [comment]
@mkordas I can't reproduce it on both desktop and mobile browsers
what browser and OS do you use ?

**Comment by mkordas** [comment]
@dmzaytsev I cannot reproduce it on Chrome but I see it in the following browsers:
* Firefox 39.0 on Windows
* Microsoft Edge 20
* Windows Phone browser
* Bundled Android browser

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will assign somebody else to this issue

**Comment by karato** [comment]
@mkordas thanks for tis bug, I topped your account for 15 mins, transaction `568c1a11f3f4f4008c00047d`
