### ISSUE TITLE
Unintuitive behaviour when 'since' parameter used to filter out bouts

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#903]
To reproduce it is required a few bouts at http://www.netbout.com/

Then open http://www.netbout.com/?since=0 - normally I would expect all bouts being displayed, as it could mean "since message with timestamp 0" or "since message with id 0", but nothing is displayed.

I would expect either displaying error that messages cannot be displayed since `0`, because message `0` doesn't exist or another approach could be to display all messages with ID greater than 0.

**Comment by karato** [comment]
@dmzaytsev dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@mkordas 
> Then open http://www.netbout.com/?since=0 - normally I would expect all bouts

why you expect this?
is it the documented feature?

**Comment by mkordas** [comment]
@dmzaytsev so maybe we should document it better? It's part of REST API. Is there any place to create such docs?

**Comment by dmzaytsev** [comment]
@mkordas I didn't get why a user should use this link `http://www.netbout.com/?since=0`
maybe you find a place on www.netbout.com where the user can click on that link?

**Comment by dmzaytsev** [comment]
@karato this is invalid

**Comment by mkordas** [comment]
@dmzaytsev sorry for missing that one. There's no direct link, but `since` is part of REST API. It is not documented and incorrect usage of it doesn't raise any errors. But if you don't think it is an issue, I'm closing this one.
