### ISSUE TITLE
PDD and estimates are not configured in Travis

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#908]
We should have puzzles and estimates verification done by Travis build instead of waiting for Rultor merge to fail. This could be done e.g. as in `jcabi-dynamo` project: https://github.com/jcabi/jcabi-dynamo/blob/6ab5f80beb9b3016cbd818cf6c3ef77c6ddddee0/.travis.yml#L15.

I'd expect `pdd --file=/dev/null` and `est --dir=est --file=/dev/null` being invoked on Travis for every build.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@mkordas since there is no milestone yet I set it to "3.1"

**Comment by dmzaytsev** [comment]
@karato assign me here please

**Comment by karato** [comment]
> @karato assign me here please

@dmzaytsev the task is yours, please proceed

**Comment by dmzaytsev** [comment]
@mkordas fixed in #912 please close the ticket

**Comment by mkordas** [comment]
@dmzaytsev I have two small concerns:
* do we really need `--verbose` pdd? It pollutes logs a lot, a few thousand lines more is there
* currently pdd analyzes also files in `/target` (https://travis-ci.org/yegor256/netbout#L8930) - I think we should do the clean beforehand

**Comment by dmzaytsev** [comment]
@mkordas you're right

**Comment by dmzaytsev** [comment]
@mkordas done

**Comment by mkordas** [comment]
@dmzaytsev thanks a lot!

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@dmzaytsev 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >The ticket describes one specific problem and provides a single solution.
 
 Two PRs were created for this issue. Please try to follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @elenavolokhova for QA review (payment ID is `73991681`). **1 hour** added to your account (payment number `73991687`), many thanks for your contribution! 1 hour and 26 mins spent here.. there is a bonus for fast delivery (m=86). +60 added to your rating, at the moment it is: [+1429](http://www.netbout.com/b/35166?open=rating)
