### ISSUE TITLE
Bump up year in header and update to the latest jcabi-parent

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#909]
1. We have year 2016 already, so all occurrences of 2015 in licenses and headers should be bumped up to 2016.
2. [jcabi-parent used by Netbout](https://github.com/yegor256/netbout/blob/master/pom.xml#L50) is pretty outdated, we should update it to the [latest version](https://github.com/jcabi/jcabi-parent/releases) and make sure the build is passing

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

we are waiting for https://github.com/teamed/qulice/issues/411

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@mkordas I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
> @karato this is postponed
> 
> we are waiting for https://github.com/teamed/qulice/issues/411

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed
> 
> we are waiting for https://github.com/teamed/qulice/issues/411

@dmzaytsev all right, we'll find someone else for this task

**Comment by karato** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 568c03e2d9f14900b50003bc

**Comment by dmzaytsev** [comment]
@karato this is not postponed

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by karato** [comment]
> @karato this is not postponed

@dmzaytsev sure, thanks, I removed "postponed" tag to it

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev done, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@karato please see PR #934

**Comment by dmzaytsev** [comment]
@mkordas fixed in #934 please close the ticket

**Comment by mkordas** [comment]
@dmzaytsev thanks!

**Comment by karato** [comment]
> @karato please see PR #934 

@dmzaytsev I will take a look, thanks

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks!

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 74722215

done, I added **1 hour** in payment `74722225`, 14 hours and 48 mins spent to complete this

there is a bonus for fast delivery (m=888)

+60 added to your rating, at the moment it is: [+2031](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment]
@yegor256 the pull request contains a [puzzle](https://github.com/yegor256/netbout/pull/934/files#diff-600376dffeb79835ede4a0b285078036R48)
PR has been merged and deployed 2 days ago however there is not a new ticket for the puzzle

**Comment by dmzaytsev** [comment]
@yegor256 maybe a new deploy can help...
Could you assist here? Rultor doesn't like this command from me :)
