### ISSUE TITLE
Enable FindBugs checks for Netbout code

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#911]
Currently all FindBugs checks are [disabled](https://github.com/yegor256/netbout/search?utf8=%E2%9C%93&q=findbugs) in the entire codebase. This is the last tool I would disable in a project.

I'd expect FindBugs to not be excluded from Qulice. All easy violations should be fixed, while for harder cases PDD approach may be used.

<hr id='w'>

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@mkordas thank you for the ticket reported, I topped your account for 15 mins, transaction `568babcc705bf266fc0001b0`

**Comment by exper0** [comment]
@dmzaytsev @karato ready to take this one

**Comment by dmzaytsev** [comment]
@karato assign @exper0 please

**Comment by karato** [comment]
> @karato assign @exper0 please

@dmzaytsev done. @exper0 the task is yours, please go ahead

**Comment by dmzaytsev** [comment]
@karato we are waiting for  #909

**Comment by karato** [comment]
> @karato we are waiting for  #909 

@dmzaytsev sure, let's wait for #909

**Comment by karato** [comment]
@mkordas FYI, the issue we were waiting for (#909) is fixed

**Comment by dmzaytsev** [comment]
@karato we need more time here

**Comment by karato** [comment]
> @karato we need more time here

@dmzaytsev OK, no problem, take your time

**Comment by exper0** [comment]
@dmzaytsev btw, why are we waiting for jcabi parent update? How will it help here? The only thing is updated qulice and repaired findbugs filters. Do you expect that I create granular exclude filters for findbug?

**Comment by dmzaytsev** [comment]
@exper0 I think it doesn't make sense to make a fix for outdated findbugs checks
I expect updated qulice will save our time

**Comment by mkordas** [comment]
@dmzaytsev actually there were almost no changes to FindBugs over entire history in Qulice, this part is very stable

**Comment by dmzaytsev** [comment]
@mkordas thanks
@exper0  let's continue

**Comment by exper0** [comment]
@dmzaytsev sure. As a reviewer of #923 what do you expect from my side? I think it's ready.

**Comment by dmzaytsev** [comment]
@exper0 see my question in the PR

**Comment by karato** [comment]
@mkordas 3 puzzles were created here: `911-a1464331`/#965, `911-20c870d4`, `911-1ad8e6c0`

**Comment by exper0** [comment]
@karato should those puzzles to be resolved to close this ticket?

**Comment by dmzaytsev** [comment]
@exper0 just ask the ticker reporter

**Comment by exper0** [comment]
@mkordas do you think we can close the ticket?

**Comment by mkordas** [comment]
@exper0 sure, thx

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks!

**Comment by karato** [comment]
@exper0 paied 10 mins to @ypshenychka for QA review (payment ID is `76555906`)

paid, thanks, added **30 mins** to your account, payment `AP-5YF64632AX157512H`, 413 hours and 56 mins was spent

+30 to your rating, your total score is [+573](http://www.netbout.com/b/36185?open=rating)

**Comment by karato** [comment]
@mkordas last 3 puzzles `911-a1464331`/#965, `911-20c870d4`/#966, `911-1ad8e6c0`/#968 that originated from here were solved
