### ISSUE TITLE
netbout-web installs bower each time it is built

### ISSUE THREAD

**Issue by prahladyeri** [yegor256/netbout#914]
Each time you build netbout-web by doing `mvn clean install -Pqulice`, the bower component is re-installed whether anything is changed/not.

    Running "npm install bower"

I've also noted that there is at least 20 megabytes of additional mavan package downloads when the build is done after some interval (like building again after a gap of 4-5 hours).

<hr id='w'>

**Comment by dmzaytsev** [comment]
@prahladyeri how can we fix it? what do you think?

**Comment by prahladyeri** [comment]
@dmzaytsev I think the easy approach is to check for an existing bower version first:

    npm list bower

This returns the available version and if present, there is no need to re-install bower again. Agreed that this is a pretty trivial thing and even running `npm install bower` might get it from cache instead of actually downloading, but installing a package each time you build doesn't seem like a good workflow (or maybe I'm missing something, @dmzaytsev ?)

**Comment by dmzaytsev** [comment]
@prahladyeri let's try to speed the build a little bit

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@prahladyeri I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@prahladyeri many thanks for the report, I topped your account for 15 mins, transaction 75042101

**Comment by karato** [comment]
@jhyle can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by jhyle** [comment]
@karato What I figured out is that "npm ls | grep bower || npm install bower" / "npm ls | grep bower && npm update bower" works on the command line, anyhow the frontend-maven-plugin does not execute this probably when given as <arguments>. I see no way to implement it, at least not without using something else then the maven-frontend-plugin or hacking it.

**Comment by karato** [comment]
> @karato What I figured out is that "npm ls | grep bower || npm install bower" / "npm ls | grep bower && npm update bower" works on the command line, anyhow the frontend-maven-plugin does not execute this probably when given as arguments. I see no way to implement it, at least not without using something else then the maven-frontend-plugin or hacking it. 

@jhyle you should address your technical comments to the project architect (@dmzaytsev)

**Comment by dmzaytsev** [comment]
@prahladyeri please explain your idea about checking bower version

> What I figured out is that "npm ls | grep bower || npm install bower" / "npm ls | grep bower && npm update bower" works on the command line, anyhow the frontend-maven-plugin does not execute this probably when given as arguments. I see no way to implement it, at least not without using something else then the maven-frontend-plugin or hacking it.

**Comment by prahladyeri** [comment]
@dmzaytsev My original idea was that if we just do a `npm ls|grep bower`, the program returns the version if the package exists on the first line: 

	└─┬ bower@1.7.2
	  ├─┬ bower-config@1.3.0
	  ├── bower-endpoint-parser@0.2.2
	  ├─┬ bower-json@0.4.0
	  ├── bower-logger@0.2.2
	  ├─┬ bower-registry-client@1.0.0

Now, if our Java class does the same thing while building (using `java.lang.Runtime` or any other means), it should also get the same output, then depending on the output, it can decide whether to install `bower` or not.

@jhyle Here is a [StackOverflow example](http://stackoverflow.com/questions/3062305/executing-shell-commands-from-java) of how to use the `Runtime` object from java to execute a shell command.

**Comment by dmzaytsev** [comment]
@prahladyeri I didn't get why we need  java class in this case?

**Comment by prahladyeri** [comment]
@dmzaytsev  I assumed that our build process might be calling a Java class, which might be installing the `bower` and other stuff, my mistake if that is not the case. In case the build process is just an `ant` script, then I don't see how this could be achieved. Maybe, we can delegate the installing part to a separate `bash` script which then does this check? But as @jhyle said, that method would be a bit hackish.

**Comment by jhyle** [comment]
@prahladyeri @dmzaytsev Sure, on bash it's a no-brainer. But how to do it with maven? The currently used maven-frontend-plugin does not support shell commands. Directions to go are:

* replace install via maven-frontend-plugin with a maven plugin that executes shell commands (and do this probably for our case)
* patch maven-frontend-plugin so that it offers a method to install if not present and update of old

Both are a day of work (or better: read and try) for me at least, as I am not a maven expert.

**Comment by dmzaytsev** [comment]
@jhyle @prahladyeri take a look at the example project 
https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/pom.xml#L38
they use `package.json` instead of direct call of `npm install bower`

I guess `bower` would be installed  as needed if we had did the same

**Comment by jhyle** [comment]
@dmzaytsev  Thank you, that worked. Unfortunately the travis build fails for a reason that is hopefully unrelated to my patch. Can you have a look?

**Comment by dmzaytsev** [comment]
@jhyle looks like a temporary network issue
try close/open the PR to trigger the build

**Comment by jhyle** [comment]
@karato Please see PR #975

**Comment by karato** [comment]
> @karato Please see PR #975 

@jhyle thanks, I'll take a look

**Comment by karato** [comment]
@prahladyeri the code made here contains a puzzle `914-ecab4401`/#982, which will be resolved soon

**Comment by jhyle** [comment]
@karato Does closing this issue has to wait until #982 is solved?

**Comment by karato** [comment]
> @karato Does closing this issue has to wait until #982 is solved?

@jhyle no, it's just an information message

**Comment by jhyle** [comment]
@karato Why isn't this task removed from my agenda?

**Comment by prahladyeri** [comment]
@jhyle I have already closed this bug. Are you referring to the labeling? I don't think its up to us to add/remove those.

**Comment by karato** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks!

**Comment by karato** [comment]
@jhyle paied 10 mins to @ypshenychka for QA review (payment ID is `76503769`). Many thanks! **30 mins** were added to your account in Transaction ID `AP-2F923971Y9576242X` (task took 216 hours and 48 mins). added +30 to your rating, now it is equal to [+120](http://www.netbout.com/b/36320?open=rating)

**Comment by karato** [comment]
@prahladyeri the last puzzle `914-ecab4401`/#982 solved
