### ISSUE TITLE
mvn package doesn't work

### ISSUE THREAD

**Issue by exper0** [yegor256/netbout#917]
`mvn clean package` doesn't work - netbout-client build fails
`mvn clean install` works

This is reproduced on clean machine - once `mvn install` is done `mvn package` becomes functional as well

here is extract from build log:

...
[ERROR] can't determine superclass of missing type com.netbout.spi.Friends$UnknownAliasException
when weaving type com.netbout.client.RtFriends
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType] 
[ERROR] can't determine superclass of missing type com.netbout.spi.Friends$UnknownAliasException
when weaving type com.netbout.client.RtFriends
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType] 
[ERROR] can't determine superclass of missing type com.netbout.spi.Friends$UnknownAliasException
when weaving type com.netbout.mock.MkFriends
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
 [Xlint:cantFindType] 
[ERROR] can't determine superclass of missing type com.netbout.spi.Friends$UnknownAliasException
when weaving type com.netbout.mock.MkFriends
when weaving classes 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0
...
[INFO] Reactor Summary: 
[INFO] netbout ............................................ SUCCESS [ 28.923 s] 
[INFO] netbout-spi ........................................ SUCCESS [01:29 min] 
[INFO] netbout-client ..................................... FAILURE [ 12.887 s] 
[INFO] netbout-web ........................................ SKIPPED

**Comment by dmzaytsev** [comment]
@exper0 `mvn package` take the compiled code and package it in a JAR
`mvn install` install the package into the local repository, for use as a dependency in other projects locally

netbout-client depend from netbout-spi that's why you need to use `mvn install` instead of `mvn package`

**Comment by exper0** [comment]
@dmzaytsev thanks, it's clear.
