### ISSUE TITLE
Post a new message using CTRL+Enter

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#918]
It would be nice to be able to post a new message using CTRL+ENTER combination.
We really used to this feature with Github :)

**Comment by dmzaytsev** [comment]
@longtimeago sure,  thanks!

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by yegor256** [comment]
@longtimeago I didn't even know that it exists in GitHub :)

**Comment by longtimeago** [comment]
@yegor256 have you ever tried GitHub? :)

**Comment by yegor256** [comment]
@longtimeago trying it now... :)

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@longtimeago there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@longtimeago thank you for reporting this, I added 15 mins to your acc, transaction `74071200`

**Comment by dmzaytsev** [comment]
@karato please assign me

**Comment by karato** [comment]
> @karato please assign me

@dmzaytsev of course, the task is yours, go ahead

**Comment by dmzaytsev** [comment]
@longtimeago fixed in #927 please close if alright

**Comment by longtimeago** [comment]
@dmzaytsev thank you!

**Comment by karato** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@ypshenychka thanks a lot ;)

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @ypshenychka for QA review (payment ID is `74586880`)... Thanks so much! Your account was topped up for **1 hour** (transaction ID is `74586890`, the task took 1 hour and 38 mins)... the bonus for fast delivery (m=98)... +60 added to your rating, current score is: [+1764](http://www.netbout.com/b/35166?open=rating)
