### ISSUE TITLE
Fix FindBugs issues

### ISSUE THREAD

**Issue by exper0** [yegor256/netbout#924]
During the work on #911 I found that there are plenty findbugs violations that fail the build. Worth fixing them

**Comment by dmzaytsev** [comment]
@exper0 no needs to create a separate ticket
just create a puzzle in the original pull request

**Comment by exper0** [comment]
@dmzaytsev where can I read about puzzles? Not quite sure how to create it

**Comment by dmzaytsev** [comment]
@exper0 check out this article http://www.yegor256.com/2009/03/04/pdd.html
you can find a lot of puzzle examples in Netbout
just search for `@todo` in the sources

**Comment by exper0** [comment]
@dmzaytsev thanks
