### ISSUE TITLE
File upload fails.

### ISSUE THREAD

**Issue by thihara** [yegor256/netbout#929]
Tried to upload a pdf file.

Kept getting bad response thrown instead.

<b>HAR File pasted below</b>

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [
      {
        "startedDateTime": "2016-01-14T16:49:55.809Z",
        "id": "page_1",
        "title": "http://www.netbout.com/b/36338/attach",
        "pageTimings": {
          "onContentLoad": 2099.4250000001102,
          "onLoad": 2092.017000000169
        }
      }
    ],
    "entries": [
      {
        "startedDateTime": "2016-01-14T16:49:55.809Z",
        "time": 2027.4390000001858,
        "request": {
          "method": "POST",
          "url": "http://www.netbout.com/b/36338/attach",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Origin",
              "value": "http://www.netbout.com"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Host",
              "value": "www.netbout.com"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.8,si;q=0.6"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"
            },
            {
              "name": "Content-Type",
              "value": "multipart/form-data; boundary=----WebKitFormBoundaryNB43D105rH47dpry"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Referer",
              "value": "http://www.netbout.com/b/36338"
            },
            {
              "name": "Cookie",
              "value": "RsFlash=; RsFlash=message+posted+to+the+bout+%2336338/INFO; __utmt=1; __utma=214497544.235451337.1452699975.1452752083.1452788035.7; __utmb=214497544.4.10.1452788035; __utmc=214497544; __utmz=214497544.1452736596.2.2.utmcsr=at.teamed.io|utmccn=(referral)|utmcmd=referral|utmcct=/join.html; PsCookie=2DFF9CD2-3B71ABE1-05852E4B-100B131E-1C1C0A04-19175345-481D5357-484E1C42-435D5343-4B5F454F-16585341-7D201512-08067562-3D1C1046-0A17185D-6A1E0104-0D1F0B08-747E5E02-060D0856-1E73390B-01061907-43014409-114E0A1C-1C0A0419-171C071C-5C080A17-09411507-4B001A1F-4659214A-3E2C0819-69103032-225A3328-35386F2A-24383C65-325C2422-34332835-386F2A24-38521049-46571106-110B024C-63441511-1250145D-0F131226; PRUM_EPISODES=s=1452790195802&r=http%3A//www.netbout.com/b/36338"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "101191"
            }
          ],
          "queryString": [],
          "cookies": [
            {
              "name": "RsFlash",
              "value": "",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "RsFlash",
              "value": "message+posted+to+the+bout+%2336338/INFO",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "__utmt",
              "value": "1",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "__utma",
              "value": "214497544.235451337.1452699975.1452752083.1452788035.7",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "__utmb",
              "value": "214497544.4.10.1452788035",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "__utmc",
              "value": "214497544",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "__utmz",
              "value": "214497544.1452736596.2.2.utmcsr=at.teamed.io|utmccn=(referral)|utmcmd=referral|utmcct=/join.html",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "PsCookie",
              "value": "2DFF9CD2-3B71ABE1-05852E4B-100B131E-1C1C0A04-19175345-481D5357-484E1C42-435D5343-4B5F454F-16585341-7D201512-08067562-3D1C1046-0A17185D-6A1E0104-0D1F0B08-747E5E02-060D0856-1E73390B-01061907-43014409-114E0A1C-1C0A0419-171C071C-5C080A17-09411507-4B001A1F-4659214A-3E2C0819-69103032-225A3328-35386F2A-24383C65-325C2422-34332835-386F2A24-38521049-46571106-110B024C-63441511-1250145D-0F131226",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "PRUM_EPISODES",
              "value": "s=1452790195802&r=http%3A//www.netbout.com/b/36338",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": 1387,
          "bodySize": 286,
          "postData": {
            "mimeType": "multipart/form-data; boundary=----WebKitFormBoundaryNB43D105rH47dpry",
            "text": "------WebKitFormBoundaryNB43D105rH47dpry\r\nContent-Disposition: form-data; name=\"name\"\r\n\r\nresume\r\n------WebKitFormBoundaryNB43D105rH47dpry\r\nContent-Disposition: form-data; name=\"file\"; filename=\"resume.pdf\"\r\nContent-Type: application/pdf\r\n\r\n\r\n------WebKitFormBoundaryNB43D105rH47dpry--\r\n"
          }
        },
        "response": {
          "status": 400,
          "statusText": "Bad Request",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Thu, 14 Jan 2016 16:49:57 GMT"
            },
            {
              "name": "Via",
              "value": "1.1 vegur"
            },
            {
              "name": "X-Netbout-Version",
              "value": "2.22 06da0da 2015-12-07T19:00:00"
            },
            {
              "name": "X-Takes-Millis",
              "value": "1692"
            },
            {
              "name": "X-Takes-Version",
              "value": "0.24.1 53cdfcc 2015-10-19T19:07:25"
            },
            {
              "name": "Vary",
              "value": "Cookie"
            },
            {
              "name": "Content-Type",
              "value": "text/plain"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Set-Cookie",
              "value": "RsFlash=;"
            },
            {
              "name": "Content-Length",
              "value": "11"
            },
            {
              "name": "Server",
              "value": "Cowboy"
            }
          ],
          "cookies": [
            {
              "name": "RsFlash",
              "value": "",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "content": {
            "size": 11,
            "mimeType": "text/plain",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 332,
          "bodySize": 11,
          "_transferSize": 343
        },
        "cache": {},
        "timings": {
          "blocked": 4.78399999997237,
          "dns": -1,
          "connect": -1,
          "send": 0.8360000001630397,
          "wait": 2020.9139999999445,
          "receive": 0.9050000001059288,
          "ssl": -1
        },
        "connection": "18521",
        "pageref": "page_1"
      }
    ]
  }
}

**Comment by dmzaytsev** [comment]
@thihara thanks for reporting but we already have ticket #703  for this

**Comment by dmzaytsev** [comment]
@karato this is duplicate #703

**Comment by dmzaytsev** [comment]
@thihara could you close this ticket? thanks
