### ISSUE TITLE
Build gets stuck when a Timer/Scheduler is implemented in the constructor.

### ISSUE THREAD

**Issue by prahladyeri** [yegor256/netbout#936]
#### Way-1:
- Open source file for any class in `netbout-web` (For example, `com.netbout.rest.TkStart`).
- Import the following two java concurrency objects to implement the scheduler:
  
  import java.util.concurrent.Executors;
  import java.util.concurrent.ScheduledExecutorService;
- Add the following code block at the end of the constructor method to implement the scheduler to run every one minute:
  
  ```
  final ScheduledExecutorService scheduler
      = Executors.newSingleThreadScheduledExecutor();
  final Runnable cleaner = new Runnable() {
          public void run() {
              return;
          }
      };
  scheduler.scheduleAtFixedRate(cleaner, 1, 1, TimeUnit.MINUTES);
  ```
- Decorate the constructor with following annotation tag to avoid the `PMD.DoNotUseThreads` violation (this is for the use-case where we actually do need multi-threading):
  
  @SuppressWarnings("PMD.DoNotUseThreads")
- Build the project by running `mvn clean install -Pqulice`.

**Expected Result:** The build should run successfully.
**Actual Result:** The build gets stuck at this point:

```
[INFO] Table 'nb-messages' is now ready for use
[INFO] Waiting for table 'nb-attachments' to become active
[INFO] Table 'nb-attachments' is now ready for use
[INFO] 
[INFO] --- exec-maven-plugin:1.3:java (start-takes-server) @ netbout-web ---
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6
```

---
#### Way-2:

As if this were not enough, I've found another way to reproduce this, but using a slightly different approach of using `Timer` instead of `ScheduledExecutorService` object:
- Open source file for any class in `netbout-web` (For example, `com.netbout.rest.TkStart`).
- Import the following two `java.util` objects to implement the timer:

import java.util.Timer;
import java.util.TimerTask;
- Add the following code block at the end of the constructor method to implement the timer to run every one minute:
  
  ```
  final int MILLIS = 60000;
  final Timer timer = new Timer();
  timer.schedule(new TimerTask() {
      @Override
      public void run() {
          return;
      }
  }, 0, MILLIS);
  ```
- Decorate the constructor with following annotation tag to avoid the `PMD.DoNotUseThreads` violation (this is for the use-case where we actually do need multi-threading):
  
  @SuppressWarnings("PMD.DoNotUseThreads")
- Build the project by running `mvn clean install -Pqulice`.

**Expected Result:** The build should run successfully.
**Actual Result:** The build gets stuck at this point:

```
[INFO] Table 'nb-messages' is now ready for use
[INFO] Waiting for table 'nb-attachments' to become active
[INFO] Table 'nb-attachments' is now ready for use
[INFO] 
[INFO] --- exec-maven-plugin:1.3:java (start-takes-server) @ netbout-web ---
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6
```

**Comment by dmzaytsev** [comment]
@yegor256 could you advise here?
I think we should call `ExecutorService#shutdown()` somewhere  to stop Takes server after integration tests
But I have no idea where exactly we should to do it

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@prahladyeri there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev sure, thanks, I added "postponed" label to it

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev I will try to find someone else

**Comment by karato** [comment]
@prahladyeri many thanks for the report, I topped your account for 15 mins, transaction 78546791
