### ISSUE TITLE
Markdown.java:59-61: We should switch to another...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#937]
Puzzle `888-3f71fb04` in `netbout-web/src/main/java/com/netbout/rest/Markdown.java:59-61` has to be resolved: We should switch to another Markdown processor MarkdownTxtMark and remove the old implementation MarkdownPegdown and its unit tests from the code.... The puzzle was created by Dmitry Zaytsev on 14-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by exper0** [comment]
@karato @dmzaytsev what does 'indie' label mean?

**Comment by dmzaytsev** [comment]
@exper0 Yegor created the original ticket as independent reviewer that's why Karato put `indie` label to all tickets and PRs that created from that ticket

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@karato please see PR #939

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev done, the task is yours, go ahead

**Comment by karato** [comment]
> @karato please see PR #939

@dmzaytsev thank you, I will check it

**Comment by dmzaytsev** [comment]
@karato fixed in #939 
the ticket can be closed

**Comment by karato** [comment]
> @karato fixed in #939 
> the ticket can be closed

@dmzaytsev thank you!

**Comment by karato** [comment]
@dmzaytsev Finished, thanks, closing..

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `75188960`. **45 mins** added to your account (payment number `75188965`), many thanks for your contribution! 27 hours and 15 mins spent here.. m=1635, that's why a bonus here for fast delivery. +45 added to your rating, at the moment it is: [+2205](http://www.netbout.com/b/35166?open=rating)
