### ISSUE TITLE
DyAlias does not throw InvalidEmailException if I pass in an invalid email.

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#938]
If I pass in an invalid email like for example  'test'  without a proper email format I think that DyAlias should throw an InvalidEmailException.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha do you mean [DyAlias#email()](https://github.com/yegor256/netbout/blob/a80198aae507fafa07de2007d04ad96d2b33c132/netbout-web/src/main/java/com/netbout/dynamo/DyAlias.java#L129) ?
```
@Override
    public void email(final String email) throws IOException {
        if (!MAIL.matcher(email).matches()) {
            throw new Alias.InvalidEmailException(email);
        }
        this.item.put(
            new AttributeUpdates().with(DyAliases.ATTR_EMAIL, email)
        );
        Logger.info(this, "@%s changed email to %s", this.name(), email);
    }
```

**Comment by kujtimiihoxha** [comment]
@dmzaytsev yes that's right.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha thanks for reporting

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag "bug" added

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@karato please see PR #940

**Comment by karato** [comment]
@kujtimiihoxha I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev of course, the task is yours, go ahead

**Comment by karato** [comment]
> @karato please see PR #940

@dmzaytsev will take a look, thanks

**Comment by karato** [comment]
@kujtimiihoxha thank you for reporting this, I added 15 mins to your acc, transaction `AP-31B64609S2887302D`

**Comment by dmzaytsev** [comment]
@kujtimiihoxha fixed in #940 please close the ticket if alright

**Comment by kujtimiihoxha** [comment]
@dmzaytsev do you think that #947 is related with your fix ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha no, I don't
my fix doesn't deployed yet

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I pulled your changes from master branch after they where merged, this is locally tested.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha now I understand, 
no, my fix not related to that issue
this ticket can be closed

**Comment by dmzaytsev** [comment]
@kujtimiihoxha ping

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks a lot :)

**Comment by karato** [comment]
@dmzaytsev added 10 mins to @elenavolokhova, for QA review, payment code is `75195641`

Much obliged! I have added **45 mins** to your account in payment "75195665", 25 hours and 11 mins spent

m=1511, that's why a bonus here for fast delivery

+45 added to your rating, at the moment it is: [+2315](http://www.netbout.com/b/35166?open=rating)
