### ISSUE TITLE
Local Netbout doesn't allow to start a new bout

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#941]
Local Netbout server https://github.com/yegor256/netbout#run-locally-and-test-it doesn't allow to start a new bout

![image](https://cloud.githubusercontent.com/assets/9972909/12389032/3dbc77b4-bdf8-11e5-93a0-ab91d3749615.png)

however Start link is available from profile page

![image](https://cloud.githubusercontent.com/assets/9972909/12389065/74b8a148-bdf8-11e5-96e3-d9f6d731469e.png)

let's enable  Start link if the email is empty

**Comment by karato** [comment]
@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@dmzaytsev since the ticket has no milestone I set it to 3.1

**Comment by exper0** [comment]
@dmzaytsev well, it allows starting new bout - but you need to click to your logic name at first

**Comment by dmzaytsev** [comment]
@exper0 I meant we need valid link on the main page as well

**Comment by exper0** [comment]
@dmzaytsev sure, I just added few more information about the fact that somehow it works from different page.

**Comment by karato** [comment]
@dmzaytsev thanks for the report, I topped your acc for 30 mins, payment ID `74968192`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I am ready for this one could you please assign me this task.

**Comment by kujtimiihoxha** [comment]
@yegor256 could you assign me to this task.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev done. @kujtimiihoxha you are assigned to this task. please proceed...

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  See PR #948

**Comment by kujtimiihoxha** [comment]
@dmzaytsev could you please close this issue, the changes are merged.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha thank!

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you

**Comment by karato** [comment]
@kujtimiihoxha 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75305810. Many thanks! **30 mins** were added to your account in Transaction ID `AP-93G361368B0174810` (task took 75 hours and 25 mins). +30 added to your rating, at the moment it is: [+150](http://www.netbout.com/b/36323?open=rating)
