### ISSUE TITLE
Email setting on local Netbout instance

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#942]
Let's disable the email checking when Netbout runs locally

**Comment by karato** [comment]
@dmzaytsev tag "bug" added

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev thanks a lot for reporting, **30 mins** added to your acc, pmt ID `74722309`

**Comment by dmzaytsev** [comment]
@karato this is invalid

**Comment by karato** [comment]
> @karato this is invalid

@dmzaytsev sure, thanks, I added "invalid" label to it
