### ISSUE TITLE
check for CI and rultor for years in copyright

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#943]
Let's add automatic check for Appveyor, Travis, Rultor  for  2009-current year in copyright
see  [Qulice project](https://github.com/teamed/qulice)  for instance

**Comment by karato** [comment]
@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@dmzaytsev many thanks for the bug report, I added 30 mins to your acc, transaction `75011331`

**Comment by karato** [comment]
@jhyle please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by jhyle** [comment]
@karato I didn't added the years.sh script to appveyor.yml because it isn't there in qulice and the script section is missing also. Would it work to just add it? Do I have a chance to test that? And should I do a pull request when the task is finished?

**Comment by dmzaytsev** [comment]
@jhyle yes, you should create a pull request to merge your changes to the master branch
you can test your script locally before

**Comment by karato** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@jhyle 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by karato** [comment]
@rultor @dmzaytsev please look at this issue, rultor closed it automatically

**Comment by jhyle** [comment]
@ypshenychka pull request is  #971

**Comment by dmzaytsev** [comment]
@jhyle I would suggest to avoid usage of `fixes #<ticket>` in a pull request description in the future.
The ticket shouldn't be closed automatically

**Comment by ypshenychka** [comment]
@jhyle Thank you.

**Comment by ypshenychka** [comment]
@karato Quality is acceptable.

**Comment by karato** [comment]
> @karato Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by karato** [comment]
@jhyle I added 10 mins to @ypshenychka (for QA review) in transaction 75677078. Many thanks! **45 mins** were added to your account in Transaction ID `AP-85U26360VG043535G` (task took 28 hours and 52 mins). m=1732, that's why a bonus here for fast delivery. +45 added to your rating, at the moment it is: [+45](http://www.netbout.com/b/36320?open=rating)
