### ISSUE TITLE
Markdown format  lost  after post message 

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#945]
In the preview page you can see that the text is formatted as 'code'  but after you post the message the message is not formatted.

Formatted in the preview : 
![formmated](https://cloud.githubusercontent.com/assets/14311743/12392354/ac370182-bdee-11e5-8448-8e4b9d9c645a.png)
Not formatted in the after post: 
![unformmated](https://cloud.githubusercontent.com/assets/14311743/12392367/c0c54d5c-bdee-11e5-9987-d37087c98fed.png)

I suspect that it has somthing to do with:
    
   final String clean = StringUtils.strip(text); 

in DyMessages#post() because it removes the  4  spaces needed to be recognized as code by markdown.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@kujtimiihoxha attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment]
@kujtimiihoxha thanks for this report, I added 15 mins to your account, in transaction `AP-5D3571449B162553H`

**Comment by karato** [comment]
@kitsook it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by kitsook** [comment]
@karato please see PR #970

**Comment by karato** [comment]
> @karato please see PR #970 

@kitsook will take a look at it, thanks

**Comment by kitsook** [comment]
@kujtimiihoxha PR #970 merged. please close the issue. thx

**Comment by kitsook** [comment]
@kujtimiihoxha ping

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@kitsook just added 10 mins to @elenavolokhova (for QA), payment ID is `75943182`

thanks, paid, **30 mins** to your account, payment ID is `AP-37V757017J690160S`, task took 143 hours and 55 mins to complete

+30 to your rating, your total score is [+60](http://www.netbout.com/b/36293?open=rating)
