### ISSUE TITLE
Email not accepted

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#947]
When I try to add email it returns a message 'Email '!kujtimii.h@gmail.com' is wrong', it appears that it ads an extra '!' to the email .
![email](https://cloud.githubusercontent.com/assets/14311743/12399683/c5837f08-be1b-11e5-9db3-b0969cb01bc6.png)

**Comment by dmzaytsev** [comment]
@kujtimiihoxha do you think an email with `!` are valid email?:)

**Comment by kujtimiihoxha** [comment]
@dmzaytsev The ```!``` is being  added after I put in my email , the email I gave was  ```kujtimii.h@gmail.com```

**Comment by dmzaytsev** [comment]
@kujtimiihoxha we use `!` as separator for new and old email for some reason

**Comment by dmzaytsev** [comment]
@kujtimiihoxha I agree, case when  a new user change his email doesn't handled properly

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@kujtimiihoxha there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@kujtimiihoxha thanks for reporting! I topped your account for 15 mins, transaction AP-45P88675RR536311N

**Comment by dmzaytsev** [comment]
@karato assign it to me please

**Comment by karato** [comment]
> @karato assign it to me please

@dmzaytsev this task is yours now, please proceed

**Comment by dmzaytsev** [comment]
@kujtimiihoxha fixed in #955 please close the tcket

**Comment by karato** [comment]
@kujtimiihoxha the code made here contains a puzzle `947-64235763`/#957, which will be resolved soon

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @ypshenychka for QA review (payment ID is `75251421`)... Much appreciated! **1 hour** was added to your account, payment ID `75251431`, time spent is 4 hours and 37 mins... the bonus for fast delivery (m=277)... +60 to your rating, your total score is [+2432](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment]
@kujtimiihoxha last puzzled solved `947-64235763`/#957
