### ISSUE TITLE
Preview doesn't display code block properly

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#952]
Preview doesn't display code block properly
Let's fix it

![image](https://cloud.githubusercontent.com/assets/9972909/12424364/a2d0b508-bef1-11e5-8e6f-fe7563b539d5.png)

![image](https://cloud.githubusercontent.com/assets/9972909/12424374/af349030-bef1-11e5-9b4d-abacc55c6b3c.png)

**Comment by karato** [comment]
@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 30 mins, transaction `75059336`

**Comment by karato** [comment]
@danff this is your task

**Comment by danff** [comment]
@karato need more time here

**Comment by karato** [comment]
> @karato need more time here

@danff sure, take your time

**Comment by danff** [comment]
@karato PR #1072 has been created adressing this issue

**Comment by karato** [comment]
> @karato PR #1072 has been created adressing this issue

@danff thank you!

**Comment by danff** [comment]
@dmzaytsev The PR #1072 has been merged. Can the ticket be closed?

**Comment by dmzaytsev** [comment]
@danff thanks!

**Comment by karato** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thank you, good quality is always good ;)

**Comment by karato** [comment]
@danff added 10 mins to @elenavolokhova, for QA review, payment code is `79801583`; Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-25N224498F156105V`, total time was 1058 hours and 57 mins; added +30 to your rating, now it is equal to [+60](http://www.netbout.com/b/36198?open=rating)
