### ISSUE TITLE
TkStart.java:57-59: Solve the puzzle for build...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#953]
Puzzle `750-23d45618` in `netbout-web/src/main/java/com/netbout/rest/TkStart.java:57-59` has to be resolved: Solve the puzzle for build mysteriously failing for this task citing a NullPointerException (See qulice issue #608 raised for the same) and then remove TkStart.java from qulice exceptions.... The puzzle was created by Prahlad Yeri on 18-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@kujtimiihoxha this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by karato** [comment]
@dmzaytsev since there is no milestone yet I set it to "3.1"

**Comment by kujtimiihoxha** [comment]
@karato  waiting for #936

**Comment by dmzaytsev** [comment]
@kujtimiihoxha this issue not related to #936 
we have to wait the qulice upgrade

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato  waiting for #936

@kujtimiihoxha sure, we'll wait for #936

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@dmzaytsev Thanks all, closed
