### ISSUE TITLE
TkStart.java:60-61: Add unit tests to test...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#954]
Puzzle `750-65232fbb` in `netbout-web/src/main/java/com/netbout/rest/TkStart.java:60-61` has to be resolved: Add unit tests to test scenarios for requests with/without a token.... The puzzle was created by Prahlad Yeri on 18-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by karato** [comment]
@kitsook could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by kitsook** [comment]
@karato I am about to start this task and I just took a look at PR #921 .  I see that even when token is specified and a cached Inbox is found, the logic still proceed to call inbox.start() to generate bout.

Opening the URL http://localhost:8080/start?post=hello&token=123 multiple times confirmed that new bouts are created.

Is my understand correct that the fix should prevent this?

**Comment by karato** [comment]
> @karato I am about to start this task and I just took a look at PR #921 .  I see that even when token is specified and a cached Inbox is found, the logic still proceed to call inbox.start() to generate bout.
> 
> Opening the URL http://localhost:8080/start?post=hello&token=123 multiple times confirmed that new bouts are created.
> 
> Is my understand correct that the fix should prevent this?

@kitsook you should address your technical comments to the project architect (@dmzaytsev)

**Comment by dmzaytsev** [comment]
@kitsook take a look https://github.com/yegor256/netbout/issues/750
* if you open url `http://localhost:8080/start?post=hello&token=123` two times or more 
only  one bout should be created
* if you open url `http://localhost:8080/start?post=hello` two times or more 
one bout should be created on each call

you have to create unit tests to check these two cases

**Comment by kitsook** [comment]
@dmzaytsev so my understanding was correct.

as said, PR #921 did not implement correctly.  [TKStart.java](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/TkStart.java#L135) calls `inbox.start()` even when a cached bot was found.  This effectively creates a new bout no matter a matching token is found or not.

just tested the latest master branch, opening `http://localhost:8080/start?post=hello&token=123` multiple times will create multiple bouts.

@karato i have done the test cases since my previous post. but i won't create PR as it will break the build

**Comment by dmzaytsev** [comment]
@kitsook you can create PR for sure
just put `@Ignore` on broken tests
and create a [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) to fix the tests for another developer

**Comment by kitsook** [comment]
@karato please see PR #960

**Comment by karato** [comment]
> @karato please see PR #960 

@kitsook I will take a look, thanks

**Comment by karato** [comment]
@dmzaytsev the code made here contains a puzzle `954-b453159b`/#973, which will be resolved soon

**Comment by kitsook** [comment]
@karato PR #960 merged.  please close this issue if it is considered to be resolved

**Comment by karato** [comment]
@dmzaytsev We are done here, thanks all

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by karato** [comment]
> @karato PR #960 merged.  please close this issue if it is considered to be resolved

@kitsook OK

**Comment by kitsook** [comment]
@karato may i know when will my payment and rating be updated?

**Comment by dmzaytsev** [comment]
@kitsook after QA review

> karato commented 14 hours ago
> @elenavolokhova please, review this ticket for compliance with our QA rules

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova many thanks

**Comment by karato** [comment]
@kitsook just added 10 mins to @elenavolokhova (for QA), payment ID is `75680321`; thank you, added **30 mins** to your acc, payment num is `AP-4TV167733Y4303337`, 116 hours and 42 mins spent in total to complete; added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/36293?open=rating)

**Comment by karato** [comment]
@dmzaytsev the last puzzle `954-b453159b`/#973 solved

**Comment by 0pdd** [comment]
@karato the only puzzle [#unknown]() is solved here.
