### ISSUE TITLE
TkSaveEmail.java:53-55: TkSaveEmail shouldn't validate a email...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#957]
Puzzle `947-64235763` in `netbout-web/src/main/java/com/netbout/rest/account/TkSaveEmail.java:53-55` has to be resolved: TkSaveEmail shouldn't validate a email when running locally. One idea how to know Netbout running locally or not is checking Version attribute from MANIFEST for substring LOCAL... The puzzle was created by Dmitry Zaytsev on 20-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by kujtimiihoxha** [comment]
@dmzaytsev please specify the task, should it only display a message after email  save that says for example``` "You are a local user this email will not be saved"``` or should the application not even ask for an email so just don't show the text ```give us your email please```.

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@karato please see #PR 958

**Comment by dmzaytsev** [comment]
@karato PR #958 merged, the ticket can be closed

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev the task is yours, please proceed

**Comment by karato** [comment]
> @karato please see #PR 958

@dmzaytsev thanks, I'll take a look

**Comment by karato** [comment]
> @karato PR #958 merged, the ticket can be closed

@dmzaytsev thank you

**Comment by karato** [comment]
@dmzaytsev Finished, thanks, closing..

**Comment by karato** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75311174

Many thanks! **1 hour** were added to your account in Transaction ID `75311185` (task took zero)

m=0, that's why a bonus here for fast delivery

+60 added to your rating, current score is: [+2566](http://www.netbout.com/b/35166?open=rating)
