### ISSUE TITLE
Old qulice

### ISSUE THREAD

**Issue by exper0** [yegor256/netbout#961]
Let's upgrade qulice to latest version - 0.15.2. upgrading jcabi-parent is good idea but it also contains outdated qulice (obviously qulice will be always ahead of jcabi-parent). So I'd propose to update qulice explicitly in Netbout pom. 
Similar task already created in takes: https://github.com/yegor256/takes/issues/530

**Comment by dmzaytsev** [comment]
@exper0 we can't do it right now due to unresolved issue in Qulice https://github.com/teamed/qulice/issues/411

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by exper0** [comment]
@dmzaytsev why this is a blocker for migration to 0.15.2? Looks not so critical

**Comment by dmzaytsev** [comment]
@exper0 I recall tried to update to jcab-parrent I got a lot of indentation issues from checkstyle
why need we fix it now and then fix again after an new update&

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@exper0 since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@exper0 many thanks for the bug report, I added 15 mins to your acc, transaction `AP-0UX27396HJ1575919`

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I will try to assign someone else

**Comment by krzyk** [comment]
@dmzaytsev indentation issues are mostly related to corrected indentation checks in the code, only in 3 cases (DyInbox, CdInbox, EmInbox) are related to bug mentioned in qulice#411. Until that one is fixed there will be many code reviews in which other issues have to be manually reported by the reviewer instead of qulice.
Also the migration won't be so fast (many new rules), so I think it is better to start it earlier than later.

**Comment by dmzaytsev** [comment]
@krzyk thanks
okay let's try to upgrade

**Comment by dmzaytsev** [comment]
@karato this is not postponed anymore

**Comment by karato** [comment]
> @karato this is not postponed anymore

@dmzaytsev thanks, I removed the "postponed" tag

**Comment by karato** [comment]
@danff this is your task

**Comment by danff** [comment]
@karato need more time

**Comment by karato** [comment]
> @karato need more time

@danff OK, take your time

**Comment by danff** [comment]
@exper0 PR #1006 addressing this issue merged and closed. What about this issue?

**Comment by exper0** [comment]
@danff thanks

**Comment by karato** [comment]
@exper0 there is a puzzle in this code `961-58fc8a23`/#1012, we'll resolve it later

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you ;)

**Comment by karato** [comment]
@danff 10 mins was added to the account of @ypshenychka (for QA review), in transaction 77297930; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-7UK21737E6189341J`, the task took 477 hours and 51 mins); +30 added to your rating, current score is: [+30](http://www.netbout.com/b/36198?open=rating)

**Comment by karato** [comment]
@exper0 Last 3 puzzles came from here were resolved: `1012-2dfa2c65`/#1063, `1012-7ae4ec06`/#1061, `1012-68768ab8`/#1062

**Comment by 0pdd** [comment]
@exper0 all 4 puzzles are solved here: [#1012](https://github.com/yegor256/netbout/issues/1012), [#1151](https://github.com/yegor256/netbout/issues/1151), [#unknown](), [#unknown]().
