### ISSUE TITLE
RsFlash is being saved in the Cookies.

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#962]
When I have an error or any other RsForward response, the RsFlash is being saved in the Cookies, so even if I refresh the page the message is still being displayed.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  could you confirm this bug ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha sure, thanks for reporting
there two issues related to Takes here 
* incorrect expiration time when Takes sets the cookie https://github.com/yegor256/takes/issues/354
* I think one hour too much for an error message, one minute good enough, but Takes doesn't allow te set the expiration time https://github.com/yegor256/takes/issues/542

so we should wait until these bug will be resolved

Also it would be great to be able to close an error message.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@kujtimiihoxha I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@kujtimiihoxha thank you for reporting this, I added 15 mins to your acc, transaction `AP-81427348J45414449`

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev OK, I will try to assign someone else
