### ISSUE TITLE
H2 temporary files cleanup

### ISSUE THREAD

**Issue by exper0** [yegor256/netbout#963]
Every time I run the build I see growing temp folder with many files similar to `netbout-9127471367576530490.h2.mv.db`. It would be great if Netbout build/tests didn't polute temp folder

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@exper0 I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@exper0 thanks for the report, I topped your acc for 15 mins, payment ID `AP-3CE10940LS153982U`

**Comment by karato** [comment]
@danff do this task

**Comment by danff** [comment]
@karato need more time

**Comment by karato** [comment]
> @karato need more time

@danff no problem, thanks for letting me know

**Comment by danff** [comment]
@karato PR #1007 has been added fixing this issue.

**Comment by karato** [comment]
> @karato PR #1007 has been added fixing this issue.

@danff thank you!

**Comment by danff** [comment]
@exper0 The pull request #1007 has been merged and closed. What about the issue?

**Comment by danff** [comment]
@exper0 any progress with closing the issue?

**Comment by exper0** [comment]
@danff ooh, sorry, thanks a lot!

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@danff I added 10 mins to @ypshenychka (for QA review) in transaction 77684592... I just added **30 mins** to your account, many thanks for your contribution (AP-2DE63275AS948760V).. 524 hours and 14 mins spent here... +30 added to your rating, current score is: [+60](http://www.netbout.com/b/36198?open=rating)
