### ISSUE TITLE
pom.xml:184-189: Fix findbugs errors in client...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#965]
Puzzle `911-a1464331` in `netbout-client/pom.xml:184-189` has to be resolved: Fix findbugs errors in client Some issues may not require fixing an should be excluded. Filters in qulice 0.12 are broken, right excludes should be more granular. I think it should be resolved when #961 completed due to broken Findbugs filters in current version of Qulice... The puzzle was created by exper0 on 15-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@danff do this task

**Comment by dmzaytsev** [comment]
@karato this is postponed
we are waiting for #961

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
> @karato this is postponed
> we are waiting for #961

@dmzaytsev of course, let's wait for #961

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev got it, "postponed" label here

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev all right, we'll find someone else for this task

**Comment by karato** [comment]
@dmzaytsev we waited for #961, it is closed already

**Comment by karato** [comment]
@dmzaytsev Thanks, closed
