### ISSUE TITLE
pom.xml:94-100: Fix findbugs errors in SPI...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#966]
Puzzle `911-20c870d4` in `netbout-spi/pom.xml:94-100` has to be resolved: Fix findbugs errors in SPI classes Friends and Attachemtns Some issues may not require fixing and should be excluded. filters in qulice 0.12 are broken, right excludes should be more granular. I think it should be resolved when #961 completed due to broken Findbugs filters in current version of Qulice... The puzzle was created by exper0 on 15-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmzaytsev** [comment]
@karato this is postponed
we are waiting for #961

**Comment by karato** [comment]
@exper0 do this task

**Comment by exper0** [comment]
@karato @dmzaytsev I thought it's postponed, isn't it?

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato this is postponed
> we are waiting for #961

@dmzaytsev yes, waiting for #961

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev right, I'll try to find someone else for this task

**Comment by karato** [comment]
@dmzaytsev impediment in issue #961 is closed, we can probably try to continue here

**Comment by karato** [comment]
@dmzaytsev Closed, done, thanks all
