### ISSUE TITLE
pom.xml:730-735: Fix findbugs errors in web...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#968]
Puzzle `911-1ad8e6c0` in `netbout-web/pom.xml:730-735` has to be resolved: Fix findbugs errors in web Some issues may not require fixing an should be excluded. Filters in qulice 0.12 are broken, right excludes should be more granular. I think it should be resolved when #961 completed due to broken Findbugs filters in current version of Qulice... The puzzle was created by exper0 on 15-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmzaytsev** [comment]
@karato this is postponed
we are waiting for #961

**Comment by karato** [comment]
@danff do this task

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
@dmzaytsev I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
> @karato this is postponed
> we are waiting for #961

@dmzaytsev yes, of course, we'll wait for #961

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev sure, thanks, I added "postponed" label to it

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev no problem, I will try to find somebody else

**Comment by karato** [comment]
@dmzaytsev I think we can continue, impediment #961 is closed

**Comment by karato** [comment]
@dmzaytsev The issue is closed
