### ISSUE TITLE
TkStartTest.java:63-65: TkStart should not create new...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#973]
Puzzle `954-b453159b` in `netbout-web/src/test/java/com/netbout/rest/bout/TkStartTest.java:63-65` has to be resolved: TkStart should not create new bout when same token is specified. When this is fixed, remove @Ignore from handlesTokens test... The puzzle was created by clarence ho on 23-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@michaelben could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by karato** [comment]
@michaelben you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)

do not forget to remove the TODO puzzle from the source code

-30 added to your rating, at the moment it is: [-45](http://www.netbout.com/b/36349?open=rating)

**Comment by karato** [comment]
@michaelben this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-135](http://www.netbout.com/b/36349?open=rating)

**Comment by karato** [comment]
@danff do this task

**Comment by karato** [comment]
@danff 15 days already, in 48 hours I will re-assign; do not forget that you should remove the `@todo` puzzle from the source code; -30 added to your rating, current score is: [+0](http://www.netbout.com/b/36198?open=rating)

**Comment by danff** [comment]
@karato need more time

**Comment by karato** [comment]
> @karato need more time

@danff no problem, thanks for letting me know

**Comment by karato** [comment]
@dmzaytsev Done, thanks all, closing..

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is bad as far as no PR or any other work is associated with this issue.

**Comment by karato** [comment]
> @karato Quality is bad as far as no PR or any other work is associated with this issue. 

@elenavolokhova OK, thanks, we'll try to be better next time

**Comment by karato** [comment]
@danff just added 10 mins to @elenavolokhova (for QA), payment ID is `111968003`
