### ISSUE TITLE
Using bold causes the space after it to disappear, again

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#977]
This is basically a reopen of #838, this problem was fixed and now it resurfaced in www.netbout.com again.
Problem description:
When I write text like this: `This is **bold** test`, the space after `bold` disappears, here's the result:
This is **bold**test.
`bold` and `test` merge into one word.
Bolding a word shouldn't make spaces after it disappear.

**Comment by dmzaytsev** [comment]
@krzyk your case works fine on http://snapshot.netbout.com . However we use Pegdown on production right now, I still wait [the confirmation] (https://github.com/yegor256/netbout/issues/848#issuecomment-174152578) from @yegor256

**Comment by krzyk** [comment]
@dmzaytsev OK, thanks, I was pretty sure it was working on production some time ago.
