### ISSUE TITLE
Text form starts with a space

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#978]
![space](https://cloud.githubusercontent.com/assets/105730/12639824/cdc68218-c5a6-11e5-9fa7-7b7920ab91e6.png)

When I want to write a text in netbout I always see that the form has a space at the beginning of the form.
This space is useless, and should be removed.

In the screenshot I have selected this space.

Browser: Firefox 45 developer edition.

**Comment by dmzaytsev** [comment]
@krzyk could you make a screenshot?

**Comment by krzyk** [comment]
@dmzaytsev here it is

**Comment by dmzaytsev** [comment]
@krzyk thanks

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by karato** [comment]
@krzyk I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@krzyk thanks a lot for reporting, **15 mins** added to your acc, pmt ID `75849205`

**Comment by karato** [comment]
@jhyle the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by jhyle** [comment]
@karato please review PR #980

**Comment by karato** [comment]
> @karato please review PR #980

@jhyle will take a look at it, thanks

**Comment by jhyle** [comment]
@karato Please close the issue.

**Comment by krzyk** [comment]
@jhyle you have to ask issue creator (in this case me) to close the issue. I'll check if it is fixed and close it.

**Comment by krzyk** [comment]
@jhyle thanks

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thank you, good quality is always good :)

**Comment by karato** [comment]
@jhyle paied 10 mins to @ypshenychka for QA review (payment ID is `75964583`). Thanks a lot, I just topped your account for **45 mins**, transaction ID `AP-2Y6021621A644413S`, total time was 41 hours and 7 mins. the bonus for fast delivery (m=2467). +45 added to your rating, current score is: [+90](http://www.netbout.com/b/36320?open=rating)
