### ISSUE TITLE
PDD check on Travis is not working for pom.xml

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#981]
We must have PDD check on Travis wrongly configured, as during code review I spotted puzzle without time specified at https://github.com/yegor256/netbout/pull/975/files#diff-127b5be4d5df4b983d3c654409321957R329 while build for this PR is fine.

Please make sure that PDD will fail for any wrongly defined puzzle in `pom.xml`.

**Comment by karato** [comment]
@dmzaytsev take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmzaytsev** [comment]
@mkordas what's wrong with "time-less" puzzle?

Travis's settings and Rultor's settings are same, so I have no idea what can we fix in this case

https://github.com/yegor256/netbout/blob/master/.travis.yml#L21
```
  - pdd --source=$(pwd) --file=/dev/null
```
https://github.com/yegor256/netbout/blob/master/.rultor.yml#L45
```
 pdd --source=$(pwd) --verbose --file=/dev/null
```

**Comment by dmzaytsev** [comment]
@mkordas ping

**Comment by mkordas** [comment]
@dmzaytsev I meant that we should configure PDD properly as in other projects: https://github.com/yegor256/takes/blob/master/.pdd

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment]
@mkordas I set the milestone to 3.1 since there is nothing set yet

**Comment by karato** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `56b4a8c7e7df065b1c00023b`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I am ready to do this task. Please assign it to me.

**Comment by dmzaytsev** [comment]
@karato assign @kujtimiihoxha please

**Comment by kujtimiihoxha** [comment]
@karato , @dmzaytsev  see PR #1000 .

**Comment by karato** [comment]
> @karato assign @kujtimiihoxha please

@dmzaytsev done. @kujtimiihoxha you are assigned to this task. please proceed...

**Comment by karato** [comment]
> @karato , @dmzaytsev  see PR #1000 .

@kujtimiihoxha thanks

**Comment by kujtimiihoxha** [comment]
@mkordas  Please close this changes are merged.

**Comment by mkordas** [comment]
@kujtimiihoxha we also need to cleanup Travis and Rultor config I think

**Comment by kujtimiihoxha** [comment]
@mkordas I am looking at takes .yml files and I don't see what is needed to be changed.

**Comment by kujtimiihoxha** [comment]
@mkordas also the .pdd is working properly because it detected the issues with the puzzles so I updated these puzzles.

**Comment by kujtimiihoxha** [comment]
@mkordas Ping.

**Comment by mkordas** [comment]
@kujtimiihoxha I mean that we have duplicated source property

**Comment by kujtimiihoxha** [comment]
@mkordas  so I should remove ```  --source=$(pwd) --verbose ```  from ``` pdd --source=$(pwd) --verbose --file=netbout.xml```

**Comment by mkordas** [comment]
@kujtimiihoxha exactly

**Comment by kujtimiihoxha** [comment]
@karato , @mkordas  see PR #1002

**Comment by karato** [comment]
> @karato , @mkordas  see PR #1002 

@kujtimiihoxha thanks for that

**Comment by kujtimiihoxha** [comment]
@mkordas changes are merged please close this issue.

**Comment by mkordas** [comment]
@kujtimiihoxha thanks!

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@kujtimiihoxha 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >The ticket describes one specific problem and provides a single solution.
 
 Two PRs were created for this issue. Please try to follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by kujtimiihoxha** [comment]
@elenavolokhova I confirm.

**Comment by elenavolokhova** [comment]
@karato Quality is acceptable here.

**Comment by karato** [comment]
> @karato Quality is acceptable here.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by karato** [comment]
@kujtimiihoxha just added 10 mins to @elenavolokhova (for QA), payment ID is `77270868`. Many thanks! **45 mins** were added to your account in Transaction ID `AP-2DX25027L7284341T` (task took 29 hours and 50 mins). m=1790, that's why a bonus here for fast delivery. +45 added to your rating, current score is: [+255](http://www.netbout.com/b/36323?open=rating)
