### ISSUE TITLE
pom.xml:330-339: investigate error messages of the...

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#982]
Puzzle `914-ecab4401` in `netbout-web/pom.xml:330-339` has to be resolved: investigate error messages of the following command and change package.json accordingly. The error messages are: [ERROR] npm WARN package.json netbout-web@ No description [ERROR] npm WARN package.json netbout-web@ No repository field. [ERROR] npm WARN package.json netbout-web@ No README data [ERROR] npm WARN package.json netbout-web@ license should be a valid SPDX license expression -->... The puzzle was created by Leo on 29-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by karato** [comment]
@dmzaytsev I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@kujtimiihoxha this is your task

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Please se PR  #985

**Comment by kujtimiihoxha** [comment]
@karato Please se PR #985

**Comment by karato** [comment]
> @karato Please se PR #985

@kujtimiihoxha thank you

**Comment by kujtimiihoxha** [comment]
@dmzaytsev please close this issue.

**Comment by dmzaytsev** [comment]
@karato will close it

**Comment by karato** [comment]
> @karato will close it

@dmzaytsev the ticket will be closed when the puzzle is removed from the code, keep in mind that it takes some time after deployment to update our statistics, please give me at least a day

**Comment by karato** [comment]
@dmzaytsev Thanks, closed

**Comment by karato** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@kujtimiihoxha 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 76631219. done, I added **30 mins** in payment `AP-300381756Y008091W`, 149 hours and 10 mins spent to complete this. +30 added to your rating, at the moment it is: [+150](http://www.netbout.com/b/36323?open=rating)
