### ISSUE TITLE
Exclamation mark icon on production after recent release

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#989]
After releasing version 2.23 to production I see exclamation mark icon on my avatar:
![image](https://cloud.githubusercontent.com/assets/5467276/12778848/57d6150a-ca65-11e5-889a-80a67ef7c9ad.png)
It shouldn't be there, as I have my email address set properly.

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@mkordas I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 56b329ea4f694f57700000c7

**Comment by karato** [comment]
@kujtimiihoxha do this task

**Comment by kujtimiihoxha** [comment]
@mkordas  @dmzaytsev  I just created a new user and I am not getting this issue It seems this is only related to already created users ? I do not know how I can test this locally. 
![screenshot from 2016-02-15 16-14-33](https://cloud.githubusercontent.com/assets/14311743/13052457/3f708010-d3ff-11e5-81a0-1655e1d0c3c1.png)

**Comment by kujtimiihoxha** [comment]
@mkordas  Now I don't see this issue in my account to. It is gone now could you please close the issue.

**Comment by mkordas** [comment]
@kujtimiihoxha I still see it in my profile

**Comment by kujtimiihoxha** [comment]
Here is my account, but I have a very strange issue now #1015.
![screenshot from 2016-02-15 19-53-07](https://cloud.githubusercontent.com/assets/14311743/13057709/3ec36b54-d41e-11e5-90f8-c505c3653fb3.png)

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I can not reproduce this with my account and cant test it ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha let's wait until fix for #1015 will be released

**Comment by kujtimiihoxha** [comment]
@karato waiting for #1015 to be released

**Comment by karato** [comment]
> @karato waiting for #1015 to be released 

@kujtimiihoxha agreed, we'll wait for #1015

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I think it hase something to do with : 
```
  private static XeSource source(final Alias alias) throws IOException {
        final String email;
        final String newemail;
        final String[] emails = alias.email().split("!");
        if (emails.length > 1) {
            email = emails[0];
            newemail = emails[1];
        } else {
            email = alias.email();
            newemail = "";
        }
        return new XeAppend(
            "alias",
            new XeDirectives(
                new Directives()
                    .add("name").set(alias.name()).up()
                    .add("locale").set(alias.locale().toString()).up()
                    .add("photo").set(alias.photo().toString()).up()
                    .add("email").set(email).up()
                    .add("newEmail").set(newemail)
            )
        );
    }
```
in XeAlias, it does return newemail even when there is no newemail ?

**Comment by kujtimiihoxha** [comment]
@mkordas Could you tell me what it says if you hover over it ?

**Comment by mkordas** [comment]
@kujtimiihoxha it says that my email is not yet verified

**Comment by kujtimiihoxha** [comment]
@mkordas does it specify the email because I want to know what the newEmail is returning, is it the same email you are now using or an old one ?

**Comment by mkordas** [comment]
@kujtimiihoxha the same as I'm using now

**Comment by kujtimiihoxha** [comment]
@mkordas Ok, I will see it is very interesting.

**Comment by karato** [comment]
@mkordas we were waiting for #1015 - it is closed already

**Comment by kujtimiihoxha** [comment]
@karato Please assign someone else because I can not find the issue here.

**Comment by karato** [comment]
> @karato Please assign someone else because I can not find the issue here.

@kujtimiihoxha 30 points was deducted from your rating

**Comment by karato** [comment]
> @karato Please assign someone else because I can not find the issue here.

@kujtimiihoxha all right, we'll find someone else for this task

**Comment by karato** [comment]
@original-brownbear this is your task

**Comment by original-brownbear** [comment]
@mkordas , I could reproduce this now. This appears to be an issue with the DynamoDB sync and is just a timing thing.
For me this happens:
* Change email, I get my verification link and experience #853 too
 * If I click the link I get something like "no verification needed" as a notice
* Then I wait for say 15 minutes
* New email appears instead of old one at last and I see the exclamation mark, the fact that I clicked the link before when I got the "not needed" notice did not validate my email.
 * But if I click it after I see the exclamation mark and the email address has changed and wait another 15 minutes, the icon disappears and all seems properly validated :)

... I'm on it fixing this, just in case you want to remove that exclamation mark ;), you should be able to remove it by simply visiting the validation link you got at some point, if you still have it that is ;)

**Comment by original-brownbear** [comment]
@mkordas PR #1066 added, reproducing and fixing(well by turning off the cache) the above explanation.

**Comment by mkordas** [comment]
@original-brownbear great job!

**Comment by original-brownbear** [comment]
@mkordas thanks :), I think we can close here right? Workaround merged, rest goes elsewhere I suppose.

**Comment by original-brownbear** [comment]
@mkordas ping :)

**Comment by mkordas** [comment]
@original-brownbear thanks!

**Comment by original-brownbear** [comment]
@karato please pay attention to this ticket as well as my other closed tickets in your project. I closed all of them in a very short period of time each, still I'm blocked by having them pile up as open tasks and receive an unrealistic speed rating by them staying open long after the PRs are closed and payment on them is handled.
Thanks :)

**Comment by karato** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova many thanks

**Comment by karato** [comment]
@original-brownbear paied 10 mins to @elenavolokhova for QA review (payment ID is `79352562`); **38 mins** added to your account (payment number `AP-0CX14905429037629`), many thanks for your contribution! 66 hours and 1 min spent here.; there is a bonus for fast delivery (m=3961); +38 added to your rating, at the moment it is: [+730](http://www.netbout.com/b/36646?open=rating)
