### ISSUE TITLE
deployment failed due to the coverage report not exists

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/netbout#992]
Let's configure the cobertura plugin to provide the coverage report
see https://github.com/yegor256/netbout/issues/848#issuecomment-179612466

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@dmzaytsev I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 30 mins, transaction `76522208`

**Comment by karato** [comment]
@kujtimiihoxha do this task

**Comment by kujtimiihoxha** [comment]
@dmzaytsev how can I test this issue ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha the cobertura plugin should build the report in `target`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  do you mean specifying the  ``` <outputDirectory>${basedir}/target</outputDirectory>``` ? because I do not fully understand this task.

**Comment by dmzaytsev** [comment]
@kujtimiihoxha just make the build locally and check for cobertura reports in `target`
if it doesn't exists you should  to do something

see the rultor [log](http://www.rultor.com/t/6736-179608350) from the link above
>Caused by: java.io.IOException: No coverage report files found

**Comment by kujtimiihoxha** [comment]
@dmzaytsev after running ```  mvn org.codehaus.mojo:cobertura-maven-plugin:cobertura ```
Build succeeds and there is a file ```cobertura.ser``` in ```target/cobertura/cobertura.ser ```

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I am reading throw rultor.yml and i don't see that the coveralls profile is called anywhere so it is not running the plugin goals at all . Can we try adding the profile to the deploy command ?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev could you please answer my question.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev could you assist in this issue ??

**Comment by dmzaytsev** [comment]
@kujtimiihoxha  as you can see in the log Rultor runs `mvn clean site-deploy` and expects to find the Coberura report in `target` but the report already deleted by `clean`
So we have two options
* remove `clean` from the last command to use Coberura report from the previous step
* use `mvn clean install site-deploy` to force run the tests and build a new Cobetura report

@yegor256 what do you think?

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I think I have to use one of your proposed solutions, I got this task 11 days before so my time is running, should we wait or proceed ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha okay let's remove `clean` from last command in the release section

**Comment by kujtimiihoxha** [comment]
@dmzaytsev I am on it .

**Comment by kujtimiihoxha** [comment]
@karato , @dmzaytsev  see PR #1018

**Comment by karato** [comment]
> @karato , @dmzaytsev  see PR #1018

@kujtimiihoxha thank you, I will check it

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.29`

**Comment by dmzaytsev** [comment]
@kujtimiihoxha let's try another way

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  I will try  to do it like this ```   mvn clean install site-deploy -Psite --errors --settings ../settings.xml --batch-mode ``` What do you say ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha let's do it

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  @karato  see PR #1027

**Comment by dmzaytsev** [comment]
@rultor release, tag=`2.30`

**Comment by kujtimiihoxha** [comment]
@dmzaytsev  It looks that this is a new issue.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Could you please look into this ?

**Comment by dmzaytsev** [comment]
@kujtimiihoxha you're right, it's a new issue
thanks

**Comment by karato** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@kujtimiihoxha Why are there 2 pull requests created for this issue?

**Comment by kujtimiihoxha** [comment]
@ypshenychka because the first solution did not solve the issue this was agreed with @dmzaytsev to try another solution

**Comment by ypshenychka** [comment]
@kujtimiihoxha I see that both PRs were merged and none of them is closed as invalid. The new committed fix could have been done in scope of the first PR. 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The ticket describes one specific problem and provides a single solution.

@dmzaytsev Please correct me if I'm missing anything.

**Comment by dmzaytsev** [comment]
@ypshenychka usually we can verify PR on a code review stage using varios tests, etc
however the solution of this issue can be verified by Rultor only on a release stage, 
PR has to be merged and released, that's why we can't mark the previous  PR as invalid.
The first PR was rolled back by the second one.

I believe a few tickets will be overkill for this particular task

**Comment by ypshenychka** [comment]
@dmzaytsev Thank you for explanation. I agree that this ticket is an exceptional case.

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks a lot

**Comment by karato** [comment]
@kujtimiihoxha paied 10 mins to @ypshenychka for QA review (payment ID is `78550562`); I added **30 mins** to your account, many thanks for working with the project (AP-33X928795Y214980G)! The completion time here was 379 hours and 34 mins.; +30 to your rating, your total score is [+353](http://www.netbout.com/b/36323?open=rating)
