### ISSUE TITLE
I am getting bower install error

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#993]
Trying to run ``` mvn clean install -Pqulice``` I get this :
"Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:bower (bower install) on project netbout-web: Failed to run task:"

Here is the full log 
[out.txt](https://github.com/yegor256/netbout/files/117490/out.txt)

**Comment by dmzaytsev** [comment]
@kujtimiihoxha it seems you have no `sh.exe` in your `path` check it
`C:\Program Files (x86)\Git\bin`
