### ISSUE TITLE
API is not described

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#994]
I just noticed that netbout has an API, but is not described anywhere (netbout.com, README.md).
It would be good to have at least some basic description how to log in and e.g. retrieve messages.
As we are at API, there is no description how to get API key to use in netbout.com, it should be also described either on netbout.com or in README.md.

**Comment by dmzaytsev** [comment]
@krzyk we have [the description how to get API key](https://github.com/yegor256/netbout#integration-tests) to use in integration tests. 
Regarding the API description, I'm not sure is it public API or not.

@yegor256 should we have a description of the Netbout API (rest client)?  what do you think?

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato this is postponed

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@krzyk there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@krzyk thank you for reporting this, I added 15 mins to your acc, transaction `78373751`

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev thanks, I added "postponed" label

**Comment by karato** [comment]
> @karato this is postponed

@dmzaytsev all right, we'll find someone else for this task
