### ISSUE TITLE
Autocompletion doesn't filter

### ISSUE THREAD

**Issue by krzyk** [yegor256/netbout#995]
Autocompletion of aliasses shows a list of parties involved in given bout, but it doesn't filter them based on the text already written.
E.g. when I write `@yeg` and I have in given bout `@krzyk` and `@yegor256`, the list of possible aliases should be reduced to just one.

See screenshot how it currently works:
![completion](https://cloud.githubusercontent.com/assets/105730/12890313/6f19304a-ce83-11e5-96cb-fb1bb6ce29dd.png)

And how I would expect it to work:
![good-completion](https://cloud.githubusercontent.com/assets/105730/12890386/b5c68b8c-ce83-11e5-82f5-744a16639851.png)

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@krzyk since the ticket has no milestone I set it to 3.1

**Comment by karato** [comment]
@krzyk thank you for reporting this, I added 15 mins to your acc, transaction `77017989`

**Comment by karato** [comment]
@2686747 please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by 2686747** [comment]
@karato the PR is ready to be reviewed thx in advance. There is other issue: autocompletion doesn't work with names != [A-Za-z0-9_] (eg @имя @&&name). Do i have to fix it?

**Comment by karato** [comment]
> @karato There is other issue: autocompletion doesn't work with names != [A-Za-z0-9_] (eg @имя @&&name). Do i have to fix it?

@2686747 please, address your technical questions to the author of the ticket

**Comment by 2686747** [comment]
@krzyk There is other issue: autocompletion doesn't work with names != A-Za-z0-9_. Do i have to fix it?

**Comment by krzyk** [comment]
@2686747 You should just fix what was in the issue description. If you find a bug then you should report it (you will get 15mins for correct bug report).

**Comment by 2686747** [comment]
@krzyk please close the ticket if you don't have any further questions.

**Comment by krzyk** [comment]
@2686747 please give reference to the PR

**Comment by 2686747** [comment]
@krzyk sure, [1005](https://github.com/yegor256/netbout/pull/1005)

**Comment by krzyk** [comment]
@2686747 it is enough to have write `#1005` you don't have to make a link :)

**Comment by karato** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by karato** [comment]
@2686747 I added 10 mins to @elenavolokhova (for QA review) in transaction 77332026

**Comment by 2686747** [comment]
@karato can you calculate this task?

**Comment by yegor256** [comment]
@karato pls add extra 30 mins to @2686747

**Comment by karato** [comment]
> @karato can you calculate this task?

@2686747 @yegor256 please help us here

**Comment by karato** [comment]
> @karato pls add extra 30 mins to @2686747 

@yegor256 I've paid 30 mins to @2686747 in transaction `56d48b308fb60a00660000c2`

**Comment by 2686747** [comment]
@karato can you explain me why [22](http://at.teamed.io/policy.html#22) doesn't work here?

**Comment by karato** [comment]
> @karato can you explain me why [22](http://at.teamed.io/policy.html#22) doesn't work here?

@2686747 @yegor256 please help us here

**Comment by yegor256** [comment]
@2686747 as I see, it took over 3 days to fix this ticket. correct me if I'm wrong

**Comment by 2686747** [comment]
@yegor256  03/11/2016 3:27PM - [start](https://github.com/yegor256/netbout/issues/995#issuecomment-182836345) 
03/12/2016 11:24 AM - #1005, fixed

**Comment by yegor256** [comment]
@2686747 check this out: http://at.teamed.io/policy.html#15
