### ISSUE TITLE
 White space after Inline link should be ignored.

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#997]
If I add an inline link like:
![withspaces](https://cloud.githubusercontent.com/assets/14311743/12914122/d31483d4-cf22-11e5-98e4-9bed0f292630.png)
It should ignore the spaces instead it does not get the image :
![noimage](https://cloud.githubusercontent.com/assets/14311743/12914108/c6605cee-cf22-11e5-98ef-0b0a25dc42aa.png)
In github the spaces are being ignored and the image displayes correctly.

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Could you confirm this bug

**Comment by karato** [comment]
@dmzaytsev please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by dmzaytsev** [comment]
@karato assign me please

**Comment by dmzaytsev** [comment]
@karato please see PR #1014

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@kujtimiihoxha there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment]
@kujtimiihoxha thank you for reporting this, I added 15 mins to your acc, transaction `AP-3SY58621UF764561S`

**Comment by karato** [comment]
> @karato assign me please

@dmzaytsev the task is yours, please proceed

**Comment by karato** [comment]
> @karato please see PR #1014

@dmzaytsev thanks, will take a look

**Comment by dmzaytsev** [comment]
@kujtimiihoxha fixed in #1014 please close the ticket

**Comment by kujtimiihoxha** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@dmzaytsev paied 10 mins to @ypshenychka for QA review (payment ID is `77858037`)... thanks, paid, **1 hour** to your account, payment ID is `77858058`, task took 1 hour and 54 mins to complete... there is a bonus for fast delivery (m=114)... +60 to your rating, your total score is [+3258](http://www.netbout.com/b/35166?open=rating)
