### ISSUE TITLE
Page not found error is displayed as success message.

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#998]
When you go to a url that does not exist netbout displays : 

![message](https://cloud.githubusercontent.com/assets/14311743/12914271/cc3d5c74-cf23-11e5-82c0-720dbe5c2018.png)

It should display the message in red to indicate that the url given was wrong

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Could you confirm this bug

**Comment by karato** [comment]
@dmzaytsev please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Is this a valid bug or should I close it ?

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev tag bug added to this issue

**Comment by karato** [comment]
@kujtimiihoxha I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@kujtimiihoxha thanks for the ticket, your account was topped for 15 mins, payment AP-4SB77262LX053121W

**Comment by karato** [comment]
@original-brownbear it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by original-brownbear** [comment]
@karato pull request added https://github.com/yegor256/netbout/pull/1029 :)

**Comment by original-brownbear** [comment]
@kujtimiihoxha PR #1029 has been merged, please close this isssue.

**Comment by kujtimiihoxha** [comment]
@original-brownbear thanks

**Comment by original-brownbear** [comment]
@karato this is fully handled as far as I understand, can you release me from this given it's closed and hence done and my current 2 task limit ? :)

**Comment by karato** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@karato Quality is good.

**Comment by original-brownbear** [comment]
@karato this issue has disappeared from my Netbout agenda, but still not been paid.

**Comment by karato** [comment]
> @karato Quality is good.

@ypshenychka many thanks

**Comment by karato** [comment]
@original-brownbear just added 10 mins to @ypshenychka (for QA), payment ID is `78373442`... Many thanks! **38 mins** were added to your account in Transaction ID `AP-2K7355691A3926930` (task took 53 hours and 33 mins)... there is a bonus for fast delivery (m=3213)... +38 added to your rating, at the moment it is: [+98](http://www.netbout.com/b/36646?open=rating)
