### ISSUE TITLE
Erros from JSR-303

### ISSUE THREAD

**Issue by kujtimiihoxha** [yegor256/netbout#999]
We should fix these error messages.

[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html) 

[ERROR] JSR-303 validator failed to initialize: Unable to instantiate Configuration. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)

**Comment by kujtimiihoxha** [comment]
@dmzaytsev Could you confirm this bug

**Comment by dmzaytsev** [comment]
@kujtimiihoxha it's a Qulice issue not Netbout
